### ISSUE TITLE
varImp function and gamlss

### ISSUE THREAD

**Issue by Hallo951** [topepo/caret#1000]
Hello,
how can I use the varImp function with a gamlss object? Is that possible? If not, what alternatives are there for obtaining the importance of the variable within a gamlss object? Unfortunately, I could not find anything on the internet. In my gamlss object I use splines and tensors.

Thank you.

best Frank

**Comment by topepo** [comment]
I've never used that package so I don't have any plans. If you want, you can send in a PR based on the [existing files]() or the documentation for [custom models](https://topepo.github.io/caret/using-your-own-model-in-train.html)
