### ISSUE TITLE
Platt scaling for LiblineaR SVM classification

### ISSUE THREAD

**Issue by BTopcuoglu** [topepo/caret#1002]
Would there be any interest in implementing Platt scaling to Liblinear SVM models to get predicted probabilities?

I've been trying and failing to do this for `svmLinear3.R` specifically.

**Comment by topepo** [comment]
I have interest but no time to do this. If you write some code, I'd be happy to incorporate it.

**Comment by topepo** [comment]
Closing with a ping to tidymodels/probably#12
