### ISSUE TITLE
caret installation does not install all dependences

### ISSUE THREAD

**Issue by ttimbers** [topepo/caret#1008]
When I install `caret` on multiple operating systems it never installs a dependency of the R package `e1071`, yet it appears to be required to run some of `caret`'s most basic functions. Would you be open to a pull request that fixes this in how the package deals with dependencies in a way such that when you install `caret`, `e1071` also gets installed?

**Comment by topepo** [comment]
The full set of dependencies takes quite a while. A good in-between place is to use 

```r
install.packages("caret", dependencies = c("Depends", "Imports", "Suggests"))
```
then go out to get lunch or something while it installs 😞

**Comment by topepo** [comment]
@ttimbers Did this work for you?

**Comment by tanlewz** [comment]
I keep getting the error package ‘caret’ is not available (for R version 3.4.3) when I try to install caret on Window computer. I installed lattice and ggplot2 first. I tried the following 3 different codes but none work. 

install.packages("caret", dependencies = TRUE)

install.packages("caret", repos = "http://cran.r-project.org", dependencies = c("Depends", "Imports"))

install.packages("caret",
                 repos = "http://cran.r-project.org",
                 dependencies = c("Depends", "Imports", "Suggests"))

What is this?

**Comment by topepo** [comment]
@tanlewz 

Your question has nothing to do with this issue. It is always better to file a new issue unless your question _exactly_ matches. 

The answer is this: on the last version, `R CMD build` (via r-devel) added the higher requirement of 3.5.0 with this message:

 > Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: `caret/inst/models/models.RData`

**Comment by tanlewz** [comment]
> @tanlewz
> 
> Your question has nothing to do with this issue. It is always better to file a new issue unless your question _exactly_ matches.
> 
> The answer is this: on the last version, `R CMD build` (via r-devel) added the higher requirement of 3.5.0 with this message:
> 
> > Added dependency on R >= 3.5.0 because serialized objects in  serialize/load version 3 cannot be read in older versions of R.  File(s) containing such objects: `caret/inst/models/models.RData`

You are absolutely right. Thanks for your response. I didn't realize that updating R Studio doesn't automatically update RGui as well. Thanks.
