### ISSUE TITLE
Use of internal functions and foreach

### ISSUE THREAD

**Issue by bwlewis** [topepo/caret#1017]
So, this is really more of an FYI and a probably bug in foreach.

Several caret functions call  non-namespace exported functions within the body of foreach expressions, see for instance `nominalTrainWorkflow` https://github.com/topepo/caret/blob/master/pkg/caret/R/workflows.R#L86 and elsewhere.  Unfortunately, foreach currently does not automatically discover the namespace context of these internal function calls and fails.

Currently, foreach resolves required symbols with a function called `getexports`, which itself in turn optionally relies on the `getGlobalsAndPackages` function from the futures package.  That approach does a nice job of exporting objects in the calling environment to the foreach workers, but fails to identify package namespace objects.  This is just the situation in caret.

Consider the following `example.r` file:

```{r}
library(doMPI)
library(caret)
cl = startMPIcluster()
registerDoMPI(cl)
data(BloodBrain)
ans = train(bbbDescr, logBBB, "knn", trControl = trainControl(method = "cv", verboseIter=TRUE))
closeCluster(cl)
mpi.quit()
```
invoked with

```
mpirun -np 3 R --slave -f example.r
```

This fails with the error
```
task 2 failed - "object 'requireNamespaceQuietStop' not found"
```

It seems that many of the changes to the `workflows.R` file attempted to deal with this deficiency in foreach in one form or another. In my opinion, this is ultimately a weakness of foreach and the long-term solution lies there (in the `getexports` function).

But in the short term, one possible fix for this is to change, for example, line https://github.com/topepo/caret/blob/master/pkg/caret/R/workflows.R#L57 from `loadNamespace("caret")` to something like
`attach(environment(caret::train))`.

Making that change fixes the above example. Prudence advises making this change in every incantation of foreach (parallel) within caret.

Again, this is just a suggestion. Long-term I think the right approach is to fix foreach, which I will try to do!

**Comment by Realsid** [comment]
I too am facing the same issue. Has this been fixed yet  ?

**Comment by saraya209** [comment]
I am getting the same error. @bwlewis, where and how do you change the L57 in the `workflows.R`? I tried downloading the workflows.R file from caret, changing the lines as you suggested and `source()`-ing the file to my code after loading caret. It did not work.

**Comment by GainsGroup** [comment]
I'm in the same boat as saraya209 - how would one fix this by altering the code? I'm using doAzureParallel as the back-end and I believe this issue is preventing me from being able to use a custom model in caret.

**Comment by topepo** [comment]
@bwlewis Do you have an annotated version of what `getexports()` does (particularly what the arguments should be)?

**Comment by bwlewis** [comment]
Sorry everyone for the huge latency, answers in process this week I promise!
