### ISSUE TITLE
add custom bin point in calibration plot

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#102]
Currently Calibration plot plots over a range 0 -1 probs evenly spaced by ncuts. Is it possible to specify a custom range (it may be useful when the probabilty distribution is concentrated on small values...).

**Comment by topepo** [comment]
Added. Here is an example:

    library(caret)
    
    set.seed(1)
    tr_dat <- twoClassSim(1000, intercept = 10)
    te_dat <- twoClassSim(1000)
    
    library(randomForest)
    set.seed(2)
    rf_mod <- randomForest(Class ~ ., data = tr_dat)
    
    library(MASS)
    lda_mod <- lda(Class ~ ., data = tr_dat)
    
    te_pred <- data.frame(Class = te_dat$Class,
                          rf = predict(rf_mod,  te_dat, type = "prob")[, 1],
                          lda =   predict(lda_mod, te_dat)$posterior[, 1])
    
    cobj1 <- calibration(Class ~ rf + lda, data = te_pred,
                         cuts = c(.1, .15, .2, .25, .4, .6))
    cobj2 <- calibration(Class ~ rf + lda, data = te_pred)

**Comment by spedygiorgio** [comment]
Thank you very much

Inviato da iPhone
