### ISSUE TITLE
how to train (and select) a model based on maximization of the AUC?  [question]

### ISSUE THREAD

**Issue by UnixJunkie** [topepo/caret#1026]
Hello,

The utility/target function I want is ROC-AUC.

How to train a model so that ROC-AUC is the target function?

Let's say I want to use the knn model.

Thanks a lot,
F.

**Comment by topepo** [comment]
This is covered in [the documentation](https://topepo.github.io/caret/model-training-and-tuning.html#alternate-performance-metrics)
