### ISSUE TITLE
fasten lift curve

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#103]
Is it possible to fasten the lift curve calculation, maybe using some approximations? It could be really very slow when the number of samples is big.

**Comment by topepo** [comment]
A new argument is added called `cuts` can now be used to control the threshold. For this code:

    library(caret)
    
    set.seed(1)
    tr_dat <- twoClassSim(1000)
    te_dat <- twoClassSim(10000)
    
    library(randomForest)
    set.seed(2)
    rf_mod <- randomForest(Class ~ ., data = tr_dat)
    
    library(MASS)
    lda_mod <- lda(Class ~ ., data = tr_dat)
    
    te_pred <- data.frame(Class = te_dat$Class,
                          rf = predict(rf_mod,  te_dat, type = "prob")[, 1],
                          lda =   predict(lda_mod, te_dat)$posterior[, 1])
    
    system.time(lobj1 <- lift(Class ~ rf + lda, data = te_pred))
    system.time(lobj2 <- lift(Class ~ rf + lda, data = te_pred, cuts = 100))
    system.time(lobj3 <- lift(Class ~ rf + lda, data = te_pred, cuts = c(.1, .1, .3, .4, .5)))

the speed-up for `cuts = 100` was 7-fold and 99-fold for the four unique cuts.
