### ISSUE TITLE
require R-3.5.0

### ISSUE THREAD

**Issue by r2evans** [topepo/caret#1041]
If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [ ] Start a new R session
- [ ] Install the latest version of caret: `update.packages(oldPkgs="caret", ask=FALSE)`
- [x] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [x] **Do not** use parallel processing in the code (unless you are certain that the issue is about parallel processing).
- [ ] run `sessionInfo()`

### Minimal, reproducible example:

Something `caret` does uses `utils::warnErrList`, which did not appear in R until R-3.5.0.

In a version of R before 3.5:

```r
> library(caret)
Error: package or namespace load failed for ‘caret’:
 object ‘warnErrList’ is not exported by 'namespace:utils'
```

I apologize for the incomplete question, I am posting the issue on behalf of a StackOverflow question: https://stackoverflow.com/questions/56367701. From my answer there:

> You can back this up by looking at the list of exported functions for [`utils` in R-3.5.0](https://www.rdocumentation.org/packages/utils/versions/3.5.0) and you can find `warnErrList`, whereas [`utils` in R-3.4.3](https://www.rdocumentation.org/packages/utils/versions/3.4.3) (the previous release of R), the function cannot be found.

(I've requested the SO/OP to add the results from `sessionInfo()` and `traceback()` to see what package is ultimately also under-requiring R. I don't have the older versions available, but if there is something else going on, my apologies.)

**Comment by topepo** [comment]
I'm pretty sure that updating `caret` to the current CRAN version would solve this.

**Comment by r2evans** [comment]
Huh, sorry about that! We'll see if the OP provides feedback to my outreach (https://stackoverflow.com/questions/56367701/cant-load-caret-in-r#comment99526532_56367701).

**Comment by topepo** [comment]
No problem.
