### ISSUE TITLE
"LOOCV" resample Rsqured values

### ISSUE THREAD

**Issue by AlirezaTafazzol** [topepo/caret#1045]
When running "LOOCV", how can you get the Rsquared and RMSE values for each model?
The output "resample" of LOOCV method is NULL. 
While, in the "lm" method without selection of any cross validation method (i.e., default of Bootstrapped method) gives values for resample.

**Comment by topepo** [comment]
There are not resamples for each model; there is a single value being predicted for each and performance  is computed using the pooled set of out-of-samples predictions.

**Comment by AlirezaTafazzol** [comment]
Is there a way to show those Rsquared values of each model?
I want to report that we have done leave-one-out analysis and the R square values for models were between A and B for example.

**Comment by topepo** [comment]
> Is there a way to show those Rsquared values of each model?

_There are not resamples for each model_

So if you run LOO on the `mtcars` data set with 32 rows, you create 32 model. Each of those is built on 31 data points and predicts the one left out. 

The 32 predictions that were held out are used to estimate R^2. There is only one R^2 value estimated.
