### ISSUE TITLE
e1071 package requirement 

### ISSUE THREAD

**Issue by labouz** [topepo/caret#1049]
Hello!
I tried to deploy a Shiny app that requires caret::confusionMatrix onto shinyapps.io. The app runs smoothly locally however deploying gives the following error in the app: 
![image](https://user-images.githubusercontent.com/25671683/60341082-5950b780-997b-11e9-9d89-4babf1e11d62.png)

and the following log (attached). 
[logs.txt](https://github.com/topepo/caret/files/3339083/logs.txt)

Is there a reason not to require this package vs suggests - so that caret can be used in shinyapps.io?

Thanks!

-Layla

**Comment by topepo** [comment]
You can solve this by explicitly loading `e1071`. From [this page](https://docs.rstudio.com/shinyapps.io/getting-started.html): 

> When you deploy your application, the rsconnect package detects the packages that your application uses by looking for explicit `library()` calls within your application.
