### ISSUE TITLE
Get the Error: cannot allocate vector of size 61.9 Gb

### ISSUE THREAD

**Issue by sfallahpour** [topepo/caret#1060]
So I have a data set with 500K records and 95 vars. There are 23 factorial vars with 4 of them having cardinality of 501, 111, 116, 70 and the rest of factorial vars with cardinality less than 5. The remaining variables are numerical. I have no missing observations and when i try to fit xgboost 

```
   xgbGrid=expand.grid(nrounds = 1000,
                     eta = c(0.01,0.05, 0.07, 0.1),
                     max_depth = c(4:14),
                     gamma=0,
                     colsample_bytree = c(0.75),
                     subsample = c(0.50),
                     min_child_weight =0 )


  trainCtrl <- trainControl(method = "repeatedcv",
                        number = 10,
                        repeats = 3,
                        classProbs=TRUE,
                        summaryFunction=twoClassSummary,
                        search = "grid",
                        sampling="down")  #rose, up, smote


   orig_fit <- train(isFraud~., data=train_final, 
                  method="xgbTree", 
                  tuneGrid=xgbGrid, 
                  metric="ROC", 
                  trControl=trainCtrl)

i get the following error:
**Error: cannot allocate vector of size 61.9 Gb**
```
my RAM mem is 32 GB and it is x64 bit system. Is there any way to fix this issue.

**Comment by topepo** [comment]
I assume that this is on windows. 

It is entirely possible that the data set is consuming enough memory that you have run out (once a new copy is made). Try running: `butcher::weigh(train_final, units = "GB")` once you have installed the `butcher` package
