### ISSUE TITLE
Feature request: Performance measure on joined test sets

### ISSUE THREAD

**Issue by denominator1** [topepo/caret#1061]
Hi,
In "mlr", one can get performance measures on *joined* test sets using the function "test.join". See https://mlr.mlr-org.com/reference/aggregations.html. I wonder if caret already provides such functionality (which I could not find) or if there exists a plan to implement it. Your help is much appreciated!

**Comment by topepo** [comment]
The docs don't explicitly describe what _joined_ means:

> Performance measure on joined test sets. This is especially useful for small sample sizes where unbalanced group sizes have a significant impact on the aggregation, especially for cross-validation test.join might make sense now. For the repeated CV, the performance is calculated on each repetition and then aggregated with the arithmetic mean.

Do you know? 

I would assume that they collect all of the holdout data into one data frame and compute performance on that. I wouldn't want to implement that though; I see their point about imbalanced samples but I think that it is more dangerous than helpful.
