### ISSUE TITLE
confusionMatrix feature request (value as third column)

### ISSUE THREAD

**Issue by angelini75** [topepo/caret#1066]
Dear all,

I would like to apply `confusionMatrix()` function to a dataframe that has three columns, such as
```
df <- data.frame(pred = sample(as.factor(1:9), size = 1000, replace = TRUE), 
           reference = sample(as.factor(1:9), size = 1000, replace = TRUE),
           area = runif(n = 1000, min = 10000, max = 50000)) # measured area in m²
```
`1:9` are categories of a classification 

I could convert `df` into a confusion matrix:
```
library(diplyr)
df %>% group_by(pred, reference) %>% summarise(area = sum(area, na.rm = T)) %>% 
spread(key = reference, value = area)

# A tibble: 9 x 10
# Groups:   pred [9]
  pred      `1`     `2`     `3`     `4`     `5`     `6`     `7`     `8`     `9`
  <fct>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>
1 1     283438. 300191. 370605. 467338. 325724. 340434. 419259. 411935. 307255.
2 2     374744. 334890. 372655. 291657. 373738. 374835. 414527. 348425. 397434.
3 3     315193. 458714. 260699. 652303. 204293. 499770. 488363. 520017. 297276.
4 4     212205. 318452. 223977. 373455. 313870. 549384. 385539. 367389. 307062.
5 5     616184. 272880. 328253. 402125. 473549. 256408. 414320. 339035. 295356.
6 6     543040. 294347. 502375. 438936. 300637. 361897. 377977. 289917. 601192.
7 7     507371. 485766. 288537. 521774. 306011. 123379. 268729. 310300. 643114.
8 8     372281. 466451. 377224. 287798. 223423.  86662. 267876. 361039. 461236.
9 9     427638. 380285. 337229. 416575. 320975. 292190. 355888. 400063. 463922.
```
It would be nice if any of these two forms could be provided as input for `confusionMatrix()` function.
_I am sorry if I am not aware of an existing function/argument to do this._

**Comment by topepo** [comment]
We wouldn't do this for `confusionMatrix()` since it is a special case. You could write a wrapper around that function for what you want (and add an extra argument). 

Is this related to #1071 ?

If you make a function to do this, you can access that extra column when resampling with `train()` when you use a recipe as the input. There is [an example in the docs](https://topepo.github.io/caret/using-recipes-with-train.html#an-example-1).

**Comment by angelini75** [comment]
Indeed, this issue is related to #1071 , sorry for not having found it before.
I did not know recipe package, but I will use it, thanks!
