### ISSUE TITLE
cannot find p values in "multinom" in caret

### ISSUE THREAD

**Issue by seymakalay** [topepo/caret#1068]
hello, assuming the following, reproducible example, how to get p values from caret in summary function, summary(glm.model) provides p values, but how can I get the pvalues for multinominal logit in caret?
Manny thanks in advance,
```
data("Fishing", package = "mlogit") ;head(Fishing)
set.seed(87)
inTrainingSet <- createDataPartition(Fishing$mode,p=.80,list=0)
Train <- Fishing[inTrainingSet,]
Test  <- Fishing[-inTrainingSet,]
myControl <- trainControl(method = "cv", 
                          number=10,
                          verboseIter = TRUE)


yy <- factor(Train$mode,levels = c( "beach", "pier", "boat","charter"))
xx <- Train[,2:10]

mmulti <- train(x=xx,
                 y=yy,
                 method = "multinom",
                 trControl = myControl,
                 tuneLength = 10)

summary(mmulti) 

multi.rrr = exp(t(coef(summary(mmulti)))) ; multi.rrr
```
ps: could not get any answer in  https://stackoverflow.com/questions/57622998/p-values-in-multinominal

**Comment by topepo** [comment]
`multinom` basically fits a neural network to do the estimation. They didn't work out the math for the strictly linear case so you can't directly get them using this implementation. 

After tuning, you could bootstrap that specific model to get empirical p-values (or maybe do a permutation test to get them too).
