### ISSUE TITLE
ModelLookUp doesn't see catboot object

### ISSUE THREAD

**Issue by Mvondoivan** [topepo/caret#1072]
```
library(caret)
library(caretEnsemble)
library(catboost)
```

I try to do a stacking model with catboost object model and others models but when I find if  catboost$method is in modelLookup() 

```
modelLookup() %>% filter(model=="catboost")
[1] model     parameter label     forReg    forClass  probModel
<0 lignes> (ou 'row.names' de longueur nulle)

models<-load(system.file("models", "models.RData", package = "caret"))
View(models)
```

Dont have catboost method but 

catboost$method gives me "custom"

**Comment by topepo** [comment]
It is not currently supported in `caret`. I'm going to wait until `catboost` is on CRAN to add it.
