### ISSUE TITLE
Caret Help

### ISSUE THREAD

**Issue by miketrevathan** [topepo/caret#1078]
Sorry for this message, but this is my last resort – my computer died (Windows) and I had to get a quick loaner (Mac), and I’ve been installing all the packages, etc. However, I cannot get ‘caret’ to install properly on the Mac, do you have any advice? See error message below (attached):

"Error: package or namespace load failed for ‘caret’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘data.table’ "

I did some Google searching, and tried the following: (this didn’t work either)
 
install.packages('caret', dependencies = TRUE)

R version is 3.6.1
RStudio is Version 1.2.5001

Thank you for any help or suggestions!

![Screen Shot 2019-10-06 at 10 28 02 AM](https://user-images.githubusercontent.com/55460711/66270659-0c0a9e80-e824-11e9-8264-ffee80e17f39.png)

**Comment by topepo** [comment]
Some dependency uses `data.table` and that didn't get installed. 

Try running 

```r
install.packages(c("caret", "data.table"), repos = "http://cran.r-project.org", dependencies = c("Depends", "Imports", "Suggests"))
```
It will take a while.
