### ISSUE TITLE
Interger, Ordinal, and Nominal variables

### ISSUE THREAD

**Issue by nipnipj** [topepo/caret#1079]
When using caret, do I need to transform Ordinal and nominal variables to multiple binary variables via "dummyVars( )"? Or does caret do this automatically when the variables are already defined via "factor( )" or "ordered( )"?

What about integer variables, is it better to define them as numeric?

**Comment by topepo** [comment]
It depends. If you use the formula method for `train()`, it does the same work as `model.matrix()` so you don't have to do anything extra. If you use `train(x, y)`, then _probably_. If you are using a tree- or rule-based model, then probably not. However, for most models you do need to convert them to dummy variables. 

There are a lot of options in the `recipes` package to do this (and you can use recipes with `train()`).
