### ISSUE TITLE
Preprocessing and prediction

### ISSUE THREAD

**Issue by nipnipj** [topepo/caret#1080]
Do I need to prepocess new data when predicting? Even when i used "preProc = c("center", "scale")" option when training the model?

**Comment by reubenkaiser** [comment]
The preProc option applies the preprocessing functions to the data being used before modelling.
`?caret::train`

**Comment by nipnipj** [comment]
So, when using "precict" function I do not need to preporcess the data, i.e., caret will use the same  transformations and operations estimated using "train" function.

Is this correct?

Thanks & Regards,

Joel
________________________________
De: reubenkaiser <notifications@github.com>
Enviado: lunes, 7 de octubre de 2019 20:54
Para: topepo/caret <caret@noreply.github.com>
Cc: nipnipj <ninjainpijama@outlook.com>; Author <author@noreply.github.com>
Asunto: Re: [topepo/caret] Preprocessing and prediction (#1080)


The preProc option applies the preprocessing functions to the data being used before modelling.
?caret::train

**Comment by reubenkaiser** [comment]
Sorry I misread your question and withdrew my answer. From the below source
I think predict.train will do preproc while predict will just run the model.

https://stats.stackexchange.com/questions/81609/is-preprocessing-needed-before-prediction-using-finalmodel-of-randomforest-with

**Comment by topepo** [comment]
> `predict.train` will do preproc while predict will just run the model.

Yes, this is true.
