### ISSUE TITLE
Interpretation of sensitivity and specificity in bwplot resamples function

### ISSUE THREAD

**Issue by LordRudolf** [topepo/caret#1081]
Hello,

This question is more related to interpretation than coding.

When we are comparing different models using resamples function we can plot the models via bwplot and compare their ROC, Sensitivty and Specificity. Here is example:

![image](https://user-images.githubusercontent.com/35683078/66806728-ea4e9d00-ef30-11e9-8fb6-caa12dbed936.png)
https://topepo.github.io/caret/model-training-and-tuning.html

While there are no questions regards the ROC but how can we interpret the results of sensitivity and specificity? 

1. First of all, which is which? We know that sensitivity shows the ability of a test to correctly identify events (TP / (TP + FN)), that is, proportion of actual positives which are identified as such. In a 2-class classification modelling, there are possible two outcomes, which may be outcome A and outcome B. How can I know whether bwplot has identified outcome A as positive, not negative, or vice verse?
2. Usually, sensitivity and specificity are measured with particular cutoff where it is clear what is TP and TN rate. In this case, no particular cutoff is given, therefore, the question is how does caret's resamples bwplot functions deals with it?

Thanks in advance.

**Comment by topepo** [comment]
For your first question, `caret` assumes that the event is the _first_ level of the factor outcome variable. You can change that if you want. See `?twoClassSummary` and `?sensitivity`

For the second question, the default is to use the 50% cutoff for two-class data sets.
