### ISSUE TITLE
bug in print.varImp.train

### ISSUE THREAD

**Issue by topepo** [topepo/caret#109]
library(caret)
    library(nnet)

    #read in data
    data = iris

    #split data into training, test, and final test samples
    trainIndex <- createDataPartition(data$Species, p=.80, list=F)
    train = data[trainIndex,]
    test = data[-trainIndex,]

    #train and plot model fit
    tree.fit = train(Species~., data=train, method="nnet")
    varImp(tree.fit)
    plot(tree.fit$finalModel)

    #predict test data
    tree.pred.test = predict(tree.fit, newdata=test)
    confusionMatrix(tree.pred.test, test$Species)

    > varImp(tree.fit)
    nnet variable importance

      variables are sorted by maximum importance across the classes
    Error in data.frame(`NA` = character(0), `NA` = character(0), `NA` = character(0),  : 
      row names supplied are of the wrong length
    In addition: Warning message:
    In format.data.frame(x, digits = digits, na.encode = FALSE) :
      corrupt data frame: columns will be truncated or padded with NAs
    > plot(tree.fit$finalModel)
    Error in xy.coords(x, y, xlabel, ylabel, log) : 
      'x' is a list, but does not have components 'x' and 'y'

**Comment by topepo** [comment]
done.

**Comment by zohrehmosleh** [comment]
I have the same problem. can you explain how i can overcome from this error.

**Comment by topepo** [comment]
You can [install the current github version](http://stackoverflow.com/questions/9656016/how-to-install-development-version-of-r-packages-github-repository) or just use the modified print function.

**Comment by zohrehmosleh** [comment]
If possible, please explain more. I install, but i receive error

**Comment by topepo** [comment]
It is difficult to help with no information about your system, what you did, or the error.

**Comment by zohrehmosleh** [comment]
what mean use the modified print function? can you help me?
