### ISSUE TITLE
SVM prediction error

### ISSUE THREAD

**Issue by rthapa26** [topepo/caret#1100]
Hi,

I am trying to use the SVM method. But got NAs while predicting from test data. Do you have any suggestions? I would appreciate it. Thanks a lot

library(kernlab)
model_svm<-train(nzv[index,],trainSet.y,method='svmRadial',trControl=fitControl,tuneLength=6)
testSet$model_svm <- predict(model_svm,testSet)
> testSet$model_svm <- predict(model_svm,testSet)
Warning message:
In method$predict(modelFit = modelFit, newdata = newdata, submodels = param) :
  kernlab class prediction calculations failed; returning NAs
> testSet$model_svm 
 [1] <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA>
[25] <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA> <NA>
Levels: N Y

**Comment by annnvv** [comment]
You probably have missing values in your dataset. See stackoverflow for a similar issue (generally the more appropriate place for questions like yours): https://stackoverflow.com/questions/42334759/r-svm-return-na-for-predictions-with-missing-data

**Comment by topepo** [comment]
or see your duplicate question in #1098
