### ISSUE TITLE
qrnn tau parameter in caret

### ISSUE THREAD

**Issue by minarikro** [topepo/caret#1111]
Is it possible to add qrnn tau parameter (user specified quantiles) into train and predict function of the caret package? To my understanding, only tau = 0.5 parameter is automatically used. 
e.g.
`qneuron.cox <- train(cox ~ ., data = data.train.cox,
                    method = "qrnn",
                    tuneLength = 2,
                    #trControl = control,
                    metric = "RMSE")`
`predict(qneuron.cox, newdata = data.test.cox[,-88])`
Where to add tau parameter?

**Comment by Steve-m611** [comment]
I also have this question.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.

**Comment by Steviey** [comment]
+1
