### ISSUE TITLE
Skip final model fitting

### ISSUE THREAD

**Issue by touala** [topepo/caret#1118]
Hello,

I have access to many compute nodes and would like to efficiently split the hyperparameters tuning on them. The easiest solution I found is simply to create many jobs with one or a couple of hyperparameters combinations, return the cross-validation results, and compare everything when all jobs are done. Is there a way to skip fitting the final model from the "best" set of hyperparameters?

I found [this stackoverflow thread](https://stackoverflow.com/questions/52966892/skip-fitting-the-final-model-with-caret) but I'm not sure those are currently the best solution.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.

**Comment by touala** [comment]
That's understandable. 

Have a good day and happy squashing!
