### ISSUE TITLE
Problems with omp.h dependency

### ISSUE THREAD

**Issue by gschiavone** [topepo/caret#1122]
Dear all, 

While I was installing caret in my 10.14 MAC OSX, I noticed that make failed because it couldn't find the dependency omp.h . Installing libomp via brew worked.

This is just the heads up to check whether openmp is present in the system before compilation.

Keep up the amazing work!

G.

**Comment by topepo** [comment]
Thanks for the note. This is more related to the other packages that get installed with `caret`
