### ISSUE TITLE
Add sampling for panel/nested data

### ISSUE THREAD

**Issue by maximilianpfau** [topepo/caret#1123]
For medical problems, it is common to have multilevel data, which was obtained in an unbalanced design.

Accordingly, it would be great to have besides of groupKFold for the patient ID (**PID**), a downsampling command for the training side of each fold. This would then ensure that the same amount of data per patient is used for training within each fold.

I tried to insert the following code as _"sampling"_ in _"trainControl("_, but that does not work (_"Error: sampling methods are only implemented for classification problems"_).

```
#Patient ID (PID) specific down sampling
PID_downsampling <- list(name = "PID_downsampling",
                         func = function (x, y) {
                           dat <- if (is.data.frame(x)) x else as.data.frame(x)
                           dat$.y <- y
                           
                           dat <- dat %>%
                             group_by(PID) %>% 
                             sample_n(20)

                           list(x = dat[, !grepl(".y", colnames(dat), fixed = TRUE)], y = dat$.y)
                           
                           },
                         first = TRUE)
```

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
