### ISSUE TITLE
foreach errorhandling argument in train_recipes

### ISSUE THREAD

**Issue by hermandr** [topepo/caret#1129]
When running many models, I encountered errors in train that quits.  
This is mainly due to ranger prediction on oob having nulls.
After I copied the train_recipes code to local and edited the foreach call and added the ".errorhandling" argument to "pass" it works great as errors encountered in one of the resample is passed and proceeded to the next resample instead of breaking.

For CV, the foreach is in line 412 and 413.

https://github.com/topepo/caret/blob/ede9913a465078dfaec5aeff2099676857c666e6/pkg/caret/R/train_recipes.R#L412

Can this be another parameter in trainControl to control whether to break out of the train test loop on error?

Herman

**Comment by topepo** [comment]
No. I want to avoid additional options and you can set this option when using the debugger or `browser()`.
