### ISSUE TITLE
Add n.minobsinnode to gbm tuning grid

### ISSUE THREAD

**Issue by zachmayer** [topepo/caret#113]
Right now the default is 10. I've found this parameter can have a big impact on the resulting model, and I think it'd be useful to have it in the `gbm` tuning grid.

We could keep the value fixed at 10, while still giving the user the option to set it in a custom `tuneGrid`.

**Comment by topepo** [comment]
Sure. Do you want to take a whack at it? After tomorrow, I'm out for about
8-9 days.

**Comment by topepo** [comment]
The code was checked-in and tested.
