### ISSUE TITLE
Error for LDA in Caret: Something is wrong; all the Accuracy metric values are missing

### ISSUE THREAD

**Issue by Lauraaas** [topepo/caret#1133]
Hi, 
I have seen a few similar issues as this, however I am new to coding and have been unable to work out how to resolve it from the answers. 
While carrying out an LDA analysis using Caret and the code:
```r
fit.lda1 <- train(Morphotype~., data=femdataframe, method="lda")

I keep getting this in return and I'm not too sure how to resolve the issue.

Something is wrong; all the Accuracy metric values are missing:
    Accuracy       Kappa    
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :1     NA's   :1    
Error: Stopping
In addition: There were 26 warnings (use warnings() to see them)

The warnings are all like this: 

1. model fit failed for Resample01: parameter=none Error in lda.default(x, grouping, ...) : 
  variables  1  2  3  5  6 10 12 23 25 27 32 36 39 42 47 50 52 53 58 63 64 appear to be constant within groups

26. In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  ... :
  There were missing values in resampled performance measures.
```
I hope you are able to offer advice! t
Thanks in advance!

**Comment by malleyne** [comment]
I have the same issue

platform       x86_64-pc-linux-gnu         
arch           x86_64                      
os             linux-gnu                   
system         x86_64, linux-gnu                  
version.string R version 4.0.0 (2020-04-24)

lattice is installed: version 0.20-41
ggplot2 is installed : version 3.31
caret is installed: version 6.0-86
i have uninstalled dplyr as per another read in here

I have no missing data
my target value is of type factor
my training data is a data frame. not a tibble



file <- "auto-mpg.data"
df <- read.table(file, header = TRUE)
names(df)
colnames(df) <- c("mpg", "cylinders", "displacement", "horsepower", "weight", "acceleration", "model year", "origin", "car name")
df <- data.frame(df)

df <- df%>% filter(horsepower != "?")
df$horsepower <- as.numeric(df$horsepower)
df$cylinders <- as.numeric(df$cylinders)
df$displacement <- as.numeric(df$displacement)
df$weight <- as.numeric(df$weight)
df$acceleration <- as.numeric(df$acceleration)
df$model.year <- as.numeric(df$model.year)
df$origin <- as.numeric(df$origin)
df$mpg <- factor(df$mpg) # y value must be a factor for caret

set.seed(1)
trainIndex <- createDataPartition(y=df$mpg, 
                                  p = .75, 
                                  list = FALSE)
train <- df[ trainIndex,]
test  <- df[-trainIndex,]

fit <- train(x = train[, 2:8],
             y = train$mpg, 
             method = "glm")


Warning messages:
1: model fit failed for Resample01: parameter=none Error in method$fit(x = x, y = y, wts = wts, param = tuneValue, lev = obsLevels,  : 
  glm models can only use 2-class outcomes

2: model fit failed for Resample02: parameter=none Error in method$fit(x = x, y = y, wts = wts, param = tuneValue, lev = obsLevels,  : 
  glm models can only use 2-class outcomes

**Comment by malleyne** [comment]
following up on the above here. Has a moderator had a chance to see this?

**Comment by topepo** [comment]
@Lauraaas This issue is in the warnings: 

> variables  1  2  3  5  6 10 12 23 25 27 32 36 39 42 47 50 52 53 58 63 64 appear to be constant within groups

Within each class, it needs more than one unique value for each predict to do the computations. 

@malleyne  it is a different issue and a different model (also spelled out in the warnings):

>  glm models can only use 2-class outcomes
