### ISSUE TITLE
Predictions for each tree in random forest using predict.train

### ISSUE THREAD

**Issue by alcantarar** [topepo/caret#1136]
Is there any any way to use `predict.train()` to make predictions for each tree in a random forest model trained using {caret}? 

If I used {randomForest} to train a model, I can use their [predict.randomForest method for random forest objects](https://www.rdocumentation.org/packages/randomForest/versions/4.6-14/topics/predict.randomForest) to extract predictions for each tree with the `predict.all = TRUE` argument. However, if I use {caret} to train a {randomForest} model, `predict.randomForest` doesn't work with `$finalModel` due to changes in the `finalModel$forest$xlevels` and `finalModel$forest$ncat` when using {caret}. 

Any ideas on how to get predictions for each tree in a random forest model? Ideally there's a general solution for other random forest models like `quantregForest`.

**Comment by topepo** [comment]
Sorry. It won't be able to do this. You could refit the final model outside of `caret` to get an object that would be able to get these predictions.

**Comment by alcantarar** [comment]
In case anyone else is interested in this, I have since found that a workaround (for the `quantregForest` type of models at least) is changing the model class to 'randomForest'. It allows for the prediction of all trees in the forest:
```
# Using iris dataset
library(caret)
library(randomForest)

# Train Model
qrf<- train(Sepal.Length~ Sepal.Width + Petal.Length, data = iris, method = 'qrf')

# Make Predictions
n_subs = 6
pred <- predict(qrf$finalModel, iris[1:n_subs,], predict.all = T)
# Returns quantiles for 100 predictions, one for each test input. 
# *May need to make categorical predictors numerical to work.*

# Changing class returns tree predictions in list:
class(qrf$finalModel) <- 'randomForest'
pred <- predict(qrf$finalModel, iris[1:n_subs,], predict.all = T)
# returns list of aggregated predictions (n_subs of them), individual predictions for each tree (n_subs x 500 trees):
# pred$aggregate
# pred$individual
```
This actually allows for some cool data visualization! You can see the variability within the forest in a predict vs observed plot:
```
# reshape individual tree predictions for ggplot
obs = iris$Sepal.Length[1:n_subs]
sub = 1:n_subs
tree_pred <- as.data.frame(pred$individual)
colnames(tree_pred) <- 1:500
tree_pred$obs <- obs
tree_pred$sub <- 1:n_subs
tree_pred_long <- gather(tree_pred, tree, pred, 1:500)

# reshape aggregate predictions for ggplot
agg <- aggregate(pred ~ obs + sub, data = tree_pred_long, FUN = mean)
colnames(agg) <- c('obs', 'sub', 'mean_pred')
pred_obs <- data.frame(pred = pred$aggregate, obs = obs)
pred_obs <- merge(pred_obs, agg, by = 'obs')

# plot distribution of tree predictions and aggregate prediction of final QRF model
ggplot(tree_pred_long) + 
  geom_abline(slope = 1, intercept = 0, lty = 2)+  # line of identity
  geom_density_ridges(aes(x = pred, y = obs, group = sub, fill = as.factor(sub)),
                      alpha = 0.2, color = 'black', rel_min_height = 0.02, size = 0.5)+
  geom_point(data = pred_obs, aes(x = pred, y = obs, fill = as.factor(sub)), pch = 21, size = 2)+
  theme_classic()+
  coord_fixed(xlim = c(4,6), ylim = c(4,6))+
  scale_y_continuous(breaks = seq(4,6,0.5))+
  scale_x_continuous(breaks = seq(4,6,0.5))
```

![image](https://user-images.githubusercontent.com/38192529/91685522-d34c7580-eb17-11ea-9fb9-88e7044a1db3.png)
