### ISSUE TITLE
Investigate irace package as an alternative to tune grids

### ISSUE THREAD

**Issue by zachmayer** [topepo/caret#114]
It looks like you can give [irace](http://cran.r-project.org/web/packages/irace/index.html) an upper and lower bound for each of your parameters, and it will automatically (and iteratively) search that space for good parameter sets.  It seems to support both qualitative (e.g. gbm$distribution must be in "gaussian", "bernoulli", etc) and quanitiative (e.g. gbm$n.trees must be between 1 and 100) parameters.

In particular, the [mlr package](https://github.com/berndbischl/mlr) uses irace, and in my testing it seems to work really well. (Although it's not yet aware of the "sub model" trick and can waste a lot of time fitting models it doesn't need).

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.
