### ISSUE TITLE
rfe: disable parameter sizes includes ncol(x) 

### ISSUE THREAD

**Issue by yPennylane** [topepo/caret#1148]
I want to perform `rfe` but the parameter sizes should not include ncol(x). I want to provide a maximum value for sizes without using ncol(x) automatically.

How can I disable that sizes includes ncol(x)?

    library(caret)

    dat <- as.data.frame(ChickWeight)

    # specify rfeControl
    contr <- caret::rfeControl(functions = rfFuncs, method="repeatedcv", number=2, repeats=1,
                               saveDetails = TRUE)

    # recursive feature elimination caret (Algorithm 2)
    set.seed(42, kind = "Mersenne-Twister", normal.kind = "Inversion")
    results <- caret::rfe(x = dat[,2:4], 
                          y = dat[,1],
                          sizes = 1, 
                          method ="rf",
                          ntree = 15, 
                          metric = "RMSE", 
                          rfeControl = contr)

How can I prevent rfe from using 3 predictors (ncol(x))? I have a huge predictor set of nearly 200.000 predictors, therefore I want to set the `sizes` parameter to a specific maximum value which should not be ncol(x).

**Comment by topepo** [comment]
RFE needs a set of models; `sizes = 1` doesn't seem appropriate. `rfe()` will always fit the largest model and do dilutions of predictors smaller than the full model. We won't be parameterizing that starting point because there are many possible permutations of models with less than `ncol(x)` inputs.
