### ISSUE TITLE
Error in seeds[[num_rs + 1L]] : subscript out of bounds in caret for LVQ.

### ISSUE THREAD

**Issue by ParnianJabbari** [topepo/caret#1156]
Hi!

I'm using caret to select important features to train my data. I'm trying to create a classifier on a dataset of 40 variables and 55 samples.
When I run the following codes I get the following error: 

[> set.seed(123)
> data=data2
> dim(data2)
[1] 55 40
> control <- trainControl(method="repeatedcv", number=5, repeats=10)
> model <- train(remission~., data=data2, method="lvq", preProcess="scale", trControl=control, importance=T)
Error in seeds[[num_rs + 1L]] : subscript out of bounds 

I have seen in previous threads that this issue can be solved with
tuneGrid = data.frame(size = 3, k = 1:2)

But I don't know how that works. Can you help me please?

**Comment by topepo** [comment]
Can you provide a reproducible example?

**Comment by topepo** [comment]
Closed due to inactivity
