### ISSUE TITLE
caret installation issue

### ISSUE THREAD

**Issue by avrenli2** [topepo/caret#1164]
Hello
I keep getting the following error message after I install the caret package.  I have a windows PC and the latest version of RStudio. 
 I would be grateful for your help.  Thank you, 
![14_fPortfolio_caret_load_errors](https://user-images.githubusercontent.com/62804852/87745361-ad634f80-c7bb-11ea-8bec-5994efcdcf6b.PNG)

**Comment by aadler** [comment]
Have you seen this on R-devel? https://stat.ethz.ch/pipermail/r-devel/2020-July/079798.html
Try reinstalling Rcpp.

**Comment by avrenli2** [comment]
Thanks for your response.
So should I run
*install.packages("Rccp")*
*library(Rccp)*
and then install the *caret* package again?

**Comment by aadler** [comment]
Just reinstalling should be enough if this is the issue. I don't think you need to load the package.

**Comment by topepo** [comment]
Closed due to inactivity
