### ISSUE TITLE
tunelength not work with ranger

### ISSUE THREAD

**Issue by woodysung** [topepo/caret#1168]
I found that when I use the tunelength argument and "ranger" to train a model, there will be error.
Below is the re-runable R-code:

```r
######################################################
##R-code#############################################
######################################################
######################################################
library(caret)
 
 set.seed(1)
 dat <- twoClassSim(100)
 



 set.seed(2)
 mod1 <- train(Class ~ ., data = dat, method = "ranger")   ### without tunelength is work####
 



 set.seed(2)
 mod2 <- train(Class ~ ., data = dat, method = "ranger", tunelength = 2 )    ### with tunelength is not work##########

########################################################

######################################################
##OUTPUT#############################################
######################################################
> set.seed(2)
>  mod1 <- train(Class ~ ., data = dat, method = "ranger")
> 
>  set.seed(2)
>  mod2 <- train(Class ~ ., data = dat, method = "ranger", tunelength = 2 )
Something is wrong; all the Accuracy metric values are missing:
    Accuracy       Kappa    
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :6     NA's   :6    
Error: Stopping
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> 
######################################################

######################################################
##sessionInfo#############################################
######################################################
> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=Chinese (Traditional)_Hong Kong SAR.950  LC_CTYPE=Chinese (Traditional)_Hong Kong SAR.950   
[3] LC_MONETARY=Chinese (Traditional)_Hong Kong SAR.950 LC_NUMERIC=C                                       
[5] LC_TIME=Chinese (Traditional)_Hong Kong SAR.950    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] ranger_0.12.1   caret_6.0-86    ggplot2_3.3.2   lattice_0.20-41

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.5           pillar_1.4.6         compiler_4.0.2       gower_0.2.2          plyr_1.8.6          
 [6] iterators_1.0.12     class_7.3-17         tools_4.0.2          rpart_4.1-15         ipred_0.9-9         
[11] lubridate_1.7.9      lifecycle_0.2.0      tibble_3.0.3         nlme_3.1-148         gtable_0.3.0        
[16] pkgconfig_2.0.3      rlang_0.4.7          Matrix_1.2-18        foreach_1.5.0        rstudioapi_0.11     
[21] yaml_2.2.1           prodlim_2019.11.13   e1071_1.7-3          stringr_1.4.0        withr_2.2.0         
[26] dplyr_1.0.2          pROC_1.16.2          generics_0.0.2       vctrs_0.3.2          recipes_0.1.13      
[31] stats4_4.0.2         nnet_7.3-14          grid_4.0.2           tidyselect_1.1.0     data.table_1.13.0   
[36] glue_1.4.1           R6_2.4.1             survival_3.2-3       lava_1.6.7           reshape2_1.4.4      
[41] purrr_0.3.4          magrittr_1.5         ModelMetrics_1.2.2.2 scales_1.1.1         codetools_0.2-16    
[46] ellipsis_0.3.1       MASS_7.3-52          splines_4.0.2        timeDate_3043.102    colorspace_1.4-1    
[51] stringi_1.4.6        munsell_0.5.0        crayon_1.3.4      
######################################################
```

**Comment by hermandr** [comment]
Your train call is a classification.
Have a look at the package testing code for ranger model here
https://github.com/topepo/caret/blob/6546939345fe10649cefcbfee55d58fb682bc902/RegressionTests/Code/ranger.R
Line 83 is test_class_rand
Have a look at the package testing results for ranger here:
https://github.com/topepo/caret/blob/6546939345fe10649cefcbfee55d58fb682bc902/RegressionTests/test_results/ranger.md
All the way down is the test results and there is no error.

May be tuneLength of 2 is too short, try 4?

**Comment by woodysung** [comment]
neither set the tuneLength of 2 or 4 have the below error.

> set.seed(2)
> mod2 <- train(Class ~ ., data = dat, method = "ranger", tunelength = 4 ) ### with tunelength is not work##########
Something is wrong; all the Accuracy metric values are missing:
    Accuracy       Kappa    
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :6     NA's   :6    
Error: Stopping
In addition: There were 50 or more warnings (use warnings() to see the first 50)




> warnings()
Warning messages:
1: model fit failed for Resample01: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

2: model fit failed for Resample01: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

3: model fit failed for Resample01: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

4: model fit failed for Resample01: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

5: model fit failed for Resample01: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

6: model fit failed for Resample01: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

7: model fit failed for Resample02: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

8: model fit failed for Resample02: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

9: model fit failed for Resample02: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

10: model fit failed for Resample02: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

11: model fit failed for Resample02: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

12: model fit failed for Resample02: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

13: model fit failed for Resample03: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

14: model fit failed for Resample03: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

15: model fit failed for Resample03: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

16: model fit failed for Resample03: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

17: model fit failed for Resample03: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

18: model fit failed for Resample03: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

19: model fit failed for Resample04: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

20: model fit failed for Resample04: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

21: model fit failed for Resample04: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

22: model fit failed for Resample04: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

23: model fit failed for Resample04: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

24: model fit failed for Resample04: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

25: model fit failed for Resample05: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

26: model fit failed for Resample05: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

27: model fit failed for Resample05: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

28: model fit failed for Resample05: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

29: model fit failed for Resample05: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

30: model fit failed for Resample05: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

31: model fit failed for Resample06: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

32: model fit failed for Resample06: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

33: model fit failed for Resample06: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

34: model fit failed for Resample06: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

35: model fit failed for Resample06: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

36: model fit failed for Resample06: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

37: model fit failed for Resample07: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

38: model fit failed for Resample07: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

39: model fit failed for Resample07: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

40: model fit failed for Resample07: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

41: model fit failed for Resample07: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

42: model fit failed for Resample07: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

43: model fit failed for Resample08: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

44: model fit failed for Resample08: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

45: model fit failed for Resample08: mtry=15, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

46: model fit failed for Resample08: mtry= 2, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

47: model fit failed for Resample08: mtry= 8, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

48: model fit failed for Resample08: mtry=15, min.node.size=1, splitrule=extratrees Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

49: model fit failed for Resample09: mtry= 2, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

50: model fit failed for Resample09: mtry= 8, min.node.size=1, splitrule=gini Error in ranger::ranger(dependent.variable.name = ".outcome", data = x,  : 
  unused argument (tunelength = 4)

**Comment by topepo** [comment]
> `unused argument (tunelength = 4)`

The argument name is `tuneLength`. Since you have it all lower case, it gets passed to `ranger`, where it causes the error.
