### ISSUE TITLE
DummyVars

### ISSUE THREAD

**Issue by nipnipj** [topepo/caret#1175]
Hello!

This is not an issue and I sorry for posting it here. I just wanted to get an answer for my questions from caret users or developers. 
My questions are: Do I need to use `dummyVars` even when I already defined categorical variables as `factor()` in R? Do `predict` and `train` functions transform categorical variables (`factor()`) to dummies automatically?

Thanks & regards!

**Comment by vanaris** [comment]
Hello, 

The short answer, I am finding out is , 'Yes'. some methods like PLS, MARS, NN, and ANN don't seem to require it, but it will impact RMSE, KAPPA, ROC, etc if you have near-zero frequency with large classes in your categories. 

If you do not use dummy variables, you will get resampling coercion warnings that lead to "something is wrong all *performance stat* are missing error for:
K-nearest neighbors, Elastic Net, Ridge, Lasso, Support Vector Machines, and pretty much all classification models. 

I've found that the following syntax is the easiest ways to implement this 

my_dummy<-model.matrix(my_response~., data=my_predictors)[,-1]
