### ISSUE TITLE
Rename AUC and ROC columns in twoClassSummary and prSummary

### ISSUE THREAD

**Issue by baderstine** [topepo/caret#1191]
In `twoClassSummary()`, the AUROC is output using variable name "ROC".
In `prSummary()`, the AUPRC is output using variable name "AUC".

In practice and widely on the internet (e.g., stackoverflow and/or crossvalidated, and elsewhere), the terms AUC and ROC are used interchangeably and most commonly refer to the "ROC" statistic output from `twoClassSummary()`.  

The choices of ROC and AUC as variable names for these outputs is 1) confusing, 2) not entirely accurate or descriptive, and 3) potentially misleading, especially for novice users or users who might not be paying close attention to source code or documentation, and who may think that that AUC/ROC output from these functions are both "AUROC".  

I suggest changing these variable names in the output of these functions to AUROC and AUPRC, respectively, to reduce confusion, be more accurate and descriptive, and to NOT mislead.  

In addition, I suggest adding a third summary function that combines the two to remove any doubt and provide more summary statistic choices for caret users:

```
combinedSummary <- function(data, lev = NULL, model = NULL) {
  out <- c(twoClassSummary(data, lev, model), prSummary(data, lev, model))
  names(out) <- gsub("AUC", "AUPRC", names(out))
  names(out) <- gsub("ROC", "AUROC", names(out))
  return(out)
}
```

**Comment by baderstine** [comment]
Or perhaps auROC and prAUC for clarity (as is used elsewhere in postResample.R - https://github.com/topepo/caret/blob/8159c8315402e44d50e97eec564b2f25da5dbc0d/pkg/caret/R/postResample.R#L254 )

**Comment by topepo** [comment]
Sorry for the inconsistency but the package is 15y old and I don't want to break backward compatibility.
