### ISSUE TITLE
Implementing/ supporting Ngboost in R 

### ISSUE THREAD

**Issue by athammad** [topepo/caret#1196]
Hi guys,
I have stumped across `Ngboost` from the [stanfordmlgroup](https://github.com/stanfordmlgroup/ngboost) , and I wondered if there is any plan to implement this great algorithm in `R` or enable some support to the `python` library directly within `caret` through `reticulate` for example.
I would love to use it with `caret`, and I believe it could be of great interest for all the R community.

Thanks

P.S.: I was unsure if it was a good idea to write a request for a new models using the project page since `ngboost` is not implemented yet in `R`.

**Comment by topepo** [comment]
It's not a bad idea. You are welcome do develop a [custom model]( https://topepo.github.io/caret/using-your-own-model-in-train.html) and add it via a pull request though.
