### ISSUE TITLE
Geographical random forest "SpatialML"

### ISSUE THREAD

**Issue by moquedace** [topepo/caret#1199]
Does anyone have any adaptation to use the geographical random forest ("SpatialML" package https://cran.r-project.org/web/packages/SpatialML/index.html) inside the caret?

For RFE and / or for training?

Although similar to randomforest it considers the x and y coordinates

Thank you

**Comment by topepo** [comment]
No. You are welcome do develop a [custom model]( https://topepo.github.io/caret/using-your-own-model-in-train.html) and add it via a pull request though.
