### ISSUE TITLE
undo dummyVars on a dataset

### ISSUE THREAD

**Issue by jkylearmstrong** [topepo/caret#1200]
Looking for a way to "undo" the predict method of the dummyVars - 

```{r}

dummyVars_map <- dummyVars(~, dat)

dat_dummy_transformed <- predict(dummyVars_map , dat)

```

Is there a function that does the following:
```{r}

predict(dummyVars_map , dat_dummy_transformed ) == dat

```

**Comment by topepo** [comment]
No. You could write one that found which column has the one in it, then pull off that column name.
