### ISSUE TITLE
Merging two immuarch objects

### ISSUE THREAD

**Issue by beginner984** [topepo/caret#1201]
Hello

I have several clone files from cancer I want to merge that

When I rbind the .txt file and use repload function I get 

`Error in dir.exists(.path[i]) : invalid filename argument
`

I tried to manually change the columns order and name in the merged data frame but I can not find matched column in immunarch object to adjust with my merged .txt file

Is this possible to merge immunearch objects?

Lets say I want to do `spectratype`

The function is `sp <- spectratype(immdata$data[[1]], .col="aa+v")
`
which we should select which sample we want to look while I want to look at all files together

Is there any way here?

Thank you so much for any help

**Comment by topepo** [comment]
I think that you have opened an issue in the wrong repository.
