### ISSUE TITLE
Error message when loading Caret/ cant found consufionMatrix function

### ISSUE THREAD

**Issue by jas-al** [topepo/caret#1217]
I get the following error message when loading the caret package:

> library(caret)
Loading required package: lattice
Loading required package: ggplot2
Need help? Try Stackoverflow: https://stackoverflow.com/tags/ggplot2
Error: package or namespace load failed for ‘caret’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘generics’
Además: Warning messages:
1: package ‘caret’ was built under R version 4.0.4 
2: package ‘ggplot2’ was built under R version 4.0.4 

Also, when trying to use the confusionMatrix function, R says it "can't find it". 

Does anyone know what the issue is?

**Comment by kstawiski** [comment]
You have updated R version, but packages were built using the old one.
Check `.libPaths()` and delete the directory with previous packages. In the next step use `install.packages('caret')` to do install it again.

Check also this out: https://stackoverflow.com/questions/3974488/after-i-upgrade-my-r-version-how-can-i-easily-reinstall-all-the-packages-that-w
