### ISSUE TITLE
Why caret triple my samples?

### ISSUE THREAD

**Issue by tozeki21** [topepo/caret#1220]
Hello.
I used train function to train my model. when I table the obs and pre classes, I got 3 X number of my samples.

         table(model$pred$obs)

I will reproduce it in the following lines

         data(iris)
         iris$setosa <- ifelse(iris$Species == "setosa", "Yes", "No")
         table(iris$setosa)
          No Yes
         100  50

         trainControl<- trainControl(method = "cv",
                                       number = 10,
                                       classProbs = TRUE,
                                       summaryFunction = twoClassSummary,
                                       verboseIter = TRUE,
                                       savePredictions = TRUE)
         set.seed(123)
         model<- train(setosa ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
                                       data = iris,
                                       method = 'rpart',
                                       trControl = trainControl,
                                       metric = "ROC")

         table(model$pred$obs)
          No Yes
         300 150

My guess that it will only create  100 No and 50 Yes. I appreciate any feedback?

**Comment by topepo** [comment]
It is tuning the model and defaults to three tuning parameter values. There is a set of predictions for each tuning parameter combination

``` r
library(caret)
#> Loading required package: lattice
#> Loading required package: ggplot2
data(iris)
iris$setosa <- ifelse(iris$Species == "setosa", "Yes", "No")
table(iris$setosa)
#> 
#>  No Yes 
#> 100  50

trainControl<- trainControl(method = "cv",
                            number = 10,
                            classProbs = TRUE,
                            summaryFunction = twoClassSummary,
                            verboseIter = FALSE,
                            savePredictions = TRUE)
set.seed(123)
model<- train(setosa ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
              data = iris,
              method = 'rpart',
              trControl = trainControl,
              metric = "ROC")

dplyr::count(model$pred, cp)
#>    cp   n
#> 1 0.0 150
#> 2 0.5 150
#> 3 1.0 150
```

<sup>Created on 2021-04-23 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0.9000)</sup>

You can change that using a different value of `savePredictions` though.
