### ISSUE TITLE
Why SMOTE option in trainControl function did not oversample my minor class in my imbalanced data?

### ISSUE THREAD

**Issue by tozeki21** [topepo/caret#1221]
Hello.
I used "sampling='smote'" in trainControl()  and the number of samples per class still the same. see my code below:

	data(iris)
	iris$setosa <- ifelse(iris$Species == "setosa", "Yes", "No")
	table(iris$setosa)
	 No Yes
	100  50

I train the model with/without SMOTE.
(1) 10-fold CV with SMOTE
(2) 10-fold CV without SMOTE
	
	#(1) SMOTE
	control.smote <- trainControl(method = "cv",
                                        number = 10,
                                        classProbs = TRUE,
                                        summaryFunction = twoClassSummary,
                                        sampling='smote',
                                        verboseIter = TRUE,
                                        savePredictions = "final")
	set.seed(123)
	fit.cart.smote <- train(setosa ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
                                       data = iris,
                                       method = 'rpart',
                                       trControl = control.usualcv.smote,
                                       metric = "ROC")
	#(2)  without SMOTE
	control.default <- trainControl(method = "cv",
                                       number = 10,
                                       classProbs = TRUE,
                                       summaryFunction = twoClassSummary,
                                       verboseIter = TRUE,
                                       savePredictions = "final")
	set.seed(123)
	fit.cart.default <- train(setosa ~ Sepal.Length + Sepal.Width + Petal.Length + Petal.Width,
                                       data = iris,
                                       method = 'rpart',
                                       trControl = control.default,
                                       metric = "ROC")

the total number of samples, were same with/without SMOTE .
	
	#(1) 10-fold CV with SMOTE
	table(fit.cart.smote$pred$obs)
	 No Yes
	100 50
	max(fit.cart.smote$results$ROC)
	 [1] 1
	#(2) 10-fold CV without SMOTE
	table(fit.cart.default$pred$obs)
	 No Yes
	100 50
	max(fit.cart.default$results$ROC)
	 [1] 1
Thank you

**Comment by topepo** [comment]
The results in the `pred` sub-objects` are from the holdout set of samples. Subsampling is only conducted on the data used to fit the model. 

Here is the breakdown for the first resample (on the data being used to fit the model): 

```
Browse[2]> # Before sampling: 
Browse[2]> table(y)
y
 No Yes 
 90  45 
```

and 

```
Browse[2]> # After sampling: 
Browse[2]> table(y)
y
 No Yes 
180 135 
```

**Comment by FADHLyemen** [comment]
@topepo 
Sorry, what is the y in table(y) function?

**Comment by topepo** [comment]
Sorry for the ambiguity; that's the outcome.
