### ISSUE TITLE
use themis::smote

### ISSUE THREAD

**Issue by topepo** [topepo/caret#1226]
The `DMwR` package is archived due to non-responsiveness. We should move to `themis::smote()` instead.

**Comment by EmilHvitfeldt** [comment]
I don't know if it will throw a wrench in this, but `smote()` is not exported from {themis} right now.

If you need I can export and do a CRAN update fairly fast

**Comment by topepo** [comment]
Ok. It would be good to export that so we can use it. I can do another release soon once that is changed and I've made the corresponding `caret` changes.

**Comment by hermandr** [comment]
Hi, when will caret be updated with themis::smote()?

**Comment by EmilHvitfeldt** [comment]
{themis} have been updated and pushed to CRAN
https://github.com/tidymodels/themis/releases/tag/v0.1.4
https://cran.r-project.org/web/packages/themis/index.html
