### ISSUE TITLE
Missing package e1071 from installation

### ISSUE THREAD

**Issue by merolagio** [topepo/caret#1238]
After installing v 6.0-88 from CRAN the call `caret::confusionMatrix` produces the error 
`Error: package e1071 is required`. Using R 3.6. I see it is in the suggest list, maybe it should be in the required for such a fundamental function?

Of course this can be fixed by fixing the package manually. It happened on two different Windows machines

**Comment by topepo** [comment]
Good idea. FYI CRAN imposes a limit on the number of imports that you can have but I'm not there yet.
