### ISSUE TITLE
ConfusionMatrix result  

### ISSUE THREAD

**Issue by Rnewbie** [topepo/caret#124]
Hi, ConfusionMatrix for both training set and 10-fold CV are the same, although there were no error when running the code. "C_Train.csv" data is available in https://github.com/Rnewbie/LikitMorganFP/blob/master/C_Train.csv
To check it, I did use weka GUI and it appear that confusion matrix of training set and 10-fold CV are different. This was also mentioned in stackoverflow.
http://stackoverflow.com/questions/28451376/traincontrol-in-caret-package?noredirect=1#comment45239703_28451376

```
> library(caret)
> fitControl <- trainControl(method= "none") 
> set.seed(1)
> Train <- read.csv("C_Train.csv", header= TRUE)
> y = Train$Activity
> x = Train[-1]
> fitControl <- trainControl(method= "none")
> fitJ48Train <- train(x = x, y =y, method = "J48", trControl = fitControl)
> fitControl <- trainControl(method= "repeatedcv", number = 10, repeats = 10)
> fitJ48cv_10 <- train(x = x, y =y, method = "J48", trControl = fitControl)
> Activity <- predict(fitJ48Train, newdata = Train)
> confusionMatrix(Activity, Train$Activity)
Confusion Matrix and Statistics

          Reference
Prediction Active Inactive
  Active       53       10
  Inactive     17       60
                                                                                    
> Activity <- predict(fitJ48cv_10, newdata = Train)
> confusionMatrix(Activity, Train$Activity) 
Confusion Matrix and Statistics

          Reference
Prediction Active Inactive
  Active       53       10
  Inactive     17       60
```

**Comment by topepo** [comment]
I think I just answered this on [SO](http://stackoverflow.com/questions/28451376/traincontrol-in-caret-package).

The only way that you would get different results between `fitJ48cv_10` and `fitJ48Train` is if they selected different models. For `J48`, there is one tuning parameter but `train` only fits one value of `C` by default. So both `fitJ48cv_10` and `fitJ48Train` yield exactly the same model and thus produce the same value when re-predicting the training set (or any other data set). 

BTW you will be much better off using `C5.0` instead of `J48`. The latter is an implementation of `C4.5` that is missing some key features while `C5.0` is more advanced and probably faster. 

Max

**Comment by Rnewbie** [comment]
Yes, Thank you. C5.0 is very fast. As expected the training set and 10-fold CV are different.

```
> library(caret)
> Train <- read.csv("C_Train.csv", header= TRUE)
> y = Train$Activity
> x = Train[-1]
> fitControl <- trainControl(method= "none")
> fitJ48Train <- train(x = x, y =y, method = "C5.0")
There were 50 or more warnings (use warnings() to see the first 50)
> 
> fitControl <- trainControl(method= "repeatedcv", number = 10, repeats = 10)
> c50Grid <- expand.grid(trials = 100, 
+                        model = 'tree', 
+                        winnow = TRUE)
> fitJ48cv_10 <- train(x = x, y =y, method = "C5.0", tuneGrid = c50Grid, trControl = fitControl)
> 
> Activity <- predict(fitJ48Train, newdata = Train)
> confusionMatrix(Activity, Train$Activity)
Confusion Matrix and Statistics

          Reference
Prediction Active Inactive
  Active       53       10
  Inactive     17       60
                                          
               Accuracy : 0.8071          

> Activity <- predict(fitJ48cv_10, newdata = Train)
> confusionMatrix(Activity, Train$Activity)
Confusion Matrix and Statistics

          Reference
Prediction Active Inactive
  Active       61       25
  Inactive      9       45
                                          
  Accuracy : 0.7571          
  
```
BTW, Please let me know when you come to Thailand, I want to get your signature on the Applied Predictive Modeling book. Kk.
