### ISSUE TITLE
confusionMatrix() should have arguments

### ISSUE THREAD

**Issue by hlydecker** [topepo/caret#1244]
The current caret::confusionMatrix() function is really great! Unfortunately, it is easy to make confusing mistakes when entering in data to the function. It would probably be easier if there were arguments for the predicted data and for the observed data, that way users can avoid confusing results.

Or at the least, the documentation for caret::confusionMatrix() should explain the order the data needs to be entered in.

**Comment by gdmcdonald** [comment]
It would be easier if the arguments were the more explicit `caret::confusionMatrix(prediction, reference)` rather than the current, confusing `caret::confusionMatrix(data, reference)`

**Comment by StatsGary** [comment]
Use ConfusionTableR wrapper for this.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by topepo** [comment]
@gdmcdonald The function takes a vector, matrix, or table as input.  The `data` argument was chosen to accommodate all of the formats. S3 methods don't really allow for different argument names for different input formats.   

The function is about 20 years old so we can't change the code without breaking a lot of scripts.
