### ISSUE TITLE
checkInstall not returning the pkg names when they're not found.

### ISSUE THREAD

**Issue by yobdoy** [topepo/caret#1246]
Hi,

Great work with the caret package!

I deployed a shiny app thru r Connect.  It was failing when doing `train` with `svmLinear`.  As the documentation states, package `kernlab` is required.  However, for a newbie like me, it can be very hard to understand the issue at hand.
    
    An error has occurred. Check your logs or contact the app author for clarification.

Since I'm not an admin, my only option were to check the logs:

    2021/08/04 14:12:04.404008496 Warning: Error in : Required package is missing
    2021/08/04 14:12:04.412768566   118: stop
    2021/08/04 14:12:04.412781386   117: checkInstall
    2021/08/04 14:12:04.412817143   116: train.default
    2021/08/04 14:12:04.412818485   114: train.formula

As you can see, the `checkInstall` function is not returning the `pkg` names that are not installed e.g. where `find.packages` returns a zero-length string.

Could you please update the `checkInstall` [here](https://github.com/topepo/caret/blob/77aab316c18ffb16324e17771b1a74fb170fca82/pkg/caret/R/modelLookup.R#L126) and [here ](https://github.com/topepo/caret/blob/77aab316c18ffb16324e17771b1a74fb170fca82/pkg/caret/R/modelLookup.R#L127)function so it returns the `pkg` names not found?  Trust me, it will save a lot of time for newbies like me using caret for the first time.

Thanks!

**Comment by topepo** [comment]
Sorry, that's a huge oversight. I've added a better message: 

```
tmp $ R CMD BATCH install_check.R
tmp $ cat install_check.Rout     

R version 4.1.0 (2021-05-18) -- "Camp Pontanezen"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(caret)
Loading required package: ggplot2
Loading required package: lattice
> 
> data(iris)
> TrainData <- iris[,1:4]
> TrainClasses <- iris[,5]
> 
> knnFit1 <- train(TrainData, TrainClasses,
+                  method = "kknn",
+                  preProcess = c("center", "scale"),
+                  tuneLength = 10,
+                  trControl = trainControl(method = "cv"))
Error: Required packages are missing: kknn
Execution halted
```

**Comment by yobdoy** [comment]
Thank you very much!
