### ISSUE TITLE
Add parameter documentation for `specificity`

### ISSUE THREAD

**Issue by ToeKneeFan** [topepo/caret#1265]
At the moment, the help documentation for `specificity` does not indicate which parameters are accepted by the function (although it is possible to find them using, for example, `getS3method`). Although one can infer from `negPredValue`, it might not be immediately obvious to the user that `specificity` accepts the `negative` parameter and not `positive`, resulting in silently erroneous results if `positive` is given explicitly rather than provided based on the levels of the factor.

**Comment by topepo** [comment]
That is an oversight. The documentation for `specificity()` needs an ` @rdname` directive in its file.
