### ISSUE TITLE
For XGBOOST can caret utilize "gpu_hist" for xgboost compiled with GPU support?

### ISSUE THREAD

**Issue by aadler** [topepo/caret#1279]
If I have finally successfully built `xgboost` with GPU support on Windows, so "gpu_hist" is valid when I run it directly in the `xgboost` package, is there any way to have caret access this functionality in the `xgbTree` method? It's near 30X faster on my computer! If not, can this become a feature request?

**Comment by aadler** [comment]
@topepo I haven't yet figured out how to build *caret* on my machine given its structure, but I'm hoping this simple PR is sufficient: #1310. If you could point me to how to build the package locally I can test personally (I built XGBOOST with GPU support, see https://github.com/dmlc/xgboost/issues/8190) but if the CI works that would indicate it's good, no?

**Comment by leedrake5** [comment]
It's not a caret problem, it's an XGBoost thing. You need to install a version of it with GPU support. They have os-specific binaries that will do it for you: 

> "We also provide experimental pre-built binary with GPU support. With this binary, you will be able to use the GPU algorithm without building XGBoost from the source. Download the binary package from the Releases page. The file name will be of the form xgboost_r_gpu_[os]_[version].tar.gz, where [os] is either linux or win64. (We build the binaries for 64-bit Linux and Windows.) Then install XGBoost by running:

> '''xgboost, Release 2.0.0-dev
    # Install dependencies
R -q -e 
> install.packages(c('data.table', 'jsonlite'))" 
> # Install XGBoost
> R CMD INSTALL ./xgboost_r_gpu_linux.tar.gz"'''

Releases page here: https://github.com/dmlc/xgboost/releases

Information in what model configurations have gpu support here: https://xgboost.readthedocs.io/en/stable/gpu/index.html

Note that caret is just a wrapper - I forked my own version to add max_delta_step and scale_pos_weight as variables: https://GitHub.com/leedrake5/caret. 

Have to stress - caret is just a nice wrapper. Everything needs to be done in XGBoost. 

Once everything is properly installed, make sure to use tree_method="gpu_hist" as an argument in train(). Any additional arguments you pass will by default go to xgboost.train, you can find those arguments here: https://xgboost.readthedocs.io/en/stable/parameter.html

**Comment by aadler** [comment]
@leedrake5 I understand. I'm sorry if I wasn't clear but I thought the l;inks I provided would explain.

I **built** XGBOOST with GPU support. Note the [XGBOOST issue](https://github.com/dmlc/xgboost/issues/8190) to which I linked; I found a bug, they fixed it, and I confirmed I can build it. Happy to send you the R package, but its 24MB AND built specifically for an NVIDIA RTX 3080 ([Ampere SM 86](https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/)) using CUDA 11.7. I've tested it on its own. It works and is 10 times faster than the default.

I have used caret for many years. I **know** caret is a wrapper, but *using* caret as the wrapper as of now does **not** expose the parameter needed to tell XGBOOST to use the GPU-enabled algorithm. For that matter, it doesn't even expose the more advanced CPU-only algorithm. The parameter name is "tree_method". Please see [here](https://xgboost.readthedocs.io/en/stable/parameter.html#parameters-for-tree-booster) and [here](https://xgboost.readthedocs.io/en/stable/treemethod.html) for more details. Therefore, by **not** exposing the parameter, I assume that the defaults apply which for XGBOOST is `tree_method = auto`. I would like to expose tree method as a changeable parameter not not an "optimizing" one, similar to `nrounds`. This way, the user can pass`hist` or `gpu_hist` **within** the caret wrapper if desired.

I believe this is what https://github.com/topepo/caret/pull/1310 does, but as I mentioned in the comments, I cannot build the R pacakge and test it locally without more detaiuled instructions, which is why I was asking @topepo to approve the CI workflow and test it.

Please let me know if there is anything else I can do to clarify. Thanks!

**Comment by leedrake5** [comment]
@aadler I guess I don't see the end goal here - are you trying to determine if gpu_hist is more or less accurate than hist? Seems like to do so just create a vector of tree_method's you would like to try, for loop, and then use your metric of choice to evaluate the results. To make caret accept it as a variable in its current grid searching framework you will need to fork the package and exit the XGBoost Tree script to accept more arguments. 

I can confirm on my end that (for Linux anyway) there is no problem using tree_method = "gpu_hist". Though unfortunately the R implementation doesn't allow you to choose which gpu.

**Comment by aadler** [comment]
@leedrake5 @topepo I think I misunderstood completely. I thought that the dots would not propagate through to the method itself. I was wrong. I can pass tree_method into the call directly and it works. My apologies. I will close this and the PR.
