### ISSUE TITLE
Troubleshooting 'Error in { : task 1 failed - "subscript out of bounds"' for gafs

### ISSUE THREAD

**Issue by andrewcstewart** [topepo/caret#129]
Wondering if I can get a quick sanity check on my syntax here.  I can provide a simulated dataset for reproducibility if need be, but I'm wondering first if I'm just doing something wrong at the syntax level.

This seems to work fine with other classifiers, so I'm wondering if it has something to do with caretGA+glmnet? 

```
caretGA$fitness_extern <- twoClassSummary
ctrl <- gafsControl(functions = caretGA,
                    metric = c(internal = "ROC", external = "ROC"),
                    verbose = TRUE,
                    allowParallel = TRUE,
                    method = "cv")

glmnet.gafs <- gafs(x = x,
            y = factor(y),
            gafsControl = ctrl,
            method = "glmnet")
```

Thanks for any advice.

**Comment by andrewcstewart** [comment]
Dataset for reproducibility:

```
set.seed(1234)
train.set <- twoClassSim(  300, noiseVars = 100, corrVar = 100, corrValue = 0.75)

caretGA$fitness_extern <- twoClassSummary
ctrl <- gafsControl(functions = caretGA,
                    metric = c(internal = "ROC", external = "ROC"),
                    verbose = TRUE,
                    allowParallel = TRUE,
                    method = "cv")

glmnet.gafs <- gafs(x = train.set,
            y = train.set$Class,
            gafsControl = ctrl,
            method = "glmnet")
```

**Comment by topepo** [comment]
Without doing much digging, my guess is that the lack of a `trainControl` object to 

  1. tell `train` to generate class probabilities and
  2. calculate the ROC statistic for the inner resampling

Give that a try (see [this example](http://appliedpredictivemodeling.com/blog/2015/1/3/cq50uv5se21lut7dh0ybfaooiqpezu)) and let me know if it works. 

Max

**Comment by andrewcstewart** [comment]
Thanks Max.  I thought that might be it as well and tried as you suggested with the same result.  

It's a bit confusing figuring out what goes where with these wrapper methods, but I believe the syntax should look like this?

```
caretGA$fitness_extern <- twoClassSummary
ctrl <- gafsControl(functions = caretGA,
                    metric = c(internal = "ROC", external = "ROC"),
                    verbose = TRUE,
                    allowParallel = FALSE,
                    method = "cv")

sim1.glmnet.gafs <- gafs(x = sim1.train.set,
                    y = sim1.train.set$Class,
                    gafsControl = ctrl,
                    trControl = trainControl(method = "cv", classProbs = TRUE),
                    method = "glmnet",metric="ROC")
```

**Comment by topepo** [comment]
A few things come up for this example:

 * First, using a wrapper feature selector with a model that internally does strong feature selection probably isn't a great idea. You have two methods of doing the same thing and they might get in the way of each other. 
 * You are using `x = sim1.train.set` which includes the outcome column. See below for syntax to get rid of it
 * For these data, the default grid doesn't do a great job. It seems to like small amounts of regularization. 
 * You probably want to center and scale the predictors too
 * For `trainControl, you need to add `summaryFunction = twoClassSummary` to get the ROC scores
 * Also, for `trainControl` you might want to add `allowParallel = FALSE` so that you don't square the number of workers

Here is some working syntax with reduced arguments for speed:

```r
library(caret)
library(doMC)
registerDoMC(cores=5)
set.seed(1234)
train.set <- twoClassSim(  300, noiseVars = 100, corrVar = 100, corrValue = 0.75)

tmp <- caretGA
tmp$fitness_extern <- twoClassSummary

gaCtrl <- gafsControl(functions = tmp,
                      metric = c(internal = "ROC", external = "ROC"),
                      verbose = TRUE,
                      allowParallel = TRUE,
                      method = "cv", number = 2)

tCtrl = trainControl(method = "cv", classProbs = TRUE,
                     summaryFunction = twoClassSummary,
                     allowParallel = FALSE)


glmnGrid <- expand.grid(alpha = c(0.05, seq(.1, 1, by = 0.05)),
                        lambda = c(.001, .01, .1, 1))

set.seed(1)
glmnet.gafs <- gafs(x = train.set[, names(train.set) != "Class"],
                    y = train.set$Class,
                    gafsControl = gaCtrl,
                    trControl = tCtrl,
                    popSize = 10,
                    iters = 3,
                    method = "glmnet",
                    preProc = c("center", "scale"),
                    tuneGrid = glmnGrid,
                    metric="ROC")
```

**Comment by andrewcstewart** [comment]
Thanks @topepo , I got this to work with your advice.

I think the main culprit here was the class labels in the training data.frame.  It's also a little confusing where to set train control, wrapper control and training parameters in these wrapper methods, so your example above illustrating all 3 is very informative.  Thanks again.

Good point on glmnet.  I think what might actually be more useful there is some sort of genetic feature ranking to search the optimal ordering going into glmnet.
