### ISSUE TITLE
glmnet prediction defaults to first lambda value if glmnet did not save coefficients for lambdaOpt

### ISSUE THREAD

**Issue by pgswartz** [topepo/caret#130]
glmnet sometimes returns a matrix of predicted probabilities / classes / link values, rather than a vector that corresponds to predictions using the 'best' lambda (however chosen).  This occurs when ```lambdaOpt``` does not correspond to one of the lambda's which glmnet has iterated through and stored optimal betas for.  In such a case, ```predict.glmnet``` just returns predictions for all lambda values.  I believe this case is usually related to glmnet not storing optimal betas for more than the first 100 lambdas in the tune grid, even if iterating through more 100.

The approach taken in caret, if I'm understanding correctly, is to just take the first column of predictions in such a case.  Looking at predict implementation, line 65 of models/files/glmnet.R, I see:
```
if(is.matrix(out)) out <- out[,1]
```

Fundamentally, I believe the issue is related to glmnet rather than caret, but I'm wondering if, for caret's purposes, it might be reasonable to take the lambda stored in ```finalModel$lambda``` that is closest to ```lambdaOpt``` rather than effectively taking the first lambda.  Happy to make a pull request for this if that'd be helpful!

As I further investigate glmnet, I may also have a cleverer solution related to storing more lambda values / beta coefficients.  In that case, we would have a less hacky solution than the one I'm proposing.

Thanks!
PGS

**Comment by topepo** [comment]
I'll take a look at this in detail within the next few days. Thanks for sending it in.

**Comment by pgswartz** [comment]
Thanks!  Please let me know if I can provide more info / help out.

**Comment by topepo** [comment]
PGS,

Thanks for the email. Below is a summary of what is happening inside of `train` with the `glmnet`. 

First is some data and a call:

```r
dat <- twoClassSim(100)
mod <- train(Class ~ ., data = dat, "glmnet", preProc = c("center", "scale"))
``` 

Inside the `fit` module, `glmnet` is called without restriction on `lambda`. For `train` and these data, the first value of `lambda` to be evaluated during cross-validation is:
```
Browse[1]> modelFit$lambdaOpt
[1] 0.03636149
```
In the `predict` module, for classification, this is the initial predicted object:
```r
 out <- predict(modelFit, newdata, s = modelFit$lambdaOpt, type = "class")
```
and it looks like this:
```
Browse[1]> head(out)
   1       
1  "Class1"
7  "Class2"
8  "Class2"
11 "Class2"
13 "Class2"
15 "Class1"
Browse[1]> class(out)
[1] "matrix"
Browse[1]> dim(out)
[1] 37  1
```

The reason for the subsequent 
```r
if(is.matrix(out)) out <- out[,1]
```
is that the prediction module expects predictions for one `lambda` at a time. Note that the `glmnet` model is not refit again if it can extract more `lambda`s from this model object. That is the whole "sub-model trick" that we use for a lot of techniques and that code starts when you see this loop:

```r
if(!is.null(submodels)) {
```

So the code is not taking the first `lambda` in `glmnet`'s possible coefficient path, it is just the first (and only) element of the matrix corresponds to the current `lambda` being evaluated. The disconnect is probably from me calling it `modelFit$lambdaOpt` when it is currently just the one under evaluation. 

Does that make sense?

Thanks,

Max

**Comment by pgswartz** [comment]
Max,

Thank you for spending the time to walk me through that!  Apologies for the delay in response, was going through the caret code.  To confirm, the "sub-model" trick to which you're referring is as explained in ```caret/pkg/caret/R/train.default.R``` in the comment on lines 189+?

In that context, I was curious about how the bestTune parameter was being passed to glmnet for prediction with the final model. If, for example, I run 
```
library('caret')
set.seed(123)
dat <- twoClassSim(100)
mod <- train(Class ~ ., data = dat, "glmnet", preProc = c("center", "scale"))
```
I get (in this case):
```
> mod$bestTune
  alpha lambda
1   0.1    0.1
```
But I don't see these exact lambda value specified in bestTune in the values returned by ```mod$finalModel$lambda```.  Instead, I see:
````
  [1] 1.8476592460 1.6835182910 1.5339591660 1.3976864614 1.2735198484
  [6] 1.1603838550 1.0572985515 0.9633710622 0.8777878322 0.7998075805
 [11] 0.7287548794 0.6640143044 0.6050251037 0.5512763410 0.5023024703
 [16] 0.4576793032 0.4170203353 0.3799733981 0.3462176087 0.3154605905
 [21] 0.2874359411 0.2619009243 0.2386343680 0.2174347485 0.1981184447
 [26] 0.1805181481 0.1644814134 0.1498693379 0.1365553590 0.1244241573
 [31] 0.1133706581 0.1032991213 0.0941223120 0.0857607452 0.0781419970
 [36] 0.0712000774 0.0648748587 0.0591115551 0.0538602474 0.0490754515
 [41] 0.0447157237 0.0407433020 0.0371237793 0.0338258051 0.0308208138
 [46] 0.0280827777 0.0255879811 0.0233148154 0.0212435914 0.0193563693
 [51] 0.0176368028 0.0160699979 0.0146423835 0.0133415945 0.0121563641
 [56] 0.0110764262 0.0100924270 0.0091958436 0.0083789102 0.0076345509
 [61] 0.0069563185 0.0063383383 0.0057752578 0.0052621998 0.0047947205
 [66] 0.0043687707 0.0039806612 0.0036270302 0.0033048148 0.0030112242
 [71] 0.0027437153 0.0024999712 0.0022778807 0.0020755200 0.0018911366
 [76] 0.0017231332 0.0015700548 0.0014305755 0.0013034871 0.0011876889
 [81] 0.0010821779 0.0009860402 0.0008984431 0.0008186279 0.0007459032
 [86] 0.0006796392 0.0006192620 0.0005642484 0.0005141222 0.0004684490
 [91] 0.0004268332 0.0003889146 0.0003543645 0.0003228837 0.0002941996
 [96] 0.0002680637 0.0002442497 0.0002225512 0.0002027804 0.0001847659
````
May I ask you to point me at how the ```bestTune``` values are being used to generate the final predictions?  The origin of my filed issue is that I'm not sure how the bestTune values were being translated into selection of the lambda for the finalModel.

With thanks and regards,
Peter

**Comment by topepo** [comment]
Normally, the `predict` module that `train` uses would use a model that has the final parameter "built-in". I don't remember the details for `glmnet` but there was a technical reason why this wouldn't work. That's were the `lambdaOpt` bit came in. We attached the final lambda value to the `glmnet` object and, in the predict module, use:
```r
out <- predict(modelFit, newdata, s = modelFit$lambdaOpt)
```
Even though `modelFit` is a `glmnet` object that can predict from many possible lambda values, we only get predictions from this one. `predict.glmnet` handles how that happens. 

(One question I get sometimes (for `rpart` models) is "why are you predicting using a `cp` value not observed in the model?". The same thing can happen with `glmnet`; there is a path of possible lambda values that are possible for a given data set. The value of  `lambdaOpt` might not be in that path because it was chosen via resampling from a pre-specificed grid. It's not that big of a deal but I do get questions about it.)

So, to finally answer your question: `bestTune` values are not directly used for this particular model; the optimized `alpha` is "baked into" the final model object and the amount of regularization used in prediction comes from `lambdaOpt` where 

```r
finalModel$lambdaOpt <- bestTune$lambda
```

**Comment by pgswartz** [comment]
Max,
That answers my question exactly!  Thank you for your time and the great library.
With thanks and regards,
Peter
