### ISSUE TITLE
consider adding PRIM

### ISSUE THREAD

**Issue by topepo** [topepo/caret#131]
<pre>
prim: Patient Rule Induction Method (PRIM)

PRIM for bump hunting in high-dimensional data

Version:    1.0.15
Depends:    R (≥ 2.10.0)
Imports:    rgl (≥ 0.66), misc3d (≥ 0.4-0)
Suggests:   MASS
Published:  2014-11-04
Author: Tarn Duong
Maintainer: Tarn Duong <tarn.duong at gmail.com>
License:    GPL-2 | GPL-3
URL:    http://www.mvstat.net/tduong
NeedsCompilation:   no
In views:   Multivariate
CRAN checks:    prim results
</pre>

**Comment by dashaub** [comment]
@topepo While reading Elements of Statistical Learning(Hastie, Tibshirani, Friedman), I saw section 8.9 on PRIM and upon checking that it isn't in "caret" thought about implementing this, so I'm glad to see it fits your plans as well. However, it looks like the `prim.box` function offered in the "prim" package is suited for unsupervised learning, although I could think of a modification to apply this to supervised classification; it's unclear to me that this technique could be applied to regression readily.

Essentially the technique labels hypercubes with abnormally high concentrations of high values or low values. This can be set with the `threshold.type` argument, so this should be a tunable parameter with acceptable values `c(-1L, 1L)`. To use both thresholds, this can be set to `0L`, but in practice this will cause overlapping boxes that must be reconciled; I believe this problem would also be far more common in high-dimension data, so it's probably best avoided. Classification could be obtained by labeling all points inside boxes with high density with the positive class and all other points with the negative class. Alternatively points outside the box could be randomly assigned according to the training proportion in the positive class outside of the high density boxes. If the negative threshold is used, we'd label points with the negative class label and all others with the positive label. To output class probabilities instead or class predictions, we'd use the same methodology of CART terminal leaf proportions.

Finally, the `peel.alpha` and `paste.alpha` parameters should also be tunable, although I need to read Friedman & Fisher (1999) to determine a plausible range for these.

So in addition to the standard caret template, this will need to have a supervised method and prediction wrapper built along with an object to hold the needed information beyond the standard `prim` object returned by `prim.box()`. This is on my radar for the next month, but progress won't be immediate.

**Comment by dashaub** [comment]
Upon more thought, creating the wrapper and supervised methods in a separate package "supervisedPRIM" might make sense. `train()` can then easily call `predict.supervisedprim()` with all the needed tunable parameters easily exposed and prepared for classification.

**Comment by topepo** [comment]
That would be great. Let me know if you need a hand.

**Comment by dashaub** [comment]
I've submitted a package "supervisedPRIM" to CRAN for this, so I'll start working on the caret template next.

**Comment by topepo** [comment]
Excellent! Let me know you you have any question.

**Comment by topepo** [comment]
in `caret` currently
