### ISSUE TITLE
Earth package training issue

### ISSUE THREAD

**Issue by bachlaw** [topepo/caret#133]
Caret's implementation of this package does not seem to support interactions (the degree=2) option. The detection of those interactions is a large part of earth's value.  Instead, I get this error message:

![weights](https://cloud.githubusercontent.com/assets/11594064/6813688/8210e214-d245-11e4-8a32-8498cc554d42.JPG)

I also get the same error message when I try to use weights for an earth call within train.

Weights are a recent addition to earth, and I have alerted the package author to the issue as well.

**Comment by topepo** [comment]
That has not the case to date. Please give us a reproducible example.

**Comment by topepo** [comment]
These test cases worked fine. Please open a new issue if you have an example that we can test with.

thanks,

Max

```r
## from ?train
library(mlbench)
data(BostonHousing)

madSummary <- function (data,
                        lev = NULL,
                        model = NULL) {
  out <- mad(data$obs - data$pred, 
             na.rm = TRUE)  
  names(out) <- "MAD"
  out
}

robustControl <- trainControl(summaryFunction = madSummary)
marsGrid <- expand.grid(degree = 1:2, nprune = (1:10) * 2)

set.seed(1)
earthFit <- train(medv ~ .,
                  data = BostonHousing, 
                  method = "earth",
                  tuneGrid = marsGrid,
                  metric = "MAD",
                  maximize = FALSE,
                  trControl = robustControl)


###################################################################

set.seed(2)
dat <- twoClassSim(100)

set.seed(3)
class_mod <- train(Class ~ ., data = dat, 
                   method = "earth",
                   tuneGrid = marsGrid)
```
