### ISSUE TITLE
trainControl for cforest with method OOB

### ISSUE THREAD

**Issue by prise6** [topepo/caret#141]
Hi everyone ! 
Thank you for this package. Really.

I think there is an issue when you use "cforest" with out-of-bag estimate in the `trainControl` function. I don't think the option "OOB" is on TRUE when computing predictions. 
Here is an example :
```
data(iris)

# delete some data to create more errors
iris = iris[-c(1:40),]

set.seed(123)
fitControl <- trainControl(classProbs = T, method = "oob")
(mod <- train(Species ~ ., data = iris,
             method = "cforest",
             tuneGrid = data.frame(mtry = 2),
             trControl = fitControl,
             controls = cforest_control(trace = F, ntree = 200, mincriterion=0)))
# Accuracy : 0.955

table(iris$Species, predict(mod))
(9+47+48)/(9+47+48+1+2+3) # 0.95

table(iris$Species, predict(mod$finalModel, OOB = T))
(8+47+46)/(8+47+46+2+4+3) # 0.92
```
Well, this example is not obvious, but on larger dataset it is.

Could you explain this choice ?
Thank you.

**Comment by topepo** [comment]
The `OOB` option in the `predict` function is used for re-predicting the training set. `predict.train` always calls the underlying predict method with a non-null `newdata` object so this option isn't very meaningful for this context. 

Note that there is a method for getting OOB estimates (and bypassing the OOB predictions):

```r
cforestStats <- function (x) {
    library(party)
    obs <- x@data@get("response")[, 1]
    pred <- predict(x, x@data@get("input"), OOB = TRUE)
    postResample(pred, obs)
}
## usage:
caret:::cforestStats(mod$finalModel)
```

**Comment by prise6** [comment]
Thank you for your answer.
But i'm still confused, correct me if i'm wrong: For `cforest` object, to obtain OOB predictions you have to set `newdata` option to `predict` function to NULL. If It's not, the OOB option is just ignored. And there is no other way to compute OOB estimates... (anyway, i didn't read the contrary and example of the party package does that)

So in my opinion : 
`predict(cforest, newdata = traindata, OOB = T ` give same result as `predict(cforest, newdata = traindata, OOB = F)`, as well as : ` predict(cforest, newdata = traindata)`.
But to obtain OOB, i do : 
`predict(cforest, newdata = NULL, OOB = T)`

That's why my first message and my confusion to the method "oob" in `trainControl` function.
