### ISSUE TITLE
with method='dnn' doesn't work classifying as below

### ISSUE THREAD

**Issue by oliverwreath** [topepo/caret#142]
grid <- expand.grid(layer1 = 1:5,
                   layer2 = 0:3,
                   layer3 = 0:3)
grid$hidden_dropout <- 0
grid$visible_dropout <- 0

# 'modelInfo' is found in the dnn.R file prior to
# next caret release. 
TrainData = c(1,2,3,4,5)
TrainClasses = c(1,2,3,4,5)

dnnFit1 <- train(TrainData, TrainClasses,
                 method = 'dnn',
                 preProcess = c("center", "scale"),
                 tuneGrid = grid,
                 trControl = trainControl(method = "cv"))

> grid <- expand.grid(layer1 = 1:5,
+                    layer2 = 0:3,
+                    layer3 = 0:3)
> grid$hidden_dropout <- 0
> grid$visible_dropout <- 0
> 
> # 'modelInfo' is found in the dnn.R file prior to
> # next caret release. 
> TrainData = c(1,2,3,4,5)
> TrainClasses = c(1,2,3,4,5)
> 
> dnnFit1 <- train(TrainData, TrainClasses,
+                  method = 'dnn',
+                  preProcess = c("center", "scale"),
+                  tuneGrid = grid,
+                  trControl = trainControl(method = "cv"))
Error in train.default(TrainData, TrainClasses, method = "dnn", preProcess = c("center",  : 
  final tuning parameters could not be determined
In addition: Warning messages:
1: In nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo,  :
  There were missing values in resampled performance measures.
2: In train.default(TrainData, TrainClasses, method = "dnn", preProcess = c("center",  :
  missing values found in aggregated results
>

**Comment by topepo** [comment]
The `x` argument cannot be a vector. From `?train`:

```
x: an object where samples are in rows and features are in columns.
This could be a simple matrix, data frame or other type (e.g. sparse 
matrix). 
```

This works:

```r
dnnFit1 <- train(data.frame(x = TrainData), TrainClasses,
                 method = 'dnn',
                 preProcess = c("center", "scale"),
                 tuneGrid = grid,
                 trControl = trainControl(method = "cv"))
```
