### ISSUE TITLE
caret installation does not install all dependences

### ISSUE THREAD

**Issue by trebi** [topepo/caret#153]
After I execute `install.packages('caret')` on fresh installation of R 3.2.0 and RStudio 0.98.1103 on Windows 7 x64, some dependences did not get installed and I need to install them manually afterwards  with `install.packages("ggplot2", "stringr", "munsell", "BradleyTerry2", "minqa", "nloptr")`

Here is R console output:

	R version 3.2.0 (2015-04-16) -- "Full of Ingredients"
	Copyright (C) 2015 The R Foundation for Statistical Computing
	Platform: x86_64-w64-mingw32/x64 (64-bit)

	R is free software and comes with ABSOLUTELY NO WARRANTY.
	You are welcome to redistribute it under certain conditions.
	Type 'license()' or 'licence()' for distribution details.

	  Natural language support but running in an English locale

	R is a collaborative project with many contributors.
	Type 'contributors()' for more information and
	'citation()' on how to cite R or R packages in publications.

	Type 'demo()' for some demos, 'help()' for on-line help, or
	'help.start()' for an HTML browser interface to help.
	Type 'q()' to quit R.

	> install.packages("caret", dependencies = c("Depends", "Suggests"))

			...

			bunch of trying URL ...

			...
			
	trying URL 'http://mirrors.nic.cz/R/bin/windows/contrib/3.2/caret_6.0-47.zip'
	Content type 'application/zip' length 4023497 bytes (3.8 MB)
	downloaded 3.8 MB

	package 'BRugs' successfully unpacked and MD5 sums checked
	package 'rjags' successfully unpacked and MD5 sums checked
	package 'R2WinBUGS' successfully unpacked and MD5 sums checked
	package 'SuppDists' successfully unpacked and MD5 sums checked
	package 'maxlike' successfully unpacked and MD5 sums checked
	package 'R2jags' successfully unpacked and MD5 sums checked
	package 'R2OpenBUGS' successfully unpacked and MD5 sums checked
	package 'gmp' successfully unpacked and MD5 sums checked
	package 'emdbook' successfully unpacked and MD5 sums checked
	package 'MuMIn' successfully unpacked and MD5 sums checked
	package 'AICcmodavg' successfully unpacked and MD5 sums checked
	package 'Rmpfr' successfully unpacked and MD5 sums checked
	package 'bbmle' successfully unpacked and MD5 sums checked
	package 'partitions' successfully unpacked and MD5 sums checked
	package 'polynom' successfully unpacked and MD5 sums checked
	package 'rugarch' successfully unpacked and MD5 sums checked
	package 'mvnormtest' successfully unpacked and MD5 sums checked
	package 'isa2' successfully unpacked and MD5 sums checked
	package 'MplusAutomation' successfully unpacked and MD5 sums checked
	package 'GPArotation' successfully unpacked and MD5 sums checked
	package 'mnormt' successfully unpacked and MD5 sums checked
	package 'copula' successfully unpacked and MD5 sums checked
	package 'biclust' successfully unpacked and MD5 sums checked
	package 'lavaan.survey' successfully unpacked and MD5 sums checked
	package 'semPlot' successfully unpacked and MD5 sums checked
	package 'semTools' successfully unpacked and MD5 sums checked
	package 'simsem' successfully unpacked and MD5 sums checked
	package 'seriation' successfully unpacked and MD5 sums checked
	package 'lavaan' successfully unpacked and MD5 sums checked
	package 'betareg' successfully unpacked and MD5 sums checked
	package 'sn' successfully unpacked and MD5 sums checked
	package 'truncnorm' successfully unpacked and MD5 sums checked
	package 'profileModel' successfully unpacked and MD5 sums checked
	package 'forward' successfully unpacked and MD5 sums checked
	package 'linprog' successfully unpacked and MD5 sums checked
	package 'scalreg' successfully unpacked and MD5 sums checked
	package 'rlecuyer' successfully unpacked and MD5 sums checked
	package 'nws' successfully unpacked and MD5 sums checked
	package 'corrplot' successfully unpacked and MD5 sums checked
	package 'TTR' successfully unpacked and MD5 sums checked
	package 'polycor' successfully unpacked and MD5 sums checked
	package 'MBESS' successfully unpacked and MD5 sums checked
	package 'mi' successfully unpacked and MD5 sums checked
	package 'combinat' successfully unpacked and MD5 sums checked
	package 'RItools' successfully unpacked and MD5 sums checked
	package 'brglm' successfully unpacked and MD5 sums checked
	package 'rgenoud' successfully unpacked and MD5 sums checked
	package 'rbounds' successfully unpacked and MD5 sums checked
	package 'igraphdata' successfully unpacked and MD5 sums checked
	package 'latticeExtra' successfully unpacked and MD5 sums checked
	package 'miscTools' successfully unpacked and MD5 sums checked
	package 'BMA' successfully unpacked and MD5 sums checked
	package 'DescTools' successfully unpacked and MD5 sums checked
	package 'gridBase' successfully unpacked and MD5 sums checked
	package 'pryr' successfully unpacked and MD5 sums checked
	package 'gtools' successfully unpacked and MD5 sums checked
	package 'hdi' successfully unpacked and MD5 sums checked
	package 'shapefiles' successfully unpacked and MD5 sums checked
	package 'spdep' successfully unpacked and MD5 sums checked
	package 'snow' successfully unpacked and MD5 sums checked
	package 'candisc' successfully unpacked and MD5 sums checked
	package 'corrgram' successfully unpacked and MD5 sums checked
	package 'FRB' successfully unpacked and MD5 sums checked
	package 'animation' successfully unpacked and MD5 sums checked
	package 'quantmod' successfully unpacked and MD5 sums checked
	package 'fBasics' successfully unpacked and MD5 sums checked
	package 'sem' successfully unpacked and MD5 sums checked
	package 'cem' successfully unpacked and MD5 sums checked
	package 'optmatch' successfully unpacked and MD5 sums checked
	package 'Matching' successfully unpacked and MD5 sums checked
	package 'WhatIf' successfully unpacked and MD5 sums checked
	package 'geoRglm' successfully unpacked and MD5 sums checked
	package 'vioplot' successfully unpacked and MD5 sums checked
	package 'ncdf' successfully unpacked and MD5 sums checked
	package 'igraph' successfully unpacked and MD5 sums checked
	package 'rasterVis' successfully unpacked and MD5 sums checked
	package 'statnet.common' successfully unpacked and MD5 sums checked
	package 'rJava' successfully unpacked and MD5 sums checked
	package 'numDeriv' successfully unpacked and MD5 sums checked
	package 'relimp' successfully unpacked and MD5 sums checked
	package 'VGAMdata' successfully unpacked and MD5 sums checked
	package 'maxLik' successfully unpacked and MD5 sums checked
	package 'Ecfun' successfully unpacked and MD5 sums checked
	package 'gnm' successfully unpacked and MD5 sums checked
	package 'ca' successfully unpacked and MD5 sums checked
	package 'gmodels' successfully unpacked and MD5 sums checked
	package 'Fahrmeir' successfully unpacked and MD5 sums checked
	package 'Sleuth2' successfully unpacked and MD5 sums checked
	package 'lars' successfully unpacked and MD5 sums checked
	package 'stabs' successfully unpacked and MD5 sums checked
	package 'BayesX' successfully unpacked and MD5 sums checked
	package 'gbm' successfully unpacked and MD5 sums checked
	package 'snowfall' successfully unpacked and MD5 sums checked
	package 'poLCA' successfully unpacked and MD5 sums checked
	package 'heplots' successfully unpacked and MD5 sums checked
	package 'bit' successfully unpacked and MD5 sums checked
	package 'httpuv' successfully unpacked and MD5 sums checked
	package 'oz' successfully unpacked and MD5 sums checked
	package 'date' successfully unpacked and MD5 sums checked
	package 'PerformanceAnalytics' successfully unpacked and MD5 sums checked
	package 'fTrading' successfully unpacked and MD5 sums checked
	package 'reshape' successfully unpacked and MD5 sums checked
	package 'gamlss.data' successfully unpacked and MD5 sums checked
	package 'gamlss.dist' successfully unpacked and MD5 sums checked
	package 'RODBC' successfully unpacked and MD5 sums checked
	package 'DBI' successfully unpacked and MD5 sums checked
	package 'Amelia' successfully unpacked and MD5 sums checked
	package 'systemfit' successfully unpacked and MD5 sums checked
	package 'MatchIt' successfully unpacked and MD5 sums checked
	package 'MCMCpack' successfully unpacked and MD5 sums checked
	package 'fields' successfully unpacked and MD5 sums checked
	package 'mapdata' successfully unpacked and MD5 sums checked
	package 'misc3d' successfully unpacked and MD5 sums checked
	package 'geoR' successfully unpacked and MD5 sums checked
	package 'denstrip' successfully unpacked and MD5 sums checked
	package 'raster' successfully unpacked and MD5 sums checked
	package 'spam' successfully unpacked and MD5 sums checked
	package 'polyclip' successfully unpacked and MD5 sums checked
	package 'gplots' successfully unpacked and MD5 sums checked
	package 'rrcov' successfully unpacked and MD5 sums checked
	package 'arm' successfully unpacked and MD5 sums checked
	package 'intergraph' successfully unpacked and MD5 sums checked
	package 'network' successfully unpacked and MD5 sums checked
	package 'scagnostics' successfully unpacked and MD5 sums checked
	package 'sna' successfully unpacked and MD5 sums checked
	package 'tnet' successfully unpacked and MD5 sums checked
	package 'roxygen2' successfully unpacked and MD5 sums checked
	package 'lokern' successfully unpacked and MD5 sums checked
	package 'qvcalc' successfully unpacked and MD5 sums checked
	package 'glmmML' successfully unpacked and MD5 sums checked
	package 'pscl' successfully unpacked and MD5 sums checked
	package 'VGAM' successfully unpacked and MD5 sums checked
	package 'mlogit' successfully unpacked and MD5 sums checked
	package 'Ecdat' successfully unpacked and MD5 sums checked
	package 'geepack' successfully unpacked and MD5 sums checked
	package 'ordinal' successfully unpacked and MD5 sums checked
	package 'vcdExtra' successfully unpacked and MD5 sums checked
	package 'glmnet' successfully unpacked and MD5 sums checked
	package 'mboost' successfully unpacked and MD5 sums checked
	package 'lqa' successfully unpacked and MD5 sums checked
	package 'lpSolve' successfully unpacked and MD5 sums checked
	package 'GAMBoost' successfully unpacked and MD5 sums checked
	package 'penalized' successfully unpacked and MD5 sums checked
	package 'effects' successfully unpacked and MD5 sums checked
	package 'biglm' successfully unpacked and MD5 sums checked
	package 'CompQuadForm' successfully unpacked and MD5 sums checked
	package 'ineq' successfully unpacked and MD5 sums checked
	package 'np' successfully unpacked and MD5 sums checked
	package 'plm' successfully unpacked and MD5 sums checked
	package 'ROCR' successfully unpacked and MD5 sums checked
	package 'sampleSelection' successfully unpacked and MD5 sums checked
	package 'truncreg' successfully unpacked and MD5 sums checked
	package 'urca' successfully unpacked and MD5 sums checked
	package 'quadprog' successfully unpacked and MD5 sums checked
	package 'Cairo' successfully unpacked and MD5 sums checked
	package 'markdown' successfully unpacked and MD5 sums checked
	package 'RDCOMClient' successfully unpacked and MD5 sums checked
	package 'fastmatch' successfully unpacked and MD5 sums checked
	package 'bit64' successfully unpacked and MD5 sums checked
	package 'googleVis' successfully unpacked and MD5 sums checked
	package 'zipcode' successfully unpacked and MD5 sums checked
	package 'expm' successfully unpacked and MD5 sums checked
	package 'diptest' successfully unpacked and MD5 sums checked
	package 'mix' successfully unpacked and MD5 sums checked
	package 'coda' successfully unpacked and MD5 sums checked
	package 'DAAG' successfully unpacked and MD5 sums checked
	package 'fts' successfully unpacked and MD5 sums checked
	package 'its' successfully unpacked and MD5 sums checked
	package 'mondate' successfully unpacked and MD5 sums checked
	package 'scales' successfully unpacked and MD5 sums checked
	package 'timeDate' successfully unpacked and MD5 sums checked
	package 'timeSeries' successfully unpacked and MD5 sums checked
	package 'tis' successfully unpacked and MD5 sums checked
	package 'xts' successfully unpacked and MD5 sums checked
	package 'TSA' successfully unpacked and MD5 sums checked
	package 'AGD' successfully unpacked and MD5 sums checked
	package 'gamlss' successfully unpacked and MD5 sums checked
	package 'mitools' successfully unpacked and MD5 sums checked
	package 'pan' successfully unpacked and MD5 sums checked
	package 'Zelig' successfully unpacked and MD5 sums checked
	package 'rgdal' successfully unpacked and MD5 sums checked
	package 'gstat' successfully unpacked and MD5 sums checked
	package 'sm' successfully unpacked and MD5 sums checked
	package 'gsl' successfully unpacked and MD5 sums checked
	package 'locfit' successfully unpacked and MD5 sums checked
	package 'rpanel' successfully unpacked and MD5 sums checked
	package 'tkrplot' successfully unpacked and MD5 sums checked
	package 'RandomFields' successfully unpacked and MD5 sums checked
	package 'deldir' successfully unpacked and MD5 sums checked
	package 'PKPDmodels' successfully unpacked and MD5 sums checked
	package 'MEMSS' successfully unpacked and MD5 sums checked
	package 'mlmRev' successfully unpacked and MD5 sums checked
	package 'optimx' successfully unpacked and MD5 sums checked
	package 'gamm4' successfully unpacked and MD5 sums checked
	package 'pbkrtest' successfully unpacked and MD5 sums checked
	package 'robust' successfully unpacked and MD5 sums checked
	package 'fit.models' successfully unpacked and MD5 sums checked
	package 'MPV' successfully unpacked and MD5 sums checked
	package 'GGally' successfully unpacked and MD5 sums checked
	package 'reshape2' successfully unpacked and MD5 sums checked
	package 'sfsmisc' successfully unpacked and MD5 sums checked
	package 'catdata' successfully unpacked and MD5 sums checked
	package 'alr4' successfully unpacked and MD5 sums checked
	package 'leaps' successfully unpacked and MD5 sums checked
	package 'survey' successfully unpacked and MD5 sums checked
	package 'AER' successfully unpacked and MD5 sums checked
	package 'bdsmatrix' successfully unpacked and MD5 sums checked
	package 'kinship2' successfully unpacked and MD5 sums checked
	package 'shiny' successfully unpacked and MD5 sums checked
	package 'digest' successfully unpacked and MD5 sums checked
	package 'bitops' successfully unpacked and MD5 sums checked
	package 'tcltk2' successfully unpacked and MD5 sums checked
	package 'R2wd' successfully unpacked and MD5 sums checked
	package 'png' successfully unpacked and MD5 sums checked
	package 'RSQLite' successfully unpacked and MD5 sums checked
	package 'RMySQL' successfully unpacked and MD5 sums checked
	package 'RPostgreSQL' successfully unpacked and MD5 sums checked
	package 'data.table' successfully unpacked and MD5 sums checked
	package 'Lahman' successfully unpacked and MD5 sums checked
	package 'nycflights13' successfully unpacked and MD5 sums checked
	package 'RUnit' successfully unpacked and MD5 sums checked
	package 'abind' successfully unpacked and MD5 sums checked
	package 'itertools' successfully unpacked and MD5 sums checked
	package 'ape' successfully unpacked and MD5 sums checked
	package 'flexmix' successfully unpacked and MD5 sums checked
	package 'gee' successfully unpacked and MD5 sums checked
	package 'mclust' successfully unpacked and MD5 sums checked
	package 'rmeta' successfully unpacked and MD5 sums checked
	package 'inline' successfully unpacked and MD5 sums checked
	package 'rbenchmark' successfully unpacked and MD5 sums checked
	package 'highlight' successfully unpacked and MD5 sums checked
	package 'pkgKitten' successfully unpacked and MD5 sums checked
	package 'tripack' successfully unpacked and MD5 sums checked
	package 'rgl' successfully unpacked and MD5 sums checked
	package 'logspline' successfully unpacked and MD5 sums checked
	package 'nor1mix' successfully unpacked and MD5 sums checked
	package 'MatrixModels' successfully unpacked and MD5 sums checked
	package 'Formula' successfully unpacked and MD5 sums checked
	package 'zoo' successfully unpacked and MD5 sums checked
	package 'dynlm' successfully unpacked and MD5 sums checked
	package 'chron' successfully unpacked and MD5 sums checked
	package 'rms' successfully unpacked and MD5 sums checked
	package 'mice' successfully unpacked and MD5 sums checked
	package 'tables' successfully unpacked and MD5 sums checked
	package 'sp' successfully unpacked and MD5 sums checked
	package 'rgeos' successfully unpacked and MD5 sums checked
	package 'spatstat' successfully unpacked and MD5 sums checked
	package 'PBSmapping' successfully unpacked and MD5 sums checked
	package 'lme4' successfully unpacked and MD5 sums checked
	package 'robustbase' successfully unpacked and MD5 sums checked
	package 'coin' successfully unpacked and MD5 sums checked
	package 'car' successfully unpacked and MD5 sums checked
	package 'lmtest' successfully unpacked and MD5 sums checked
	package 'coxme' successfully unpacked and MD5 sums checked
	package 'SimComp' successfully unpacked and MD5 sums checked
	package 'testit' successfully unpacked and MD5 sums checked
	package 'rmarkdown' successfully unpacked and MD5 sums checked
	package 'XML' successfully unpacked and MD5 sums checked
	package 'RCurl' successfully unpacked and MD5 sums checked
	package 'plotrix' successfully unpacked and MD5 sums checked
	package 'TeachingDemos' successfully unpacked and MD5 sums checked
	package 'neuralnet' successfully unpacked and MD5 sums checked
	package 'rpart.plot' successfully unpacked and MD5 sums checked
	package 'dplyr' successfully unpacked and MD5 sums checked
	package 'gdata' successfully unpacked and MD5 sums checked
	package 'plyr' successfully unpacked and MD5 sums checked
	package 'sandwich' successfully unpacked and MD5 sums checked
	package 'tseries' successfully unpacked and MD5 sums checked
	package 'dichromat' successfully unpacked and MD5 sums checked
	package 'HSAUR' successfully unpacked and MD5 sums checked
	package 'iterators' successfully unpacked and MD5 sums checked
	package 'gclus' successfully unpacked and MD5 sums checked
	package 'Rcpp' successfully unpacked and MD5 sums checked
	package 'quantreg' successfully unpacked and MD5 sums checked
	package 'Hmisc' successfully unpacked and MD5 sums checked
	package 'mapproj' successfully unpacked and MD5 sums checked
	package 'maps' successfully unpacked and MD5 sums checked
	package 'hexbin' successfully unpacked and MD5 sums checked
	package 'maptools' successfully unpacked and MD5 sums checked
	package 'multcomp' successfully unpacked and MD5 sums checked
	package 'knitr' successfully unpacked and MD5 sums checked
	package 'SparseM' successfully unpacked and MD5 sums checked
	package 'xtable' successfully unpacked and MD5 sums checked
	package 'plotmo' successfully unpacked and MD5 sums checked
	package 'akima' successfully unpacked and MD5 sums checked
	package 'foreach' successfully unpacked and MD5 sums checked
	package 'mvtnorm' successfully unpacked and MD5 sums checked
	package 'TH.data' successfully unpacked and MD5 sums checked
	package 'scatterplot3d' successfully unpacked and MD5 sums checked
	package 'som' successfully unpacked and MD5 sums checked
	package 'modeltools' successfully unpacked and MD5 sums checked
	package 'strucchange' successfully unpacked and MD5 sums checked
	package 'colorspace' successfully unpacked and MD5 sums checked
	package 'vcd' successfully unpacked and MD5 sums checked
	package 'Rmpi' successfully unpacked and MD5 sums checked
	package 'microbenchmark' successfully unpacked and MD5 sums checked
	package 'logcondens' successfully unpacked and MD5 sums checked
	package 'doParallel' successfully unpacked and MD5 sums checked
	package 'cba' successfully unpacked and MD5 sums checked
	package 'RColorBrewer' successfully unpacked and MD5 sums checked
	package 'ISwR' successfully unpacked and MD5 sums checked
	package 'corpcor' successfully unpacked and MD5 sums checked
	package 'devtools' successfully unpacked and MD5 sums checked
	package 'ggplot2' successfully unpacked and MD5 sums checked
	package 'e1071' successfully unpacked and MD5 sums checked
	package 'earth' successfully unpacked and MD5 sums checked
	package 'fastICA' successfully unpacked and MD5 sums checked
	package 'gam' successfully unpacked and MD5 sums checked
	package 'ipred' successfully unpacked and MD5 sums checked
	package 'kernlab' successfully unpacked and MD5 sums checked
	package 'klaR' successfully unpacked and MD5 sums checked
	package 'ellipse' successfully unpacked and MD5 sums checked
	package 'mda' successfully unpacked and MD5 sums checked
	package 'mlbench' successfully unpacked and MD5 sums checked
	package 'party' successfully unpacked and MD5 sums checked
	package 'pls' successfully unpacked and MD5 sums checked
	package 'pROC' successfully unpacked and MD5 sums checked
	package 'proxy' successfully unpacked and MD5 sums checked
	package 'randomForest' successfully unpacked and MD5 sums checked
	package 'RANN' successfully unpacked and MD5 sums checked
	package 'spls' successfully unpacked and MD5 sums checked
	package 'subselect' successfully unpacked and MD5 sums checked
	package 'pamr' successfully unpacked and MD5 sums checked
	package 'superpc' successfully unpacked and MD5 sums checked
	package 'Cubist' successfully unpacked and MD5 sums checked
	package 'testthat' successfully unpacked and MD5 sums checked
	package 'caret' successfully unpacked and MD5 sums checked

	The downloaded binary packages are in
			C:\Users\<me>\AppData\Local\Temp\RtmpiyONTJ\downloaded_packages
	> library(caret)
	Loading required package: lattice
	Loading required package: ggplot2
	Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
	  there is no package called 'gtable'
	Error: package 'ggplot2' could not be loaded
	>

**Comment by topepo** [comment]
This doesn't have anything to do with `caret`; `gtable` is [required](http://cran.r-project.org/package=ggplot2) by `ggplot2` and didn't get installed. 

`install.packages` has an argument called `dependencies` that will fix this. Try using:

```r
install.packages(pkgs = "caret", 
                 dependencies = c("Depends", "Imports"))
```

**Comment by aayush26** [comment]
It seems 
install.packages(pkgs = "caret", 
                 dependencies = c("Depends", "Imports"))

didn't solve the problem.

ERROR: dependency ‘car’ is not available for package ‘caret’ 
                                                                              is displayed.
