### ISSUE TITLE
problem with dnn and train() - it can't find the "class2ind" function

### ISSUE THREAD

**Issue by ruggerorossi** [topepo/caret#159]
I am training a model with the dnn method using train(). It doesn't work.
I have a dataframe consisting of 53 variables: 52 of them are either numerics or integers and are input variables, the response variable is a factor with 5 levels ("A","B","C","D","E"). I have approximately 14000 samples.
I run:
fitControl <- trainControl(method = "cv", p = 0.7)
dnnFit1 <- train(classe ~ ., data = training, method = "dnn", trControl = fitControl)

and I obtain:
Loading required package: deepnet
Something is wrong; all the Accuracy metric values are missing:
    Accuracy       Kappa    
 Min.   : NA   Min.   : NA  
 1st Qu.: NA   1st Qu.: NA  
 Median : NA   Median : NA  
 Mean   :NaN   Mean   :NaN  
 3rd Qu.: NA   3rd Qu.: NA  
 Max.   : NA   Max.   : NA  
 NA's   :27    NA's   :27   
Error in train.default(x, y, weights = w, ...) : Stopping
In addition: There were 50 or more warnings (use warnings() to see the first 50)

then when I ask for warnings() it gives 50 messages similar to the following:
1: In eval(expr, envir, enclos) :
  model fit failed for Fold01: layer1=1, layer2=0, layer3=0, hidden_dropout=0, visible_dropout=0 Error in method$fit(x = x, y = y, wts = wts, param = tuneValue, lev = obsLevels,  : 
  could not find function "class2ind"

It looks like that it can't find the "class2ind" function.
If I make exactly the same calling with methods like "pcaNNet" or "gbm" or "rf" it works perfectly.
for instance:
rfFit1 <- train(classe ~ ., data = training, method = "rf", trControl = fitControl)
works well and doesn't give me any error/warning (and I tested it predicts with great accuracy).
Curiously, if I try to manually source the function "class2in", then also method ="dnn" works !
It give me 30 warnings anyway, all similar to:
In sae$encoder[[i - 1]]$W[[1]] %*% t(train_x) + sae$encoder[[i -  ... :
  longer object length is not a multiple of shorter object length

So is it a scope problem for the function class2ind ?

I experienced this problem with R x64 3.1.3 with caret 6.0-41 on windows 7.
The same exact behavior happens with Revolution RRO x64 3.2.0 on windows 7 both with caret 6.0-41 and with 6.0-47.
> sessionInfo()
R version 3.2.0 (2015-04-16)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=Italian_Italy.1252  LC_CTYPE=Italian_Italy.1252    LC_MONETARY=Italian_Italy.1252
[4] LC_NUMERIC=C                   LC_TIME=Italian_Italy.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] deepnet_0.2     caret_6.0-47    ggplot2_1.0.1   lattice_0.20-31

loaded via a namespace (and not attached):
 [1] Rcpp_0.11.5         magrittr_1.5        splines_3.2.0       MASS_7.3-40         munsell_0.4.2      
 [6] colorspace_1.2-6    foreach_1.4.2       minqa_1.2.4         car_2.0-25          stringr_1.0.0      
[11] plyr_1.8.2          tools_3.2.0         parallel_3.2.0      pbkrtest_0.4-2      nnet_7.3-9         
[16] grid_3.2.0          gtable_0.1.2        nlme_3.1-120        mgcv_1.8-6          quantreg_5.11      
[21] e1071_1.6-4         class_7.3-12        iterators_1.0.7     gtools_3.4.2        lme4_1.1-7         
[26] digest_0.6.8        Matrix_1.2-0        nloptr_1.0.4        reshape2_1.4.1      codetools_0.2-11   
[31] stringi_0.4-1       compiler_3.2.0      BradleyTerry2_1.0-6 scales_0.2.4        SparseM_1.6        
[36] brglm_0.5-9         proto_0.3-10       
>

**Comment by topepo** [comment]
That is a bug and it didn't fail during regression testing, so that's weird.

You can use this code in a custom method:

```r
modelInfo <- list(label = "Stacked AutoEncoder Deep Neural Network",
                  library = "deepnet",
                  loop = NULL,
                  type = c("Classification", "Regression"),
                  parameters = data.frame(parameter = c("layer1", "layer2", "layer3", "hidden_dropout", "visible_dropout"),
                                          class = rep("numeric", 5),
                                          label = c("Hidden Layer 1", "Hidden Layer 2", "Hidden Layer 3", 
                                                    "Hidden Dropouts", "Visible Dropout")),
                  grid = function(x, y, len = NULL) {
                    expand.grid(layer1 = 1:len, layer2 = 0:(len -1), layer3 = 0:(len -1),
                                hidden_dropout = 0, visible_dropout = 0)
                  },
                  fit = function(x, y, wts, param, lev, last, classProbs, ...) {
                    if(!is.matrix(x)) x <- as.matrix(x)
                    is_class <- is.factor(y)
                    if (is_class) y <- caret:::class2ind(y)
                    layers <- c(param$layer1, param$layer2, param$layer3)
                    layers <- layers[layers > 0]
                    sae.dnn.train(x, y, hidden = layers, 
                                  output = if(is_class) "sigm" else "linear",
                                  hidden_dropout = param$hidden_dropout,
                                  visible_dropout = param$visible_dropout,
                                  ...)
                  },
                  predict = function(modelFit, newdata, submodels = NULL) {
                    pred <- nn.predict(modelFit, as.matrix(newdata))
                    if(ncol(pred) > 1)
                      pred <- modelFit$obsLevels[apply(pred, 1, which.max)]
                    pred
                  },
                  prob = function(modelFit, newdata, submodels = NULL) {
                    out <- exp(nn.predict(modelFit, as.matrix(newdata)))
                    out <- apply(out, 1, function(x) x/sum(x))
                    t(out)
                  },
                  predictors = function(x, ...) {
                    NULL
                  },
                  varImp = NULL,
                  levels = function(x) x$classes,
                  tags = c("Neural Network"),
                  sort = function(x) x[order(x[,1]),])
```

then use

```r
dnnFit1 <- train(classe ~ ., data = training, method = modelInfo, trControl = fitControl)
```

**Comment by zachmayer** [comment]
Maybe adding `class2ind` to exports would fix the problem?  It's kinda weird though... I'd expect caret to be able to find un-exported functions in its own namespace!

**Comment by topepo** [comment]
This code is saved in an RData file so it isn't in the same environment as
the package. I need to figure out why the regression test didn't fail.

I should export the function; maybe put it in the "internal function" man
page.

**Comment by topepo** [comment]
fixed and a test case was added
