### ISSUE TITLE
Checks in Confusion matrix Parameters

### ISSUE THREAD

**Issue by premadh** [topepo/caret#171]
We should be able to calculate a confusion matrix when predicted levels and truth are:
predicted are all ones and truth is a combination of ones and zeros: Eg. 

predVal <- ifelse(runif(10)<1,1,0)
acTruth <- ifelse(runif(10)<.5,0,1)

Now, if we run 
confusionMatrix(as.factor(predVal),as.factor(acTruth))

it fails with an error: 

Error in confusionMatrix.default(as.factor(predVal), as.factor(acTruth)) : 
  the data and reference factors must have the same number of levels

Could we fix this?

**Comment by topepo** [comment]
There is nothing to fix. The inputs have to be factors with the same levels and that does not stop you from having predicted values that are all one class.

**Comment by premadh** [comment]
Well, in that case could you please point out the issue with three lines of code above? I believe I should not get any errors but I get the following error:

Error in confusionMatrix.default(as.factor(predVal), as.factor(acTruth)) : 
  the data and reference factors must have the same number of levels

**Comment by zachmayer** [comment]
The correct approach:
```{R}
library(caret)
set.seed(1)
my_levels <- c(1,0)
predVal <- factor(ifelse(runif(10)<1,1,0), levels=my_levels)
acTruth <- factor(ifelse(runif(10)<.5,0,1), levels=my_levels)
confusionMatrix(as.factor(predVal),as.factor(acTruth))
```

**Comment by zachmayer** [comment]
We used to just issue a warning and try to re-factor the data, but this led to all sorts of hard-to-debug problems (e.g. when re-sampling, you often end up guessing incorrectly as some factor levels may be missing).

This used to just issue a warning, and now issues an error:
```{R}
library(caret)
set.seed(1)
predVal <- factor(ifelse(runif(10)<1,1,0))
acTruth <- factor(ifelse(runif(10)<.5,0,1))
confusionMatrix(as.factor(predVal),as.factor(acTruth))
```
Long story short, you should convert categorical data to factors before modeling to ensure the factors are setup correctly.
