### ISSUE TITLE
Is that possible to tune the parameter by some heuristic methods?

### ISSUE THREAD

**Issue by ajing** [topepo/caret#175]
Except grid search, does caret support other heuristic parameter searching? I found that if there are many parameters to tune, then to finish the tuning takes a long time. For example, xgboost has eta, nround and max_depth as major parameters. But, to tune three of them at the same time will takes a long time.

**Comment by zachmayer** [comment]
Try using method=''adaptive_cv" or method="adaptive_boot".  This will use a meta-model to discard sections of the grid that probably won't improve the model.

**Comment by topepo** [comment]
Are there any specific methods that you are interested in? We could treat it like a nonlinear programming exercise and use something like Nelder-Mead but there are a lot of issues in doing this mostly related to the breadth of models wrapped in the package (e.g. some have discrete tuning parameters, etc).

**Comment by ajing** [comment]
If I could choose, I would like to see the fine tuning of xgboost. Currently, what I am doing is more or less empirical. I set nround to 100 and tune eta first, and then tune max_depth...

**Comment by zachmayer** [comment]
That's not the approach caret takes. Caret does grid-search by default, but can adaptively discard regions of the grid it thinks will be low performing.

Caret is also aware of the sub-model trick, so for example with an xgboost model with nround=100 it knows it can make predictions for nround=90, nround=80, etc. all the way down to nround=1.

**Comment by topepo** [comment]
ajing,

I think you are better off simultaneously tuning the model instead of doing things sequentially. I would suggest using a wider grid, especially with the number of iterations. As Zach mentioned, the cost of evaluating those is much lower than the other tuning parameters.

**Comment by hermandr** [comment]
Hi @zachmayer, how is caret aware of the sub model trick?  
When I pass the nround = c(100,200) in a tune grid, do you mean it will fine tune the values between 0 to 100 and 100 to 200?
