### ISSUE TITLE
Use data.tables internally to store data?

### ISSUE THREAD

**Issue by zachmayer** [topepo/caret#176]
Hi Max,

I was thinking we might consider using data.tables internally to save memory in `caret::train`.  In particular the `pred` object can get pretty huge when `savePredictions=TRUE` (especially for GBMs and glmnets).  I often find myself trying to run caretEnsemble on caret models with pred objects that take up 16-20 GB of RAM.  The out-of-sample predictions are essential for ensembling, but a 20GB data.frame is unbearably slow to work with.  (A 20GB data.table is workable).

These models also take a really long time to train, because every re-sample has to append data to a really large pred object.

If this seems like a good idea to you, I think it could save a TON of RAM when training large models.  I could start investigating this weekend.

Thanks,

Zach

**Comment by topepo** [comment]
That sounds good. IIRC, data tables are passed by reference and that might matter with parallel processing and maybe in a few other areas. That's just my recollection though.

**Comment by terrytangyuan** [comment]
Is this being addressed?

**Comment by zachmayer** [comment]
It's on my todo list, but I have no plans as of yet.

**Comment by terrytangyuan** [comment]
Sounds good. Look forward to it. It will be extremely useful.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
