### ISSUE TITLE
plot pca in preProcess  

### ISSUE THREAD

**Issue by acocac** [topepo/caret#181]
Dear,

I just wonder if there is any function in caret to access to the pca transformed data using the preProcess function. It would be a great development to produce plots like the following post:
https://tgmstat.wordpress.com/2013/11/28/computing-and-visualizing-pca-in-r/

**Comment by zachmayer** [comment]
`model$preProcess$rotation` will give you the PCA rotation matrix, but it doesn't look like we save the eigenvalues.  You can use the rotation matrix to recovery the PCA components for the original dataset as follows:
```{R}
library(caret)
model <- train(Species ~ ., data=iris, method='lda', preProcess='pca')
model$preProcess$rotation
pca_x <- as.matrix(iris[,-5]) %*% model$preProcess$rotation
plot(pca_x, col=iris[,5])
```
![image](https://cloud.githubusercontent.com/assets/581590/8660579/c122619e-297f-11e5-8c3a-1f360ebd125c.png)

**Comment by acocac** [comment]
Hi Zach,

I am glad for your great response. What do you suggest if I would like to generate similar plots? which PCA is the caret package based on? I just wonder if I can set up a threshold in the PCA raw function like I can do in the caret package.

I am also wondered if you can provide me any indication how to know which variables have high loading in which principal components using the pca results from preprocess function. In principle, I would like to generate a plot like the second one posted in this website: http://www.r-bloggers.com/using-r-two-plots-of-principal-component-analysis/

Kind regards,

Alejandro

**Comment by acocac** [comment]
Hi, 

I just realised I also would like to know how to get access to the rotation values using the "pcaNNet" method in the train function.

Thanks!

A.

**Comment by topepo** [comment]
I think that you would be better off using `prcomp` directly if you want to explore the PCA analysis. `preProcess` is really geared towards computations and not exploration.

For `pcaNNet`:

```r
mod <- train(Species ~ ., data = iris, method = "pcaNNet")
## the `pc` component is a `preProcess` object:
mod$finalModel$pc
```

**Comment by acocac** [comment]
Max, thanks for your help!
