### ISSUE TITLE
issue for combining prediction with ID in new data 

### ISSUE THREAD

**Issue by acocac** [topepo/caret#182]
Hi,

I am using a new data that I would like to score using a PCANnnet trained (classification type). My issue is that there are less observations in the predicted data than the raw new dataset and therefore I can not join the new data IDs with the predicted data. The code lines (prediction and join procedures) and error as follows:

#new dataset to score
pattern.score.nn <- predict(pattern.fit.nn, newdata=score.PCAnnet[,,with = F], type="raw")

#join with IDs from new dataset
id<-score.db[,1,with = F]
output<-cbind(id,pattern.score.nn) 

The following information is about my model and new dataset features:

My final model is:
Neural Network Model with PCA Pre-Processing

Created from 30 samples and 121 variables
PCA needed 11 components to capture 99 percent of the variance

a 11-4-3 network with 63 weights
options were - decay=0.4

The str of my new dataset is:
> str(score.PCAnnet)
Classes ‘data.table’ and 'data.frame':	493 obs. of  122 variables:
 $ pattern      : chr  "null" "null" "null" "null" ...
 $ c_.CA.       : num  3669 8600 1572 11192 2857 ...
 $ c_.PLAND.    : num  0.252 0.57 0.104 0.741 0.189 ...
 $ c_.NP.       : num  312 388 212 1140 294 203 653 263 251 232 ...
 $ c_.PD.       : num  0.0215 0.0257 0.014 0.0755 0.0195 0.0134 0.0432 0.0174 0.0166 0.0154 ...
 $ c_.LPI.      : num  0.0174 0.0301 0.0015 0.0088 0.0187 0.0072 0.0504 0.0095 0.0023 0.0141 ...
 $ c_.TE.       : num  452880 758400 236880 1512000 364800 ...
 $ c_.ED.       : num  0.311 0.502 0.157 1.001 0.242 ...
 $ c_.LSI.      : num  18.7 20.6 14.6 35.5 16.9 ...
 $ c_.AREA_MN.  : num  11.76 22.16 7.42 9.82 9.72 ...
 $ c_.AREA_AM.  : num  51.13 92.77 9.39 22.98 54.12 ...
 $ c_.AREA_CV.  : num  183 178.5 51.6 115.8 213.8 ...
 $ c_.GYRATE_MN.: num  144 183 126 137 134 ...
 $ c_.GYRATE_AM.: num  279 379 133 198 267 ...
 $ c_.GYRATE_CV.: num  54 67.1 14.5 40.9 49.2 ...
 $ c_.SHAPE_MN. : num  1.07 1.1 1.02 1.05 1.03 ...
 $ c_.SHAPE_AM. : num  1.37 1.31 1.05 1.21 1.24 ...
 $ c_.SHAPE_CV. : num  18.77 18.12 8.12 15.87 13.09 ...
 $ c_.FRAC_MN.  : num  1.01 1.02 1.01 1.01 1.01 ...
 $ c_.FRAC_AM.  : num  1.04 1.04 1.01 1.03 1.03 ...
 $ c_.FRAC_CV.  : num  2.48 2.65 1.45 2.16 1.77 ...
 $ c_.PARA_MN.  : num  153 137 159 154 158 ...
 $ c_.PARA_AM.  : num  124.8 89.5 151.4 135.6 127.9 ...
 $ c_.PARA_CV.  : num  16.1 27.3 10.8 14.8 13.5 ...
 $ c_.CIRCLE_MN.: num  0.183 0.282 0.109 0.17 0.103 ...
 $ c_.CIRCLE_AM.: num  0.421 0.524 0.209 0.352 0.301 ...
 $ c_.CIRCLE_CV.: num  151 107 204 155 212 ...
 $ c_.CONTIG_MN.: num  0.0702 0.1536 0.0362 0.0631 0.0432 ...
 $ c_.CONTIG_AM.: num  0.2258 0.4226 0.0757 0.1613 0.2103 ...
 $ c_.CONTIG_CV.: num  174 129 220 174 248 ...
 $ c_.PAFRAC.   : num  1.49 1.34 1.44 1.48 1.4 ...
 $ c_.TCA.      : num  3669 8600 1572 11192 2857 ...
 $ c_.CPLAND.   : num  0.252 0.57 0.104 0.741 0.189 ...
 $ c_.NDCA.     : num  312 388 212 1140 294 203 653 263 251 232 ...
 $ c_.DCAD.     : num  0.0215 0.0257 0.014 0.0755 0.0195 0.0134 0.0432 0.0174 0.0166 0.0154 ...
 $ c_.CORE_MN.  : num  11.76 22.16 7.42 9.82 9.72 ...
 $ c_.CORE_AM.  : num  51.13 92.77 9.39 22.98 54.12 ...
 $ c_.CORE_CV.  : num  183 178.5 51.6 115.8 213.8 ...
 $ c_.DCORE_MN. : num  11.76 22.16 7.42 9.82 9.72 ...
 $ c_.DCORE_AM. : num  51.13 92.77 9.39 22.98 54.12 ...
 $ c_.DCORE_CV. : num  183 178.5 51.6 115.8 213.8 ...
 $ c_.PROX_MN.  : num  0.3772 1.3743 0.0721 0.541 0.2431 ...
 $ c_.PROX_AM.  : num  0.6154 2.3386 0.0749 0.6899 0.4155 ...
 $ c_.PROX_CV.  : num  217 141 174 127 339 ...
 $ c_.SIMI_MN.  : num  0.3772 1.3743 0.0721 0.541 0.2431 ...
 $ c_.SIMI_AM.  : num  0.6154 2.3386 0.0749 0.6899 0.4155 ...
 $ c_.SIMI_CV.  : num  217 141 174 127 339 ...
 $ c_.ENN_MN.   : num  1900 1806 3681 1374 2829 ...
 $ c_.ENN_AM.   : num  1594 1185 3633 1206 2201 ...
 $ c_.ENN_CV.   : num  0.0432 0.1072 0.0034 0.0501 0.0291 ...
 $ c_.CWED.     : num  0.311 0.502 0.157 1.001 0.242 ...
 $ c_.TECI.     : num  98.9 98.6 99.5 99.7 99.9 ...
 $ c_.ECON_MN.  : num  98.8 99.1 99.5 99.6 99.8 ...
 $ c_.ECON_AM.  : num  98.8 97.7 99.5 99.6 99.9 ...
 $ c_.ECON_CV.  : num  6.06 4.85 3.74 2.9 2.06 ...
 $ c_.CLUMPY.   : num  0.2598 0.4726 0.0967 0.1849 0.2425 ...
 $ c_.PLADJ.    : num  25.12 46.32 9.16 18.66 23.29 ...
 $ c_.COHESION. : num  48 61.2 15.7 35.5 39.7 ...
 $ c_.DIVISION. : num  1 1 1 1 1 1 1 1 1 1 ...
 $ c_.MESH.     : num  0.129 0.5284 0.0098 0.1703 0.1024 ...
 $ c_.SPLIT.    : num  1.13e+07 2.86e+06 1.54e+08 8.87e+06 1.47e+07 ...
 $ c_.AI.       : num  26.17 47.56 9.77 19.09 24.39 ...
 $ c_.NLSI      : num  0.738 0.524 0.902 0.809 0.756 ...
 $ l_.NP.       : num  317 390 213 1141 295 ...
 $ l_.PD.       : num  0.0218 0.0258 0.0141 0.0756 0.0195 0.0135 0.0434 0.0175 0.0167 0.0154 ...
 $ l_.LPI.      : num  99.7 99.4 99.9 99.3 99.8 ...
 $ l_.TE.       : num  452880 758400 236880 1512000 364800 ...
 $ l_.ED.       : num  0.311 0.502 0.157 1.001 0.242 ...
 $ l_.LSI.      : num  2.18 2.54 1.48 4.08 1.74 ...
 $ l_.AREA_MN.  : num  4588 3872 7089 1323 5118 ...
 $ l_.AREA_AM.  : num  1446681 1492777 1506806 1487649 1504241 ...
 $ l_.AREA_CV.  : num  1773 1961 1454 3351 1711 ...
 $ l_.GYRATE_MN.: num  291 302 346 178 293 ...
 $ l_.GYRATE_AM.: num  46014 46685 46963 46654 46917 ...
 $ l_.GYRATE_CV.: num  886 783 927 781 930 ...
 $ l_.SHAPE_MN. : num  1.07 1.11 1.03 1.05 1.04 ...
 $ l_.SHAPE_AM. : num  2.14 2.52 1.48 4.06 1.74 ...
 $ l_.SHAPE_CV. : num  19.61 19.16 8.63 17.97 13.63 ...
 $ l_.FRAC_MN.  : num  1.01 1.02 1.01 1.01 1.01 ...
 $ l_.FRAC_AM.  : num  1.07 1.08 1.03 1.12 1.05 ...
 $ l_.FRAC_CV.  : num  2.5 2.66 1.46 2.18 1.78 ...
 $ l_.PARA_MN.  : num  152 136 159 154 157 ...
 $ l_.PARA_AM.  : num  1.034 1.33 0.639 2.328 0.809 ...
 $ l_.PARA_CV.  : num  17.5 27.7 12.8 15.1 14.7 ...
 $ l_.CIRCLE_MN.: num  0.185 0.283 0.11 0.17 0.104 ...
 $ l_.CIRCLE_AM.: num  0.389 0.368 0.364 0.368 0.364 ...
 $ l_.CIRCLE_CV.: num  150 106 202 155 211 ...
 $ l_.CONTIG_MN.: num  0.0748 0.1558 0.0407 0.0639 0.0464 ...
 $ l_.CONTIG_AM.: num  0.993 0.991 0.996 0.985 0.994 ...
 $ l_.CONTIG_CV.: num  182 130 253 177 260 ...
 $ l_.PAFRAC.   : num  1.31 1.29 1.13 1.41 1.22 ...
 $ l_.NDCA.     : num  317 390 213 1141 295 ...
 $ l_.DCAD.     : num  0.0218 0.0258 0.0141 0.0756 0.0195 0.0135 0.0434 0.0175 0.0167 0.0154 ...
 $ l_.CORE_MN.  : num  4588 3872 7089 1323 5118 ...
 $ l_.CORE_AM.  : num  1446681 1492777 1506806 1487649 1504241 ...
 $ l_.CORE_CV.  : num  1773 1961 1454 3351 1711 ...
 $ l_.DCORE_MN. : num  4588 3872 7089 1323 5118 ...
 $ l_.DCORE_AM. : num  1446681 1492777 1506806 1487649 1504241 ...
 $ l_.DCORE_CV. : num  1773 1961 1454 3351 1711 ...
  [list output truncated]
 - attr(*, ".internal.selfref")=<externalptr>

**Comment by topepo** [comment]
Are there missing values in the data being predicted? It's hard to help out without a reproducible example.

**Comment by zachmayer** [comment]
As Max said, please make a [minimal reproducible example](http://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example) of the problem.

I suspect that `score.PCAnnet` has fewer rows than `score.db`.  Please confirm that:
1. `pattern.score.nn` has the same length as the number of rows in `score.PCAnnet`.
2. `score.db` has the same number of rows as `score.PCAnnet`

**Comment by acocac** [comment]
Dear Max and Zach,
You both were right. There were missing values in my datasets.
Thanks,
