### ISSUE TITLE
rfe with functions=gamFuncs results in Error in { : task 1 failed - "could not find function "gam""

### ISSUE THREAD

**Issue by carlosfamilia** [topepo/caret#183]
This happens on OS X 10.10.4, R 3.2.0, caret_6.0-47, mgcv_1.8-6. Running the code present in https://github.com/topepo/caret/blob/master/RegressionTests/Code/rfe_gam.R .

Solution found:

In gamFuncs$fit adding 

    gam <- get("gam", asNamespace("mgcv")) 

before 

    do.call("gam", args)

seems to do the trick.

**Comment by topepo** [comment]
Done. Thanks.
