### ISSUE TITLE
gam classification label flipped

### ISSUE THREAD

**Issue by slyuee** [topepo/caret#184]
For some reason, when using gam for binary classification, caret seems to flip the labels internally, causing the predictions to be the exact opposite of what's expected. I don't know whether there is any reason for this behavior.

Here is a reproducible example:

library(caret)
library(mgcv)

set.seed(123456)

d <- data.frame(y = as.factor(c('ONE', 'ZERO'))[rep(1:2, 10)])
d$x <- rnorm(20, 0, 1)
d[d$y == 'ONE', 'x'] <- rnorm(10, 2, 1)

fit <- train(y ~ x, data = d, method = 'gam', tuneGrid = data.frame(select = F, method = 'GCV.Cp'))

print(d$y)
print(predict(fit, d))

**Comment by topepo** [comment]
You are correct. I've fixed it and it will be in the next release (on CRAN in within a week or so).

Thanks,

Max
