### ISSUE TITLE
Add ROSE and DMwR to Travis testing

### ISSUE THREAD

**Issue by topepo** [topepo/caret#188]

**Comment by terrytangyuan** [comment]
Are all the ROSE and DMwR code in [/pkg/caret/R/misc.R]? And add a new testthat for that, right? I'd appreciate if you can provide more instructions on this and I would be very happy to help.  :-) This is my opportunity to get familiar with the package structure.

**Comment by topepo** [comment]
So, `caret` is a little odd in that it depends on a lot of packages without formal dependencies in the DESCRIPTION file. 

For the built-in models accessed by `train`, the R code that defines the modules (e.g. model fitting prediction, etc.) are in an RData file contain in the package sources. See `?getModelIfno` on loading those R modules. We actually had good reasons for doing this. 

The current issue is that we've incorporated some R code for sub-sampling in a similar way and that R code depends on the packages `ROSE` and `DMwR`. The tests are failing because Travis doesn't know that they are needed from the DESCRIPTION file.  

I think that the solution is to add the line
```
  - ./travis-tool.sh install_r ROSE DMwR
```
to the .travis.yml file under the section `before_install:`

Zach - would this work?

**Comment by zachmayer** [comment]
Yes that should work.




You can also use testhat::skip_if_not_installed() to skip tests with outside dependencies.



—
