### ISSUE TITLE
Question on LGOCV

### ISSUE THREAD

**Issue by andrewcstewart** [topepo/caret#200]
My first impression of the term 'leave group out CV" would be that the resampling population consists of some level of grouping which can be used as the basis for resampling.  For example, a population consisting of a single species may consist of several genus level groups, in which case it may make sense in some scenario to leave each group out in order to infer performance.  It seems that LGOCV within the context of caret actually refers to Monte Carlo CV though.

Anyway, I'm wondering if you have any thoughts on achieving the former with caret.  Perhaps by writing a wrapper around manual split selection?

**Comment by topepo** [comment]
I agree which the poor naming. That's what a lot of people that I work with call it but it really is Monte Carlo CV (also, I think, poorly named). 

I don't have any plans on doing a strata-like option but there are [examples on how to do this](http://stackoverflow.com/questions/31135740/controlling-sampling-for-crossvalidation-in-the-caret-r-package/31141754#31141754). Maybe a separate function like `createFolds` would be a good idea.

**Comment by topepo** [comment]
Created issue #204

**Comment by andrewcstewart** [comment]
Thanks for the info!

**Comment by Deleetdk** [comment]
@topepo Any intention to implement this feature now or any time in the future? Or did you stop development on new features in caret due to switching to working on the caret replacement package (I could not find the name of it again). Maybe I should attempt a merge request for this feature. Currently, I have implemented a custom routine for doing this, similar to your example, but it would be nice if it was a feature of caret itself since this situation often happens.

**Comment by gtalckmin** [comment]
> @topepo Any intention to implement this feature now or any time in the future? Or did you stop development on new features in caret due to switching to working on the caret replacement package (I could not find the name of it again). Maybe I should attempt a merge request for this feature. Currently, I have implemented a custom routine for doing this, similar to your example, but it would be nice if it was a feature of caret itself since this situation often happens.

As I understand, this is implemented under the rsample package. 
CreateFolds is available in carets and there is something called makeStrate in rsample.
