### ISSUE TITLE
bug in nearZeroVars?

### ISSUE THREAD

**Issue by BirdyDC** [topepo/caret#201]
I'm running R version 3.2.1 with caret 6.0-52. I'm trying to run the "nearZeroVar" function to filter out my dataset, but I keep getting an error message: "Error in .subset(x, j) : invalid subscript type 'language'"

I tried running the example code from the manual, to check if there was something wrong with my dataframe, but I still get the same error:

> library(caret) 
> data(mdrr)
> mdrrDescr<-mdrrDescr[,~nearZeroVar(mdrrDescr)]
Error in .subset(x, j) : invalid subscript type 'language'

That example is copied directly out of the manual for caret (https://cran.r-project.org/web/packages/caret/caret.pdf, p9) so I don't think it's a problem with my syntax. Is this a bug in the newest version of caret???

**Comment by topepo** [comment]
**~**`nearZeroVar(mdrrDescr)]` is the issue (tilde not minus) =]
