### ISSUE TITLE
tuneLength and SuperLearner

### ISSUE THREAD

**Issue by cancandan** [topepo/caret#205]
As far as I understand SuperLearner docs talk about creating "wrapper creators" for the same model with different tuning parameters, the idea is that a not so good tuning parameter might contribute to the ensemble in the end, so including it in the ensemble anyway is suggested. With caret's tuneLength a grid is searched for the best parameters and final model is fit with that, discarding the others. Isn't that  wasteful from this angle?

**Comment by zachmayer** [comment]
Potentially, but we fit the final model to the full dataset.  Doing that for all of the parameters in the tune grid could be very costly.




Also, ensembles benefit most from diverse models.  The same model with different parameters is likely to produce very similar (if less accurate) predictions.



—

**Comment by topepo** [comment]
We've also added random search in the last version, which might be less wasteful.

Any issues with me closing this one?

**Comment by zachmayer** [comment]
Nope!  I'll close
