### ISSUE TITLE
Is VarImportance for J48 algorithm reliable? 

### ISSUE THREAD

**Issue by acocac** [topepo/caret#207]
Hi,

I am testing the J48 algorithm and I do not know if the VarImportance function is working for this algorithm. In others words, my final model which was pruned using a confidence value of 25% only show for example that 4 variables out of 10 in total were used. However when I run the variable importance function it seems that others variables were also important in the model by outcome class. How should I handle this? Is there any way that I only know the variable importance of features used in the pruned decision tree?

Thanks!

**Comment by acocac** [comment]
As it is reported for CART models, please see page 30 in http://www.cs.umd.edu/~samir/498/10Algorithms-08.pdf, it would be great if the VarImportance function can return the importance score confined to splitters. The full importance rankings will be a useful diagnostic too.

**Comment by topepo** [comment]
Note that, when no variable importance score is implemented, you get model-free estimates:

```r
> mod1 <- train(Species ~ ., data = iris, method = "J48")
Loading required package: RWeka
> varImp(mod1)
ROC curve variable importance

  variables are sorted by maximum importance across the classes
             setosa versicolor virginica
Petal.Width  100.00     100.00     100.0
Petal.Length 100.00     100.00     100.0
Sepal.Length  90.70      59.30      90.7
Sepal.Width   54.59      54.59       0.0
```

For that model, you would have to talk to the people who maintain it to get importance scores for `J48` since it comes back as a java object.

Better yet, use `C5.0`. `J48` is a poor imitation of `C4.5`:

```r
> mod2 <- train(Species ~ ., data = iris, method = "C5.0Tree")
> varImp(mod2)
C5.0Tree variable importance

             Overall
Petal.Length  100.00
Petal.Width    66.67
Sepal.Width     0.00
Sepal.Length    0.00
> summary(mod2)

Call:
C5.0.default(x = x, y = y, weights = wts)


C5.0 [Release 2.07 GPL Edition]  	Mon Aug  3 17:40:38 2015
-------------------------------

Class specified by attribute `outcome'

Read 150 cases (5 attributes) from undefined.data

Decision tree:

Petal.Length <= 1.9: setosa (50)
Petal.Length > 1.9:
:...Petal.Width > 1.7: virginica (46/1)
    Petal.Width <= 1.7:
    :...Petal.Length <= 4.9: versicolor (48/1)
        Petal.Length > 4.9: virginica (6/2)


Evaluation on training data (150 cases):

	    Decision Tree   
	  ----------------  
	  Size      Errors  

	     4    4( 2.7%)   <<


	   (a)   (b)   (c)    <-classified as
	  ----  ----  ----
	    50                (a): class setosa
	          47     3    (b): class versicolor
	           1    49    (c): class virginica


	Attribute usage:

	100.00%	Petal.Length
	 66.67%	Petal.Width


Time: 0.0 secs
```

**Comment by zachmayer** [comment]
:+1: For C5.0

**Comment by acocac** [comment]
Hi Max, 
Thanks for your great responses! However I am comparing the goodness of others algorithms in comparison with C4.5 algorithm which has been traditionally used in my data-mining problem. What do you mean when you said J48 is a poor imitation of C4.5? Could I get different results if I use the raw Quintan's C4.5 code regarding the results obtained by J48?

**Comment by topepo** [comment]
J48 handles splits on categorical features differently and can produce mush
larger trees.

Also, C5.0 has boosting and a lot of other features that C4.5 and/or J48
does not.
