### ISSUE TITLE
How to create data partitions using multiple categorical and numerical columns?

### ISSUE THREAD

**Issue by vitorbaptista** [topepo/caret#217]
My problem is that I'd like to split a dataset while maintaining the relative proportions of multiple columns. If there was a single column, I could use `createDataPartition`. With multiple categorical columns, I could pass `paste(data$column1, data$column2, ...)` as the `y` in `createDataPartition` and everything would be fine. With multiple numerical columns passing `data$num1 * data$num2 ...` should be enough, but I couldn't find how to do the same when I have multiple categorical and numerical columns.

I asked [this question on StackOverflow](http://stats.stackexchange.com/questions/166337/how-to-create-a-data-partition-in-r-using-categorical-and-numerical-columns) a few days ago, but had no answers. I ended up solving it by writing a `createGroups` function that converts the numerical data to categorical using quantiles and paste them all together, returning something like:

```
"[-3.54,-0.634](0.724,3.06]Class2"
"(0.715,2.86](0.724,3.06]Class1"
"(-0.634,-0.0055][-3.21,-0.677]Class1"
...
```

This could then be used with `createDataPartition`. The full code and explanation is in [the StackOverflow page](http://stats.stackexchange.com/questions/166337/how-to-create-a-data-partition-in-r-using-categorical-and-numerical-columns)

I'm posting it here to double check if this problem was solved somewhere in caret I can't find and, if not, if it would be useful to add to caret. If that's the case, I would be happy to clean the code and submit a pull request in a few weeks.

**Comment by zachmayer** [comment]
This seems like a good idea for me.  Make a PR to include your `createGroups` function.

**Comment by vitorbaptista** [comment]
Cool! Will do.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
