### ISSUE TITLE
Passing optional parameters in RFE causing errors

### ISSUE THREAD

**Issue by lsusatyo-gcmlp** [topepo/caret#220]
Hi,

In the process of trying to customize parameters for the svmLinear method, we tried to pass in the scaled=FALSE, which technically should be accepted by ksvm function. But it fails the rfe().

Multiple attempts trying to override the trainFuncs produce different errors as well.

Thank you!

**Comment by topepo** [comment]
Can you give a reproducible example?

**Comment by lsusatyo-gcmlp** [comment]
This is the code that can be used to reproduce the issue:

currentDirectory <- getwd()
library(caret)
library(kernlab)
library(robustHD)
library(glmnet)
library(parallel)
library(doParallel)
library(paran)
#library(mvtnorm)


###...... Import Data ....####
ptm <- proc.time()

response <- as.data.frame(matrix(rnorm(60)), nrow=60) * 0.01
factors <- as.data.frame(matrix(rnorm(60 * 10), nrow=60)) * 0.01

# test only first

cl <- makeCluster(6)
registerDoParallel(cl)



output <- foreach(i=c(1), .packages=c('paran','caret', 'kernlab')) %dopar% {
  
  resp <- response[which(!is.na(response[,i])),i]
  fact <- factors[which(!is.na(response[,i])),]
  
  
  
  ## SVM-RFE ###
  
  
  caretFuncs$selectSize <- function (x, metric, tol = .5, maximize) 
  {
    if (!maximize) {
      best <- min(x[-nrow(x), metric])
      perf <- (x[-nrow(x), metric] - best)/best * 100
      flag <- perf <= tol
    }
    else {
      best <- max(x[-nrow(x), metric])
      perf <- (best - x[-nrow(x), metric])/best * 100
      flag <- perf <= tol
    }
    min(x[flag, "Variables"])
  }
  
  
  #create a list of seed, here change the seed for each resampling
  set.seed(123)
  seeds <- vector(mode = "list", length = 101)
  for(j in 1:100) seeds[[j]]<- sample.int(n=1000, 6) 
  
  seeds[[101]]<-sample.int(1000, 1)#for the last model
  
  svmRfe1 <- rfe(fact,resp,size=c(4,6,8,10,12),
                 metric="RMSE",
                 maximize=FALSE,
                 method="svmLinear",
                 
                 rfeControl=rfeControl(method="repeatedcv",
                                       seeds = seeds,
                                       index = createFolds(resp,
                                                           k=10,
                                                           returnTrain=T),
                                       repeats=10,
                                       verbose=FALSE,
                                       functions= caretFuncs), 
                 tuneGrid= data.frame(.C=10^(-4:-2))
                 , scaled = FALSE ###################### <--- CAUSES ISSUE. ONCE REMOVED, NO FAILURE.
                 
  )
  
  print(paste('done with',i,sep=" "))
  
  svmRfe1
  
}
stopCluster(cl) 
setwd(currentDirectory)
print(proc.time()-ptm)

**Comment by zachmayer** [comment]
Is there any of this code you can cut out, while preserving the error?  That will help us specifically identify where the problem is.

**Comment by lsusatyo-gcmlp** [comment]
Here's the slimmed down version with no paralization:

library(caret)
library(kernlab)
library(robustHD)
library(glmnet)
library(parallel)
library(doParallel)
library(paran)

response <- as.data.frame(matrix(rnorm(60)), nrow=60) * 0.01
factors <- as.data.frame(matrix(rnorm(60 * 10), nrow=60)) * 0.01

output <- foreach(i=c(1), .packages=c('paran','caret', 'kernlab')) %do% {
  
  resp <- response[, i]
  fact <- factors
  
  caretFuncs$selectSize <- function (x, metric, tol = .5, maximize) 
  {
    if (!maximize) {
      best <- min(x[-nrow(x), metric])
      perf <- (x[-nrow(x), metric] - best)/best * 100
      flag <- perf <= tol
    }
    else {
      best <- max(x[-nrow(x), metric])
      perf <- (best - x[-nrow(x), metric])/best * 100
      flag <- perf <= tol
    }
    min(x[flag, "Variables"])
  }
  
  #create a list of seed, here change the seed for each resampling
  set.seed(123)
  seeds <- vector(mode = "list", length = 101)
  for(j in 1:100) seeds[[j]]<- sample.int(n=1000, 6) 
  seeds[[101]]<-sample.int(1000, 1)#for the last model
  
  svmRfe1 <- rfe(fact,resp,size=c(4,6,8,10,12),
                 metric="RMSE",
                 maximize=FALSE,
                 method="svmLinear",
                 
                 rfeControl=rfeControl(method="repeatedcv",
                                       seeds = seeds,
                                       index = createFolds(resp,
                                                           k=10,
                                                           returnTrain=T),
                                       repeats=10,
                                       verbose=FALSE,
                                       functions= caretFuncs), 
                 tuneGrid= data.frame(.C=10^(-4:-2))
                 # , scaled = FALSE ###################### <--- CAUSES ISSUE. ONCE REMOVED, NO FAILURE.
                 
  )
  svmRfe1
}

**Comment by topepo** [comment]
It might be an issue with this particular data set:

```r
> tmp <- as.data.frame(factors)
> tmp$response <- response[,1]
> tt <- ksvm(response ~ ., data = tmp, kernel = vanilladot())
> tt <- ksvm(response ~ ., data = tmp, kernel = vanilladot(), scaled = FALSE)
Error in .local(x, ...) : 
  No Support Vectors found. You may want to change your parameters
> tt <- ksvm(response ~ ., data = tmp, kernel = vanilladot(), scaled = FALSE, C = 10^-4)
Error in .local(x, ...) : 
  No Support Vectors found. You may want to change your parameters
> tt <- ksvm(response ~ ., data = tmp, kernel = vanilladot(), scaled = FALSE, C = 10^-2)
Error in .local(x, ...) : 
  No Support Vectors found. You may want to change your parameters
```

I have no idea why; the predictors and the first response look fine to me. It looks unrelated to `ref` though.
