### ISSUE TITLE
Sensitivity and Specificity switched due to factor ordering 

### ISSUE THREAD

**Issue by affans** [topepo/caret#222]
Using the standard `glm` method in caret's training function, I found a small bug. My response variable is binary, so by `glm` documentation, it expects the **order** of the 2 factors levels to denote (`failure`, `success`).  

When the summary control method is 'twoClassSummary', it runs the following sensitivity and specificity code. In `twoClassSummary()` function: 

`sensitivity(data[, "pred"], data[, "obs"],  lev[1])`
`specificity(data[, "pred"], data[, "obs"], lev[2]))`

Here,  the last argument of `sensitivity` asks for the *positive* factor. However, `lev[1]` corresponds to the *negative* factor as required by `glm`. Similar problem for `specificity`

**Comment by topepo** [comment]
That was a deliberate choice. Different functions handle the event of interest differently and we went with the choice that the _first_ factor level is of interest.

**Comment by affans** [comment]
Oh okay, thanks for the fast response. 

Might I suggest including this in the documentation. It took me a few hours trying to see why I was getting *apparent* wrong results. It wasn't until I dived into the source code that I realized what is going on.
