### ISSUE TITLE
Lift function can't handle NAs

### ISSUE THREAD

**Issue by MarwaNabil** [topepo/caret#225]
I am trying to evaluate different models using Lift chart. The different model predictions have different length. So combining them all results in some rows with NA,as shown below,
X    Model-A     Model-B
1        0.7            NA
2        NA             0.6

This results in NA values in computed lift values. Is there any way to remove NAs of different models through the evaluation steps?

Thanks.

**Comment by topepo** [comment]
That sounds like a bug. I'll try to come up with a fix soon.

**Comment by topepo** [comment]
fixed.

**Comment by ahmadhamada77** [comment]
I am facing some troubles with the accuracy coming out from the `rfe` function in the `caret` package.

1. I am using `caretFuncs + svmRadial`
2. My RFe control was 

        ctrl_rfe3 <- rfeControl(method = "repeatedcv",
                                number= 2, 
                          		repeats = 0,
                         		functions= caretFuncs)

3. My RFe function is

        set.seed(100)

        svm_rfe_li <- rfe(class~.,
                          data=bw,
                          method = "svmRadial",
                          sizes = c(20:252),
                          rfeControl = ctrl_rfe3)

4. I have 58 variables
5. I need on 20 to 25 variables
6. The output from RFe gives me low accuracy 52 -55% for the 20 to 25 variables and on the other hand when for the whole 58 variables , the accuracy was 83%
7. When I checked the variables using ..$variables, I found that it was( for example in the 20 variable model)  choosing the first 20 variables by order of columns from the data frame and didn’t include for example the variable from 21 to 58 as shown below

           Variables   Var1 Freq Prob
        1         20  A26_1    4    1
        2         20 A26_10    4    1
        3         20 A26_11    4    1
        4         20 A26_12    4    1
        5         20 A26_13    4    1
        6         20 A26_14    4    1
        7         20 A26_15    4    1
        8         20 A26_16    4    1
        9         20 A26_17    4    1
        10        20 A26_18    4    1
        11        20 A26_19    4    1
        12        20  A26_2    4    1
        13        20 A26_20    4    1
        14        20  A26_3    4    1
        15        20  A26_4    4    1
        16        20  A26_5    4    1
        17        20  A26_6    4    1
        18        20  A26_7    4    1
        19        20  A26_8    4    1
        20        20  A26_9    4    1

**Comment by ahmadhamada77** [comment]
I am facing some troubles with the accuracy coming out from the `rfe` function in the `caret` package.

1. I am using `caretFuncs + svmRadial`
2. My RFe control was 

        ctrl_rfe3 <- rfeControl(method = "repeatedcv",
                                number= 2, 
                          		repeats = 0,
                         		functions= caretFuncs)

3. My RFe function is

        set.seed(100)

        svm_rfe_li <- rfe(class~.,
                          data=bw,
                          method = "svmRadial",
                          sizes = c(20:252),
                          rfeControl = ctrl_rfe3)

4. I have 58 variables
5. I need on 20 to 25 variables
6. The output from RFe gives me low accuracy 52 -55% for the 20 to 25 variables and on the other hand when for the whole 58 variables , the accuracy was 83%
7. When I checked the variables using ..$variables, I found that it was( for example in the 20 variable model)  choosing the first 20 variables by order of columns from the data frame and didn’t include for example the variable from 21 to 58 as shown below

           Variables   Var1 Freq Prob
        1         20  A26_1    4    1
        2         20 A26_10    4    1
        3         20 A26_11    4    1
        4         20 A26_12    4    1
        5         20 A26_13    4    1
        6         20 A26_14    4    1
        7         20 A26_15    4    1
        8         20 A26_16    4    1
        9         20 A26_17    4    1
        10        20 A26_18    4    1
        11        20 A26_19    4    1
        12        20  A26_2    4    1
        13        20 A26_20    4    1
        14        20  A26_3    4    1
        15        20  A26_4    4    1
        16        20  A26_5    4    1
        17        20  A26_6    4    1
        18        20  A26_7    4    1
        19        20  A26_8    4    1
        20        20  A26_9    4    1
