### ISSUE TITLE
keeping the predictions 

### ISSUE THREAD

**Issue by satyausc** [topepo/caret#227]
Hi, 
I am using Caret to do the leave one out cross validation (LOOCV) with linear model(lm) as the method. 
I was wondering how to keep the predictions for every test  cases. I have seen in glmnet there is an option of keep=TRUE, which basically saves the predictions. I was looking for the same in Caret, but was not able to. Please let me know if there is one. 

Thanks, 
Satya

**Comment by zachmayer** [comment]
See the docs for [trainControl](http://www.inside-r.org/packages/cran/caret/docs/trainControl), which controls all the cross-validation parameters.  Specifically:
```{R}
library(caret)
model <- train(Sepal.Length~., iris, method='glm', trControl=trainControl(method='cv', number=3, savePredictions=TRUE))
> head(model$pred)
      pred obs rowIndex parameter Resample
1 4.753010 4.7        3      none    Fold1
2 4.872196 4.6        4      none    Fold1
3 4.884776 4.9       10      none    Fold1
4 5.134377 5.4       11      none    Fold1
5 5.084727 4.8       12      none    Fold1
6 4.759638 4.8       13      none    Fold1
```
