### ISSUE TITLE
classification with Naive Bayes - error when asking for class probilities

### ISSUE THREAD

**Issue by antoine-sachet** [topepo/caret#228]
When doing classification with Naive Bayes, I get an error when asking for class probabilities.

The error message is "Error in `[.data.frame`(out, , obsLevels, drop = FALSE) : undefined columns selected". Yet, I can obtain those probabilities by calling predict on the naiveBayes model directly. And the modelInfo$prob function can get them too!

I am using the last version of caret, installed with devtools::install_github today.
 
Here is a small reproducible example:
```R
library("caret")
data <- matrix(rnorm(1000), nrow = 1000, ncol=10)
y <- factor(rowSums(data) > 10 )

tr <- createDataPartition(y = y, p = 0.75)[[1]]

fit <- caret::train(x=data[tr,], y=y[tr], method="nb")

# This does not work
predict(fit, newdata=data[-tr,], type="prob")
# Error in `[.data.frame`(out, , obsLevels, drop = FALSE) : 
# undefined columns selected

# Yet the following does work:
getProb <- fit$modelInfo$prob
getProb(fit$finalModel, newdata=data[-tr,])

# which is equivalent to 
predict(fit$finalModel, newdata=data[-tr,], type="raw")$posterior
```

**Comment by topepo** [comment]
Using class probabilities will require data frames with column names equal to the levels of the outcome. Having `TRUE` and `FALSE` as levels is a bad idea and causes the error.

**Comment by antoine-sachet** [comment]
Thank you, I had a similar issue in my actual code. Apologies, I thought it was a bug.
