### ISSUE TITLE
pROC library not loaded and thus glm model won't run.

### ISSUE THREAD

**Issue by yina** [topepo/caret#233]
Posted a stackoverflow question here.

http://stackoverflow.com/questions/32292908/glm-with-caret-package-producing-missing-values-in-resampled-performance-measur/32292948#32292948

Maybe I'm doing something simple that is not correct, but once pROC was loaded, everything worked as expected.

I am using v6.0-52 of caret.

**Comment by topepo** [comment]
You should install using

```r
install.packages("caret", dependencies = c("Imports", "Depends", "Suggests"))
```

That gets most of the default packages. If there are specific modeling packages that are missing, the code usually prompts you to install them.
