### ISSUE TITLE
error passing data to python

### ISSUE THREAD

**Issue by topepo** [topepo/caret#236]
For the `pythonKnnReg` model, I get an error executing the line:

```r
python.exec('X = pd.DataFrame(X)')
```
that
```
SyntaxError: EOL while scanning string literal
  File "<string>", line 2
    X =' [ {
           ^
```
I'm using `rPython_0.0-5`, `RJSONIO_1.3-0` in R and 

```python
Python 2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> np.__version__
'1.6.2'
>>> 
>>> import pandas as pd
>>> pd.__version__
'0.13.1'
>>> 
>>> import sklearn as skl
>>> skl.__version__
'0.16.1'
>>> 
```

**Comment by cancandan** [comment]
When I run the following in R:
```
python.exec('import sys')
python.exec('import pandas as pd')
python.exec('import numpy as np')
python.exec('import sklearn as sk')
python.exec('print(sys.version)')
python.exec('print(np.__version__)')
python.exec('print(pd.__version__)')
python.exec('print(sk.__version__)')
```
I get this
```
2.7.5 (default, Mar  9 2014, 22:15:05) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
> python.exec('print(np.__version__)')
1.8.0
> python.exec('print(pd.__version__)')
0.16.2
> python.exec('print(sk.__version__)')
0.16.1
```
Printing versions this way is just to make sure rPython links to the python on your machine that has the required libs installed (in case you have multiple pythons)

I don't get this error so I think it might be related to versions of the libs

**Comment by cancandan** [comment]
Can you check whether its related to the version of the libs by installing the latest libs?

**Comment by cancandan** [comment]
Searching for this error I see stackoverflow posts suggesting that it might be related to json serialization and encoding, do you get this error when you run the following for example?

```
library(rPython)
x=matrix(1:100,10,10)
python.assign("X",x)
python.exec('import pandas as pd')
python.exec('import numpy as np')
python.exec('X = pd.DataFrame(X)')
```

**Comment by topepo** [comment]
I have it worked out. I had to make small changes to the model script for other reasons.

**Comment by andrejastojic** [comment]
I've just installed rPython, when I run the  examples above, I get:

Example 1. 
library(rPython)
python.exec('import sys')
python.exec('import pandas as pd')
python.exec('import numpy as np')
python.exec('print(sys.version)')
python.exec('print(np.__version__)')
python.exec('print(pd.__version__)')

nothing;

Example 2.
library(rPython)
x=matrix(1:100,10,10)
python.assign("X",x)
python.exec('import pandas as pd')
python.exec('import numpy as np')
python.exec('X = pd.DataFrame(X)')

Error in python.get("X") : Variable not found

I use R 
version 3.4.3 (2017-11-30) rPython_0.0-6 RJSONIO_1.3-0

and 

Python 3.6.4
np.__version__
'1.14.1'
pd.__version__
'0.22.0'

**Comment by topepo** [comment]
You would have to contact the package maintainer for `rPython`. The code above doesn't have anything to do with `caret` AFAICT.
