### ISSUE TITLE
update.train error

### ISSUE THREAD

**Issue by topepo** [topepo/caret#241]
It looks like the weights are not being passed to `createModel` as one would expect:

```r
library(caret)

set.seed(1)
dat <- twoClassSim(100)

set.seed(2)
gbm_mod <- train(Class ~ ., data = dat, 
                 method = "gbm",
                 trControl = trainControl(method = "cv"),
                 verbose = FALSE)


gbm_up <- update(gbm_mod, 
                 list(interaction.depth = 1,  
                      n.trees  = 10,
                      shrinkage = .1, 
                      n.minobsinnode = 20))
```
```
Error in method$fit(x = x, y = y, wts = wts, param = tuneValue, lev = obsLevels,  : 
  argument "wts" is missing, with no default
```

`update` does work on other models (e.g. FDA) so the bug may only be for models that might be able to use weights.

**Comment by jameskyle** [comment]
Any suggestions on a manual workaround? Like how to extract the requried parameters from the caret model and pass them into a new rpart train method?

**Comment by topepo** [comment]
I don't have one. I'll need to make some updates to `train`. I was planning on having a new release by now but like and work have gotten in the way. I'll see if I can sneak this change into this new release. I don't think that it is too invasive but if it is then it will have to wait a little bit. In either case I will keep you posted.

**Comment by jameskyle** [comment]
> but like and work have gotten in the way

I know that song well.

> In either case I will keep you posted.

Thanks!

**Comment by topepo** [comment]
Your example works with the code that I just checked in. Can you please verify that it works for you?

Thanks,

Max

**Comment by jameskyle** [comment]
Thank you for working on this @topepo. I'll try to find time to test it out next week, got a paper due this weekend..
