### ISSUE TITLE
Dependency Issue When Loading in R

### ISSUE THREAD

**Issue by angoodkind** [topepo/caret#250]
When I try to load this package in R, I get the following error:
`ERROR: dependency ‘car’ is not available for package ‘caret’`

**Comment by jknowles** [comment]
@angoodkind You should be able to easily solve this by running: 

```r
install.packages("car")
library(caret)
```

If this does not work try running:

```r
install.packages("caret", depencencies = c("Depends", "Suggests"))
library(caret)
```

**Comment by angoodkind** [comment]
Thanks. Turned out I just needed to upgrade R to 3.2.2.
