### ISSUE TITLE
bucketing with preProcess

### ISSUE THREAD

**Issue by smsaladi** [topepo/caret#251]
Is bucketing features currently possible with preProcess? If not, I think it would be a good feature to add and would be happy to contribute this.

**Comment by topepo** [comment]
Not yet, but it is in the works. I have a class for binning that I haven't
checked in yet and there are some changes to `preProcess` that would have
to happen before we could integrate this.

**Comment by topepo** [comment]
You can do this using a recipe as input. Beyond that, we wont be implementing anything.
