### ISSUE TITLE
plsda: 'length of 'dimnames' [1] not equal to array extent'

### ISSUE THREAD

**Issue by kimberlymcm** [topepo/caret#252]
When I try to run any data, include the example on the ?plsda R documentation, I run into an error. The plsda method runs, but when I look at summary(result), it gives me the below error. This is based on running all of the exact code from the R-documentation example, though I get this from any type of data I try to run. What does this error come from?

> useSoftmax <- plsda(trainDescr, trainMDRR, ncomp = 5)
> summary(useSoftmax)
Data: 	X dimension: 450 297 
	Y dimension: 450 2
Fit method: kernelpls
Number of components considered: 5
TRAINING: % variance explained
Error in dimnames(tbl) <- list(c("X", yvarnames), paste(1:object$ncomp,  : 
  length of 'dimnames' [1] not equal to array extent

**Comment by FunderBolt** [comment]
I get the same error!  ... ? any clues?

**Comment by kimberlymcm** [comment]
I never figured it out :/. I just ended up using the plsda function implemented in the mixOmics R package instead. But any insights for the future would be useful!

**Comment by FunderBolt** [comment]
:)  thanks for help! will move to mixOmics ...  and if (IF) I figure something out I will let you know.
c

**Comment by topepo** [comment]
It's not really a bug _per se_... the `summary` function calls `pls:::summary.mvr` which calls `pls:::explvar`. Because of our `Y` matrix being a singular matrix of binary data, it cannot compute some statistics and produces an error. Basically, it is a consequence of doing discriminant analysis.
