### ISSUE TITLE
typo on website - training

### ISSUE THREAD

**Issue by smsaladi** [topepo/caret#253]
Currently the page reads:

>```R
gbmFit2 <- train(Class ~ ., data = training,
                 method = "gbm",
                 trControl = fitControl,
                 verbose = FALSE,
                 ## Now specify the exact models 
                 ## to evaludate:
                 tuneGrid = gbmGrid)
gbmFit2

`evaludate` should probably be `evaluate`

**Comment by topepo** [comment]
You are correct. Thanks
