### ISSUE TITLE
Error in forceNetwork(Links = links, Nodes = nodes, Source = "source", : unused argument (fontsize = 6)

### ISSUE THREAD

**Issue by tobigithub** [topepo/caret#254]
Hi,
network graph does not show in [http://topepo.github.io/caret/similarity.html](http://topepo.github.io/caret/similarity.html). True in FF and Chrome.
Also code in repo is different from code shown on website.

Error also cached on Google
```HTML
The caret Package
topepo.github.io/caret/similarity.html
Error in forceNetwork(Links = links, Nodes = nodes, Source = "source", : unused argument (fontsize = 6). The data used to create this graph can be found here.
````
Cheers
Tobias

**Comment by topepo** [comment]
Thanks. I'm fixing it now. It looks like `forceNetwork` changed some argument names.

**Comment by tobigithub** [comment]
Thank you.
Tobias
