### ISSUE TITLE
mlp model with RSNNS  package masks confusionMatrix, train

### ISSUE THREAD

**Issue by tobigithub** [topepo/caret#256]
HI,
downloading the test or example data from > model <- "mlp" the following issue occurs:

````R
> library(RSNNS)
Loading required package: Rcpp

Attaching package: ‘RSNNS’

The following objects are masked from ‘package:caret’:

    confusionMatrix, train
````
this will lead from the correct 

````R
> apropos("confusion")
[1] "confusionMatrix"       "confusionMatrix.train"

````
to the incorrect:

````R
> apropos("confusion")
[1] "confusionMatrix"       "confusionMatrix"       "confusionMatrix.train"

````
This will further down the road lead  to the following error for all packages that are used after the "mlp" training model such as

````R
Error in confusionMatrix :  $ operator is invalid for atomic vectors
or
Error in toNumericClassLabels(targets) :    (list) object cannot be coerced to type 'double'

````
Still need to verify that but it is under RSNNS_0.4-7,  Rcpp_0.12.0 ,    caret_6.0-52   
under PRO 3.2.2 under Windows. Basically, code that was running OK, will after the install of the mlp training model, generate only errors such as  confusionMatrix  $ operator is invalid for atomic vectors or others. One solution would be to use:

````R
caret::confusionMatrix(...)
`````
But I have not tested that for all scenarios.
Cheers
Tobias

**Comment by topepo** [comment]
I checked in a change. Please give it a try to see if it fixes the issue for you. 

Thanks,

Max

**Comment by tobigithub** [comment]
Cool. Thank you
Tobias

**Comment by tobigithub** [comment]
Cool. Thank you
Tobias

**Comment by topepo** [comment]
Looking at my changes, there really isn't anything else that I can do. The function in `RSNNS` isn't object oriented so that does not solve it. You will have to call using `caret::confusionMatrix` to get the right version when you have them both loaded.
