### ISSUE TITLE
Consider including "Rborist" or "ranger" (fast randomForest implementations) already available in R.

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#258]
Hello,
Just a question about if you are can consider including "Rborist" or "ranger" faster implementations of randomForest and more suitable for big datasets (in the number of features and in the number of cases).

Both packages are already availble in R.
For ranger, here is a more detailed description of its implementation, execution times, etc. compared with other randomForest implementations (included the one already in R): http://arxiv.org/abs/1508.04409

**Comment by zachmayer** [comment]
We should definitely put a wrapper for these into caret.  We'd be happy to get a pull request from you =D, or we can work on it ourselves when time allows.

**Comment by topepo** [comment]
[Added](https://github.com/topepo/caret/issues/196) and will be in the next version.

**Comment by pras4** [comment]
I notice that Rborist is not yet in. The advantage of Rborist is that it gives you option to train with quantile information (which ranger does not give) - I think this would be useful to add to caret

**Comment by topepo** [comment]
I have not been able to use that package without is set faulting on me (or aborting in other ways). I just reinstalled it today (precompiled and later from sources) and had the same experience.

**Comment by pras4** [comment]
Bummer! Including quantile regression in the code with parallelization seemed like a good idea - should wait for more mature code i suppose.
Thanks for trying.
