### ISSUE TITLE
Predicted probabilities for multiclass avNNet don't sum to one

### ISSUE THREAD

**Issue by brentonk** [topepo/caret#261]
When I fit an `avNNet` model for multiclass output via `train()` and then calculate predicted probabilities via `predict(..., type = "prob")`, the resulting probabilities don't sum to one. The problem seems not to occur with two-class problems (though I haven't tested extensively), and it doesn't occur when I use the fitted model directly instead of the `train` object. The problem seems to be that the raw scores don't get normalized. See the example below.

## Reproducible Example

``` r
library("caret")

sessionInfo()
```

    ## R version 3.2.2 (2015-08-14)
    ## Platform: x86_64-apple-darwin14.5.0 (64-bit)
    ## Running under: OS X 10.10.5 (Yosemite)
    ## 
    ## locale:
    ## [1] en_US/en_US/en_US/C/en_US/en_US
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] rmarkdown_0.8   nnet_7.3-11     caret_6.0-52    ggplot2_1.0.1  
    ## [5] lattice_0.20-33
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.1         formatR_1.2.1       compiler_3.2.2     
    ##  [4] nloptr_1.0.4        plyr_1.8.3          iterators_1.0.7    
    ##  [7] class_7.3-14        tools_3.2.2         digest_0.6.8       
    ## [10] lme4_1.1-10         evaluate_0.8        nlme_3.1-122       
    ## [13] gtable_0.1.2        mgcv_1.8-7          Matrix_1.2-2       
    ## [16] foreach_1.4.2       yaml_2.1.13         parallel_3.2.2     
    ## [19] brglm_0.5-9         SparseM_1.7         proto_0.3-10       
    ## [22] e1071_1.6-7         knitr_1.11          BradleyTerry2_1.0-6
    ## [25] stringr_1.0.0       gtools_3.5.0        MatrixModels_0.4-1 
    ## [28] stats4_3.2.2        grid_3.2.2          minqa_1.2.4        
    ## [31] reshape2_1.4.1      car_2.1-0           magrittr_1.5       
    ## [34] htmltools_0.2.6     scales_0.3.0        codetools_0.2-14   
    ## [37] MASS_7.3-44         splines_3.2.2       pbkrtest_0.4-2     
    ## [40] colorspace_1.2-6    quantreg_5.19       stringi_0.5-5      
    ## [43] munsell_0.4.2

``` r
set.seed(97)
y <- factor(rbinom(50, 2, 0.5), levels = 0:2, labels = c("A", "B", "C"))
x <- matrix(rnorm(100), ncol = 2)

fit <- train(x, y,
             method = "avNNet",
             trControl = trainControl(method = "none",
                                      classProbs = TRUE,
                                      allowParallel = FALSE),
             tuneGrid = data.frame(size = 3,
                                   decay = 1e-1,
                                   bag = FALSE),
             trace = 0)

dat <- matrix(rnorm(10), ncol = 2)
(pp_train <- predict(fit, newdata = dat, type = "prob"))
```

    ##         A       B       C
    ## 1 0.16821 0.68700 0.20245
    ## 2 0.59285 0.22636 0.21299
    ## 3 0.40549 0.38868 0.20865
    ## 4 0.33042 0.45889 0.21405
    ## 5 0.43398 0.36333 0.20754

``` r
rowSums(pp_train)
```

    ##      1      2      3      4      5 
    ## 1.0577 1.0322 1.0028 1.0034 1.0049

``` r
(pp_finalModel <- predict(fit$finalModel, newdata = dat, type = "prob"))
```

    ##         A       B       C
    ## 1 0.15904 0.64955 0.19142
    ## 2 0.57435 0.21930 0.20634
    ## 3 0.40435 0.38758 0.20807
    ## 4 0.32931 0.45736 0.21333
    ## 5 0.43189 0.36158 0.20654

``` r
rowSums(pp_finalModel)
```

    ## 1 2 3 4 5 
    ## 1 1 1 1 1

``` r
all.equal(pp_finalModel, data.matrix(pp_train / rowSums(pp_train)))
```

    ## [1] TRUE

**Comment by topepo** [comment]
Ah yes the problem is that the default is:

```r
predict.avNNet
function (object, newdata, type = c("raw", "class", "prob"), 
    ...)
```

and the model code used

```r
predict(modelFit, newdata)
```

There actually is code to ensure that they sum to one in `predict.avNNet` when `type[1] == "prob"`. 

Thanks,

Max
