### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by wabee** [topepo/caret#263]
When running a gbm model on a fairly modest dataset (15k observations and 31 predictors) I noticed that my computer basically ran out of memory during training. Also, when the analysis finished after a few hours the memory was not released.
I ran the analysis on a machine with 16GB of memory using repeated 10-fold crossvalidation, repeated 10 times. 
OS is Windows 2008R2 and running most recent version of R and Rstudio with caret installed from the cran repository

**Comment by zachmayer** [comment]
Did you run them in parallel or sequentially?  Did you run with savePredictions=True?




Both those options can suck up a lot of ram, especially with 100 rounds (10x10) of modeling.



—

**Comment by topepo** [comment]
We would need a lot more information. Were you running in parallel?

**Comment by wabee** [comment]
Zachmayer & topepo:
I did not specify "savePrediction=True" explicitly and I didn't register multiple cores either. 

Have run much larger problems before using gbm directly with 10-fold CV. I'm new to caret and really like the capability to "auto tune" the models but puzzled regarding how the RAM was all consumed. Memory was not released until I closed down Rstudio completely.

I'll be happy to supply further information.

**Comment by topepo** [comment]
It's hard to reproduce the issue with this information. Is there anything else in your workspace when you execute the code? In other words, can you isolate the part using `train` to see if that is the issue? Also, sending the results of `str` on your training set objects and showing some code would help.

**Comment by wabee** [comment]
Here is the result of "str":
> str(training)
'data.frame':   15699 obs. of  33 variables:
 $ user_name           : Factor w/ 6 levels "adelmo","carlitos",..: 2 2 2 2 2 2 2 2 2 2 ...
 $ yaw_belt            : num  -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 -94.4 ...
 $ gyros_belt_x        : num  0 0 0.02 0.02 0.02 0.02 0.02 0.02 0.03 0.03 ...
 $ gyros_belt_y        : num  0 0 0 0.02 0 0 0 0 0 0 ...
 $ gyros_belt_z        : num  -0.02 -0.02 -0.03 -0.02 -0.02 -0.02 -0.02 -0.02 0 -0.02 ...
 $ magnet_belt_x       : int  -3 -2 -6 -6 0 -4 -2 1 -3 -5 ...
 $ magnet_belt_y       : int  599 600 604 600 603 599 603 602 609 596 ...
 $ roll_arm            : num  -128 -128 -128 -128 -128 -128 -128 -128 -128 -128 ...
 $ pitch_arm           : num  22.5 22.5 22.1 22.1 22 21.9 21.8 21.7 21.6 21.5 ...
 $ yaw_arm             : num  -161 -161 -161 -161 -161 -161 -161 -161 -161 -161 ...
 $ total_accel_arm     : int  34 34 34 34 34 34 34 34 34 34 ...
 $ gyros_arm_y         : num  0 -0.02 -0.03 -0.03 -0.03 -0.03 -0.02 -0.03 -0.03 -0.03 ...
 $ gyros_arm_z         : num  -0.02 -0.02 0.02 0 0 0 0 -0.02 -0.02 0 ...
 $ magnet_arm_x        : int  -368 -368 -372 -374 -369 -373 -372 -369 -376 -366 ...
 $ magnet_arm_z        : int  516 513 512 506 513 509 510 518 516 509 ...
 $ roll_dumbbell       : num  13.1 12.9 13.4 13.4 13.4 ...
 $ pitch_dumbbell      : num  -70.5 -70.3 -70.4 -70.4 -70.8 ...
 $ yaw_dumbbell        : num  -84.9 -85.1 -84.9 -84.9 -84.5 ...
 $ total_accel_dumbbell: int  37 37 37 37 37 37 37 37 37 37 ...
 $ gyros_dumbbell_y    : num  -0.02 -0.02 -0.02 -0.02 -0.02 -0.02 -0.02 -0.02 -0.02 -0.02 ...
 $ magnet_dumbbell_z   : num  -65 -63 -60 -68 -66 -70 -74 -65 -69 -64 ...
 $ roll_forearm        : num  28.4 28.3 28.1 28 27.9 27.9 27.8 27.7 27.7 27.6 ...
 $ pitch_forearm       : num  -63.9 -63.9 -63.9 -63.9 -63.9 -63.9 -63.8 -63.8 -63.8 -63.8 ...
 $ yaw_forearm         : num  -153 -152 -152 -152 -152 -152 -152 -152 -152 -152 ...
 $ total_accel_forearm : int  36 36 36 36 36 36 36 36 36 36 ...
 $ gyros_forearm_x     : num  0.03 0.03 0.02 0.02 0.02 0.02 0.02 0.03 0.02 0.02 ...
 $ gyros_forearm_z     : num  -0.02 0 0 -0.02 -0.03 -0.02 0 -0.02 -0.02 -0.02 ...
 $ accel_forearm_x     : int  192 196 189 189 193 195 193 193 190 193 ...
 $ accel_forearm_z     : int  -215 -213 -214 -214 -215 -215 -213 -214 -215 -214 ...
 $ magnet_forearm_x    : int  -17 -18 -16 -17 -9 -18 -9 -16 -22 -17 ...
 $ magnet_forearm_y    : num  654 658 658 655 660 659 660 653 656 657 ...
 $ magnet_forearm_z    : num  476 469 469 473 478 470 474 476 473 465 ...
 $ classe              : Factor w/ 5 levels "A","B","C","D",..: 1 1 1 1 1 1 1 1 1 1 ...

The dependent variable is classe, a multinomial classification problem.

The actual command to run the training is:
#Partition data into training and test sets
set.seed(998)
inTraining <- createDataPartition(train.file$classe, p = .80, list = FALSE)
training <- train.file[ inTraining,]
testing  <- train.file[-inTraining,]
#Set parameters for model training
fitControl <- trainControl(## 10-fold CV
        method = "repeatedcv",
        number = 10,
        repeats = 10)
#Fit gbm model to training data
gbmFit1 <- train(classe ~ ., data = training,
                 method = "gbm",
                 trControl = fitControl
                 verbose = FALSE)

**Comment by wabee** [comment]
Reopen

**Comment by tobigithub** [comment]
Hi,
I think the [HAR Dataset](http://groupware.les.inf.puc-rio.br/har) is not a good example for testing split or CV methods, because its either too big or the R ML methods are too slow. I agree, it will easily eat multiple GBytes of RAM, for trainControl(method="LOOCV") each instance of rscript will consume 4 GByte of RAM, so with 8 threads = 32 Gbyte of RAM etc. Also people in the past mentioned [memory leaks](https://www.google.com/?gws_rd=ssl#q=gbm+%22memory+leak%22) with using older GBM packages, but I can not confirm that yet. Using standard parameters will lead to the same results as using some of the more time and memory consuming methods. The example is of course nice, because it has many implementations from all the people who worked with coursera. I also do not see any advantage of using GBM, unless its faster, uses less memory and is more accurate than any other ML method. 

````R
# Parallel Random Forest and Generalized Boosted Regression Models with R PRO
# Sources used: 
# http://bigcomputing.blogspot.com/2014/10/an-example-of-using-random-forest-in.html
# https://www.coursera.org/specializations/jhudatascience?utm_medium=courseDescripTop
# https://rstudio-pubs-static.s3.amazonaws.com/89748_264cbfde747d4d779d7bd6b9b3f31f45.html
# Google -> "InTrain<-createDataPartition(" predict(rf_model,test) "pml-training.csv"
# Google -> "Using devices such as Jawbone Up, Nike FuelBand, and Fitbit" caret
# Google -> https://www.google.com/?gws_rd=ssl#q=%22B+A+B+A+A+E+D+B+A+A+B+C+B+A+E+E+A+B+B+B%22
# https://yoke2.github.io/PMLCourseProject/pmlreport.html
# Tobias Kind (2015)


library(caret)
require(ggplot2)
require(randomForest)

library(doSNOW)
library(parallel)

training_URL<-"http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
test_URL<-"http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training<-read.csv(training_URL,na.strings=c("NA",""))
test<-read.csv(test_URL,na.strings=c("NA",""))

training<-training[,7:160]
test<-test[,7:160]

mostly_data<-apply(!is.na(training),2,sum)>19621
training<-training[,mostly_data]
test<-test[,mostly_data]
dim(training)


#plot feature wise
#https://rpubs.com/davizuku/practical_ml
selCols <- grep("^accel_", names(training));
featurePlot(x = training[,selCols],
            y = training$classe,
            plot = "boxplot");
            
selCols <- grep("^magnet_", names(training));
featurePlot(x = training[,selCols],
            y = training$classe,
            plot = "boxplot");

selCols <- grep("^gyros_", names(training));
featurePlot(x = training[,selCols],
            y = training$classe,
            plot = "boxplot");
            
          
#plot training data
featurePlot(x=training[,c(1:12)], y=training$classe, plot = 'box')
  
InTrain<-createDataPartition(y=training$classe,p=0.3,list=FALSE)
training1<-training[InTrain,]

# detect true cores requires parallel()
nCores <- detectCores(logical = FALSE)
# detect threads
nThreads <- detectCores(logical = TRUE)

cl <- makeCluster(nThreads, type="SOCK")
registerDoSNOW(cl); cl;
getDoParWorkers()
getDoParName()

#------------------------------------------------------------
# rf = random forest usually works
ptm <- proc.time()
rf_model<-train(classe~.,data=training1,method="rf")
		# method="repeatedcv", number=10, repeats=3 ## repeated k-fold Cross Validation
		# method="cv",number=5 ## k-fold Cross Validation
                # method="LOOCV" ## Leave One Out Cross Validation
                # method="boot", number=100 ## Bootstrap
                # method = "boot632" ## The .632+ Bootstrap 
                # trControl=trainControl(method="boot632"),
                # prox=TRUE,allowParallel=TRUE)
proc.time() - ptm
#------------------------------------------------------------
# gbm - no traincontrol
ptm <- proc.time()
model1<-train(classe~.,data=training1,method="gbm")
		# trControl=trainControl(method="repeatedcv", number=10, repeats=3), ## repeated k-fold Cross Validation
		# trControl=trainControl(method="cv",number=5), ## k-fold Cross Validation
                # trControl=trainControl(method="LOOCV"), ## Leave One Out Cross Validation
                # trControl=trainControl(method="boot", number=100), ## Bootstrap
                # trControl=trainControl(method="boot632"), ## The .632+ Bootstrap 
                # trControl=trainControl(method="boot632"),

proc.time() - ptm
#------------------------------------------------------------
# gbm -"repeatedcv"
ptm <- proc.time()
model2<-train(classe~.,data=training1,method="gbm",
		  trControl=trainControl(method="repeatedcv", number=3, repeats=3)) ## repeated k-fold Cross Validation
 proc.time() - ptm
#------------------------------------------------------------
# gbm - "cv"
ptm <- proc.time()
model3<-train(classe~.,data=training1,method="gbm",
		  trControl=trainControl(method="cv",number=3))  ## k-fold Cross Validation
proc.time() - ptm
#------------------------------------------------------------
# gbm - "LOOCV"
ptm <- proc.time()
model4<-train(classe~.,data=training1,method="gbm",
                  trControl=trainControl(method="LOOCV"))  ## Leave One Out Cross Validation
proc.time() - ptm
#------------------------------------------------------------
# gbm - "boot"
ptm <- proc.time()
model5<-train(classe~.,data=training1,method="gbm",
                  trControl=trainControl(method="boot", number=100)) ## Bootstrap
proc.time() - ptm
#------------------------------------------------------------
# gbm - "boot632"
ptm <- proc.time()
model6<-train(classe~.,data=training1,method="gbm",
                 trControl=trainControl(method="boot632"))  ## The .632+ Bootstrap 
proc.time() - ptm
#------------------------------------------------------------
rf_model
model1
model2
model3
model4
model5
model6
#------------------------------------------------------------

# Core-i7 2600K@4.2 Ghz (4 cores/8 threads) 
# user  system elapsed for "rf" cv-5
# 36.30    0.35  142.82 (8  threads)
# "rf" repeatedcv, number=10, repeats=3
# 35.91    0.90  686.10  (8 threads)
# "gbm" no parameters
# 9.78    0.33  149.06  (8 threads)


# 2x Xeon-2687W (3.1 Ghz)
# user  system elapsed 
# 45.78    0.48  130.85 (8 threads)
 

print(rf_model)
print(rf_model$finalModel)
plot(rf_model$finalModel)
rf_model$results

#  number of variables per level (mtry)
confusionMatrix(rf_model)
plot(rf_model)

#QPLOT
qplot(roll_belt, magnet_dumbbell_y, colour=classe, data=training)  
 
rf_test <- predict(rf_model,test)
rf_test
#B A B A A E D B A A B C B A E E A B B B

stopCluster(cl)

#--- register foreach for sequential mode
registerDoSEQ()

### END


````

**Comment by wabee** [comment]
This is not about a specific dataset, I was trying out the capabilities of caret and encountered this issue which seemed worth to explore and report. The dataset is not very big from a practical perspective and still consumes all RAM in a 16GB machine. Further the RAM was not 'returned' after the analysis finished.
Since I do this 'for real' it's important to know the limitations of a particular workflow.

**Comment by tobigithub** [comment]
Hi,
agreed, maybe the HAR Dataset is too big for R as I already pointed out above, that is why one would always start benchmarking with a very very small dataset "that works", measure the execution times and then use memory profiling for all the clients. Then stepwise increase the size of the dataset. Many ML methods do not scale linear with size, they demand exponential execution time and memory. So one problem that runs a few seconds with a small matrix, can explode to hours and GBytes of RAM with a matrix that is only double in size. You simply would not expect that. Hence see the code above, use a small(er) dataset, then use gbm without CV, then with one round, with 2 rounds, 4 rounds,8 rounds then with 1 repeat, 5 repeats, 10 repeats. With each run the execution time goes up from original 2 minutes, 10 minutes and longer, plus 16 GByte memory is not enough.

In R one can use Rprof, microbenchmark and other libraries and functions, but basically graphical memory profiling in R sucks or is nonexisting, other languages have excellent profilers such as Intel Vtune etc. The external R clients also need to be profiled, not sure how they can send back the true memory allocation, here an OS based solution that measures client memory use and CPU use is probably better. 

RAM "not returned" can be invoked by gc() if  its still not returned its a memory allocation bug as the link mentioned, very common in R.  Also increasing RAM sometimes helps, especially if you do this "for real", if it creaps up to 128 or 256 GByte RAM with  small dataset its surely a bug. 

Not to forget that R covers a vast number of platforms that are usually not compatible and a number languages and compiler options plus any given package still needs a lot of testing of all possible conditions. These R issues and constant breaking code were the reasons that I hesitated to use R for a long time, but surely many of the packages such as GBM have an active developer community here on GH, so just remove the caret commands and test the native GBM commands and send your memory bug to [GBM-Developers](https://github.com/gbm-developers/gbm). People listen and help, I like that much better than on some of the commercial packages.
Cheers
Tobias

**Comment by topepo** [comment]
`caret` heavily uses the underlying package code, which can vary in terms of requirements (e.g. memory) and implementation. I hate to punt, but it is unlikely that `train` is not releasing the memory since that is all R-based code. 

Try fitting one of the models outside of `caret` and see what happens (especially if you know that the model fails for specific tuning variable values). 

You can try other boosting models too. I recommend C5.0 and xgboost. 

 > each instance of rscript will consume 4 GByte of RAM, so with 8 threads = 32 Gbyte of RAM etc.

Plus one instance for the original (so 36GB total).

**Comment by tobigithub** [comment]
Hi,
the above code works for rf and gm alone, also gbm+3x CV but LOOCV crashes R after eating around 80-100 GByte RAM.

````R
rf_model<-train(classe~.,data=training1,method="rf")
   user  system elapsed 
  17.91    1.34  126.15 

> model1<-train(classe~.,data=training1,method="gbm")
   user  system elapsed 
  11.57    1.24   52.65

,method="gbm",
+           trControl=trainControl(method="cv",number=3)
   user  system elapsed 
  10.83    0.60   19.91 

> model4<-train(classe~.,data=training1,method="gbm",
+                   trControl=trainControl(method="LOOCV"))

Error in unserialize(socklist[[n]]) : error reading from connection
> proc.time() - ptm
   user  system elapsed 
  19.89   35.10 2898.77 

````
After eating 80 GByte memory it churns some numbers and then crashes. So yes, probably a memory bug, actually if that is in caret or in gbm still needs to be tested.

![gbm-memory](https://cloud.githubusercontent.com/assets/2569565/10437897/2455148a-70e5-11e5-909b-9b81bfd59b66.png)

![r-crash1](https://cloud.githubusercontent.com/assets/2569565/10437820/a3264884-70e4-11e5-83ea-3c2a30c72eae.png)

![r-stopped-working](https://cloud.githubusercontent.com/assets/2569565/10437999/bb6d544a-70e5-11e5-80bc-91693a7fbcb1.png)

Cheers
Tobias

**Comment by topepo** [comment]
What is `nThreads` and `nCores`? That is a lot of copies. Are you running `train` is side some other loop that is running in parallel?

**Comment by tobigithub** [comment]
Hi,
nThreads=32 and nCores=16, under doSNOW one could use 120 (128) threads just for testing,
but commonly R should not crash (I assume). But I have not tested that. Also i dont have all 200 GByte RAM, only half of it because of other stuff.

**Comment by tobigithub** [comment]
So these are the results for knn, just for testing the memory requirement, it used 1-4 Gbyte memory max, dont remember, but nothing like 80 Gbyte with method="gbm" So I think it could be a gbm memory bug as proposed already hours ago. So basically 120 slower with LOOCV and three times slower with repeated CV. So unless knn inserts different parameters for "args(trainControl)" it must be a bug in GBM as seen from the [crash](https://github.com/topepo/caret/issues/263#issuecomment-147512225).
````R
## 16 cores (3.1 Ghz) 
## knn with different training splits
##                 user  system elapsed 
## rf............ 17.78    0.74  126.16
## knn...........  0.87    0.80   19.76
## knn-repeatedcv  0.75    0.56    3.12 
## knn-cv........  0.69    0.45    1.81
## knn-LOOCV..... 77.60   34.54  120.77
## knn-boot......  0.69    0.67    6.35
## knn-boot632     0.99    0.80   23.12
````

````R

library(caret)
require(ggplot2)
require(randomForest)

library(doSNOW)
library(parallel)

training_URL<-"http://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
test_URL<-"http://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
training<-read.csv(training_URL,na.strings=c("NA",""))
test<-read.csv(test_URL,na.strings=c("NA",""))

training<-training[,7:160]
test<-test[,7:160]

mostly_data<-apply(!is.na(training),2,sum)>19621
training<-training[,mostly_data]
test<-test[,mostly_data]
dim(training)


#plot feature wise
#https://rpubs.com/davizuku/practical_ml
selCols <- grep("^accel_", names(training));
featurePlot(x = training[,selCols],
            y = training$classe,
            plot = "boxplot");

selCols <- grep("^magnet_", names(training));
featurePlot(x = training[,selCols],
            y = training$classe,
            plot = "boxplot");

selCols <- grep("^gyros_", names(training));
featurePlot(x = training[,selCols],
            y = training$classe,
            plot = "boxplot");


#plot training data
featurePlot(x=training[,c(1:12)], y=training$classe, plot = 'box')

InTrain<-createDataPartition(y=training$classe,p=0.3,list=FALSE)
training1<-training[InTrain,]

# detect true cores requires parallel()
nCores <- detectCores(logical = FALSE)
# detect threads
nThreads <- detectCores(logical = TRUE)

cl <- makeCluster(nThreads, type="SOCK")
registerDoSNOW(cl); cl;
getDoParWorkers()
getDoParName()

#------------------------------------------------------------
#  rf usually works
ptm <- proc.time()
rf_model<-train(classe~.,data=training1,method="rf")
        	# method="repeatedcv", number=10, repeats=3 ## repeated k-fold Cross Validation
        	# method="cv",number=5 ## k-fold Cross Validation
                # method="LOOCV" ## Leave One Out Cross Validation
                # method="boot", number=100 ## Bootstrap
                # method = "boot632" ## The .632+ Bootstrap 
                # trControl=trainControl(method="boot632"),
                # prox=TRUE,allowParallel=TRUE)
proc.time() - ptm

#------------------------------------------------------------
# knn
ptm <- proc.time()
model1<-train(classe~.,data=training1,method="knn")
proc.time() - ptm

#------------------------------------------------------------
# "repeatedcv" ##  repeated k-fold Cross Validation
ptm <- proc.time()
model2<-train(classe~.,data=training1,method="knn",
          trControl=trainControl(method="repeatedcv", number=3, repeats=3)) ## repeated k-fold Cross Validation
 proc.time() - ptm
#------------------------------------------------------------
#  "cv"  ##  k-fold Cross Validation
ptm <- proc.time()
model3<-train(classe~.,data=training1,method="knn",
          trControl=trainControl(method="cv",number=3))  ## k-fold Cross Validation
proc.time() - ptm
#------------------------------------------------------------
# "LOOCV" ## Leave One Out Cross Validation
ptm <- proc.time()
model4<-train(classe~.,data=training1,method="knn",
                  trControl=trainControl(method="LOOCV", repeats=1))  ## Leave One Out Cross Validation
proc.time() - ptm
#------------------------------------------------------------
#  "boot" ## Bootstrap
ptm <- proc.time()
model5<-train(classe~.,data=training1,method="knn",
                  trControl=trainControl(method="boot", number=10)) ## Bootstrap
proc.time() - ptm
#------------------------------------------------------------
#  "boot632" ## The .632+ Bootstrap 
ptm <- proc.time()
model6<-train(classe~.,data=training1,method="knn",
                 trControl=trainControl(method="boot632"))  ## The .632+ Bootstrap 
proc.time() - ptm
#------------------------------------------------------------
## Times for splits and trains
##                 user  system elapsed 
## rf............ 17.78    0.74  126.16
## knn...........  0.87    0.80   19.76
## knn-repeatedcv  0.75    0.56    3.12 
## knn-cv........  0.69    0.45    1.81
## knn-LOOCV..... 77.60   34.54  120.77
## knn-boot......  0.69    0.67    6.35
## knn-boot632     0.99    0.80   23.12
#------------------------------------------------------------
rf_model
model1
model2
model3
model4
model5
model6
#------------------------------------------------------------

print(rf_model)
print(rf_model$finalModel)
plot(rf_model$finalModel)
rf_model$results

#  number of variables per level (mtry)
confusionMatrix(rf_model)
plot(rf_model)

#QPLOT
qplot(roll_belt, magnet_dumbbell_y, colour=classe, data=training)  

rf_test <- predict(rf_model,test)
rf_test
# Correct solution
#B A B A A E D B A A B C B A E E A B B B

stopCluster(cl)

#--- register foreach for sequential mode
registerDoSEQ()

### END

````

**Comment by wabee** [comment]
I've reported this to the gbm developers pointing to this thread. Thanks for all the feedback! I'll continue to investigate

**Comment by topepo** [comment]
Try running the code in R and not RStudio

**Comment by wabee** [comment]
I made a couple of modifications and reran it i R. Reduced number of CV repeats to "3" and explicitly set number of processor cores to "2" and set the flag "returnData=F" in TrainControl. Ran in ~30 mins using around 13GB.

**Comment by zachmayer** [comment]
Also try using the non-formula interface, e.g.:
```{R}
train(training1[,c(1:12)], training1$classe,method="knn",
                 trControl=trainControl(method="cv"))
```

**Comment by wabee** [comment]
I did. Reduced memory footprint to about 11,5 Gb

**Comment by topepo** [comment]
> try using the non-formula interface

That should save memory but may take more time to execute. Using the formula interface encodes any factor predictors to dummy variables and trees spend less time figuring out splits for them in comparison to splitting the original predictor (even taking into account the expanded number of dummy variable predictors). 

The non-formula interface will preserve the factors but many trees have added algorithms to determine how to split the categories into binary splits (or nigher order splits in the case of `C5.0`) and these can take a lot of time when you have a lot of categories in the predictors.
