### ISSUE TITLE
Unsupported packages such as SDDA, sddaLDA, sddaQDA

### ISSUE THREAD

**Issue by tobigithub** [topepo/caret#266]
Hi,
just a question, I see the advantage of having a lot of models supported. What is with those such as  SDDA, sddaLDA, sddaQDA that are not on CRAN anmore, just use an error handler for installation or just write general code that installs everything automatically, that would also create problems with (non available) updates.
Thank you
Tobias

**Comment by topepo** [comment]
I know some people used them so I still provide wrappers.There are a few packages like this one that you can still get from the CRAN archive pages so they can still be used.

**Comment by tobigithub** [comment]
Tnx.
