### ISSUE TITLE
extractProb fails with some models for probability prediction

### ISSUE THREAD

**Issue by caewok** [topepo/caret#269]
The extractProb function assumes that the model will have a levels function in modelInfo:

tempUnkPred <- factor(tempUnkPred, 
                            levels = models[[i]]$modelInfo$levels(models[[i]]$finalModel))

This apparently is not always the case (perhaps for older caret models?). So when using predict.train to predict newdata probabilities, predict.train will fail if levels does not exist in modelInfo. A simple fix would be fall back on using the obsLevels variable set earlier in extractProb: obsLevels <- levels(models[[1]]).

**Comment by topepo** [comment]
Good point. I just changed it.
