### ISSUE TITLE
"ranger" description is not included in "train_model_list()" help page.

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#270]
Thanks for including "ranger" in the new version 6.0-57.
The issue is that it is not included in the help page for the "train_model_list()".

Well, you have it in http://topepo.github.io/caret/modelList.html and there it is possible to know which is the tunning parameter, but not in the function's help page.

Thanks, 
Carlos Ortega.

**Comment by topepo** [comment]
I forgot to update that page on the latest release. I'll update for the next CRAN version. Thanks,

Max
