### ISSUE TITLE
Rcpp knn3 unused variable warning

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#271]
I noticed this warning: "caret.c: In function 'knn3': caret.c:23:14: warning: variable 'index' set but not used [-Wunused-but-set-...". Fixing is just extetical, I suppose...

**Comment by topepo** [comment]
I'm not sure what that is about. `index` is defined on line 23 of `caret.c` and used on lines 114, 118, and 122.

**Comment by topepo** [comment]
Unless you have an objections, I'm going to close this.

**Comment by spedygiorgio** [comment]
No problem at all...

2015-10-20 17:06 GMT+02:00 topepo <notifications@github.com>:
