### ISSUE TITLE
A question about subsampling, resampling, and model prediction

### ISSUE THREAD

**Issue by acercyc** [topepo/caret#273]
Hi, 
I don't know what part of a training set is used to train the final model if I use subsampling as a  training option.

Just assume I have an imbalanced data set for binary classification. 
I plan to use 10-fold. 10 resampling, and subsampling for cross-validation in the training stage. 
Then the trainControl() should be something like this:
```r
ctrl <- trainControl(method = "repeatedcv", number = 10,
                     repeats = 10,
                     sampling = "down")
```
In the training stage, the trainControl() parameters should yield 10*10 resampling data sets for cross-validation.
However, I don't know how Caret trains the final model. 
In prediction stage, I suppose the final model should be trained by a subsampled and balanced dataset. 
But now there are 100 subsampled data sets (or at least 10 resampled runs), which one is used to train the final model? Or what process is used to combine results to train the final model? 

It should not be the whole data set because it is imbalanced.

**Comment by topepo** [comment]
`train` applies the same modeling procedure during resampling _and_ the final model fit. 

In your case, for each 100 resamples (with the 90% of the training data selected by 10-fold CV):

 2. down-samples these data to balance
 3. fits the model on the down sampled version

The same thing happens for the final model fit with the final model (with 100% of the training data). 

So the final model used by `predict.train` is based on the down sampled training set. 

Max

**Comment by acercyc** [comment]
Thanks a lot Max.
Let me confirm this again.
Assume that the number of samples of class_A vs class_B are **10:1** in the training data set.
In the final model fitting, 100% training data are used and then **10% of the class_A** samples are randomly selected to yield a balanced data set to train the final model. 
So, in the end, **90% of the class_A samples are unused**.
Is this correct? 

Acer

**Comment by topepo** [comment]
If you had that imbalance with 100 samples, each fold would have 90% = 90 and 81 are _A_ and 9 are _B_. Within the fold, downsampling yields a data set with 18 samples and the model is fit on this. 

In the final model fit, the model is fit on a balanced set of 20 samples.
