### ISSUE TITLE
Investigate mxnet for deep learning

### ISSUE THREAD

**Issue by topepo** [topepo/caret#286]
[here](https://github.com/dmlc/mxnet/tree/master/R-package)

**Comment by terrytangyuan** [comment]
Hi Max, is this being developed?

**Comment by zachmayer** [comment]
I don't think anyone is working on it yet, but we take PRs =D

**Comment by terrytangyuan** [comment]
@zachmayer Thanks :-) Not sure if I have time on this yet. Please keep me posted on the progress of this.

**Comment by schelhorn** [comment]
I strongly second this request since it would add proper deep learning support to caret (which the autoencoders do not provide, IMO). Also, the package seems to be actively supported again.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.
