### ISSUE TITLE
Namespace issues during parallel training

### ISSUE THREAD

**Issue by terrytangyuan** [topepo/caret#290]
When there are a couple of different parallel packages(doParallel, doSnow, parallel) loaded as some other packages dependencies, R doesn't know correctly which parallel package it should use for the task.  The order of loading packages then becomes vital. 

It would be better to call parallel functions in caret package with explicit namepace, for example, `parallel::makeCluster`.

**Comment by topepo** [comment]
I don't think that this matters to `caret` since it does not call `makeCluster` or anything like it. If uses `foreach` so any parallel backend that is registered is used.

**Comment by terrytangyuan** [comment]
Okay, I'll find other workaround then. Thanks Max!
