### ISSUE TITLE
At least one of the class levels is not a valid R variable name

### ISSUE THREAD

**Issue by philipus** [topepo/caret#294]
is it a feature or a bug???

if(trControl$classProbs && any(classLevels != make.names(classLevels)))

in train makes problems if label has entries like 0, 1 which is typical for being aktiv (1) and in activ (0)

make.names makes "x0" "x1" which is non equal "0" "1"

**Comment by topepo** [comment]
Feature. Otherwise, we get a ton of emails about how the columns are not named the same as the levels. 

Basically, treat categorical data as categorical and not as numbers (when you do not have to)

**Comment by philipus** [comment]
ok, thank you for the quick respond

i didnt find a note about it in the documentation or i didnt noticed it

could be more cleare in my opinion - just a opinion ;-) from me

**Comment by topepo** [comment]
I'll try to think of a way to make it more clear. Thanks
