### ISSUE TITLE
Train glmnet with family="cox" results an error due to incorrect dimensions of y

### ISSUE THREAD

**Issue by abossenbroek** [topepo/caret#298]
I am trying to train a glmnet of family="cox". In contrast to other packages `glmnet` does not take a `Surv` object as `y` when training a `cox` model. Instead it takes a matrix with two columns. This causes the function `check_dims` to throw an error. 

I would be more than happy to fix this but  a quick look at `check_dims` tells me it is agnostic of the type of model I am trying to train. Any suggestions what a better fix would be?

**Comment by topepo** [comment]
It isn't really designed to do Cox models (yet). We've [discussed it in issue #30 ](https://github.com/topepo/caret/issues/30) but it isn't there yet. 

For example, a lot of `train` is built around getting predictions but you wouldn't get those for the outcome from a Cox model (you get the relative-risk instead). A lot of details are discussed [here](https://github.com/topepo/caret/tree/master/docs). 

I've laid some groundwork for this, but it isn't going to be this calendar year.

**Comment by alice-i-cecile** [comment]
The same issue occurs when attempting to fit continuous logistic models or multivariate gaussian models in glmnet because they have multiple columns for y. Taking a look at the code of train.default(), this breaks on check_dims, determining appropriate metrics, get_range(y) and model fitting.
