### ISSUE TITLE
What is the way to pass non-tuning model's parameters to the caret train function

### ISSUE THREAD

**Issue by ronencozen** [topepo/caret#299]
Hello,
I am running the xgb model using caret, i include xgb's parameter verbose=1 as part of the train function call like the following exp.

control <- trainControl(method = "cv", number = 3,
                                  # method = "none",
                                  verboseIter = TRUE,
                                  summaryFunction = fnRMSPE,
                                  allowParallel = TRUE)

xgbModel <- train(log(Sales + 1) ~ .,
                      data = train[,features],
                      method = "xgbTree",
                      metric = "RMSPE",
                      # tuneGrid = grid,
                      tuneGrid = data.frame(nrounds = 4000, max_depth = 8, eta = 0.025),
                      maximize = FALSE,
                      trControl = control,
                      verbose=1)

but i don't get any progress report to the screen. is it a missing implementation?
generally speaking what is the way to pass non-tuning model's parameters to the caret train function.
in the xgb example there is a bunch of them.

Thanks in advance,
and keep up the great work u are doing with this package.

Ronen

**Comment by topepo** [comment]
The results of `sessionInfo` and a reproducible example are really needed. For example, if you are using RStudio and parallel processing, it doesn't pass a lot of output to the screen (whereas basic R does) so the more details that you offer, the better we can help. 

Passing them in this way works and, in this case, the `...` get passed to `xgb.train`.

For this example with `verbose = 2` it works so we know that the option is being passed:

```r
control <- trainControl(method = "cv", number = 3,
                        # method = "none",
                        verboseIter = TRUE,
                        allowParallel = TRUE)

xgbModel <- train(Species ~ .,
                  data = iris,
                  method = "xgbTree",
                  metric = "RMSPE",
                  # tuneGrid = grid,
                  tuneGrid = data.frame(nrounds = 4000, max_depth = 8, eta = 0.025),
                  maximize = FALSE,
                  trControl = control,
                  verbose=2)
```

**Comment by ronencozen** [comment]
ok, i get your point.
I tried verbose=2 and it is working on my end as well, but verbose=1 doesn't, but it's not that crucial.
