### ISSUE TITLE
Investigate deep learning packages

### ISSUE THREAD

**Issue by topepo** [topepo/caret#3]
Including [autoencoder](http://cran.r-project.org/web/packages/autoencoder/index.html), [deepnet](http://cran.r-project.org/web/packages/deepnet/index.html) and [darch](http://cran.r-project.org/web/packages/darch/index.html).

**Comment by topepo** [comment]
now there is [SAENET: A Stacked Autoencoder Implementation with Interface to 'neural net'](http://cran.r-project.org/web/packages/SAENET/index.html)  and [RcppDL: Deep Learning Methods via Rcpp](http://cran.r-project.org/web/packages/RcppDL/index.html)

**Comment by andrewcstewart** [comment]
@zachmayer I wonder if h2o's deep learning method might be a bit difficult to incorporate into caret without a more general caret interface for h2o to handle things like establishing/maintaining connection with the h2o server and data transit.

**Comment by coforfe** [comment]
Hello,

I am just curious about how do you see the integration of any of these packages in `caret`.
Except for `H2O` which could have a more difficult integration process, the rest of the *DeepLearning*  packages are pretty stable and their working flow seems to be quite clear. Most of them have been available in CRAN in some cases for two years.

It could be worth to wait for their integration for some packages that are going to be evolved under the _Google Summer of Code_:

https://github.com/rstats-gsoc/gsoc2016/wiki/table-of-proposed-coding-projects

After this summer, hopefully we will have even more _DeepLearning_ packages and frameworks available in `R`.

Thanks in advance,
Carlos.

**Comment by pverspeelt** [comment]
And how about mxnet? From the same team that develops xgboost. With an mxnet R package. 
https://github.com/dmlc/mxnet
http://mxnet.readthedocs.io/en/latest/

**Comment by topepo** [comment]
It _may_ be in the next release but I doubt it. The issue is saving the mxnet object and using it in a later session. So far that I've seen, they don't have a [method to serialize the object](https://github.com/dmlc/mxnet/issues/362). I haven't looked in a while though and might wait until useR to talk to them. 

Also, regression doesn't seem to work. 

In the meantime, you can download and use what I have ([here](https://github.com/topepo/caret/blob/master/models/files/avMxnet.R) and [here](https://github.com/topepo/caret/blob/master/models/files/mxnet.R)) for a custom model.

**Comment by topepo** [comment]
Added cards to [project page for new models](https://github.com/topepo/caret/projects/2) instead of using issues.
