### ISSUE TITLE
bagEarth finalModel output deletes prior results

### ISSUE THREAD

**Issue by tobigithub** [topepo/caret#301]
Hi,
the method "bagEarth" deletes data during output of  $finalModel. Observe life demo.
length(t1$finalModel) is 12 for "bagEarth", after the 2nd call data is not fully shown.
Maybe an issue with the cat function.

Minimal sequential example (slow for bagged MARS)
````R
# knn works and gives the final model
require(caret); data(BloodBrain); t1 <- train(bbbDescr, logBBB, "knn"); t1; t1$finalModel;
# invokes cls/clear during finalModel output
require(caret); data(BloodBrain); t1 <- train(bbbDescr, logBBB, "bagEarth"); t1; t1$finalModel;
````
Minimal parallel example (faster for 12 threads)
````R
library(doParallel); cl <- makeCluster(12); registerDoParallel(cl)
require(caret); data(BloodBrain); t1 <- train(bbbDescr, logBBB, "knn"); t1;
stopCluster(cl); registerDoSEQ();
t1$finalModel

library(doParallel); cl <- makeCluster(12); registerDoParallel(cl)
require(caret); data(BloodBrain); t1 <- train(bbbDescr, logBBB, "bagEarth"); t1;
stopCluster(cl); registerDoSEQ();
t1$finalModel
length(t1$finalModel)
t1$finalModel
````
Cheers
Tobias

**Comment by topepo** [comment]
What is the issue exactly? Are you saying that execution of `bagEarth` is affecting the object that previously created?

**Comment by tobigithub** [comment]
Hi,
ok, let me rerun my code, ah, ok, so  I think its just that R is incapable of putting out the list when calling 
t1$finalModel. However its probably a list of different objects, so R has no way to format them correctly and puts out some stuff, for some models that can be hundreds of KBytes. 

So for some caret models the simple text output from finalModel can contain the mean of squared residuals and some other useful information. For some models it contains a $summary, for others not. Few have finalModel$problemType others have finalModel$type. I was under the impression it should be the same/similar output for each model (comparable to  the confusionMatrix) but its not and probably can not.

````R
> t1$finalModel

, 14.6664, 20.1332, 32.4398, 18.816099,     19.825899, 17.743601, 

Data:
   # variables:  134 
   # samples:    208 

B: 50 
> 
````

So one has to parse the length of structure and then put them out list by list using a loop or lapply. 
Because the "finalModel" is not a unified output for each caret model (for trees it can be trees, for pls it can be a function etc) it will also change from model to model. 

````R
require(caret); data(BloodBrain); t1 <- train(bbbDescr, logBBB, "bagEarth");
lapply(1:length(t1$finalModel), function(x) {print(t1$finalModel[x])})
````
I had a number of other cases where simply calling t1$finalModel for other caret models invoked an error that broke the program flow. I have to find them. But I think the above script solves the case for method bagEarth.

Cheers
Tobias
