### ISSUE TITLE
Sparse Linear Regression using Nonsmooth Loss Functions and L1 Regularization (flare)

### ISSUE THREAD

**Issue by topepo** [topepo/caret#314]
[Sparse Linear Regression using Nonsmooth Loss Functions and L1 Regularization](https://cran.r-project.org/web/packages/flare/index.html)

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.

**Comment by hadjipantelis** [comment]
Using the project pages looks interesting but how can be make comments about their implementation? For example, I was thinking to ask if in a `train` method, using `lambda` directly or allowing the user to use the arguments `nlambda` and `lambda.min.ratio` would be preferable. (Apologies for writing in a closed issue.)
