### ISSUE TITLE
Submodel trick for xgboost

### ISSUE THREAD

**Issue by terrytangyuan** [topepo/caret#315]
Is submodel trick for xgboost available in the current master branch? If not, could you share some instructions on how to implement it?

**Comment by topepo** [comment]
The [`predict`](https://github.com/dmlc/xgboost/blob/master/R-package/man/predict-xgb.Booster-method.Rd) function looks like it exposes the number of trees via the `ntreelimit` argument so it could probably be done. 

There is code that describes what you need to do [here](http://topepo.github.io/caret/custom_models.html#Illustration2). You can use [gbm](https://github.com/topepo/caret/blob/master/models/files/gbm.R) and [earth](https://github.com/topepo/caret/blob/master/models/files/earth.R) as good templates for implementation. 

Give it a try and let me know if you run into issues. 

Thanks,

Max

**Comment by terrytangyuan** [comment]
Got it. I'll look into it later this week. Thanks!

**Comment by terrytangyuan** [comment]
https://github.com/topepo/caret/blob/5c63e49450aada276feb82abdc53dc25cf5beeeb/models/files/xgbTree.R#L109

Looks like it's already there, am I correct?
