### ISSUE TITLE
rf model with oob does not produce ROC as a metric

### ISSUE THREAD

**Issue by petemere** [topepo/caret#319]
I love caret!  Thank you so much for maintaining this wonderful package.

The below is based on SO: http://stackoverflow.com/questions/33645602/roc-metric-not-in-result-set

I'm trying to produce a random forest model with the caret package, using area under the ROC curve as the train metric, but I get the following warning:

``` {r}
Warning message:
In train.default(x = TrainData, y = TrainClasses, method = "rf",  :
  The metric "ROC" was not in the result set. Accuracy will be used instead.
```
Clearly this is not what I'm after, but it seems (see note below from fg nu) that it is the expected behaviour of caret, rather than something I've mis-specified.

Here is a reproducible example:

``` {r}
library(caret)
library(doParallel)
library(data.table)

cl <- makeCluster(detectCores() - 1) # I'm using 3 cores.
registerDoParallel(cl)

data(iris)
iris <- iris[iris$Species != 'virginica',] # to get two categories
TrainData <- as.data.table(iris[,1:4]) # My data is a data.table.
TrainClasses <- as.factor(as.character(iris[,5])) # to reset the levels to the two remaining flower types.

ctrl <- trainControl(method = 'oob',
                     classProbs = TRUE,
                     verboseIter = TRUE,
                     summaryFunction = twoClassSummary,
                     allowParallel = TRUE)
model.fit <- train(x = TrainData,
                   y = TrainClasses,
                   method = 'rf',
                   metric = 'ROC',
                   tuneLength = 3,
                   trControl = ctrl)
```
The result is the same if I don't create the parallel cluster and set `allowParallel = FALSE`.

In case it is of use, here's the result from a `sessionInfo()` call:

```{r}
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] randomForest_4.6-10 data.table_1.9.6    doParallel_1.0.10   iterators_1.0.7     foreach_1.4.3      
[6] caret_6.0-52        ggplot2_1.0.1       lattice_0.20-33    

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.1         compiler_3.2.2      nloptr_1.0.4        plyr_1.8.3          tools_3.2.2        
 [6] digest_0.6.8        lme4_1.1-8          nlme_3.1-121        gtable_0.1.2        mgcv_1.8-7         
[11] Matrix_1.2-2        brglm_0.5-9         SparseM_1.6         proto_0.3-10        BradleyTerry2_1.0-6
[16] stringr_1.0.0       gtools_3.5.0        stats4_3.2.2        grid_3.2.2          nnet_7.3-10        
[21] minqa_1.2.4         reshape2_1.4.1      car_2.0-26          magrittr_1.5        scales_0.3.0       
[26] codetools_0.2-14    MASS_7.3-44         splines_3.2.2       pbkrtest_0.4-2      colorspace_1.2-6   
[31] quantreg_5.11       stringi_0.5-5       munsell_0.4.2       chron_2.3-47       
```

In SO, fg nu dug into the code and discovered that:

> When you choose method = "oob", AUC-ROC is not one of the metrics that is returned.
> 
> You need to dig a little into the source code to figure out where the metrics are being computed. It is computed by method$oob which is called by oobTrainWorkflow on line 19, in turn called by train.default on line 258. method in your case is models$rf, where the object models is loaded from an external package file called models.RData:
> 
> ```{r}
load(system.file("models", "models.RData", package = "caret"))
```
> You can inspect the oob method for `models$rf` (which is the same as method):
> 
> ```{r}
function(x) {
  out <- switch(x$type,
                regression =   c(sqrt(max(x$mse[length(x$mse)], 0)), x$rsq[length(x$rsq)]),
                classification =  c(1 - x$err.rate[x$ntree, "OOB"],
                                    e1071::classAgreement(x$confusion[,-dim(x$confusion)[2]])[["kappa"]]))
  names(out) <- if(x$type == "regression") c("RMSE", "Rsquared") else c("Accuracy", "Kappa")
  out
}
```
> You can see that when classification RF is requested, only the acuracy and kappa metrics are computed.

Fg nu seems to be correct, but is this exclusion of ROC intentional?
- Oob and rf are a good combination (rf is one of a few models that can use oob),  
- Rf is a good classifier, and can return probabilities, and 
- AUC ROC is a good performance metric for two class classification models.

So why is oob + rf + AUC not available in caret even with `trainControl(classProbs = TRUE, summaryFunction = twoClassSummary, ...)`?

Perhaps I'm missing something obvious?

Thanks!

Pete

**Comment by zachmayer** [comment]
Change `method = 'oob'` to `method = 'cv' in your trainControl and try again.  Right now caret doesn't support custom summary functions for out-of-bag resampling for random forests.

**Comment by petemere** [comment]
Thanks @zachmayer .  That works, obviously.
Are there plans to support custom summary functions for oob resampling in rf?

**Comment by fgnu** [comment]
@zachmayer Won't it be possible to get `method$oob` to use `method$prob(mod$fit)` and compute the AUC-ROC?

**Comment by topepo** [comment]
It is an exclusion by necessity. The OOB statistics are derived form whatever the underlying function exposes. I don't think that any of them will give you the OOB predictions. 

For example, `randomForest` gives the OOB confusion matrix:

```r
> library(randomForest)
> mod <- randomForest(Species ~ ., data = iris)         
> mod$confusion
           setosa versicolor virginica class.error
setosa         50          0         0        0.00
versicolor      0         47         3        0.06
virginica       0          4        46        0.08
```

All `caret` does is to figure out whatever statistics that it can from this (i.e. accuracy and kappa). There's no way to get the ROC curve from the `randomForest` object.

**Comment by fgnu** [comment]
@topepo But like I noted, doesn't `models$rf$prob(mod$fit)` give you the probabilities you need for computing the AUC?

**Comment by petemere** [comment]
I'm not sure if it fits within the caret design to do so, but it is possible to get class probabilities from a `randomForest()` call by passing `xtest` and `ytest`.  As per the doco:

> If `xtest` is given, prediction of the test set is done “in place” as the trees are grown. If `ytest` is also given, and `do.trace` is set to some positive integer, then for every `do.trace trees`, the test set error is printed. Results for the test set is returned in the `test` component of the resulting randomForest object. For classification, the `votes` component (for training or test set data) contain the votes the cases received for the classes. **If `norm.votes=TRUE`, the fraction is given, which can be taken as predicted probabilities for the classes**.

This is also discussed in this SO post: http://stackoverflow.com/questions/25715502/using-randomforest-package-in-r-how-to-get-probabilities-from-classification-mo

**Comment by topepo** [comment]
Right now, as you point out, the framework of `train` uses the `oob` to compute performance using the model fit object. The issue is that the OOB statistic calculations are likely to be very different form model to model. I don't want to make substantial changes to the infrastructure that may not generalize. 

I agree that it would be great to have so if you want to propose something and see how is scales to the other models that have OOB components, we can start form there.

**Comment by petemere** [comment]
I suspect that it's a little beyond my current level of R skill to propose something that would fit in at the level you guys are coding, but once I have done what I need to get done for work, I'll see if I can come up with something worth sharing.

Thanks for looking into this!
