### ISSUE TITLE
"ranger" and "oob" error....

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#320]
Hello,
I am getting this error with caret/ranger (it's the same error I get on my data.frame).
A reproducible example:

> bootControl <- trainControl(method='oob',number=5, verboseIter=TRUE) 
> rfGrid <- expand.grid(.mtry=2)
> 
> modFitrf <-  train(
+   Species ~ ., 
+   data = iris,
+   trControl = bootControl,
+   tuneGrid = rfGrid,
+   method = "ranger",
+   num.trees = 500,
+   importance = 'impurity',
+   verbose = TRUE,
+   classification = TRUE
+ )
+ : mtry=2 
*Error in { : task 1 failed - "all arguments must have the same length"*

* I am using caret version: 6.0-58
* And ranger version: 0.2.7
** (I got initially the error on the new version of ranger: 0.3.0 that appeared yesterday, but I removed and installed the old one that worked fine before but not now).
* The same error appears when I remove "number=5" in trainControl().

I have run this kind of configuration (for trainControl() and for train()) since ranger appeared in caret in this new version (6.0.58). It worked flawlessly very fast and without any problem on my data.frame (60,000x35), but today I have run it again on the same data.frame that I run before and it gets that same error.

The only change to my knowledge is the version of RStudio. Version for e1071 which rangers depends, it is the same since August.

Kind Regards,
Carlos.

**Comment by topepo** [comment]
This was related to [changes to `ranger`](https://cran.r-project.org/web/packages/ranger/NEWS). I've made a change that should be more robust.

**Comment by coforfe** [comment]
Thanks a lot!
