### ISSUE TITLE
Train issue for method = "glmStepAIC" and direction = "forward"

### ISSUE THREAD

**Issue by rfeu** [topepo/caret#324]
Dear Max,
 
First, let me thank you for the caret package and your book. Both of them have been tremendously helpful for predictive modeling.
The team has found a bug in your package and we thought that we would reach out to you.
 
**Details of the bug**
*Library*: caret
*Function*: train
*Details*: When using the method “glmStepAIC”  with the parameter direction ="forward", the function does not work.
*Reason*: After inspection of the train code, it seems that the train function starts with “y~.” This is correct if direction = “backward”, but in the case of direction=”forward”, the train function should probably start with “y~1”
 
**Reproducible code to identify the error**
```{r comment=""}
library(dplyr)
library(caret)
data(iris)
 
#Keep only two levels for the output class
iris2 <- iris %>% filter(Species %in% c("setosa", "versicolor"))
iris2$Species <- factor(iris2$Species)
 
#Split predictors and outcome
TrainData <- iris2[ ,1:4]
TrainClasses <- iris2[ ,5]
 
####Warnings will be issued when building the model because of separation issues.
###These warnings can be ignored
allNames <- names(TrainData) #Get the names of all the variables in the dataset
allVar <- paste("~", paste(allNames, collapse=" + ")) #Turn allNames into a formula
 
#Backward Selection of Variables (base library): Works
fit <-glm(Species~., data = iris2, family = binomial)
library(MASS) #must be loaded after dplyr
backward.Mass <- stepAIC(fit, direction = "backward", trace = TRUE)
 
#Forward selection of variables (base library): Works
fit2 <-glm(Species~1, data = iris2, family = binomial)
forward.Mass <- stepAIC(fit2, direction = "forward", trace = TRUE, scope = allVar)
 
#Backward selection of variables (caret library): Works
backward.caret <- train(x = TrainData, y = TrainClasses, method = "glmStepAIC")
 
#Forward selection of variables (caret library): Does NOT work
forward.caret <- train(x = TrainData, y = TrainClasses, method = "glmStepAIC", direction ="forward")
```

**Comment by topepo** [comment]
Can you take a look at the method changes and see if that agrees with your thoughts on this model?

**Comment by zachmayer** [comment]
looks good to me.  @rfeu what do you think of 7b2cf2270e2561785d0271c123a007abad65fa0d?

**Comment by rfeu** [comment]
Looks good to me too!
I appreciate your super-fast answer.

**Comment by petemere** [comment]
Hi all.  I was having this same problem.  Thanks to both @rfeu for raising it and @topepo and @zachmayer for their lightning fast response.
This may be a bit of a beginner question, but how can I find out when this code will be released to the CRAN version?
Thanks!

**Comment by rfeu** [comment]
@petemere you can use the following code
```{r comment=""}
devtools::install_github('topepo/caret/pkg/caret')
```

You will need the devtools library (and the httr library if you are behind a proxy).

**Comment by petemere** [comment]
Thanks @rfeu .  I've got the install-from-github OK.  I was actually wondering when the new code will be released to the CRAN (i.e. install.packages()) version.
