### ISSUE TITLE
Please provide source for train_algo.pdf

### ISSUE THREAD

**Issue by rbalint** [topepo/caret#340]
pkg/caret/vignettes/train_algo.pdf's source is not included in the package which makes the file undistributable under GPL.
I have packaged caret for Debian and I had to exclude train_algo.pdf and caret.pdf due to the missing source but I would love to ship them again.
http://anonscm.debian.org/cgit/debian-science/packages/r-cran-caret.git
Rewriting train_algo.pdf's content in caret.Rnw and dropping train_algo.pdf would be an other solution.

**Comment by topepo** [comment]
It is created using LaTeX's `algorothm2e` package:

```tex
\usepackage[boxed, linesnumbered]{algorithm2e}

\begin{algorithm}[H]
   \label{A:tune}
   \SetLine
   \restylealgo{plain}
   \dontprintsemicolon
    Define  sets of model parameter values to evaluate \nllabel{A:grid}\;
    \For{each parameter set}{
    \For{each resampling iteration}{
      Hold--out specific samples \nllabel{A:resample} \;
      
      [Optional] Pre--process the data\;
      Fit the model on the remainder\;
      
      Predict the hold--out samples\;
    }
    Calculate the average performance across hold--out predictions \nllabel{A:perf}
  }
  Determine the optimal parameter set \nllabel{A:best}\;
  
  Fit the final model to all the training data using the optimal
  parameter set\;  
\end{algorithm}
```

IIRC, I took it out when the CRAN maintainers wanted to avoid LaTeX package dependencies. 

Can I assign the image file a license to get around the issue? Also, since the package is GPL, would that transfer to the image file?

**Comment by rbalint** [comment]
@topepo Simply adding the .tex file without using it in the build process would be enough. This would satisfy both CRAN maintainers and GPL requirements.
I may regenerate the .pdfs in Debian, during the build, but this is not very important now .:-)

**Comment by topepo** [comment]
It's there so that it will show up in the next version.

**Comment by rbalint** [comment]
Thanks, I'll update the package.
