### ISSUE TITLE
error when predict probabilities on model trained on a dgCMatrix

### ISSUE THREAD

**Issue by anmiko** [topepo/caret#342]
when a model is trained on a dgCMatrix (e.g. created by hashed.model.matrix of FeatureHashing  )

an attempt to call predict with type ="prob" raises error 
>Error in as.data.frame.default(unkX) : 
  cannot coerce class "structure("dgCMatrix", package = "Matrix")" to a data.frame

but *predict* works fine when *type='raw"*. Also as a workaround *probFunction* can be called directly.

code example
```R
library(glmnet)
library(FeatureHashing)
library(caret)
tmp.df <- data.frame(A=1:12, B=3:14, Y = c('a','a','b','c','b','a','a','a','c','c','b','a'))

mat.fh <- hashed.model.matrix(~ A+B, tmp.df, 2^10, create.mapping = TRUE)

model <- train(x = mat.fh, y = as.factor(tmp.df$Y), method = 'glmnet')

probs <- predict(model, newdata = mat.fh, type = "prob")

#a workaround  
probs <- probFunction(model$modelInfo, model$finalModel, mat.fh, model$preProcess)
```

caret version '6.0.62'

**Comment by topepo** [comment]
Thanks. This is a bug and has been fixed.
