### ISSUE TITLE
GAM splines formula

### ISSUE THREAD

**Issue by nickdoban** [topepo/caret#343]
For reproducible reasons for many computing environments, is there a way in R of extracting the splines' formulas from the gam model built with caret?

**Comment by topepo** [comment]
I don't really know but you should look at the `coef` method for the package that you are using (`gam` or `mgcv`) and run this on the `finalModel` object returned by `train`.

**Comment by nickdoban** [comment]
I tried following your advice but couldn't find anything that would work for me.
Sorry for my poor editing skills, but below is shown what I get when I run the summary of the model. So, I am after finding the explicit `s()` formulas.

`R> summary(model.gam)`

`Family: gaussian `
`Link function: identity `

`Formula:
.outcome ~ TypeOfDayWeekend + monthFebruary + monthMarch + monthApril + 
    monthMay + monthJune + s(WindSpeed.mean) + s(Temp.mean)
`
`Parametric coefficients:`

`                  Estimate Std. Error t value Pr(>|t|)    `
`(Intercept)      44.802412   3.629122  12.345  < 2e-16 ***`
`TypeOfDayWeekend  0.344814   1.210903   0.285 0.775979    `
`monthFebruary     3.578585   1.546631   2.314 0.021191 *  `
`monthMarch       -4.130601   1.284129  -3.217 0.001404 ** `
`monthApril        3.042411   1.300948   2.339 0.019853 *  `
`monthMay          8.814726   1.741340   5.062 6.37e-07 ***`
`monthJune         6.665986   1.235092   5.397 1.17e-07 ***`
`---
`Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

`Approximate significance of smooth terms:`
                                           `edf Ref.df      F  p-value`    
`s(WindSpeed.mean)          2.4224      9  6.908 1.92e-15 ***`
`s(Temp.mean)                   2.2274      9  0.907 0.007033 ** `
`---`
`Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1`

`Rank: 69/72`
`R-sq.(adj) =  0.661   Deviance explained =   69%`
`GCV = 35.873  Scale est. = 32.76     n = 433`

**Comment by Sandy4321** [comment]
Do u have R code file with full example?

**Comment by topepo** [comment]
I don't know which GAM package that you are using. Here is an example with `gam:::gam`:

```r
> library(mgcv)
> mod <- gam(Sepal.Width ~ s(Sepal.Length) + Species + Petal.Width, data = iris)
> mod

Family: gaussian 
Link function: identity 

Formula:
Sepal.Width ~ s(Sepal.Length) + Species + Petal.Width

Estimated degrees of freedom:
3.16  total = 7.16 

GCV score: 0.06789715     
> coef(mod)
      (Intercept) Speciesversicolor  Speciesvirginica       Petal.Width 
      3.597320162      -1.608819343      -1.904027657       0.526094084 
s(Sepal.Length).1 s(Sepal.Length).2 s(Sepal.Length).3 s(Sepal.Length).4 
      0.132183961       0.018850130      -0.019446177      -0.024113469 
s(Sepal.Length).5 s(Sepal.Length).6 s(Sepal.Length).7 s(Sepal.Length).8 
     -0.002489114       0.036866986      -0.008234857       0.223552502 
s(Sepal.Length).9 
      0.355505958
```

**Comment by nickdoban** [comment]
this is the R-code I used
`train_control.gam <- trainControl(method = "repeatedcv", number = 10, repeats = 3, p = 0.75, fixedWindow = FALSE)`

`model.gam <- train(y ~., data = train, trControl = train_control.gam,method = "gam", tuneLength = 18)`

`train$pred.gam <- predict(model.gam, train) `

I used the `gam method` from `caret` package. 

@topepo , in your example- how would you know the formulas behind `s(Sepal.Length)`? I would expect it's some kind of regression equation, such as: `s(x) = a+b*x` So, I want to extract these (regression)  exact/explicit formulas. Is there a way to do it with/in `caret`?

**Comment by topepo** [comment]
These are coefficients for linear models for a nonlinear basis function. I don't have the exact formula for this. For this package, see `?smooth.construct` and perhaps you should look at [page 20 of this document](https://cran.r-project.org/doc/Rnews/Rnews_2001-2.pdf) too.
