### ISSUE TITLE
predict.dummyVars - Prior factor levels do not persist when predicting on new data

### ISSUE THREAD

**Issue by doublej2** [topepo/caret#344]
When applying predict.dummyVars to a different data set factor levels do not persist in the creation of the design matrix.

I noticed this issue with caret version 6.0-52. Due to IT constraints I am not able to install the latest version of caret, but checking the code for dummyVars.default and predict.dummyVars it appears this is still an issue.

Example:
[predictExample.pdf](https://github.com/topepo/caret/files/75620/predictExample.pdf)

**Comment by topepo** [comment]
You've found and fixed the problem. Thanks. I've checked in the change and unit tests
