### ISSUE TITLE
Bug in predict.train

### ISSUE THREAD

**Issue by jknowles** [topepo/caret#347]
I think this is causing our issue over on zachmayer/caretEnsemble#180

Here's a simple minimal reproducible example:

```r
library(caret)
myGBM <- train(x=iris[, 1:2], y = iris[, 5], 
tuneLength = 1, method = "gbm", 
trControl = trainControl(method = "cv", number =2, 
savePredictions = "final", classProbs = FALSE), verbose = FALSE)

predict(myGBM) # results in error
predict(myGBM, newdata = NULL) # results in error
```

Here is the error message:

```
Error in object$var.levels[[i]] : subscript out of bounds
Called from: predict.gbm(modelFit, newdata, type = "response", 
n.trees = modelFit$tuneValue$n.trees)
```

This behavior is inconsistent, as the following works:

```r
myRF <- train(x=iris[, 1:2], y = iris[, 5], 
tuneLength = 1, method = "rf", 
trControl = trainControl(method = "cv", number =2, 
savePredictions = "final", classProbs = FALSE), verbose = FALSE)

predict(myRF) # results in no error
predict(myRF, newdata = NULL) # results in no error
```

@zachmayer and @topepo -- any advice about investigating whether this is just limited to the `predict.gbm` implementation? How might we investigate it further?

**Comment by topepo** [comment]
In the last version, I changed `predict.train` to avoid using `extrctPredictions` and go straight to `predictionFunciton`. In doing so I didn't account for the use of `predict(obj)` with no `newdata`. 

It's generally _not_ a good idea to do that but I will fix it since it was working before I "fixed" the other issue =]

**Comment by jknowles** [comment]
Thanks Max. If it's not a good idea to do `predict(modelobj)` without `newdata`, perhaps in the case where our users do not specify `newdata` in `caretEnsemble` we should modify the `predict` call to get the fitted values from the `train` objects instead of doing using the `predict` function. 

What do you think @zachmayer ?

**Comment by zachmayer** [comment]
@jknowles How about if it's not a good idea to call `predict.train` without newdata, we disable calling `predict.caretEnsemble` without new data?

**Comment by topepo** [comment]
Do these changes fix the issue? The examples that you've shown don't show errors now.
