### ISSUE TITLE
add sampling option to train

### ISSUE THREAD

**Issue by topepo** [topepo/caret#35]
In `trainControl`, think about having an option to do sampling after resampling and prior to pre-processing/model fitting with options for `upSample`, `downSample`, `SMOTE` and `ROSE`. Make offline code available (the same way models are stored) to avoid more package dependencies.

**Comment by topepo** [comment]
code checked in with unit and regression tests

**Comment by jplaborde** [comment]
The sampling functionality which you added has been convenient and helpful - thank you. Have you considered adding sampling algorithms that deal with multi-class data? Note that SMOTE and ROSE are for binary classifiers only (simple "up" and "down" sampling will perform on multiple classes, but these methods may not be ideal for many users). Surprisingly, I have not been able to locate an R package that performs multi-class resampling algorithms, although several have been developed in the literature.

**Comment by topepo** [comment]
ROSE won't work with multiple classes but SMOTE will:

```r
library(AppliedPredictiveModeling)
data("schedulingData")

library(DMwR)

smoted <- SMOTE(Class ~ ., data = schedulingData)
table(smoted$Class)
table(schedulingData$Class)
```

The [UBL](https://cran.r-project.org/web/packages/UBL/index.html) package might help but I haven't had a change to look at it yet. If you do and have any workflows, let me know and I'll add them here too.

**Comment by jplaborde** [comment]
I may be misunderstanding, but in your example, although all the classes are present the SMOTE procedure exacerbated the imbalances in data (e.g. M = 0.08 of total data in "smoted", and M = 0.12 of total data in "schedulingData"), it did not balance them:


```
table(smoted$Class)

 VF   F   M   L 
583 333 120 777 
> table(schedulingData$Class)

  VF    F    M    L 
2211 1347  514  259 

```

**Comment by topepo** [comment]
You can adjust the `perc.over` and `perc.under` parameters of SMOTE to get more balance. My point was that SMOTE can work with multi-class data

**Comment by jplaborde** [comment]
I understand now, thanks. If I can pull together a workflow for additional resampling methods for multi-class data, I will be sure to let you know.
