### ISSUE TITLE
method = "none" in trControl does not help speeding up the training (random forest)?

### ISSUE THREAD

**Issue by KristinaPlazonic** [topepo/caret#350]
Hi, 

I found in several places (including issues here) that trControl = trainControl(method = "none") and providing custom tuneGrid to the train() function will bring the execution of caret on par with the original package. However, I do not find it so. 

What additional operations are performed in caret and how can you bring caret execution time down? 

In the below code which should be reproducible (and tuneGrid is a single mtry row), 

- randomForest package takes 6 ms to train a classifier on the iris dataset, 
- caret takes 424ms to train with method = "boot" and number = 1
- caret takes 339ms to train with method = "none"
- caret takes 1226ms to train with method = "repeatedcv", number = 10, repeats = 10 - while this is reasonable, the previous times are not!

Many thanks!

library(caret)
seed(998)

iris$isSetosa = ifelse(iris$Species == "setosa", 1.0, 0.0)
iris$isSetosa = as.factor(iris$isSetosa)
mydata = iris[,-5]
#############################################################
inTraining <- createDataPartition(mydata$isSetosa, p = 0.75, list = F)
t <- iris[inTraining, ]
h <- iris[- inTraining, ]

rfControl <- trainControl(method = "boot", number = 1, repeats = 1)
rfControl2 <- trainControl(method = "none", number = 1, repeats = 1)
rfControl3 <- trainControl(method = "repeatedcv", number = 10, repeats = 10)
rfGrid <- expand.grid(mtry = c(2))

system.time( train( isSetosa ~ ., data = t, method = "rf", ntree = 100, 
                    trControl = rfControl, tuneGrid = rfGrid))

system.time( train( isSetosa ~ ., data = t, method = "rf", ntree = 100, 
                    trControl = rfControl2, tuneGrid = rfGrid))

system.time( train( isSetosa ~ ., data = t, method = "rf", ntree = 100, 
                    trControl = rfControl3, tuneGrid = rfGrid))

system.time( randomForest(isSetosa ~ ., data = t, ntree = 100, mtry = 2))

**Comment by washcycle** [comment]
There are a lot of if statements between caret and the underlying model. I'd try a larger dataset to see how that affects the results. There is some overhead even if the method in trainControl is set to "none". Will see what I can come up with when I get home.

**Comment by washcycle** [comment]
```r
irisbig <- rbind(iris, iris)
for(i in 1:1000){
    irisbig <- rbind(irisbig, iris)
}


system.time( train( isSetosa ~ ., data = irisbig, method = "rf", ntree = 100, 
                    trControl = rfControl2, tuneGrid = rfGrid))
 user  system elapsed 
  5.685   0.000   5.711 

system.time( randomForest(isSetosa ~ ., data = irisbig, ntree = 100, mtry = 2))
 user  system elapsed 
  4.513   0.000   4.498 

I scaled the problem and the "slowness" does seem to scale to some degree.

**Comment by topepo** [comment]
@washcycle I think that this accounts for the issue. It is similar to reports where parallel processing takes longer than sequential when the computations are simple (e.g. `mean(1:5)`). 

@KristinaPlazonic I can see your point. However, one of the advantages of `train` is to unify the interface and to fix some things that some models do poorly. The price, for small data sets, is some additional overhead.
