### ISSUE TITLE
svmLinear2

### ISSUE THREAD

**Issue by DanaAverbuch** [topepo/caret#360]
In the documentation, it is written that the only parameter is needed for this model is the cost parameter:
"
Support Vector Machines with Linear Kernel (method = 'svmLinear2')
For classification and regression using package e1071 with tuning parameters:
• Cost (cost, numeric)
"

but when trying to run it just with this parameter, I get the flowing error:
"
Error in train.default(x, y, weights = w, ...) : 
  The tuning parameter grid should have columns cost, gamma
"

**Comment by topepo** [comment]
It looks like I didn't update the package model list. I'll do that on the next version. 

Thanks,

Max
