### ISSUE TITLE
probFunction using single observation

### ISSUE THREAD

**Issue by caewok** [topepo/caret#363]
It looks like there is a bug when using predict.train to predict probabilities on newdata comprised of a single row.  This code from predict.train expects probFunction to return a data frame with a column for each class:

```
out <- probFunction(method = object$modelInfo, modelFit = object$finalModel, 
                    newdata = newdata, preProc = object$preProcess)
obsLevels <- levels(object)
out <- out[, obsLevels, drop = FALSE]
```

Typically, the data frame "out" looks like this (here, for two observations):
```
> out
ChargeOff      Paid
1 0.1185421 0.8814579
2 0.1185421 0.8814579
```

But if newdata has only one observation (one row), then probFunction returns a slightly different result:
```
> out
classProb
ChargeOff 0.1185421
Paid      0.8814579
```
That throws an error because predict.train expects multiple columns.

**Comment by topepo** [comment]
Can you send a reproducible example? I don't get this for LDA models:

```r
> mod <- train(Species ~ ., data = iris, method = "lda", trControl = trainControl(classProbs = TRUE))
> predict(mod, iris[1,])
[1] setosa
Levels: setosa versicolor virginica
> predict(mod, iris[1,], type = "prob")
  setosa   versicolor    virginica
1      1 3.896358e-22 2.611168e-42
```

I suspect that you might be giving `predict.train` a vector that was automatically downcast from a matrix such as 
```r
> matrix(1:12, ncol = 4)[1,]
[1]  1  4  7 10
> ## instead of 
> matrix(1:12, ncol = 4)[1,, drop = FALSE]
     [,1] [,2] [,3] [,4]
[1,]    1    4    7   10
```

**Comment by topepo** [comment]
Any information on this?
