### ISSUE TITLE
LGOCV displays incorrect p in summary

### ISSUE THREAD

**Issue by zsharpm** [topepo/caret#366]
In trainControl method LGOCV summary shows p % instead of p * 100 %.

library(caret)

train(Species ~ ., data = iris,
      trControl = trainControl(method = "LGOCV", p = 0.50)
)

Random Forest 

150 samples
  4 predictor
  3 classes: 'setosa', 'versicolor', 'virginica' 

No pre-processing
**Resampling: Repeated Train/Test Splits Estimated (25 reps, 0.5%) **
Summary of sample sizes: 75, 75, 75, 75, 75, 75, ... 
Resampling results across tuning parameters:

  mtry  Accuracy   Kappa   Accuracy SD  Kappa SD  
  2     0.9472000  0.9208  0.02017699   0.03026549
  3     0.9498667  0.9248  0.01935248   0.02902872
  4     0.9514667  0.9272  0.01958079   0.02937119

Accuracy was used to select the optimal model using  the largest value.
The final value used for the model was mtry = 4.

**Comment by topepo** [comment]
Thanks for finding that. Fixed
