### ISSUE TITLE
Data lost after preprocessing

### ISSUE THREAD

**Issue by tengpeng** [topepo/caret#367]
I am using `preprocess` to clean data. The data lost 90% rows after clean up. 

```
> nrow(df_train)
[1] 114321
> df_train <- preProcess(df_train, method = c("knnImpute"))
> df_train$dim
[1] 17765   130
> df_train = read_csv("train.cv")
> df_train <- preProcess(df_train, method = c("BoxCox"))
> df_train$dim
[1] 17756    40
```

**Comment by tengpeng** [comment]
Weird enough. Both methods, kin and BoxCox, would result in data lost. And the number of remain rows are 17765. Is it caused by limitation of some internal function.

The data is available https://www.kaggle.com/c/bnp-paribas-cardif-claims-management/data

No other code needed to replicate the bug.

**Comment by topepo** [comment]
You'll need to supply a small, reproducible example to test with.

**Comment by tengpeng** [comment]
Please close the issue. The problem is that I am stupid enough to forget use `predict`.

**Comment by topepo** [comment]
Not a problem =]

**Comment by tantanchen** [comment]
@tengpeng have you noticed if the predict function had overwritten all the values and not just the missing values?

I am also using preProcess for this kaggle competition, and I noticed that knnImpute will overwrite all the values, not just the missing ones

**Comment by tengpeng** [comment]
@topepo No, I have not got the problem as you described. Try simply start over again.
