### ISSUE TITLE
custom probability buckets in calibration plot

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#371]
Calibration plot is a great tool to check classification methods predictive accuracy. A small problem arises when implied probability is not evenly distributed in the whole 0-1 range but maybe is is concetrated in the leftmost part (skewed toward small probabilities) es for small event classification. I wonder wether it were possible to provide calibration plot a custom set of probabilities on which assessing the predictive performance.

**Comment by topepo** [comment]
That is doable (but maybe not in the short term). I would worry that custom ranges might really overfit the curve though (for the same reason that histograms do equal bin widths across the data range).

**Comment by topepo** [comment]
This goes to show how much I use that function... this feature has been available for [about 18 months](https://github.com/topepo/caret/commit/361adfdaea949a4562e75277617ae6e5ad476960).  

For example: 

```r
data(mdrr)
mdrrDescr <- mdrrDescr[, -nearZeroVar(mdrrDescr)]
mdrrDescr <- mdrrDescr[, -findCorrelation(cor(mdrrDescr), .5)]

inTrain <- createDataPartition(mdrrClass)
trainX <- mdrrDescr[inTrain[[1]], ]
trainY <- mdrrClass[inTrain[[1]]]
testX <- mdrrDescr[-inTrain[[1]], ]
testY <- mdrrClass[-inTrain[[1]]]

library(MASS)
ldaFit <- lda(trainX, trainY)
testProbs <- data.frame(obs = testY,
                        lda = predict(ldaFit, testX)$posterior[,1])
obj <- calibration(obs ~ lda, data = testProbs, cuts = c(.2, .6, .7, .8, .9))

xyplot(obj)
```

The documentation has 

> `cuts`: If a single number this indicates the number of splits of the data are used to create the plot. By default, it uses as many cuts as there are rows in data. **If a vector, these are the actual cuts that will be used.**
