### ISSUE TITLE
Question: Does train function support class.weights for XGBTREE?

### ISSUE THREAD

**Issue by dianjunren** [topepo/caret#373]
I looked up online and could not find related information. I hope someone could help me out here.

I have an sampled data from an extreme large imbalanced dataset, and I only have access to the sampled dataset. The sampling is created by downsample non-events and keep all events. As a result, event and non-event each has a class weight, say 1 for event, 10 for non-event. 

Question, how to include the class weight (1,10) into the XGBTree train function? Thank you!

**Comment by topepo** [comment]
Do you know how to do it with native `xgb.train`? I do not but if you know it should not be difficult to make another method (as we did with `rpart`, `C5.0` etc).

**Comment by dianjunren** [comment]
Thanks for your reply. I only read from tutorial that xgboost supports instance weights through libsvm format data, but I don't know how it is actually implemented nor do I have real experience. 

Do you think I should ask author of xgboost this question instead? 

Thanks,

**Comment by topepo** [comment]
> Do you think I should ask author of xgboost this question instead?

That's probably best but I'd like to know what you come up with.

**Comment by dianjunren** [comment]
Hello, it's me again. I checked with author of the xgboost, and got some ideas on how to implement the weight. See this for examples. 
https://github.com/dmlc/xgboost/blob/master/demo/kaggle-higgs/higgs-train.R#L17
It incorporates the weight variable when creating the sparse DMatrix. Also, xgboost allows you to set scale_pos_weight parameters. 

May I ask that 1) can Caret supports the xgbDmatrix format as X variable input and, 2) can Caret support the scale_pos_weight?

Thank you very much!

**Comment by topepo** [comment]
The code in the link looks like _case_ weights. You description seemed like you were interested in weights for the different classes. 

If these were parameters to `xgb.train`, you could pass them through with `train`. However, specially since you need to change the `xgb.Dmatrix` syntax, your best bet is to make a [custom model](http://topepo.github.io/caret/custom_models.html). For example:

```r
> code <- getModelInfo("xgbTree")[[1]]
> names(code)
 [1] "label"      "library"    "type"       "parameters" "grid"       "loop"       "fit"       
 [8] "predict"    "prob"       "predictors" "varImp"     "levels"     "tags"       "sort"    
```
