### ISSUE TITLE
Stratified sampling uses arbitrary response factor levels

### ISSUE THREAD

**Issue by eric-czech** [topepo/caret#374]
This is a subtle bug that results in classifiers trained on a factor response to produce different results than the same classifier trained on *almost* the same response factor, where nothing is different about that that second response vector except that it has it's levels in a different order.

For example, training a classifier on this response, 

```y <- factor(c('A', 'A', 'B'), levels=c('A', 'B'))```, 

does not necessarily produce the same model as when trained on this response: 

```y <- factor(c('A', 'A', 'B'), levels=c('B', 'A'))```.

The problem, I believe, is that resample methods like ```createFolds``` use the table function to generate counts of each response value after turning them into characters.  Here is a relevant portion of the code in createFolds:

```
y <- factor(as.character(y))
numInClass <- table(y)
foldVector <- vector(mode = "integer", length(y))
for (i in 1:length(numInClass)) 
   # Do stuff for stratified sampling
```

The table function then sorts the character values lexically, which results in ```numInClass``` having the same counts for each factor value, but in the opposite order.

Also, here is an example showing that a performance measure like accuracy does differ when using the default cross validation built into caret, when applying the same model to two different responses (that are basically the same except with levels transposed):

```

library(caret)
library(dplyr)

set.seed(123)
d <- twoClassSim(n=100) 
X <- d %>% select(-Class)
y <- ifelse(d$Class == 'Class1', 'A', 'B')
y[1:50] <- 'A' # Create an imbalance in the response classes
y1 <- factor(y, levels=c('A', 'B'))
y2 <- factor(y, levels=c('B', 'A'))

set.seed(123)
folds <-  split(sample(seq_along(y)), seq_along(seq_along(y)) %% 2) %>% setNames(c('Fold1', 'Fold2'))

set.seed(123)
m1 <- train(X, y1, method='rf', trControl=trainControl(method='cv', number=10))
m1.acc <- max(m1$results$Accuracy)

set.seed(123)
m2 <- train(X, y2, method='rf', trControl=trainControl(method='cv', number=10))
m2.acc <- max(m2$results$Accuracy)

set.seed(123)
m3 <- train(X, y1, method='rf', trControl=trainControl(index=folds))
m3.acc <- max(m3$results$Accuracy)

set.seed(123)
m4 <- train(X, y2, method='rf', trControl=trainControl(index=folds))
m4.acc <- max(m4$results$Accuracy)

print(sprintf('Max accuracy using original levels = %s (with caret folds)', m1.acc))
print(sprintf('Max accuracy using reversed levels = %s (with caret folds)', m2.acc))

print(sprintf('Max accuracy using original levels = %s (with custom folds)', m3.acc))
print(sprintf('Max accuracy using reversed levels = %s (with custom folds)', m4.acc))

# Results when using built-in caret folding:
Max accuracy using original levels = 0.741010101010101 (with caret folds)
Max accuracy using reversed levels = 0.742121212121212 (with caret folds)

# Results when using manually generated folds:
Max accuracy using original levels = 0.77 (with custom folds)
Max accuracy using reversed levels = 0.77 (with custom folds)
```

I think it should be simple enough to fix by just imposing an order on the factor labels in ```createFolds``` but I'm not sure what other functions/locations in the code might have similar issues.

Any ideas?  It's obviously not a huge problem but it does seem like model fitting should be invariant to how factors are named.

**Comment by topepo** [comment]
The main reason for using `y <- factor(as.character(y))` was to get rid of factor levels that were not observed. I suspect that we could add a `levels` argument to that line with the levels (in the original order) of the observed values. 

I can see how that 1000th decimal place could bother someone =]

**Comment by eric-czech** [comment]
Cool I'll put out a PR for it soon.  Yea, it was a minor difference in this isolated case but the in the real problem I was working on where I ran into it was a whole percentage point or two different.  Still no big deal, but I'll try to get in there and fix it wherever the same thing could happen.

**Comment by topepo** [comment]
I'm putting together a CRAN release. If you have a PR, I would need it soon to get it in the next version.

Thanks,

Max

**Comment by eric-czech** [comment]
Hey @topepo sorry but it turns out I was wrong.  I was trying to put together more isolated tests for the same small discrepancies I was finding and realized that the index being created for the folds for all models was actually already the same (whether manually generated or generated by train.default), and the difference in accuracy is just coming from the models themselves.  

In other words, It looks like the only difference seems to be that certain models like random forest or gbm produce different results because they handle the response differently based on it's level order while models invariant to this like glm always produce the same accuracy numbers no matter what.

I'll close this out since it doesn't seem to be an issue in that case.
