### ISSUE TITLE
"size" argument in pcaNNet not documented

### ISSUE THREAD

**Issue by hack-r** [topepo/caret#377]
Just a note -- the argument "size" is required but not documented for the function pcaNNet.

It appears in the only usage example for that function, but is not described in the list of arguments. Presumably it's the number of Principal Components (?), but it would be good to document it.

**Comment by topepo** [comment]
Any answer is in the documentation for `...` which says `arguments passed to nnet`. 

To be more clear, I changed it to `arguments passed to nnet, such as size, decay, etc.`
