### ISSUE TITLE
[Feature Request]: Progress Bar...

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#379]
Except for some particular models ( `ranger` or `randomForest` among others) it is quite difficult to know in which step of the processing is function `train()`. Most of the time, one is completely blind about how far is the model to finish. Even when parameter `verboseIter = TRUE`

For those models that can verbose its status, it happens when most of the process finished, when `train()` collects the results from the different samplings.

This feature is already available in `H2O`, and although it is in text format, it is quite informative about giving a clear indication of where the process is.

There are some packages in `R` already available for this, although I do not know if they are the adequate for `caret` structure:
* https://cran.r-project.org/web/packages/progress/
* http://www.inside-r.org/packages/cran/r.utils/docs/ProgressBar

Thanks,
Carlos.

**Comment by timcdlucas** [comment]
This has been brought up before.
https://github.com/topepo/caret/issues/85

As they say, it's difficult because of the parallel processing in caret.

**Comment by topepo** [comment]
> Most of the time, one is completely blind about how far is the model to finish. Even when parameter `verboseIter = TRUE`

Can you be more specific? This option tells you what model is being run on which resample. Are you able to see it or do you find the information uninformative?

**Comment by coforfe** [comment]
Thanks.
Yes, I usually use option `verboseIter = TRUE`, but most of the times I only get the progress of the process at the very end, when the `train`is almost finished. I end up including the special parameters in `train` that most of the algorithms have to verbose the progress.

I read many threads in `StackOverflow`about this issue, but since they are quite old (some of them one or more years ago) I thought this could be achieved now.

**Comment by topepo** [comment]
Are you using Rstudio with parallel processing? They do some things with std out and the messages don't show up (but will with base R).

**Comment by twest820** [comment]
This still appears to be an issue 7.5 years later (RStudio 2023.06.1, R 4.3.1, caret 6.0-94, `verboseIter = TRUE` messages displayed by default or with `makePSOCKcluster(1)` but not on larger clusters). Some of this issue's contemporaries note difficulty with message routing but, for example, future uses progressr to show progress bars and works fine in RStudio, so progress display during parallel operations has definitely become a solved problem within R. I'm not seeing `train()` currently provides a hook users could use to call progressr but perhaps I've missed something.
