### ISSUE TITLE
ROC based variable importance error

### ISSUE THREAD

**Issue by eric-czech** [topepo/caret#383]
varImp.train currently tries to use trainingData attached to a train object when creating non-model based variable importance (see [here](https://github.com/topepo/caret/blob/7d637bf7c874edf36fd557b70ee55c2ede2829f5/pkg/caret/R/varImp.train.R#L34)) but if returnData is false in trainControl, this code will fail with a difficult-to-debug error (isX ends up being NULL).  

The use of that training data ought to be pre-empted with a check for its existence and a more helpful error message thrown if it does not.

I'd be happy to make a PR from a fork if it isn't a two-minute fix for you @topepo (or someone else).

**Comment by topepo** [comment]
> I'd be happy to make a PR from a fork if it isn't a two-minute fix for you @topepo (or someone else).

That would be helpful. I'm pretty buried right now.
