### ISSUE TITLE
[New Model]: fastAdabost

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#384]
Hello,

There is a fast (C++) version of Adabost already available in CRAN that it would be interesting to incorporate in `caret`:

https://cran.r-project.org/web/packages/fastAdaboost/index.html

Thanks,
Carlos.

**Comment by topepo** [comment]
I'll put one together. I've also asked the package maintainer to add an `nIter` argument to the `predict` function so that model tuning takes less time.

**Comment by coforfe** [comment]
Thanks!!
