### ISSUE TITLE
knnImpute overwrites all values, not just the NA

### ISSUE THREAD

**Issue by tantanchen** [topepo/caret#385]
#### Minimal code:
```{R}
library(caret)
data("airquality")
head(airquality)
```
  Ozone Solar.R Wind Temp Month Day
1    41     190  7.4   67     5   1
2    36     118  8.0   72     5   2
3    12     149 12.6   74     5   3
4    18     313 11.5   62     5   4
5    NA      NA 14.3   56     5   5
6    28      NA 14.9   66     5   6
```{R}
pp <- preProcess(airquality, method = "knnImpute")
test <- predict(pp, newdata = airquality)
head(test)
```
Ozone     Solar.R       Wind       Temp     Month       Day
1 -0.03423409  0.04517615 -0.7259482 -1.1497140 -1.407294 -1.670019
2 -0.18580489 -0.75430487 -0.5556388 -0.6214670 -1.407294 -1.557210
3 -0.91334473 -0.41008388  0.7500660 -0.4101682 -1.407294 -1.444401
4 -0.73145977  1.41095624  0.4378323 -1.6779609 -1.407294 -1.331592
5 -0.80235378 -0.20626799  1.2326091 -2.3118573 -1.407294 -1.218782
6 -0.42831817  0.01972740  1.4029185 -1.2553634 -1.407294 -1.105973
### Session Info:
```{R}
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.1 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] caret_6.0-64    ggplot2_1.0.1   lattice_0.20-33

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.0         magrittr_1.5        splines_3.2.2       MASS_7.3-43        
 [5] munsell_0.4.2       colorspace_1.2-6    foreach_1.4.2       minqa_1.2.4        
 [9] car_2.1-0           stringr_1.0.0       plyr_1.8.3          tools_3.2.2        
[13] parallel_3.2.2      pbkrtest_0.4-2      nnet_7.3-10         grid_3.2.2         
[17] gtable_0.1.2        nlme_3.1-121        mgcv_1.8-7          quantreg_5.19      
[21] MatrixModels_0.4-1  iterators_1.0.7     gtools_3.5.0        lme4_1.1-9         
[25] digest_0.6.8        Matrix_1.2-2        nloptr_1.0.4        reshape2_1.4.1     
[29] codetools_0.2-14    stringi_0.5-5       BradleyTerry2_1.0-6 scales_0.3.0       
[33] stats4_3.2.2        SparseM_1.7         brglm_0.5-9         RANN_2.5           
[37] proto_0.3-10       
```

**Comment by topepo** [comment]
The reason for this is that the distance metric needed by KNN requires the predictors to be on the same scale. If you use `method = "knnImpute"` it actually uses  `method = c("center", "scale", "knnImpute")`. Since it centers and scales the data, it does it for all of the predictors. 

It is possible to back-trasform the data for the missing values but that adds nontrivial complexity to the process. I can add that to the list but it will probably take a while to implement and test.

**Comment by tantanchen** [comment]
So I'm not a programmer, but I would like to help. What can I do to help implement/test this?

**Comment by topepo** [comment]
I'm always interested in getting help but this is likely to be complex...

Off the top of my head, the steps that I can think of are:

 1. develop small test cases with known expected results
 2. get acquainted with github especially pull requests
 3. import caret into your github account
 4. look at the `preProcess` code and get to know it
 5. figure out how to back transform the results and replace the relevant data
 6. determine how to _not_ impact the process when people call other options involving centering and scaling. 
 7. test, test, and test
 8. submit a pull request

**Comment by topepo** [comment]
I'm going to close this due to inactivity. Let me know offline if you need help putting together a PR.

**Comment by agilebean** [comment]
Hi @topepo can you reopen this issue?
I just found that knnImpute implicitly standardizes the data - this was very unexpected and took some time to realize. So I guess other people will also the same so it would be worth changing.
