### ISSUE TITLE
Error in numInClass[i]%/%k : non-numeric argument to binary operator

### ISSUE THREAD

**Issue by eakl** [topepo/caret#387]
I cannot thrive to train a model without errors and I didn't find any clue on SO 

Here is a reproductible set:

You can find a minimal dataset I'm working on here : [Link](http://s000.tinyupload.com/index.php?file_id=36193914216851032970)

And here is the code...
```{R}
data <- read.csv('file.csv', header = TRUE, sep = ',')

library(caret)
data <- data[complete.cases(data), ]
data$donation <- as.factor(data$donation)

set.seed(1337)
ctrl <- trainControl(
  method="repeatedcv",
  number="10",
  repeats=10)

data <- data[,-2]
nnet.fit <- train(donation ~ ., data = data,
                  method = "nnet",
                  trControl = ctrl,
                  verbose = FALSE,
                  tuneLength = 5)
```

...that leads to this error:

> Error in numInClass[i]%/%k : non-numeric argument to binary operator

Anu clue ?

**Comment by topepo** [comment]
`number="10"` should be `number=10`.

Also, you should consider not using "0" and "1" as factor levels too.

**Comment by eakl** [comment]
Thanks topepo for your advice. Problem solved. Too bad for such a typo.
