### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by lucasxteixeira** [topepo/caret#391]
Hey,
First of all, caret is a awesome package!
This issue is not a feature request, it's more like a general wondering.

Right now, caret uses foreach as parallel backend allowing the use of processor multicores.
Even though this is incredibly fast compared to a single threaded execution, using a GPU backend might make it much more faster.

My point is: how hard would it be to implement GPU backend support in caret? Could it be done using packages such as gpuR? Is there any plans for it?

Thanks for the attention.

**Comment by zachmayer** [comment]
We'd need a gpu foreach package.

This is unlikely to happen though, as gpus aren't great for general purpose computing.  They excel at matrix operations, but aren't so great for other algorithms, eg a gbm or random forest.

**Comment by topepo** [comment]
Agreed. It would probably best be implemented by the individual packages
(when the gpu helps) and then caret would benefit by extension.

**Comment by topepo** [comment]
I'm going to close this due to inactivity.

**Comment by ssh352** [comment]
I also wonder if caret and tidymodels will support GPU training in the future.
