### ISSUE TITLE
Incorrect output of 'findCorrelation' - zero output if no more item over the cutoff set.

### ISSUE THREAD

**Issue by demydd** [topepo/caret#395]
I have come across some malfunction of 'findCorrelation' considering the final output (details see http://stackoverflow.com/questions/35984919/incorrect-output-of-findcorrelation-caret-package).  

I have done debuging with the step into 'findCorellation_exact'. 
So it looks like the wrong output the bold segment (see the scrip after the message).

But it is the result of the wrong logics in italic -> if you have no items over the cutoff you must left the vector 'newOrder' as it is. Otherwise the red segment will generate zero vector -> generate the zero output.

'findCorellation_exact': 

    function (x, cutoff = 0.9, verbose = FALSE) 
    {
    varnum <- dim(x)[1]
       if (!isTRUE(all.equal(x, t(x)))) 
           stop("correlation matrix is not symmetric")
       if (varnum == 1) 
           stop("only one variable given")
       x <- abs(x)
    originalOrder <- 1:varnum
    averageCorr <- function(x) mean(x, na.rm = TRUE)
    tmp <- x
    diag(tmp) <- NA
    maxAbsCorOrder <- order(apply(tmp, 2, averageCorr), decreasing = TRUE)
    x <- x[maxAbsCorOrder, maxAbsCorOrder]
    newOrder <- originalOrder[maxAbsCorOrder]
    rm(tmp)
    deletecol <- rep(FALSE, varnum)
    x2 <- x
    diag(x2) <- NA
    for (i in 1:(varnum - 1)) {

** if (!any(x2[!is.na(x2)] > cutoff)) {
            if (verbose) 
                cat("All correlations <=", cutoff, "\n")
            (break)()
} **

        if (deletecol[i]) 
            next
        for (j in (i + 1):varnum) {
            if (!deletecol[i] & !deletecol[j]) {
                if (x[i, j] > cutoff) {
                  mn1 <- mean(x2[i, ], na.rm = TRUE)
                  mn2 <- mean(x2[-j, ], na.rm = TRUE)
                  if (verbose) 
                    cat("Compare row", newOrder[i], " and column ", 
                      newOrder[j], "with corr ", round(x[i, j], 
                        3), "\n")
                  if (verbose) 
                    cat("  Means: ", round(mn1, 3), "vs", round(mn2, 
                      3))
                  if (mn1 > mn2) {
                    deletecol[i] <- TRUE
                    x2[i, ] <- NA
                    x2[, i] <- NA
                    if (verbose) 
                      cat(" so flagging column", newOrder[i], 
                        "\n")
                  }
                  else {
                    deletecol[j] <- TRUE
                    x2[j, ] <- NA
                    x2[, j] <- NA
                    if (verbose) 
                      cat(" so flagging column", newOrder[j], 
                        "\n")
                  }
                }
            }
        }
    }
_newOrder[which(deletecol)]_
}

**Comment by topepo** [comment]
Now that I look at this, it is not a bug. 

In `?findCorrelation`, it describes the value returned as

 >  A vector of indices denoting the columns to remove (when `names = TRUE`) otherwise a vector of column names. If no correlations meet the criteria, `integer(0)` is returned.

The issue that you are seeing results because you need to make sure that the subsetting vector has elements to it via something like

```r
if(length(hc) > 0) df2 <- df2[-hc, -hc]
```

Any zero length integer would produce this issue.
