### ISSUE TITLE
[New Model]: classyfire - Robust multivariate classification using highly optimised SVM ensembles

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#397]
Hello,

Although this is not a new package in CRAN, **`classyfire`** offers a very interesting way of building model ensembles based on SVMs, that `caret` could integrate:

[https://cran.rstudio.com/web/packages/classyfire/index.html](url)

Just a note of caution to consider: Its Github page has some open issues for a big while....

[https://github.com/eaHat/classyfire/issues](url)

Thanks,
Carlos.

**Comment by topepo** [comment]
Sure. I'll take a look.

Thanks,

Max

**Comment by coforfe** [comment]
Thanks!

Carlos.
