### ISSUE TITLE
Q: where can I feed nthread to xgboost?

### ISSUE THREAD

**Issue by Puriney** [topepo/caret#399]
Hi, I was wondering where to feed `nthread` parameter to xgboost?

Solely in xgboost context: 

```r
bst <- xgboost(params = xbt_param,
               data   = tr_x,
               label  = tr_yInt - 1, ## meet xgboost input format
               nrounds = num_bstrees,
               nthread = num_threads
               )
```

Within caret context, I cannot find a way to feed the `nthread`. My guess is:

```r
library(doMC)
registerDoMC(cores = 5)

xgb_trCtrol <- trainControl(method = 'cv',
                            number = 5,
                            classProbs = TRUE,
                            summaryFunction = multiClassSummary,
                            allowParallel = TRUE)
)
```

Is this the proper way to set `nthread` in caret context?

**Comment by topepo** [comment]
`allowParallel` helps set the parallelism of resampling which is the loop outside of the model training. If you want to use parallelism within each `xgboost` call, you need to pass `nthread` to `xgb.train`. According to `?xgb.train`, `...` goes to "other parameters to pass to `params`."

So you should be able to pass `nthread` to `xgb.train` by using it as an argument to `train`. 

Also, I would not use `nthread` in conjunction with the resampling-level parallel processing; if you were to ask for _M_ workers, doing so will actually request _M_<sup>2</sup> cores.
