### ISSUE TITLE
Calculation of R2 when the variables are non-stationary

### ISSUE THREAD

**Issue by crossxwill** [topepo/caret#403]
I understand that `caret` supports two different calculations for R-Squared. I personally prefer the traditional method, but am unable to tell the `train` function to maximize the traditional R2. I tried setting `formula="traditional"` in both `train` and `trainControl`, but the functions do not register the `formula` argument.

Here's an extreme example where using R2=cor(pred, actuals)^2 is misleading.

```{R}
> library(caret)
> pred <- c(1, 2, 3, 4, 5)
> actuals <- c(100, 200, 300, 400, 500)
> R2(pred, actuals)
[1] 1
> 
> R2(pred, actuals, formula = "traditional")
[1] -4.39055
> 
```
 Here's some non-stationary variables.

```{R}
nobs <- 1000
set.seed(1983)
y <- cumsum(rnorm(nobs, 10, 10))  # random walk
x <- cumsum(rnorm(nobs, 10, 10))  # random walk

df <- data.frame(t=1:nobs, y=y, x=x)

df.train <- df[801:880,]  # 80 quarters training
df.test <- df[881:889,]  # 9 quarters test set
```
Here's the control and train using timeSlice cross-validation.
```{R}
ts.ctrl <- trainControl(method = "timeSlice",
                        initialWindow = 40,  ## size of training data
                        horizon = 9,         ## size of test set
                        fixedWindow = TRUE)  ## fix the size of the training set?

set.seed(12345)
ts.lm.mod <- train(form=y ~ x, data=df.train, trControl=ts.ctrl, metric="RMSE",
 maximize=FALSE, method="lm")

set.seed(12345)
ts.stepwise <- train(form=y ~ x, data=df.train, trControl=ts.ctrl, metric="RMSE",
 maximize=FALSE, method="lmStepAIC", trace=0)

```

The cross-validation R2 (using cor^2) grossly overestimates out-of-sample R2. Cross-validation estimates out-of-sample (9-quarter-ahead) R2 to be between 18% and 97%. The true test set R2 is -298%. Cross-validation RMSE (9-quarter-ahead) appear reasonable.

```{R}
> timePerf <- resamples(list(OLS=ts.lm.mod, Stepwise=ts.stepwise))
> 
> summary(timePerf)

Call:
summary.resamples(object = timePerf)

Models: OLS, Stepwise 
Number of resamples: 32 

RMSE 
          Min. 1st Qu. Median  Mean 3rd Qu.  Max. NA's
OLS      20.48   25.91   28.7 38.26   47.25 75.29    0
Stepwise 20.48   25.91   28.7 38.26   47.25 75.29    0

Rsquared 
          Min. 1st Qu. Median   Mean 3rd Qu.   Max. NA's
OLS      0.183   0.644 0.7304 0.6812  0.7803 0.9731    0
Stepwise 0.183   0.644 0.7304 0.6812  0.7803 0.9731    0

> 
> ### test set performance
> 
> test.pred <- predict(ts.lm.mod, newdata = df.test)
> 
> RMSE(test.pred, df.test$y)
[1] 54.19845
> R2(test.pred, df.test$y)
[1] 0.9551522
> R2(test.pred, df.test$y, formula="traditional")
[1] -2.982959

```

**Comment by topepo** [comment]
You will need to pass a new summarization function to the `summaryFunction` argument of `trainControl`.  You could alter the default function used, `postResample`, to add the extra option to `R2`. 

See the [web page](http://topepo.github.io/caret/training.html#metrics) for examples.
