### ISSUE TITLE
[Just Informative]: New 'caret' version already ?...

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#405]
Hello,

Some days ago I updated the packages I have installed and I realized that there is a new `caret` version: `6.0-66`. I was (I am) interested in knowing the whole list of changes but still, in CRAN it appears the previous version `6-0.64`. 

https://cloud.r-project.org/web/packages/caret/index.html
https://cloud.r-project.org/web/packages/caret/news.html

Thanks,
Carlos.

**Comment by topepo** [comment]
The change list for 6-0.64 are mislabeled; those are for 6.0-66. 

I'll fix it in the next release (hopefully in a few days).

Thanks,

Max
