### ISSUE TITLE
Caret won't install/load properly - despite trying everything

### ISSUE THREAD

**Issue by jsylves** [topepo/caret#411]
When I go to Tools > Install Packages > "caret," it appears that the package is successfully installed (R response is posted at the bottom of this text).  However, when I run library(caret), I get the following error messages:

> library(caret)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  aucun package nommé ‘pbkrtest’ n'est trouvé
In addition: Warning message:
le package ‘caret’ a été compilé avec la version R 3.2.4 
Error: le chargement du package ou de l'espace de noms a échoué pour ‘caret’

My program responds in French sometimes because I bought my computer in Belgium (it's quite annoying), but this translates to: "no package named ' pbkrtest ' is found
In addition : Warning message:
package ' caret ' was compiled with version 3.2.4 R
Error: loading the package or namespace failed for ' caret '

When I try to download pbkrtest, it says "package ‘pbkrtest’ is not available (for R version 3.2.0)."  Also when I run ??pbkrtest, no results are found.

I have updated my R Studio to the latest version.  I looked at some other posts and then tried "install.packages(pkgs = "caret", dependencies = c("Depends", "Imports"))" and "install.packages("caret", repos="http://cran.rstudio.com/")"  and "install.packages("caret", depencencies = c("Depends", "Suggests"))" ........and none of these commands worked either.

I really need this package! Can anyone help me?

 
Full R response:

> install.packages("caret")
Installing package into ‘C:/Users/user/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/caret_6.0-68.zip'
Content type 'application/zip' length 4653641 bytes (4.4 MB)
downloaded 4.4 MB
package ‘caret’ successfully unpacked and MD5 sums checked
The downloaded binary packages are in
	C:\Users\user\AppData\Local\Temp\RtmpoflVnl\downloaded_packages

> library(caret)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  aucun package nommé ‘pbkrtest’ n'est trouvé
In addition: Warning message:
le package ‘caret’ a été compilé avec la version R 3.2.4 
Error: le chargement du package ou de l'espace de noms a échoué pour ‘caret’

**Comment by topepo** [comment]
What version of R are you using? Please show the results of `sessionInfo()`.

The [CRAN page for pbkrtest](https://cran.r-project.org/web/packages/pbkrtest/index.html) says that it depends on R (≥ 3.2.3).

You should install `caret' using

```r
install.packages("caret",
                 repos = "http://cran.r-project.org", 
                 dependencies = c("Depends", "Imports", "Suggests"))
```

This is different from what one would normally expect but `caret` has a ton of dependencies that you don't necessarily want to load whenever you start `caret`.

**Comment by xanstorm** [comment]
I am not sure how relevant my comment is, but when I installed caret, I also had to install e1071.

**Comment by topepo** [comment]
Is everything good now?

**Comment by xanstorm** [comment]
Hi,
Thanks. I am a noob and I tried to use load(caret) instead of
library(caret).
But while you're here....
Can you decipher this one?
Error in train.default(x, y, weights = w, ...) :
  Metric RMSE not applicable for classification models

Thanks for caring and responding. That is cool.
Stephen


On Sun, May 1, 2016 at 8:57 PM, topepo <notifications@github.com> wrote:

> Is everything good now?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/topepo/caret/issues/411#issuecomment-216086522>
>



-- 
Stephen Hobbs, M.Sc., MBA
Skype: stephenmhobbs
Cell: 404-441-2858
Google Voice: 951-249-3247

**Comment by topepo** [comment]
No problem =]

It looks like you want to do classification (with a categorical outcome) but you are giving the function a numeric outcome instead. Perhaps it should be converted to a factor with levels that are valid R names.

**Comment by xanstorm** [comment]
U r magnificent !!!  Thnx!!

**Comment by jsylves** [comment]
Hi, thanks for all the quick responses. Nothing worked for me until I
downloaded the caret zip file from the cran.r-project.org website and
loaded the package manually from a file included in the zip. Cheers

**Comment by keithhickman07** [comment]
I had similar issues, but my error indicated that 'lubridate' wasn't installed.  I installed lubridate, loaded it, then reloaded caret and everything worked.

**Comment by samiatasmim** [comment]
Hi! I tried the suggestion above: install.packages("caret",
                 repos = "http://cran.r-project.org", 
                 dependencies = c("Depends", "Imports", "Suggests"))

--but it was taking over 30 minutes so I cancelled it. I restarted and did the same again, and it is still taking very long! I was wondering if there is a way around this?

Thank you!

**Comment by topepo** [comment]
FYI It is always better to start a new issue instead of appending to a closed one. 

It is the "Suggests" that is taking so long. The install process finds all dependencies _recursively_ so that something that `caret` depends on is install along with all of its dependencies and so on.

**Comment by amolps** [comment]
I would suggest you to check the R version. I updated the version to 3.5.1 and it works perfectly :)

Mac only – use updateR

Similar to installr, updateR is the package to help updating R on Mac OS.

The R code you will need is these 5 lines:

install.packages('devtools') #assuming it is not already installed

library(devtools)

install_github('andreacirilloac/updateR')

library(updateR)

updateR(admin_password = 'Admin user password')

**Comment by RickyRahardja** [comment]
Hello topepo!
A noob need help here.
I tried several ways already but seems I cant load caret still.
it shows:
Error: package or namespace load failed for ‘caret’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘dimRed’

can please kindly guide?
thank you in advance.

**Comment by Manish3323** [comment]
I have installed caret successfully without any errors.
but while running `library("caret") `gives this error : ` Error in library(cret) : there is no package called ‘caret’`

**Comment by topepo** [comment]
@Manish3323 

Try using this:

```r
source("https://bioconductor.org/biocLite.R")
biocLite("Biobase")
```

**Comment by Manish3323** [comment]
@topepo 
Thanks. i have update my comment above. i had version mismatch issue . :(

**Comment by topepo** [comment]
I'm going to lock this old thread. For current install issues, please see if #964 is more appropriate for your issues. If not, please start a new issue.
