### ISSUE TITLE
LSSVMs have a regularization parameter

### ISSUE THREAD

**Issue by catastrophic-failure** [topepo/caret#415]
Just a minor comment, while in the models list it makes clear SVM have a regularization parameter `C` || `cost` to be tuned, the LSSVM also has one: `tau`. `caret` doesn't reflect that.

**Comment by topepo** [comment]
Ah, I overlooked that. Do you want to suggest a range of appropriate values?

**Comment by catastrophic-failure** [comment]
@topepo Well, I have no theory to back it, 1E-2 is the default. `tau` 10^(-4:4) brings great variability in `iris`. See these results
```
y = c(0.01342282, 0.01342282, 0.006711409,0.01342282,0.02013423,0.02684564,0.03355705,0.04026846,0.1073826,0.3288591,0.3288591)
x = 10^(-5:5)
```
The region around 10^(-4:-2) is the optimum.

**Comment by topepo** [comment]
Once I went back and looked at the papers, I think that I will base the
grid off of the same ones for cost in the usual SVM models.

I've sent an email to the package maintainer. I have almost always gotten
an error using the linear kernel with these models and would like to know
if there is a fix.

I'll check in some code as soon as I'm done testing.

**Comment by topepo** [comment]
on CRAN
