### ISSUE TITLE
column order of data affects results

### ISSUE THREAD

**Issue by skw90** [topepo/caret#416]
It seems that using the same data but with different column orders will change results.

Minimal, reproducible example:

```{R}
library(mlbench)
data(Sonar)
library(caret)
set.seed(998)
inTraining <- createDataPartition(Sonar$Class, p = .75, list = FALSE)
training <- Sonar[ inTraining,]
testing  <- Sonar[-inTraining,]
fitControl <- trainControl(## 10-fold CV
                           method = "repeatedcv",
                           number = 10,
                           ## repeated ten times
                           repeats = 10)

set.seed(825)
gbmFit1 <- train(Class ~ ., data = training,
                 method = "gbm",
                 trControl = fitControl,
                 ## This last option is actually one
                 ## for gbm() that passes through
                 verbose = FALSE)
gbmFit1
```

Stochastic Gradient Boosting 

157 samples
 60 predictor
  2 classes: 'M', 'R' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 10 times) 
Summary of sample sizes: 142, 142, 140, 142, 142, 141, ... 
Resampling results across tuning parameters:

  interaction.depth  n.trees  Accuracy   Kappa    
  1                   50      0.7609191  0.5163703
  1                  100      0.7934216  0.5817734
  1                  150      0.7977230  0.5897796
  2                   50      0.7858235  0.5667749
  2                  100      **0.8188897**  **0.6316548**
  2                  150      **0.8194363**  **0.6329037**
  3                   50      **0.7889436**  **0.5713790**
  3                  100      0.8130564  0.6195719
  3                  150      0.8221348  0.6383441

Tuning parameter 'shrinkage' was held constant at a value of 0.1

Tuning parameter 'n.minobsinnode' was held constant at a value of 10
Accuracy was used to select the optimal model using  the largest value.
The final values used for the model were n.trees = 150, interaction.depth =
 3, shrinkage = 0.1 and n.minobsinnode = 10. 

```{R}
finalVars <- colnames(training)
# reorder columns
finalVars <- finalVars[order(finalVars)]

set.seed(825)
gbmFit1 <- train(Class ~ ., data = training[, finalVars],
                 method = "gbm",
                 trControl = fitControl,
                 ## This last option is actually one
                 ## for gbm() that passes through
                 verbose = FALSE)
gbmFit1
```

Stochastic Gradient Boosting 

157 samples
 60 predictor
  2 classes: 'M', 'R' 

No pre-processing
Resampling: Cross-Validated (10 fold, repeated 10 times) 
Summary of sample sizes: 142, 142, 140, 142, 142, 141, ... 
Resampling results across tuning parameters:

  interaction.depth  n.trees  Accuracy   Kappa    
  1                   50      0.7609191  0.5163703
  1                  100      0.7934216  0.5817734
  1                  150      0.7977230  0.5897796
  2                   50      0.7858235  0.5669550
  2                  100      **0.8194779**  **0.6331626**
  2                  150      **0.8207279**  **0.6354601**
  3                   50      **0.7946936**  **0.5831441**
  3                  100      0.8130564  0.6195719
  3                  150      0.8220931  0.6381234

Tuning parameter 'shrinkage' was held constant at a value of 0.1

Tuning parameter 'n.minobsinnode' was held constant at a value of 10
Accuracy was used to select the optimal model using  the largest value.
The final values used for the model were n.trees = 150, interaction.depth =
 3, shrinkage = 0.1 and n.minobsinnode = 10. 

We can see from the bold numbers that using different column orders gives different results.

>sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS release 6.7 (Final)
gbm_2.1.1
caret_6.0-68
mlbench_2.1-1

This issue applies for several other models I checked as well: rpart, C5.0. Does anyone knows why this is happening?

**Comment by topepo** [comment]
Just to let you know, I'm looking into this.

**Comment by topepo** [comment]
This was a weird one to track down. 

The problem appears to be with `gbm`. One rare occasions you will get slightly different results when the column order is different. 

For your example, 901 total models were fit. I controlled everything (e.g. the seeds, resamples, eliminating the sub-model trick, etc.) and in 37 cases (4.1%) the model object was different. There appears to be no discernible pattern (in terms of the tuning parameters, etc) that I can see. 

I also tried to replicate it with different data sets and haven't been able to do so (yet). If you could send the similar `rpart` and `C5` code, I'll take a look at that too.
