### ISSUE TITLE
preProcess zv and nzv for factors

### ISSUE THREAD

**Issue by JocelynBarker** [topepo/caret#417]
At present, the preProcess function ignores factor variables, which is appropriate for options like "center" and "scale".  However, for options like "zv" and "nzv" where variables with low variance are removed, it would be nice if factors with one level or where they are dominated by one level could be removed.

Thank you!

**Comment by topepo** [comment]
I'll put it on the list...

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
