### ISSUE TITLE
[New Model]: fuzzyforest 

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#421]
Hello,

This is a new randomForest variation that seems to handle better than randomForest the presence of correlated features.

https://cloud.r-project.org/web/packages/fuzzyforest/index.html

Thanks,
Carlos.

**Comment by topepo** [comment]
There aren't any examples in the documentation and the paper is not released. Unless you want to offer a workflow for this model, I'd rather wait until there is more information.

**Comment by coforfe** [comment]
Thanks.
Well, I have not any special interest.

Yes, and also, as with other recent algorithms, in this case again I am not fully sure if even the predict is ready for `prob` which is a limitation.

Thanks again,
Carlos.

**Comment by coforfe** [comment]
Hello,

The package is now in version 1.0.2 and the documentation includes some examples so it seems it has reached some good level of stability.

Also there is available a [paper](http://escholarship.org/uc/item/55h4h0w7#page-1) that describes its strengths compared with _randomForest_.

Thanks,
Carlos.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.
