### ISSUE TITLE
possible bug in deepboost

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#423]
I am using deepboost package for classification using the code below:
In particular caret general configuration (see list caretTrainCtrl) works well for all classification machine learning techniques (rf, glmnet, gbm, neural networks, etc...) but not for deepboost

# running deepboost
caretTrainCtrl <- trainControl(method = "cv", #cross validation
                               number=5, #five folds
                               #used to configure the classification probabilities
                               summaryFunction = twoClassSummary,
                               classProbs = TRUE,
                               returnData =FALSE,
                               verboseIter=TRUE)

cl<-makeCluster(cores)
registerDoParallel(cl)
#tune the model

deepboostGrid=expand.grid(
  num_iter=c(1,100,400),
  tree_depth =c(3,7,10),
  beta=c(0.05,0.15,0.25),
  lambda=c(0.05,0.15,0.25),
  loss_type="l"
)

model.deepboost <- train(x = data.train.train[,filteredPredictors],
                      y =data.train.train[,"gender"],  
                      method="deepboost", trControl=caretTrainCtrl, 
                      metric="ROC",tuneGrid = deepboostGrid)

stopCluster(cl)
getTrainPerf(model.deepboost)

I get the following error: 

 train()'s use of ROC codes requires class probabilities. See the classProbs option of trainControl()
In addition: Warning message:
In train.default(x = data.train.train[, filteredPredictors], y = data.train.train[,  :
  Class probabilities were requested for a model that does not implement them

**Comment by topepo** [comment]
It isn't a bug. The output says

>  Class probabilities were requested for a model that does not implement them

Look at `?deepboost.predict`. It only produces the classes and not probabilities.
