### ISSUE TITLE
confidence intervals in calibration plot

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#426]
Calibration plots are great to assess the accuracy of classification models. A nice add on could be the addition of two confidence band lines based on binomial distribution... This would help when the data set is small...

**Comment by topepo** [comment]
I've checked in some code to do this. Please test and let me know what you think. 

It is a lot easier to add the confidence intervals using `ggplot` so you will have to use the `ggplot` method for the calibration object.

**Comment by spedygiorgio** [comment]
On this example
[checksCalibration.zip](https://github.com/topepo/caret/files/387140/checksCalibration.zip)

calibration(flag_stipendio_vero~pred.c50,data = datatest,class="si") raises an error.
Please consider it is a quite extreme example (quasi - perfect prediction)... However the new function does not work...I would suggest: 1- to put the option to have confidence interval confint=FALSE; 2- try to handle thus extreme (but not so uncommon) situations by try and catch

**Comment by spedygiorgio** [comment]
The error is:
Error in binom.test(x = sum(x$class == cls), n = nrow(x)) : 
  'n' must be a positive integer >= 'x'

**Comment by spedygiorgio** [comment]
Running example from #371 using ggploy(obj) I notice that the confidence intervals are well displayed but not the line connecting midpoints...

**Comment by topepo** [comment]
> Running example from #371 using ggploy(obj) I notice that the confidence intervals are well displayed but not the line connecting midpoints...

It got a little crowded when I added those. You can add them using `ggplot(obj) + geom_line()`

**Comment by topepo** [comment]
The changes that I just checked in should fix the case where there are no data in the interval.

**Comment by topepo** [comment]
on CRAN
