### ISSUE TITLE
[New Model]: kinn (an Implementation of 'kinn' Algorithm, a Graph Based Regression Model)

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#429]
Hello,

There is a new model (just for `regression`) that predicts based on graph proximity.

https://cran.r-project.org/web/packages/kinn/index.html

_A graph based regression model from flat unstructured dataset. Each line in the input data set is treated as a node from which an edge to another line (node) can be formed. In the training process, a model is created which contains sparse graph adjacency matrix. This model is then used for prediction by taking a predictor and the model as inputs and outputs a prediction which is an average of the most similar node and its neighbours in the model graph._

Thanks,
Carlos.

**Comment by topepo** [comment]
I'm looking into it but ran into an error

```r
library(caret)
library(kinn)

set.seed(242)
tr_dat <- SLC14_1(100)
te_dat <- SLC14_1(100)

tr_y <- tr_dat$y
te_y <- te_dat$y

p <- ncol(tr_dat)

## center and scale the predictors
pp <- preProcess(tr_dat[, -p])
tr_dat <- predict(pp, tr_dat)
te_dat <- predict(pp, te_dat)

tr_dat$y <- tr_y
te_dat$y <- te_y


form <- paste("y ~", paste0(names(tr_dat[, -p]), collapse = "+"))
mod <- kinn.train(form, data = tr_dat)

preds <- kinn.predict(mod, te_dat[, -p])
```

I sent an email to the package author...

**Comment by coforfe** [comment]
Thanks!

I also get an error with your code. 
The examples in `knn.train` and `knn.predict` (simpler than yours) work.
I tried also `knn.train` with `pre.process = TRUE` :

```{r}
mod <- kinn.train(form, data = tr_dat, pre.process = TRUE)
```
But also fails in the prediction.

The error I get is this:
`Error in g[simv, ] : subindex out of range`

Thanks again,
Carlos

**Comment by coforfe** [comment]
Hello,

Yesterday I saw a new version of `knn` in CRAN. And with it, your code does not fail.
So your request has been effective... and their change has been immediate.

Thanks,
Carlos.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.
