### ISSUE TITLE
Y-aware PCA for preprocessing

### ISSUE THREAD

**Issue by rwarnung** [topepo/caret#430]
Hi Dr.Kuhn,
I just contacted you by mail.  I stumbled upon Y-aware PCA http://www.win-vector.com/blog/2016/05/pcr_part2_yaware/ which is compared to prProcess in caret.

They cover the case where Y is continuous numeric. There seems to be no solution where Y is binary or a class indicator.

Wouldn't it be great to have Y-aware PCA (Y-PCA?) as an option in preProcess?

The method is similar to partial least-squares regression.
So far I played and applied pls to the data (using all components) and then extracted the projection matrix and applied it to the training data and to new data. This should work for continuous as well as binary response (but I am not sure).

```
library(pls)
## apply pls with all components to get the projection matrix 
  pls.model = plsr(target ~., scale = FALSE, data = cbind(target = data[,22],numPart ),ncomp = ncol(numPart))
  numPart = as.data.frame(as.matrix(numPart)%*%pls.model$projection)
## apply the projection to the test set
  numPart.testing= as.data.frame(as.matrix(numPart.testing)%*%pls.model$projection)
```

**Comment by topepo** [comment]
I'll put it on the list but it might be a while. I'm currently refactoring `preProcess` and those changes will come first.
