### ISSUE TITLE
Feature proposal: time partition for time series classification/regression

### ISSUE THREAD

**Issue by KBlansit** [topepo/caret#434]
I was currently working on a time series classification project and wanted to create partitions (similar to those in the createDataPartition method) but using contiguous slices of data. I already investigated the createTimeSlices method, but it appear to be for forecasting rather than for classification/regression. I was wanting to contribute to the caret project this functionality.

An example of the data would be similar to that of regularly sampled data from EKG (where there are multiple classes of EKG data nested in a list). My proposed solution would be to draw contiguous sample slices from each individual data set for the sample for the training and test data sets.

I would be grateful for any feedback or suggestions that would enable a successful pull request.

**Comment by topepo** [comment]
Can you mock up an example showing examples of what the holdout patterns would look like?

**Comment by KBlansit** [comment]
I believe the main concern I see with the current implimentation of createTimeSlices is a lack of ability to use values that are not of a future time index from the dependent variables. For example, the following use of createTimeSlices performs the following:

```r
createTimeSlices(1:5, initialWindow = 2)
$train
$train$Training1
[1] 1 2

$train$Training2
[1] 2 3

$train$Training3
[1] 3 4


$test
$test$Testing1
[1] 3

$test$Testing2
[1] 4

$test$Testing3
[1] 5
```
While this is useful for forecasting (where information of the future is the desired regression or classification issue), use of the label at the last training time slice index may be useful for other use cases (so for example, instead of $test$Training producing the index of 3, producing the index of 2). I can understand how an advanced user of R can extract this information by writing their own function (by using a do.call and rbind on the $training list, and extracting the rightmost column) this feels a little hacky. I would therefore propose values such as -1 in the horizon parameter allow for such behavior (horizon = 0 currently will return data, and would not want to compromise other's use of this functionality). This would allow one to produce a time series regression or classification model that is specific to the current dependent variable, not a future predictive model.

**Comment by topepo** [comment]
I can't tell what you are trying to get at. Do you want to include the same sample in the model fitting and holdout sets? Mocking up an example will be helpful in understanding this.
