### ISSUE TITLE
Error when fitting nonstandard formula for gam (mgcv) model

### ISSUE THREAD

**Issue by adamdsmith** [topepo/caret#437]
Generate test data
------------------

    library(mgcv, quietly = TRUE)
    library(caret, quietly = TRUE)
    dat <- gamSim(3, n=400, scale=2, verbose=FALSE)
    head(dat)

    ##            y         x1          x2           f
    ## 1 -0.6214585 0.72785018 0.006100046 0.002135138
    ## 2  1.9245661 0.04954822 0.009249645 0.007211367
    ## 3 -0.3630785 0.66521243 0.011423078 0.013287831
    ## 4 -1.3458304 0.34340275 0.011554818 0.013734575
    ## 5 -0.9480075 0.20614605 0.012163713 0.015923858
    ## 6  1.6789991 0.52966272 0.014891997 0.028424794

Create custom `modelInfo` from gam.R
------------------------------------

Goal is to fit: `y ~ s(x1) + s(x2, by = f)`

    modelInfo <- list(label = "Generalized Additive Model using Splines",
                      library = "mgcv",
                      loop = NULL,
                      type = c('Regression', 'Classification'),
                      parameters = data.frame(parameter = c('select', 'method'),
                                              class = c('logical', 'character'),
                                              label = c('Feature Selection', 'Method')),
                      grid = function(x, y, len = NULL, search = "grid") {
                        if(search == "grid") {
                          out <- expand.grid(select = c(TRUE, FALSE), method = "GCV.Cp")
                        } else {
                          out <- data.frame(select = sample(c(TRUE, FALSE), size = len, replace = TRUE),
                                            method = sample(c("GCV.Cp", "ML"), size = len, replace = TRUE))
                        }
                        out[!duplicated(out),]
                      },
                      fit = function(x, y, wts, param, lev, last, classProbs, ...) { 
                        dat <- if(is.data.frame(x)) x else as.data.frame(x)
                        
                        ## Ignored original code
                        #modForm <- caret:::smootherFormula(x)
                        #if(is.factor(y)) {
                        #  dat$.outcome <- ifelse(y == lev[1], 0, 1)
                        #  dist <- binomial()
                        #} else {
                        #  dat$.outcome <- y
                        #  dist <- gaussian()
                        #}
                        
                        ## New code
                        modForm <- y ~ s(x1) + s(x2, by = f)
                        dist <- gaussian()
                        
                        ## Resume original code
                        modelArgs <- list(formula = modForm,
                                          data = dat,
                                          select = param$select, 
                                          method = as.character(param$method))
                        ## Intercept family if passed in
                        theDots <- list(...)
                        if(!any(names(theDots) == "family")) modelArgs$family <- dist
                        modelArgs <- c(modelArgs, theDots)
                        
                        out <- do.call(getFromNamespace("gam", "mgcv"), modelArgs)
                        out
                        
                      },
                      predict = function(modelFit, newdata, submodels = NULL) {
                        if(!is.data.frame(newdata)) newdata <- as.data.frame(newdata)
                        if(modelFit$problemType == "Classification") {
                          probs <-  predict(modelFit, newdata, type = "response")
                          out <- ifelse(probs < .5,
                                        modelFit$obsLevel[1],
                                        modelFit$obsLevel[2])
                        } else {
                          out <- predict(modelFit, newdata, type = "response")
                        }
                        out
                      },
                      prob = function(modelFit, newdata, submodels = NULL){
                        if(!is.data.frame(newdata)) newdata <- as.data.frame(newdata)
                        out <- predict(modelFit, newdata, type = "response")
                        out <- cbind(1-out, out)
                        ## glm models the second factor level, we treat the first as the
                        ## event of interest. See Details in ?glm
                        colnames(out) <-  modelFit$obsLevels
                        out
                      },
                      predictors = function(x, ...) {
                        predictors(x$terms)
                      },
                      levels = function(x) x$obsLevels,
                      varImp = function(object, ...) {
                        smoothed <- summary(object)$s.table[, "p-value", drop = FALSE]
                        linear <- summary(object)$p.table
                        linear <- linear[, grepl("^Pr", colnames(linear)), drop = FALSE] 
                        gams <- rbind(smoothed, linear)
                        gams <- gams[rownames(gams) != "(Intercept)",,drop = FALSE]
                        rownames(gams) <- gsub("^s\\(", "", rownames(gams))
                        rownames(gams) <- gsub("\\)$", "", rownames(gams))
                        colnames(gams)[1] <- "Overall"
                        gams <- as.data.frame(gams)
                        gams$Overall <- -log10(gams$Overall)
                        allPreds <- colnames(attr(object$terms,"factors"))
                        extras <- allPreds[!(allPreds %in% rownames(gams))]
                        if(any(extras)) {
                          tmp <- data.frame(Overall = rep(NA, length(extras)))
                          rownames(tmp) <- extras
                          gams <- rbind(gams, tmp)
                        }
                        gams
                      },
                      notes = "Which terms enter the model in a nonlinear manner is determined by the number of unique values for the predictor. For example, if a predictor only has four unique values, most basis expansion method will fail because there are not enough granularity in the data. By default, a predictor must have at least 10 unique values to be used in a nonlinear basis expansion.",
                      tags = c("Generalized Linear Model", "Generalized Additive Model"),
                      sort = function(x) x)

Try to fit model
----------------

    ctrl <- trainControl(method = "repeatedcv",   # 10fold cross validation
                         number = 5,                            # do 5 repititions of cv
                         summaryFunction=RMSE)  # Use RMSE to pick the best model
    set.seed(182)
    mod <- train(y ~ x1 + x2 + f,
                 data = dat,
                 method = modelInfo,
                 trControl = ctrl)

    ## Error in if (na.rm) x <- x[!is.na(x)]: argument is not interpretable as logical

    traceback()

    8: mean.default((pred - obs)^2, na.rm = na.rm)
    7: mean((pred - obs)^2, na.rm = na.rm)
    6: ctrl$summaryFunction(testOutput, lev, method)
    5: evalSummaryFunction(y, wts = weights, ctrl = trControl, lev = classLevels, 
           metric = metric, method = method)
    4: train.default(x, y, weights = w, ...)
    3: train(x, y, weights = w, ...)
    2: train.formula(y ~ x1 + x2 + f, data = dat, method = modelInfo, 
           trControl = ctrl)
    1: train(y ~ x1 + x2 + f, data = dat, method = modelInfo, trControl = ctrl)

Session info
------------

    devtools::session_info()

    ## Session info --------------------------------------------------------------

    ##  setting  value                       
    ##  version  R version 3.2.5 (2016-04-14)
    ##  system   x86_64, mingw32             
    ##  ui       RTerm                       
    ##  language (EN)                        
    ##  collate  English_United States.1252  
    ##  tz       America/New_York            
    ##  date     2016-06-14

    ## Packages ------------------------------------------------------------------

    ##  package      * version date       source                            
    ##  car            2.1-2   2016-03-25 CRAN (R 3.2.4)                    
    ##  caret        * 6.0-70  2016-06-13 CRAN (R 3.2.5)                    
    ##  codetools      0.2-14  2015-07-15 CRAN (R 3.2.5)                    
    ##  colorspace     1.2-6   2015-03-11 CRAN (R 3.2.2)                    
    ##  devtools       1.10.0  2016-01-23 CRAN (R 3.2.3)                    
    ##  digest         0.6.9   2016-01-08 CRAN (R 3.2.3)                    
    ##  evaluate       0.8.3   2016-03-05 CRAN (R 3.2.3)                    
    ##  foreach        1.4.3   2015-10-13 CRAN (R 3.2.3)                    
    ##  formatR        1.3     2016-03-05 CRAN (R 3.2.3)                    
    ##  ggplot2      * 2.1.0   2016-03-01 CRAN (R 3.2.3)                    
    ##  gtable         0.2.0   2016-02-26 CRAN (R 3.2.3)                    
    ##  htmltools      0.3.5   2016-03-21 CRAN (R 3.2.4)                    
    ##  iterators      1.0.8   2015-10-13 CRAN (R 3.2.2)                    
    ##  knitr          1.12.3  2016-01-22 CRAN (R 3.2.3)                    
    ##  lattice      * 0.20-33 2015-07-14 CRAN (R 3.2.5)                    
    ##  lme4           1.1-11  2016-02-12 CRAN (R 3.2.3)                    
    ##  magrittr       1.5     2014-11-22 CRAN (R 3.2.2)                    
    ##  MASS           7.3-45  2015-11-10 CRAN (R 3.2.4)                    
    ##  Matrix         1.2-4   2016-03-02 CRAN (R 3.2.4)                    
    ##  MatrixModels   0.4-1   2015-08-22 CRAN (R 3.2.2)                    
    ##  memoise        1.0.0   2016-01-29 CRAN (R 3.2.3)                    
    ##  mgcv         * 1.8-12  2016-03-03 CRAN (R 3.2.4)                    
    ##  minqa          1.2.4   2014-10-09 CRAN (R 3.2.2)                    
    ##  munsell        0.4.3   2016-02-13 CRAN (R 3.2.3)                    
    ##  nlme         * 3.1-126 2016-03-14 CRAN (R 3.2.4)                    
    ##  nloptr         1.0.4   2014-08-04 CRAN (R 3.2.2)                    
    ##  nnet           7.3-12  2016-02-02 CRAN (R 3.2.4)                    
    ##  pbkrtest       0.4-6   2016-01-27 CRAN (R 3.2.5)                    
    ##  plyr           1.8.3   2015-06-12 CRAN (R 3.2.2)                    
    ##  quantreg       5.21    2016-02-13 CRAN (R 3.2.3)                    
    ##  Rcpp           0.12.5  2016-05-14 CRAN (R 3.2.5)                    
    ##  reshape2       1.4.1   2014-12-06 CRAN (R 3.2.2)                    
    ##  rmarkdown      0.9.5.9 2016-04-22 Github (rstudio/rmarkdown@445936b)
    ##  scales         0.4.0   2016-02-26 CRAN (R 3.2.3)                    
    ##  SparseM        1.7     2015-08-15 CRAN (R 3.2.2)                    
    ##  stringi        1.0-1   2015-10-22 CRAN (R 3.2.2)                    
    ##  stringr        1.0.0   2015-04-30 CRAN (R 3.2.2)                    
    ##  yaml           2.1.13  2014-06-12 CRAN (R 3.2.2)

**Comment by topepo** [comment]
The issue is with `summaryFunction=RMSE`. You can leave that option out or use a function that has the right arguments (described [here](http://topepo.github.io/caret/training.html#metrics)).

**Comment by adamdsmith** [comment]
Thanks very much Max!

**Comment by dwinsemius** [comment]
This looks very promising as a worked example of a custom function with mgcv::gam, but it apparently links to a 404'ed location.
