### ISSUE TITLE
Feature Request: Vowpal Wabbit

### ISSUE THREAD

**Issue by perrystephenson** [topepo/caret#438]
Hi Max,

I'd love to use Vowpal Wabbit through caret. Vowpal is fast and efficient, but it has it's own peculiar syntax and also requires file read/write and calls to the command line. It also doesn't provide any CV functionality. Both of these seem like problems that could be solved using caret!

Not sure if it's possible given that it has requirements beyond installing R packages, but it would be a powerful addition to caret.

Cheers,
Perry

**Comment by topepo** [comment]
There is an old R package that has this model but it is not maintained. Someone would have to port it to R; I think that it would be too much to call reliably from the command line, do the file handling, etc..
