### ISSUE TITLE
Parameter tuning with sbf()

### ISSUE THREAD

**Issue by claczny** [topepo/caret#439]
Hi,

when using `train()`, I can successfully use `tuneGrid` to try out some parameters as part of my `repeatedcv`.
However, using `tuneGrid` in `sbf()` seems not to work or I am doing something wrong:

In `str(my_model)`, I can see
```
  ..$ tuneGrid :'data.frame':	1 obs. of  1 variable:
  .. ..$ mtry: num 3
```

But `my_model$fit$mtry` says
```
[1] 2
```

Here are my commands:
```{R}
library(caret)
iris.sub <- subset(iris, Species != "virginica") # Make it two-class
set.seed(42)
iris.sub <- iris.sub[sample(nrow(iris.sub), 50),]

x <- iris.sub[,-5]
y <- droplevels(iris.sub[,5])

my_model.grid <- expand.grid(.mtry=c(3))
my_model.train_ctrl <- trainControl(search = "random", 
                                    classProbs = TRUE)
myFunc <- rfSBF
myFunc$summary <- twoClassSummary
myFunc$score <- function(x, y)
{
  out <- wilcox.test(x ~ y)$p.value # Will have warnings due to ties; ignore for now.
  out
}

my_model.sbf_ctrl <- sbfControl(functions = myFunc,
                                method = "repeatedcv",
                                number = 5,
                                repeats = 10,
                                verbose = TRUE)
set.seed(42)
my_model <- sbf(x,
                y,
                trControl = my_model.train_ctrl,
                sbfControl = my_model.sbf_ctrl,
                tuneGrid = my_model.grid)
```

Your input into this is greatly appreciated.

Best,

Cedric

**Comment by claczny** [comment]
Using a different dataset for testing, as I thought that the number of predictors/features could be too small in the iris-dataset.

```
data("segmentationData")
bla <- subset(segmentationData, Case=="Train")
bla_PS <- subset(bla, Class == "PS")
bla_WS <- subset(bla, Class == "WS")
n_samples <- 13
set.seed(42)
bla_PS_sample <- sample(c(1:nrow(bla_PS)), n_samples)
bla_PS_sampled <- bla_PS[bla_PS_sample, c(-1:-2)]
set.seed(42)
bla_WS_sample <- sample(c(1:nrow(bla_WS)), n_samples)
bla_WS_sampled <- bla_WS[bla_WS_sample, c(-1:-2)]
blub <- rbind(bla_PS_sampled, bla_WS_sampled)
x <- blub[,-1]
y <- blub[,1]
```
Here, `my_model$fit$mtry` gets set to 5, despite being specified to be 3...

**Comment by topepo** [comment]
Using `rfSBF` avoids tuning over `mtry`: 

```r
rfSBF$fit
function (x, y, ...) {
    if (ncol(x) > 0) {
        loadNamespace("randomForest")
        randomForest::randomForest(x, y, ...)
    }
    else nullModel(y = y)
}
```

You'll want to use `caretSBF` to do this:

```r
myFunc <- caretSBF
myFunc$summary <- twoClassSummary
myFunc$score <- function(x, y) {
  out <- wilcox.test(x ~ y)$p.value # Will have warnings due to ties; ignore for now.
  out
}

my_model.sbf_ctrl <- sbfControl(functions = myFunc,
                                method = "repeatedcv",
                                number = 5,
                                repeats = 10,
                                verbose = TRUE)
set.seed(42)
my_model <- sbf(x,
                y,
                trControl = my_model.train_ctrl,
                sbfControl = my_model.sbf_ctrl,
                ## now arguments to `train`:
                method = "rf",
                tuneGrid = my_model.grid)
```

That gives me 

```r
> my_model$fit$finalModel$mtry
[1] 3
```

**Comment by claczny** [comment]
Great! Thanks @topepo! And my apologies for missing on this point.

**Comment by claczny** [comment]
I have a related question: Do I get this right that the parameter tuning is done on *all* features - incl. cross-validation - and based on the selected parameters, a feature selection is done - again cross-validated - to ultimately provide as results the set of "relevant" features and the "sensible" parameter values for the model?

Thank you very much for the clarification.

**Comment by topepo** [comment]
For `sbf`, it does the feature selection then fits the model however you tell it to. For your example, it filters the parameters down then tunes the random forest model using the _inner_ resampling process. The _outer_ resampling repeats that process.

**Comment by claczny** [comment]
Thank you!
Could you please tell me which is the *inner* and which is the *outer* resampling process in the following example code? Is the *inner* resample process the 5-fold-3-repeats as specified by `sbfControl` or the 5-fold-5-repeats as specified by `trainControl`?

```{R}
library(caret)
# DATA 2
data("segmentationData")
bla <- subset(segmentationData, Case=="Train")
bla_PS <- subset(bla, Class == "PS")
bla_WS <- subset(bla, Class == "WS")
n_samples <- 13
set.seed(42)
bla_PS_sample <- sample(c(1:nrow(bla_PS)), n_samples)
bla_PS_sampled <- bla_PS[bla_PS_sample, c(-1:-2)]
set.seed(42)
bla_WS_sample <- sample(c(1:nrow(bla_WS)), n_samples)
bla_WS_sampled <- bla_WS[bla_WS_sample, c(-1:-2)]
blub <- rbind(bla_PS_sampled, bla_WS_sampled)
x <- blub[,-1]
y <- blub[,1]

my_model.grid <- expand.grid(mtry=c(2:5))
my_model.train_ctrl <- trainControl(classProbs = TRUE,
                                    summaryFunction = twoClassSummary,
                                    method = "repeatedcv",
                                    number = 5,
                                    repeats = 5)
myFunc <- caretSBF
myFunc$summary <- twoClassSummary
myFunc$score <- function(x, y)
{
  out <- wilcox.test(x ~ y)$p.value # Will have warnings due to ties; ignore for now.
  out
}

my_model.sbf_ctrl <- sbfControl(functions = myFunc,
                                method = "repeatedcv",
                                number = 5,
                                repeats = 3,
                                verbose = TRUE)
set.seed(42)
my_model <- sbf(x,
                y,
                trControl = my_model.train_ctrl,
                sbfControl = my_model.sbf_ctrl,
                ## now arguments to `train`:
                method="rf",
                tuneLength = 4)

```

Moreover, could you please let me know if I got your explanation right, i.e., is the following correctly paraphrased?
For each *inner* fold and according to some performance measure, e.g., ROC AUC:
1) Select features, e.g., via `wilcox.test`
2) For the selected features, tune the model parameters, e.g., `mtry` for random forest, e.g., for max. ROC AUC
3) Save selected features and respectively tuned model parameters as "best"

For each *outer* fold:
1) Perform all the above steps for each *inner* fold

Finally:
Select the combination of selected features and model parameters that yielded the highest performance, e.g., max. ROC AUC, for the most folds.

Accordingly and for the above example, would that mean that in total 5x3x5x5 = 375 fold in total would be used to decide upon which combination of features and model parameters would be "best"?

**Comment by topepo** [comment]
`sbfControl` controls the outer loop and, in this case, `trainControl` is the inner loop. 

For the "Finally" section, the final feature set is only based on applying the same filtering algorithm to the entire training set. It doesn't really use the resampled filters to do that. This might seem like a waste and you can always go back to determine the probability of being selected over all the outer resamples. 

For the inner resamples, these are only used to tune the model. For a specific outer resample, the inner resamples only pick the tuning parameters. 

The purpose of the outer resamples, is to basically simulate the filtering and model fitting process so that we can get a good estimate of performance when _the same filtering and model fitting process is applied to the entire training set_.  Since your outer resampling scheme has 15 different resamples, the filtering/modeling are replicated 15 times and are only used measure overall performance. 

Does that help?

**Comment by claczny** [comment]
Thank you very much @topepo! 👍 

I will think about this, will work my understanding and come back to you, should I have further questions.
