### ISSUE TITLE
categorical binning of continuous predictors

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#450]
Despite some says it is not optimal, it could be useful when splines / polynomials are not available in the model's formula and when marginal linearity is a too strong assumption. I would suggest to add a dicotomize / optimal binning preprocess function for the continuous predictors. 

At this regards I would suggest: 

- having a look to cut2 function in Hmisc package (g parameters for percentile binning)
- the smbinning package.

**Comment by topepo** [comment]
I have some code packed away to do this but some changes are needed in `preProcess` before it can be integrated. I'm working on it and will be updating the code soon.

**Comment by spedygiorgio** [comment]
Thank you very much 

Sent from my ASUS

-------- Messaggio originale --------
Da:topepo <notifications@github.com>
Inviato:Wed, 06 Jul 2016 02:20:03 +0200
A:topepo/caret <caret@noreply.github.com>
Cc:Giorgio Alfredo Spedicato <spedygiorgio@gmail.com>,Author <author@noreply.github.com>
Oggetto:Re: [topepo/caret] categorical binning of continuous predictors (#450)

**Comment by topepo** [comment]
I'm going to close this for now. I'll reference it as I check code into the package so you can monitor things. 

Thanks,

Max
