### ISSUE TITLE
C5.0 Final Model Extract Rules / Trees

### ISSUE THREAD

**Issue by TonyDIRL** [topepo/caret#451]
Hi,

Really fantastic package - wish to thank you for your continuous contribution. 

Within C5.0 is it possible to extract the rules from a final model in a more readable format. Alternatively, if a tree based model is returned, I'm aware in the C50 package there is plot.C5.0 but I'm not sure if that is exposed within caret?

As an example:

```
require(caret)
C50Ctrl <- trainControl(method = "repeatedcv", number=5,repeats = 5,classProbs = TRUE,verboseIter = FALSE)
c50grid<-expand.grid( .winnow = c(TRUE,FALSE), .trials=c(1,5,10,15,20,35,50), .model=c("tree","rules"))
IRISTrain<- train(Species ~ .,data = iris,tuneGrid=c50grid,trControl=C50Ctrl,method="C5.0")
IRISTrain$finalModel$rules
```

Thank you

**Comment by topepo** [comment]
The plot method for C5.0 objects is only for trees (and should be considered "not production" even then). 

I don't have any parsing code and probably won't get to any this year. It probably shouldn't be too hard to reverse engineer it (there is little to no documentation for the format besides the C code that creates and _prints_ it).  For example:

<pre>
> mod <- C5.0(Species ~ ., data = iris, rules = TRUE)
> summary(mod)

Call:
C5.0.formula(formula = Species ~ ., data = iris, rules = TRUE)


C5.0 [Release 2.07 GPL Edition]  	Mon Jul 11 21:48:42 2016
-------------------------------

Class specified by attribute `outcome'

Read 150 cases (5 attributes) from undefined.data

Rules:

Rule 1: (50, lift 2.9)
	Petal.Length <= 1.9
	->  class setosa  [0.981]

Rule 2: (48/1, lift 2.9)
	Petal.Length > 1.9
	Petal.Length <= 4.9
	Petal.Width <= 1.7
	->  class versicolor  [0.960]

Rule 3: (46/1, lift 2.9)
	Petal.Width > 1.7
	->  class virginica  [0.958]

Rule 4: (46/2, lift 2.8)
	Petal.Length > 4.9
	->  class virginica  [0.938]

Default class: setosa


Evaluation on training data (150 cases):

	        Rules     
	  ----------------
	    No      Errors

	     4    4( 2.7%)   <<


	   (a)   (b)   (c)    <-classified as
	  ----  ----  ----
	    50                (a): class setosa
	          47     3    (b): class versicolor
	           1    49    (c): class virginica


	Attribute usage:

	 96.00%	Petal.Length
	 62.67%	Petal.Width


Time: 0.0 secs

> cat(mod$rules)
id="See5/C5.0 2.07 GPL Edition 2016-07-11"
entries="1"
rules="4" default="setosa"
conds="1" cover="50" ok="50" lift="2.94231" class="setosa"
type="2" att="Petal.Length" cut="1.9" result="<"
conds="3" cover="48" ok="47" lift="2.88" class="versicolor"
type="2" att="Petal.Length" cut="1.9" result=">"
type="2" att="Petal.Length" cut="4.9000001" result="<"
type="2" att="Petal.Width" cut="1.7" result="<"
conds="1" cover="46" ok="45" lift="2.875" class="virginica"
type="2" att="Petal.Width" cut="1.7" result=">"
conds="1" cover="46" ok="44" lift="2.8125" class="virginica"
type="2" att="Petal.Length" cut="4.9000001" result=">"
</pre>

There are 4 rules (`rules="4" default="setosa"`).

The first has one condition (`conds="1"`) that is shown on the next line. 

The second rule has three conditions (`conds="3"`) that is shown on the three lines etc. 

`type="2"` probably means that it is a binary split on a numeric predictor and so on.
