### ISSUE TITLE
Model request: bam models from mgcv

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#453]
Mgcv package has recently proposed an optimized version of gam... It could be nice to add this feature https://stat.ethz.ch/R-manual/R-devel/library/mgcv/html/bam.html

**Comment by topepo** [comment]
Go ahead and try that code out for testing.

**Comment by topepo** [comment]
> There seems to be an error: 
Error in train.default(x = dat[, c("x1", "x2", "x3", "x0")], y = dat$y, : 
Model bam is not in caret's built-in library

>Also I would suggest to let the family not be bounded to binomial or gaussian cause the model could be very useful to fit other glms (poisson or gamma ones for example)

It isn't in the package yet. You'll have to source the [model code]() into an R session then use `method = modelInfo`. For example:

```r
library(caret)
set.seed(24)
tr_dat <- SLC14_1(500)

set.seed(13)
mod <- train(y ~ ., data = tr_dat, 
             method = modelInfo,
             trControl = trainControl(method = "cv"))
```

You should also be able to pass `family` in also. For example:

```r
hist(exp(tr_dat$y/100))

set.seed(13)
mod <- train(exp(y/100) ~ ., data = tr_dat, 
             method = modelInfo,
             family = Gamma(),
             trControl = trainControl(method = "cv"))
```

**Comment by topepo** [comment]
on CRAN
