### ISSUE TITLE
Feature suggestion - LIME

### ISSUE THREAD

**Issue by farbodr** [topepo/caret#463]
This would make a nice addition to caret:

http://www.kdd.org/kdd2016/subtopic/view/why-should-i-trust-you-explaining-the-predictions-of-any-classifier

**Comment by hadjipantelis** [comment]
This has (indirectly) taken care of. Please see the `lime` package on [CRAN](https://cran.r-project.org/web/packages/lime/index.html) (or the associated [github repo](https://github.com/thomasp85/lime)). The package works with `caret` objects out-of-the-box. (And it is generally a nifty piece of work.)

Probably this issue can be closed now.
