### ISSUE TITLE
Feature proposal - multiple input mulitple output

### ISSUE THREAD

**Issue by amarchin** [topepo/caret#466]
I am working on a multiple-output problem. The pls package supports multi-response regression but as far I know caret does not supports this kind of models. Would it be possible to consider this enhancement?

**Comment by topepo** [comment]
Sorry for the (year later) late response. No, that's not something that `caret` will do since it is a significantly invasive change. I am working on other packages that should let you do this though.

**Comment by schelhorn** [comment]
For the record, I'm using this multivariate GBM for these kinds of scenarios: https://cran.r-project.org/web/packages/mvtboost/vignettes/mvtboost_vignette.html

**Comment by topepo** [comment]
Thanks for the link. That will be a good testing/development example.

**Comment by GreatEmerald** [comment]
@topepo What are these "other packages" you're working on?

**Comment by topepo** [comment]
[`tidymodels`](https://github.com/tidymodels)

**Comment by GreatEmerald** [comment]
And which one of those tackles the multiple input issue?

**Comment by topepo** [comment]
Can you be more specific?

**Comment by GreatEmerald** [comment]
It's about what this issue is about: models that handle multiple inputs and multiple outputs. In my case I have ~10 response variables (fractions expressed as 0-100%) and ~60 covariates to predict the fractions from. `caret` would have been really useful for this use case, if it supported multiple inputs and outputs.

**Comment by topepo** [comment]
Sure, it's one of the things that we account for. It's still in development, but the `parsnip` package treats linear regression the same when it's a univariate or multivariate model. 

When it comes to resampling and preprocess, `rsample` and `recipes` also handle multivariate outcomes. Model tuning and other operations will do the same. 

Having some good reproducible test cases/workflows would be helpful that we can use for testing and/or documentation. Public data sets are good if you don't want to make data available.

**Comment by GreatEmerald** [comment]
Right now I'm using the neuralnet package, the code I used is here: https://github.com/GreatEmerald/master-classification/blob/master/src/classification/classify-nn.r The associated data is also in the repo. I could make a stand-alone example as well, if you'd like.
