### ISSUE TITLE
memory size problem in caret / caretEnsemble

### ISSUE THREAD

**Issue by sparcycram** [topepo/caret#472]
I am using the gbm package inside the  caretEnsemble package using caretList on an dataframe of 500 000 rows and 50 columns. The data is mainly numeric with some factors in it. I am receiving the following error.   

Error in { : task 1 failed - "cannot allocate vector of size 1.7 Gb"

The gbm tuning is as follows:-

gbmeg=caretModelSpec(method="gbm", tuneGrid=expand.grid(interaction.depth= (7),n.trees=seq(10,10000, by=10), shrinkage=c(0.05, 0.01), n.minobsinnode = c(10))),

I do have 256GB of RAM so I am surprised by the inability to allocate the vector

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows Server >= 2012 x64 (build 9200)

The script runs error free if I cut down on the number of trees substantially. I was wondering if packages such as bigmemory and or ff might help but have no experience in using them. I believe they might not work with caret.

PS I am using the x/y interface

Any thoughts would be appreciated

**Comment by topepo** [comment]
Is the outcome a factor (how many levels) or numeric?

**Comment by zachmayer** [comment]
Recode all your factors as integers, such that your x matrix is entirely numeric.

**Comment by sparcycram** [comment]
The outcome is a factor of 2 levels.  

Zach the x dataframe is entirely numeric. Should I convert it to a matrix?

Thanks

**Comment by zachmayer** [comment]
Does the GBM itself run out of RAM?  Or only when you call it from caretEnsemble?

**Comment by zachmayer** [comment]
Try `seq(10,10000, by=100)` or `seq(10,10000, by=500)`.  caretList saves the out-of-sample predictions for EVERY model, so `seq(10,10000, by=10)` gives you 1,000 models.  Since you're testing 2 parameters for shrinkage, that's 2,000 models.    Multiply that by 500,000 rows of data, and that's a 1 billion row data.table of out of sample predictions  that caretList is trying to save.

I'd recommend starting with `seq(10,10000, by=500)`, and a single value for shrinkage.  That will be only 20 models caretList has to save, but you'll still explore up to a very large number of trees.

**Comment by zachmayer** [comment]
also try `returnResamp = "final"` in your trainControl.  I think caretList already does that, but I'm not sure.

**Comment by topepo** [comment]
Also, you can (should?) use `xgboost`. It is higher performance that `gbm` and has more tuning parameters to optimize.

**Comment by sparcycram** [comment]
Great fantastic thanks for the suggestions will try these. Zach I haven't tried  gbm outside of caretEnsemble yet.

I have used xgbtree in caretEnsemble and have noticed  2 things that concern me. 

It appears no faster than gbm when running in parallel. (I am using 56 cores) 
It has a very different varImp output to gbm. It has much higher weights to some of the features up to 5 times higher, which is different to any of the other models I have ensembled eg rf  svm. This surprised me.

PS great packages for testing machine learning options

**Comment by topepo** [comment]
> It appears no faster than gbm when running in parallel. (I am using 56 cores) 

That's a lot of cores. Do you really see any benefit after 10? 

> It has a very different varImp output to gbm. It has much higher weights to some of the features up to 5 times higher, which is different to any of the other models I have ensembled eg rf svm. This surprised me.

Its not exactly the same model so I would't expect exact parity to `gbm`. Also, it doesn't treat factor predictors the same way (it always uses dummy variables) and that can affect the model too. 

Did the model fit the data well?

**Comment by sparcycram** [comment]
#### That's a lot of cores. Do you really see any benefit after 10?

10 cores takes 27 min to run what runs in 15 min on 56 cores.

#### Did the model fit the data well?

median logloss on resamples using defaults on caretlist viz

_xgbTree = caretModelSpec(method = "xgbTree"),
   gbm0 = caretModelSpec(method = "gbm"),_

logloss
 gbm = 0.6445
xgbTree = 0.6485

Most important features
gbm VI_1 = 6.5
         VI_2 = 5.1
         VI_3 = 4.7

xgbTree VI_1 = 36.7
              VI_2 = 36.5
               VI_3 = 2.5 an order of magnitude drop?

So my take is no better than gbm and I don't trust the high variable importance scores

Will try Zachs reduced by = 500 suggestion when I get the server back

Thanks
