### ISSUE TITLE
What is the varImp mathematical calculation expression?

### ISSUE THREAD

**Issue by xiejiachen** [topepo/caret#473]
Hello , Anyone here can help about:
What is the mathematical expression to calculate the feature importance?
For an example, if we say importances for feature A is 5 and B is 1 with linear regression.
**How caret to get 5 and 1 exactly?**

**Comment by dashaub** [comment]
These are explained [here](https://topepo.github.io/caret/varimp.html). There are dozens of papers explaining proposed methodologies for each method. [Elements of Statistical Learning](http://statweb.stanford.edu/~tibs/ElemStatLearn/printings/ESLII_print10.pdf) explains it well in each section also. If you're curious specifically how "caret" calcluates importance, take a look at the [code](https://github.com/topepo/caret/blob/c65a05e4fc62a4f109a944b6178e1e328505c671/pkg/caret/R/varImp.R) and follow any functions from other packages.

**Comment by xiejiachen** [comment]
@dashaub  Thanks for your answer, I also wanna trying to read and understand the codes in caret varImp, but you know each function always do calculation by refer to other functions not in varImp.
I am... I am just do not have enough time to do that at currently, and hence trying to find some help. Anyway, I would like to try do it in the future. Thank you.
