### ISSUE TITLE
Model request glm.nb

### ISSUE THREAD

**Issue by Terry01** [topepo/caret#476]
If possible, I would find it very useful if glm.nb (from the Mass package) was added to caret 

Kind regards

Terry01

**Comment by topepo** [comment]
Give that a try. It tunes over the link function and, for my test cases, the identity link may produce errors (since the predictions are not constrained to be non-negative). Using `tuneLength = 1` will only evaluate the log link.

**Comment by Terry01** [comment]
Thank you very much
