### ISSUE TITLE
Ability to send additional data to trainControl's summaryFunction

### ISSUE THREAD

**Issue by timothyslong** [topepo/caret#478]
Hi Max, looking for a feature where one can pass additional data to the summaryFunction in trainControl for computing custom losses.  Today only the observed and predicted values are available for computing loss.  Thanks!

**Comment by topepo** [comment]
There is a new branch of the package ("recipe_integration") that I hope to merge in within two weeks that uses the [`recipes`](https://topepo.github.io/recipes/) package that can help here. An example of how the code works can be found [here](https://github.com/topepo/caret/commit/ef2ca41e5c341f7506c3361877a1d708e3dd5014#diff-adfc9c815ccf21ae160019a7721fe7da). 

If you take a look please let me know if you see any issues by posting something on the [project page](https://github.com/topepo/caret/projects/1).
