### ISSUE TITLE
Number of data points used to estimate lambda in Box-Cox transformations

### ISSUE THREAD

**Issue by sluijs** [topepo/caret#481]
Normally I perform Box-Cox transformations using the caret package in R, but when I used the forecast package, it gave me different lambda estimates. I think it's due to the amount of data points used to estimate lambda. Why does caret uses only 100 data points by default? Is it better or just quicker? 

```r
x <- sample(1:10, size = 100, replace = TRUE, prob = 10:1)
forecast::BoxCox.lambda(x)

# [1] -0.1138864

caret::BoxCoxTrans(x)

# Box-Cox Transformation

# 100 data points used to estimate Lambda

# Input data summary:
# Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
# 1.00    2.00    4.00    4.34    7.00   10.00 

# Largest/Smallest: 10 
# Sample Skewness: 0.454 

# Estimated Lambda: 0.3 
```

**Comment by topepo** [comment]
Our function is a wrapper around `MASS::boxcox`. It says "100 data points used to estimate Lambda" because you used `size = 100` when you generated the data.

**Comment by sluijs** [comment]
@topepo 
Oh my, I didn't read it properly. Do you have any other explanation for `MASS:boxcox` giving such a different result than `forecast::BoxCox.lambda`? Else I'll try the maintainers of these packages. Thanks!

**Comment by topepo** [comment]
I haven't looked at Rob's function, but the fractional number that `forecast` produces might be from doing a iterative search whereas, IIRC, `MASS` uses a grid search.
