### ISSUE TITLE
sbf() returns anomalous results with factors

### ISSUE THREAD

**Issue by JocelynBarker** [topepo/caret#483]
#### Problem description
I am not sure if this is more of a bug or a feature request, but I have had some difficulty with the `sbf()` function.  When I use the function on a dataframe containing factors there appears to be some strange data type conversion that occurs resulting in inappropriate results for the `lmSBF` functions (it ignores any non-factor variables).  Here is my best guess at the source of the error.  The error seems to occur somewhere between the call

`scores <- apply(x, 2, sbfControl$functions$score, y = y)`

in `sbfIter()` and when it is received by the `score` function of the `sbfControl` parameter.  In `sbfIter()` all the variables have their original datatypes, however when it is received by the `score` function all of the variables are converted to type `character`.  This happens with both the `lmSBF` functions and the `rfSBF` functions, however `rfSBF` still works and `lmSBF` does not.  I believe this is because `rfSBF$score()` calls either `anovaScores(x, y)` or `gamScores(x,y)` where as `lmSBF$score()` calls `anovaScores(y, x)` (y and x are reversed).  Either way, a number of warnings are thrown.  For `rfSBF` it is:

`In model.response(mf, "numeric") : NAs introduced by coercion`

and for `lmSBF` it is:

`In anova.lm(object) :`
`  ANOVA F-tests on an essentially perfect fit are unreliable`

Bellow is an example to reproduce the result.  Note that if the `sbf()` function is run with `x` instead of `xfact` in either of the examples below everything runs just fine and the same variables (`Var04 (14%)` and `Var02 (10%)`) are returned for both models.

#### Minimal dataset:
```{R}
library(caret)
set.seed(1)
dat <- caret::SLC14_1(100)
x <- dat[, 1:5]
x <- as.data.frame(x) #lmSBF requires x to be a dataframe
y <- dat$y
set.seed(10)
xfact <- x
xfact[["bogusLetters"]] <- LETTERS[sample(1:2, nrow(xfact), replace = TRUE)]
```

#### Minimal, runnable code:
```{R}
filterCtrl <- sbfControl(functions = rfSBF, method = "repeatedcv", repeats = 5)
set.seed(10)
rfWithFilterFact <- sbf(xfact, y, sbfControl = filterCtrl)
rfWithFilterFact

filterCtrl <- sbfControl(functions = lmSBF, method = "repeatedcv", repeats = 5)
set.seed(10)
lmWithFilterFact <- sbf(xfact, y, sbfControl = filterCtrl)
lmWithFilterFact
```

### Session Info:
```{R}
>sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] caret_6.0-62        ggplot2_2.0.0       lattice_0.20-33     RevoUtilsMath_3.2.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.2         magrittr_1.5        splines_3.2.3       MASS_7.3-45         munsell_0.4.2       colorspace_1.2-6   
 [7] foreach_1.4.3       minqa_1.2.4         stringr_1.0.0       car_2.1-1           plyr_1.8.3          tools_3.2.3        
[13] nnet_7.3-11         pbkrtest_0.4-4      parallel_3.2.3      grid_3.2.3          gtable_0.1.2        nlme_3.1-122       
[19] mgcv_1.8-9          quantreg_5.19       MatrixModels_0.4-1  iterators_1.0.8     randomForest_4.6-12 lme4_1.1-10        
[25] Matrix_1.2-3        nloptr_1.0.4        reshape2_1.4.1      codetools_0.2-14    gam_1.12            stringi_1.0-1      
[31] compiler_3.2.3      scales_0.3.0        stats4_3.2.3        SparseM_1.7        
```

#### Possible solutions

If the function is not designed to work with factors that is understandable, though since most other `caret` functions do, it would be nice if it threw and error to inform the user.  If support for factors is desired it could potentially be fixed using `model.matrix` to convert the factors into numeric values (though that may interfere with proper functioning of `anova` since it assumes independence and the new factor variables would not be independent).  Ideally the variables would just keep their class when passed to the `score` function, but I am not sure how that would be fixed since it seems to happen somewhere in the apply function.

**Comment by topepo** [comment]
> I am not sure if this is more of a bug or a feature request

A little of both =]

The solution is either to implement the formula method to `sbf` (and `rfe`) or to make the scoring function more intelligent. The latter might be better but there would have to be some consistency in the results between numeric and factor predictors. Although p-values can be used, there still might be a bias between the two methods. 

For now, I've added some error trapping. Let me know if you have any suggestions or would like to volunteer. 

Thanks,

Max
