### ISSUE TITLE
[Documentation Enhancement]: Include reference in "Random Hyperparameter Search"...

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#486]
Hello,

I have just seen your remodeled page with all the relevant documentation about [caret ](http://topepo.github.io/caret/index.html), thanks a lot for this change and congratulations for the effort, it is already ready to be edited as a book...

Although the solution relies in a external package `rBayesianOptimization`, I think it could be very positive to include either a reference to your recent [post](http://blog.revolutionanalytics.com/2016/06/bayesian-optimization-of-machine-learning-models.html) or even including an equivalent (less detailed) example of what you developed in that post.

Thanks again,
Carlos.

**Comment by topepo** [comment]
We're working on integrating that into the package (but will take a little time). I'm hesitant to add code or documentation on a topic that I'm not currently supporting. That's been an issue in the past.

**Comment by coforfe** [comment]
OK.
Thanks for the clarification. 
We will stay tuned...
