### ISSUE TITLE
[New Model]: monmlp: Monotone Multi-Layer Perceptron Neural Network

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#489]
Hello,

This package `monmlp` , a variation of a kind of deep neural network, is available in [CRAN](https://CRAN.R-project.org/package=monmlp) and it has already reached a stable version (1.1.3).

Some examples of how to use it are described in this [book](http://www.auscov.com/deep-learning-made-easy-with-r-vol-ii.html).

It could be a good candidate to extend `caret` capabilities related to _deep learning_.

Thanks,
Carlos.

**Comment by topepo** [comment]
There was some weirdness in the `To` parameter of `monmlp.fit`. I would have thought that chasing it to `logistic` would have constrained predictions to be on [0, 1]. Right now, it seems to work but further testing would be a big help.
