### ISSUE TITLE
[New Model]: kernDeepStackNet: Kernel Deep Stacking Networks

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#490]
Hello,

This package `kernDeepStackNet`  is another kind of deep neural network algorithm. It is available in [CRAN](https://CRAN.R-project.org/package=kernDeepStackNet).

Some examples of how to use it are described in this [book](http://www.auscov.com/deep-learning-made-easy-with-r-vol-ii.html).

Thanks,
Carlos.

**Comment by topepo** [comment]
Is there any other documentation on this besides the book (or maybe a worked example)? The package documentation isn't vey detailed on it.

**Comment by coforfe** [comment]
Thanks.

I have just sent to your gmail account a reference for a working example.

Thanks,
Carlos.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.
