### ISSUE TITLE
Gini and logLoss Goodness of Fit function

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#494]
It could be nice to have user - exposed functions like Gini and logLoss as $R^2$ and $RMSE$ showing the same sintax es. Gini(act=, pred=) and logLoss(act=, pred=). Possible souces to grab from are [logLoss](https://www.kaggle.com/wiki/LogarithmicLoss) and [Normalized Gini](https://www.kaggle.com/wiki/RCodeForGini)

**Comment by topepo** [comment]
log-loss is already in the package. Do you know another package with Gini or would you like to write your own? I probably won't get to it for a while.

**Comment by spedygiorgio** [comment]
I can provide a function based on the linked one and propose a pull request. 

Would you like an Rcpp one? 

Sent from my ASUS

-------- Messaggio originale --------
Da:Max Kuhn <notifications@github.com>
Inviato:Mon, 26 Sep 2016 14:57:23 +0200
A:topepo/caret <caret@noreply.github.com>
Cc:Giorgio Alfredo Spedicato <spedygiorgio@gmail.com>,Author <author@noreply.github.com>
Oggetto:Re: [topepo/caret] Gini and logLoss Goodness of Fit function (#494)

**Comment by topepo** [comment]
Either way (Rcpp or not) is fine.

**Comment by JackStat** [comment]
There is a `gini` function in ModelMetrics built using Rcpp

**Comment by spedygiorgio** [comment]
@JackStat implementation in ModelMetric development is fine, my issue can be closed
