### ISSUE TITLE
non-default parameters in nzv method (preProcess function)

### ISSUE THREAD

**Issue by lumatt** [topepo/caret#495]
Is there a way to provide non-default parameters (freqCut, uniqueCut) to nzv method inside preProcess function? I tried sth like this: 
preProcess(data, method = c("center", "scale", "medianImpute", "nzv"), na.remove = TRUE, freqCut = 10)
but didn't work.

**Comment by topepo** [comment]
Not right now. It is on the feature list but might take a while unless you want to make a PR

**Comment by topepo** [comment]
I did this on the train last night and added another filter for highly correlated predictors. It will be in the next CRAN version

**Comment by lumatt** [comment]
Thank you!

2016-10-25 15:37 GMT+02:00 Max Kuhn <notifications@github.com>:
