### ISSUE TITLE
Error occured when using prSummary for imbalanced data

### ISSUE THREAD

**Issue by kstseng** [topepo/caret#496]
Example is an artificial imbalanced data, I want to do stratified cross validation and use precision-recall AUC as my evaluation metric.

The process is that I use createFolds to do stratified sampling(I use 2 folds), and use `index` and `indexOut` in `trainControl`. 

The error occur when I use prSummary, the data in prSummary only use 10 sample, because of the imbalance, there is only one class in these 10 sample, so the `ROCR::prediction(y_pred, y_true)` encounter the error.

I am confused with this error, because I have specified the `index` and `indexOut`, so it shouldn't have the issue of only one class in my dataset.

The following is a reproducible example. Thank in advance
#### Minimal dataset:
```{R}
library(randomForest)
library(mlbench)
library(caret)

# Load Dataset
data(Sonar)
dataset <- Sonar
x <- dataset[,1:60]
y <- dataset[,61]
# make this data very imbalance
y[4:length(y)] <- "M"
y <- as.factor(y)
dataset$Class <- y

# create index and indexOut 
set.seed(seed)
folds <- 2
idxAll <- 1:nrow(x)
cvIndex <- createFolds(factor(y), folds, returnTrain = T)
cvIndexOut <- lapply(1:length(cvIndex), function(i){
  idxAll[-cvIndex[[i]]]
})
names(cvIndexOut) <- names(cvIndex)

# set the index, indexOut and prSummaryCorrect
control <- trainControl(index = cvIndex, indexOut = cvIndexOut, 
                        method="cv", summaryFunction = prSummary, classProbs = T)
seed <- 1
metric <- "AUC"
set.seed(seed)
mtry <- sqrt(ncol(x))
tunegrid <- expand.grid(.mtry=mtry)
rf_default <- train(Class~., data=dataset, method="rf", metric=metric, tuneGrid=tunegrid, trControl=control)
```

**Comment by kstseng** [comment]
Even I use `prSummary`, I still encounter the problem.

**Comment by kstseng** [comment]
I think I found the weird thing, when the performance evaluation is ongoing, it will computer a size 10 of sample at first, like testing(I am not sure)
After this sample is done, it will then use the index I specified to compute the performance.

**Comment by topepo** [comment]
You are correct; `train` does an initial test of the summary function code to make sure that it returns the correct data format. 

I just checked in some code that resolves the issue by sampling from the levels instead of the observed data. 

Please test.
