### ISSUE TITLE
Override the default behavior of "pca" in preProcess

### ISSUE THREAD

**Issue by ajing** [topepo/caret#499]
For the train() function in caret, the argument preProcess accepts a string vector. The behavior of "pca" is

"If PCA is requested but centering and scaling are not, the values will still be centered and scaled. " in preProcess()

Is there any way to override this behavior? I don't want the data to be scaled.

**Comment by topepo** [comment]
No, not directly, but you can write a [custom method](https://topepo.github.io/caret/using-your-own-model-in-train.html#Illustration4) to do it.
