### ISSUE TITLE
Feature request: resamples-type function for predictions on test set

### ISSUE THREAD

**Issue by zross** [topepo/caret#513]
This is a spectacularly useful package and this is not a critical feature request -- it's a "nice to have". I am teaching a class on predictive modeling with R and we're using `caret` extensively. The `caret` package saves so much work teaching the subtleties of specific packages etc.

In my sections on regression, classification etc I do something similar to what you do in your book -- run a bunch of models on training and then predict on test (of course). It would be nice to have a function like `resamples` that takes all the models and applies predictions to a test set along the lines of something like this:

```r
lm1 <- train(....., method = "lm")
svm1 <- train(...., method = "svmRadial")
rf1 <- train(...., method = "rf")

mod_list <- list(lm = lm1, svm = svm1, rf = rf1)
pred_res <- pred_compare(mod_list, newdata = testing)
# and then the result with show RMSE or Kappa or whatever
```

Thank you for your consideration!

**Comment by topepo** [comment]
Have you seen `extractPrediction` and `extractProb`? That generates the model predictions for a single data set across a list of models. Right now there isn't any summarization function to compute performance measures from those. It would be nice to have a tidy implementation of that.

**Comment by zross** [comment]
Somehow I did miss that! I appreciate it. And yes it would be nice to have a tidy implementation, but this saves a ton of code. Thanks and sorry to have not noticed before.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
