### ISSUE TITLE
Wrong reference in http://topepo.github.io/caret/model-training-and-tuning.html

### ISSUE THREAD

**Issue by boxuancui** [topepo/caret#515]
Page: http://topepo.github.io/caret/model-training-and-tuning.html 

When clicking on **Model Training and Parameter Tuning** section under content, it is directing users to **Models with Built-In Feature Selection** section.

I was checking the source and found the following line:

    <a href="feature-selection-overview.html#builtin">Model Training and Parameter Tuning</a>

By investigating further, and found out that both tags are `#builtin`. Maybe renaming one of them is going to solve the problem?

**Comment by topepo** [comment]
I've made the change and will update the website along with the next caret version. 

Thanks
