### ISSUE TITLE
BRT train error

### ISSUE THREAD

**Issue by yazheli** [topepo/caret#519]
Hello I am trying use the code below to train a boosted regression tree by CV of AUC.
But I were got the message:
Error in { : task 1 failed - "subscript out of bounds"

If I didn't specify distribution="gaussian", I will not receive the error message.

Any ideal to fix this problem? Thank you very much.
```{r}
gbmGrid <- expand.grid(interaction.depth=(3:6), n.trees=(1:40)*100, shrinkage=.01)
gbmGrid$n.minobsinnode = rep(10,nrow(gbmGrid))
head(gbmGrid)

bootControl <- trainControl(method='cv',classProbs = TRUE,number=3,summaryFunction = twoClassSummary)

gmbFit<- caret::train(X,Y,
                      distribution="gaussian",
                      method = "gbm", 
                      verbose = F, 
                      trControl = bootControl, 
                      bag.fraction=0.5,
                      metric="ROC",
                      tuneGrid=gbmGrid)
```

**Comment by visnaga** [comment]
I did not run your code, but I am confused about  using AUC for a regression problem. From my understanding, AUC  & hence two class summary are for classification two classes problems only.
 Please correct me if I am wrong.

**Comment by visnaga** [comment]
You are welcome.

I think the correct approach is to convert the response to factor and check the class probabilities from the predictions that are returned from the train function and that will be a classification problem.

to convert the response to factor, assuming you want the positive response as default:
response <- factor(ifelse(response == 0, 'noDefault', 'default'), levels=c('default', 'noDefault))

also, in the trainControl, use savePredictions = T.

**Comment by yazheli** [comment]
@visnaga This is the code I use, for produce X and Y. However, it didn't work.
`index = sample(1:nrow(sample_set[[i]]), floor(nrow(sample_set[[i]])/10), replace=FALSE)#use 10% data for training
train = sample_set[[i]][index,]
test = sample_set[[i]][-index,]
train$def_flag = as.factor(as.logical(train$def_flag))
test$def_flag = as.factor(as.logical(test$def_flag))

X = train[,-8]
Y = train[,8]
Y = as.numeric(Y)
Y[which(Y==1)] = 'no'
Y[which(Y==2)] = 'yes'`

**Comment by visnaga** [comment]
I think using caret to get 10% stratified sample is better to make sure that your training set has the same distribution of the response of the original data set.

assuming that the original data set in your session is names sample_set:
`
sample_set$def_flag <- factor(ifelse(sample_set$def_flag == 0, 'noDefault', 'default'), levels=c('default', 'noDefault'))
inTrainRows <- createDataPartition(sample_set$def_flag, p=.1)[[1]] 
training <- sample_set[inTrainRows, ]
testing <- sample_set[-inTrainRows, ]
`
Hope that helps.

**Comment by yazheli** [comment]
@visnaga oops, still not work.
If you are interested in, may I send the data set and the code to you?

**Comment by visnaga** [comment]
ok np.

**Comment by yazheli** [comment]
@visnaga please use this link for data set.
[https://drive.google.com/file/d/0Byv0IbN-OIPrOUs4SzJIR042N00/view?usp=sharing](url)

code is 
This version works well, but I think this Boosted decision tree, which I don't want.
```{r}
index = sample(1:nrow(sample_set), floor(nrow(sample_set)/10), replace=FALSE)
train = sample_set[index,]
test = sample_set[-index,]
train$def_flag = as.factor(as.logical(train$def_flag))
test$def_flag = as.factor(as.logical(test$def_flag))

X = train[,-8]
Y = train[,8]
Y = as.numeric(Y)
Y[which(Y==1)] = 'no'
Y[which(Y==2)] = 'yes'

gbmGrid <- expand.grid(interaction.depth=(3:6), n.trees=(1:10)*100, shrinkage=.01)
gbmGrid$n.minobsinnode = rep(10,nrow(gbmGrid))
head(gbmGrid)

bootControl <- trainControl(method='cv',classProbs = TRUE,number=3,summaryFunction = twoClassSummary)

gmbFit<- caret::train(X,Y,
                      method = "gbm", 
                      verbose = F, 
                      trControl = bootControl, 
                      bag.fraction=0.5,
                      metric="ROC",
                      tuneGrid=gbmGrid)
plot(gmbFit)
```

If I specify distribution="gaussian", not work.
```{r}
gbmGrid <- expand.grid(interaction.depth=(3:6), n.trees=(1:10)*100, shrinkage=.01)
gbmGrid$n.minobsinnode = rep(10,nrow(gbmGrid))
head(gbmGrid)

bootControl <- trainControl(method='cv',classProbs = TRUE,number=3,summaryFunction = twoClassSummary)



gmbFit<- caret::train(X,Y,
                      distribution="gaussian",
                      method = "gbm", 
                      verbose = F, 
                      trControl = bootControl, 
                      bag.fraction=0.5,
                      metric="ROC",
                      tuneGrid=gbmGrid)
```

**Comment by visnaga** [comment]
The problem is the levels of the classes are TRUE and FALSE which is not accepted by gbm.

use the following code :


```
index = sample(1:nrow(sample_set), floor(nrow(sample_set)/10), replace=FALSE)
train = sample_set[index,]
test = sample_set[-index,]
train$def_flag = as.factor(as.logical(train$def_flag))
test$def_flag = as.factor(as.logical(test$def_flag))

X = train[,-8]
Y = train[,8]
# change the levels from TRUE/FALSE to default_TRUE, default_FALSE
Y <- as.character(Y)
Y <- factor(paste0('default_', Y))

gbmGrid <- expand.grid(interaction.depth=(3:6), n.trees=(1:10)*100, shrinkage=.01)
gbmGrid$n.minobsinnode = rep(10,nrow(gbmGrid))
head(gbmGrid)

bootControl <- trainControl(method='cv',classProbs = TRUE,number=3,summaryFunction = twoClassSummary)

gmbFit<- caret::train(X,Y,
                      method = "gbm", 
                      verbose = F, 
                      trControl = bootControl, 
                      bag.fraction=0.5,
                      metric="ROC",
                      tuneGrid=gbmGrid)
plot(gmbFit)
```

**Comment by visnaga** [comment]
and also note that Gaussian distribution is used only in regression problems and this is a classification one.

**Comment by yazheli** [comment]
That work's well, Thank you so much.

**Comment by topepo** [comment]
Should this issue be closed?

**Comment by yazheli** [comment]
Sure, Thank you
