### ISSUE TITLE
Error in train function of caret "Error in `[.data.frame`(data, , all.vars(Terms), drop = FALSE) :    undefined columns selected"

### ISSUE THREAD

**Issue by BinhNguyen2** [topepo/caret#521]
Hello,

I'd like to seek your help to fix an error which is happening with the train function of the package 'caret' on R.  Provided the same dataset, the following code runs smoothly on my old computer of the Windows 32-bit operating system and the R version 3.3.0. However, when I run the same thing using a new computer of the Windows 64-bit operating system, the current R version 3.3.2 and the latest version of caret, this error "Error in `[.data.frame`(data, , all.vars(Terms), drop = FALSE) :    undefined columns selected" happen. Could you please advise on how to get this fixed. Many thanks, Binh Nguyen.

ctrl <- trainControl(method="repeatedcv", number=10, repeats=5, search = "grid")

tunegrid <- expand.grid(.mtry=c(1:10))

set.seed(1016)

custom <- train(trainset$Segment ~ ., data = trainset[-c(1,2)],
                   method = "rf",  
                   metric = "Accuracy",tuneGrid=tunegrid, 
                   trControl = ctrl)

**Comment by topepo** [comment]
I don't have the data so it is hard to tell. You probably don't want to use the formula method with the data frame name. Try using `Segment ~ ., data = trainset[-c(1,2)]` instead.

**Comment by BinhNguyen2** [comment]
Many thanks for your speedy reply.

Removing the data frame name didn't work.

The 2 computers differ in the operating system, the R version and the caret
version. Therefore, I tested the following 2 options using the new computer:

   - Using the latest R version for the 32-bit operating system and the
   latest version of caret
   - The error still happens.
   - Using the latest R version for the 64-bit operating system and the
   previous version of caret
   - The code runs smoothly but 'Accuracy' and 'Kappa' are a little bit
      lower than the same model in my old computer.

I will test several models and embed the final one into a web app on Shiny.
I hope it will work well with the previous caret version.

Warm Regards,

Binh

**Comment by topepo** [comment]
Providing a reproducible example would allow is to troubleshoot.

**Comment by BinhNguyen2** [comment]
I enclose the code and sample data. It would be great if you could
troubleshoot.

Many Thanks,

Binh

**Comment by topepo** [comment]
I don't see any data. You can always send it to `mxkuhn@gmail.com` if you don't want to post it here.

**Comment by AkthemRehab** [comment]
I am having the same issue as you BinhNguyen2 . Please let me know if you found a fix other than rolling back the caret package to an older version.

I would also appreciate your help in rolling back a package to an older version. You can always reach me at akthem@gmail.com

**Comment by topepo** [comment]
Providing a reproducible example would allow is to troubleshoot.

**Comment by AkthemRehab** [comment]
Thanks topepo for the speedy reply. I found a fix/workaround for the issue. I am attaching the code and data for you to cross validate. (Please note that this is an exercise in one of the MOOC courses):
-OS: Windows 10
- R x64 3.3.2
- R Studio Version 1.0.136

The data sets used are already present in R and here is the code chunk:
-----
library(caret)
library(AppliedPredictiveModeling)
data(AlzheimerDisease)
adData = data.frame(diagnosis,predictors)
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]

newtraining <- training[, c(names(training)[grep("^IL",colnames(training))], "diagnosis")]
newtesting <- testing[, c(names(testing)[grep("^IL",colnames(testing))], "diagnosis")]

preProc <- preProcess(newtraining**[,-13]**, method = "pca", thresh = 0.8)
trainPC <- predict(preProc, newtraining**[,-13]**)
testPC <- predict(preProc, newtesting**[,-13]**)

PCModel <- train(diagnosis~., data = trainPC, method = "glm")
NonPCModel <- train(diagnosis~., data = newtraining, method = "glm")
-----
By removing the [,-13] in bold above, the code works just fine. I was thinking that in previous versions of caret, adding the [,-13] would run smoothly.

Much appreciate your support and thoughts. Many thanks.

**Comment by wangruinju** [comment]
I met the same problem with those errors. Also check your code in Rstudio Version 1.0.136
still generates error like the following
Error in model.frame.default(form = diagnosis ~ ., data = trainPC, na.action = na.fail) : 
variable lengths differ (found for 'PC1')

**Comment by wangruinju** [comment]
`library(caret)
library(AppliedPredictiveModeling)

set.seed(3433)
data(AlzheimerDisease)
adData = data.frame(diagnosis,predictors)
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]
# get the data with column names started with IL
New_training <- data.frame(training[,grep('^IL',names(training))],training$diagnosis)
New_testing <- data.frame(testing[,grep('^IL',names(testing))],testing$diagnosis)

# non-PCA
NotPCFit <- train(training.diagnosis ~.,data = New_training, method="glm")
NotPCTestPredict <- predict(NotPCFit, New_testing[, -13])
confusionMatrix(New_testing$testing.diagnosis, NotPCTestPredict)

# PCA
preProc <- preProcess(New_training[, -13],method="pca",thresh=.8)
trainPC <- predict(preProc, New_training[, -13])
testPC <- predict(preProc, New_testing[, -13])

PCFit <- train(New_training$training.diagnosis ~.,data= trainPC, method="glm")
PCTestPredict <- predict(PCFit, testPC)
confusionMatrix(New_testing$testing.diagnosis, PCTestPredict)
`
Here is my code, still have issues
Would you please help check it?

**Comment by wangruinju** [comment]
`library(caret)
library(AppliedPredictiveModeling)
set.seed(3433)
data(AlzheimerDisease)
adData = data.frame(diagnosis,predictors)
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]
# get the data with column names started with IL
New_training <- data.frame(training[,grep('^IL',names(training))],training$diagnosis)
New_testing <- data.frame(testing[,grep('^IL',names(testing))],testing$diagnosis)
# non-PCA
NotPCFit <- train(training.diagnosis ~.,data = New_training, method="glm")
NotPCTestPredict <- predict(NotPCFit, New_testing[, -13])
confusionMatrix(New_testing$testing.diagnosis, NotPCTestPredict)
# PCA
preProc <- preProcess(New_training[, -13],method="pca",thresh=.8)
trainPC <- predict(preProc, New_training[, -13])
testPC <- predict(preProc, New_testing[, -13])
PCFit <- train(New_training$training.diagnosis ~.,data= trainPC, method="glm")
PCTestPredict <- predict(PCFit, testPC)
confusionMatrix(New_testing$testing.diagnosis, PCTestPredict)`
Here is my code, could you please help check that?

**Comment by wangruinju** [comment]
It seems that the last column of the data used in `train` function need to be diagnosis. 
so just need to add one column data to the new data after `preProcess`, then apply`train`

**Comment by topepo** [comment]
I see the issue now. Yes, you can add the outcome to the `trainPC` object. 

However, a much better way of approaching this would be to do the preprocessing _during_ resampling via:
```r
set.seed(13)
PCFit <- train(training.diagnosis ~.,
               data = New_training, 
               method ="glm",
               preProc = "pca",
               trControl = trainControl(preProcOptions = list(thresh = 0.8)))
```
The reasons are:
* it will automatically preprocess the data and assemble the features and outcome (and also do this on new data being predicted). The code is a lot cleaner and less subject to issues.
* the variation caused by PCA is included in resample (i.e. the PCA loadings are recalculated for every resample as well as the final time on the entire training set). Doing PCA outside of sampling will give the resampling results an optimistic bias although it is hard to say how much).

**Comment by wangruinju** [comment]
That looks neat and nice. Thanks for the explanation.

**Comment by AkthemRehab** [comment]
Thank you guys. Topepo your code is looking smooth and easier to comprehend. Will go with that in future models/exercises.

Much appreciated!

**Comment by lalitpanwar10086** [comment]
library(caret)
library(AppliedPredictiveModeling)
data(AlzheimerDisease)
adData = data.frame(diagnosis,predictors)
inTrain = createDataPartition(adData$diagnosis, p = 3/4)[[1]]
training = adData[ inTrain,]
testing = adData[-inTrain,]

newtraining <- training[, c(names(training)[grep("^IL",colnames(training))], "diagnosis")]
newtesting <- testing[, c(names(testing)[grep("^IL",colnames(testing))], "diagnosis")]

preProc <- preProcess(newtraining[,-13], method = "pca", thresh = 0.8)
trainPC <- predict(preProc, newtraining[,-13])
testPC <- predict(preProc, newtesting[,-13])

## The addition of preProcess = "pca" will exclude the need of creating preProcess model 
## and we can directly predict the dependent variable through this PCModel
PCModel <- train(diagnosis~., data = newtraining[,-13], method = "glm", preProcess = "pca")

**Comment by amanyiraho** [comment]
Hello there; I was reading through, but can someone explain to me what the line 
`newtraining <- training[, c(names(training)[grep("^IL",colnames(training))], "diagnosis")]` 
does. I am not understanding.

Please help me out on that

**Comment by dris-thinker98** [comment]
I'm facing the same problem with gbm:

set.seed(13)
control <- trainControl(method="repeatedcv",number = 15, repeats = 3)
install.packages("gbm")
library(gbm)
feature_model <- train(pd_data$status~., 
                       data = pd_data1, 
                       method = "gbm", 
                       preProcess = "scale", 
                       trControl = control)
importance <- varImp(feature_model, scale=FALSE)
print(importance)

Error:
Error in `[.data.frame`(data, , all.vars(Terms), drop = FALSE) : 
  undefined columns selected
