### ISSUE TITLE
SPLSDA Method error

### ISSUE THREAD

**Issue by ttuti** [topepo/caret#527]
I keep getting the error message
_

> Model splsda is not in caret's built-in library

_

from the following code:

                   ctrl=trainControl(method="repeatedcv",
                    repeats=5,
                    number=10,
                    classProbs=T,
                    summaryFunction=twoClassSummary,
                    returnResamp="all",
                    allowParallel=T)
  
 
                   train.model=train(x=dataset.x.tr,
                    y=dataset.y.tr,
                    method="splsda",
                    trControl=ctrl,
                    tuneLength=10,
                    probMethod="Bayes",
                    preProc=c("center","scale"))

What might be wrong?

**Comment by MosMK** [comment]
Try sparseLDA instead of splsda.

check available models from http://topepo.github.io/caret/available-models.html

**Comment by topepo** [comment]
It is invoked using `spls`: 
```r
> names(getModelInfo("pls"))
 [1] "enpls.fs"      "enpls"        
 [3] "gpls"          "kernelpls"    
 [5] "ORFpls"        "pls"          
 [7] "plsRglm"       "simpls"       
 [9] "spls"          "widekernelpls"
```

I (usually try to) make the `method` the same as the function name.
