### ISSUE TITLE
Changing activation function in dnn

### ISSUE THREAD

**Issue by sparcycram** [topepo/caret#531]
Is there anyway to change the activationfunction on dnn in caret?

I have tried using activationfun = "linear" from  package deepnet in both tuneGrid = expand.grid(...., activationfun = "linear") and in trControl.

Neither worked. Am I doing something wrong or is this functionality not available?

Thanks

**Comment by topepo** [comment]
[The method](https://github.com/topepo/caret/blob/master/models/files/dnn.R) isn't parameterized for changing that right now. You can use the existing code to create a [custom method](https://topepo.github.io/caret/using-your-own-model-in-train.html). Pull requests are always welcome too =]
