### ISSUE TITLE
Getting beta coefficients  from pls methods

### ISSUE THREAD

**Issue by ttuti** [topepo/caret#538]
How do I get beta coefficients from pls model using the caret package? And is it possible to get an **_additive_** plot of variance in Y explained by each additional X variable included in the model?

**Comment by topepo** [comment]
You can do this using the `finalModel` component of `train`. Most of what you are asking for comes from the `pls` package, so take a close look at that. 
```r
library(caret)
library(pls)

data(yarn)

set.seed(1)
yarn.pls <- train(density ~ NIR, data = yarn, method = "pls",
                  tuneLength = 6, preProc = c("center", "scale"))

yarn.pls$finalModel # the pls model
coef(yarn.pls$finalModel) # etc etc
```

**Comment by ttuti** [comment]
Thank you for this. it is very useful. Final, clarification, is it possible to get the p-values with the coefficients?

**Comment by topepo** [comment]
Maybe, I don't know. the `pls` package would be the place to look

**Comment by zachmayer** [comment]
Try `summary(model$finalModel)`  I know if you use `method='lm'` or  `method='glm'`, that gives p-values for the final model coefficients.  Maybe pls works the same way.

Regardless, `model$finalModel` gives you the final pls model.  You can then do whatever you want with it.  Use the [manual for the pls package](https://cran.r-project.org/web/packages/pls/pls.pdf) as a reference.
