### ISSUE TITLE
Feature request: Add iteration progress status when verbose is TRUE

### ISSUE THREAD

**Issue by boxuancui** [topepo/caret#542]
When I do parameter tuning, I always train a lot of models using either `cv` or `repeatedcv`. In the case when model takes a long time to train, and each iteration produces a lot of output, I often lose track of the progress. It will be nice to print some progress status before each iteration, e.g.,

    Running iteration 1 out 100:
    Iter   TrainDeviance   ValidDeviance   StepSize   Improve
       1          1.3779             nan     0.1000    0.0042
       2          1.3707             nan     0.1000    0.0035
     ...
    
    Running iteration 2 out 100:
    Iter   TrainDeviance   ValidDeviance   StepSize   Improve
       1          1.3779             nan     0.1000    0.0042
       2          1.3707             nan     0.1000    0.0035
     ...

**Comment by topepo** [comment]
That is difficult to do since we don't fit every submodel in some cases. It looks like you might be using `gbm`. If so, use `verbose = FALSE` to avoid getting the extra output from the underlying function. Also, use `verboseIter = TRUE` in `trainControl`.
