### ISSUE TITLE
hyperband - hyperparameter optimization

### ISSUE THREAD

**Issue by smsaladi** [topepo/caret#548]
`hyperband` is a recently proposed hyperparameter optimization method. Based on a talk I saw and the results reported in the paper, it looks pretty promising. In particular, it's nice because it works by  terminating early with bad parameters which is great when trying to optimize across multiple parameters. Is there a way to implement this in/through caret?

https://people.eecs.berkeley.edu/~kjamieson/hyperband.html

https://arxiv.org/abs/1603.06560

**Comment by topepo** [comment]
It looks pretty cool. The [adaptive resampling](https://topepo.github.io/caret/adaptive-resampling.html) approach does something philosophically similar but using completely different means. 

Like adaptive resampling, this would require another workflow. That is doable but a fair amount of work. I might shoot for this in the week between the holidays.

**Comment by topepo** [comment]
I'm going to close this but it is on my medium term to-do list. Thanks
