### ISSUE TITLE
Feature reqest: add PDF generation to the Bookdown documentation

### ISSUE THREAD

**Issue by znmeb** [topepo/caret#553]
I just learned of the documentation site on Twitter and through a little research landed here. ;-) I'd like to request a downloadable PDF for the documentation site. Since it's Bookdown, I can probably fork the repo and add the code myself, which is what I'll do if nobody else chimes in.

**Comment by topepo** [comment]
The documentation takes quite a long time to generate and I've cleared the caches form the last run. A few people have asked for this so I will add some code for the next release. You're welcome to give it a go; there might be some formatting that could be done instead of me simply adding:
```r
bookdown:::render_book("index.Rmd", output_format = "bookdown::pdf_book")
```

**Comment by znmeb** [comment]
I've forked the project and I'm in the process of getting the build running. Is there a script somewhere that installs all the CRAN packages you're using?

**Comment by topepo** [comment]
I think that [this one](https://github.com/topepo/caret/blob/master/release_process/update_pkgs.R) contains damn near everything. It will take a while. I haven't tested to see if anything is missing so please let me know. 

I would also suggest omitting the files `10-Sampling.Rmd`, `11-Custom-Models.Rmd`, `12-Adaptive-Resampling.Rmd`, `19-GA.Rmd`, and `20-SA.Rmd` when you initially test. Those take a while to run.

**Comment by topepo** [comment]
I'm going to close this. Please reopen if you have any issues. A PR would be great if you get this worked out in an elegant way.
