### ISSUE TITLE
[New Model]: msgl (High Dimensional Multiclass Classification Using Sparse Group Lasso)

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#562]
Hello,

This algorithm (`multiclass classification`) is available in CRAN since 2015 and seems to be specially suitable to _p>>n_ cases :

**msgl**: High Dimensional Multiclass Classification Using Sparse Group Lasso

Multinomial logistic regression with sparse group lasso penalty. Simultaneous feature selection and parameter estimation for classification. Suitable for high dimensional multiclass classification with many classes.

Link in CRAN: **[msgl](https://cloud.r-project.org/web/packages/msgl/index.html)**

Thanks,
Carlos.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.
