### ISSUE TITLE
Feature Request: Allow custom sampling for train for regression problems

### ISSUE THREAD

**Issue by camdenhu** [topepo/caret#570]
I would like to apply custom sampling functions to the training set for my regression problem, (e.g. Undersampling samples with y = 0).

This throws an error that "sampling methods are only implemented for classification problems".

I am not sure about the implementation and am wondering if simply removing the following line of error checking will solve the issue.

if (modelType != "Classification" & !is.null(trControl$sampling)) 
        stop("sampling methods are only implemented for classification problems")

**Comment by topepo** [comment]
I'm pretty sure that the underlying sampling functions would not work with numeric outcomes. 

You would have to write a [custom method](https://topepo.github.io/caret/using-your-own-model-in-train.html) and modify the `fit` component (which shouldn't be too hard).

**Comment by camdenhu** [comment]
What do you mean by the underlying sampling functions?

I know they would not work with "down", etc. Would they work if I pass in a list (to the sampling argument) with name, func and first, where func would handle numeric y?

**Comment by topepo** [comment]
> What do you mean by the underlying sampling functions?

`train` uses [sampling functions](https://topepo.github.io/caret/subsampling-for-class-imbalances.html) in `caret`, `DMwR`, and `ROSE` to do the additional subsampling. 

> Would they work if I pass in a list (to the sampling argument) with name, func and first, where func would handle numeric y?

No, I don't think so. I'm skeptical about removing the check to see if the outcomes are factors. The testing involved and the potential for people to accidentally misuse the feature are not small.

**Comment by camdenhu** [comment]
Ok understood about possible misuse. I will make the change locally.
Why would you not expect it to work if the check is removed?
The following lines in createModel seem like they would work for the regression case as well.
```
tmp <- sampling$func(x, y)
x <- tmp$x
y <- tmp$y
rm(tmp)
```

**Comment by topepo** [comment]
> Why would you not expect it to work if the check is removed?

Many of the subsampling functions either 1) split the data by class level before subsampling or 2) use the class variable to impute/synthesize new data. Either way, they tend to use the `levels` of the expected factor

**Comment by camdenhu** [comment]
Yes understood about the default ones. I am talking about custom functions that handle numeric y.
I have already tried it with the check removed, and it appears to work. I will close the issue now.
