### ISSUE TITLE
`predict` fails if formula method is used with deleted variables

### ISSUE THREAD

**Issue by adatum** [topepo/caret#574]
In a multi-class classification problem, trying to get the class probabilities from a model object trained with the formula method with deleted variables (i.e. `-variable`) fails with `predict` when `newdata` is not specified. 

Reproducible example:
```
fit.lda <- train(Species ~ . -Petal.Length, 
  data = iris, 
  preProcess = c("center", "scale"), 
  trControl = trainControl(method = "repeatedcv", 
    number = 10, 
    repeats = 3, 
    classProbs = TRUE, 
    savePredictions = "final", 
    selectionFunction = "best", 
    summaryFunction = multiClassSummary), 
  method = "lda", 
  metric = "Mean_F1")
```
then

`predict(fit.lda, type = "prob")`

fails with:

> Error in predict.lda(modelFit, newdata) : wrong number of variables

If the `-Petal.Length` is omitted in the `train` formula, there is no error. 

This error occurs for some models (`lda`, `knn`, `svmRadial`, `mlpML`) but not others (`nnet`, `rf`, `xgbTree`).

=====

**Workaround** 

If `newdata` is specified with the training data, it seems to succeed in retrieving the class probabilities. Is this the correct way of doing it? 

In the documentation for `predict`: 

> `newdata`: an optional set of data to predict on. If NULL, then the original training data are used

In the past, I always omitted `newdata` for obtaining information from the trained model, and included the parameter when using on new testing data.

**Comment by adatum** [comment]
I'm not sure the workaround is correct. According to http://stats.stackexchange.com/a/112052/130941 `predict` might behave differently depending on whether `newdata` is specified or not.

**Comment by topepo** [comment]
This should work find in the devel version and also the one that I just sent to CRAN.
