### ISSUE TITLE
Bug: imputation does not work in train

### ISSUE THREAD

**Issue by adatum** [topepo/caret#575]
For data with missing values, imputing with either `knnImpute`, `bagImpute`, or `medianImpute` (in the `preProcess` argument of `train`) just results in omitting the rows with missing data, or failing with an error due to them. i.e. imputation is not done.

Using the `preProcess()` function outside of `train` works as expected to impute missing data and not drop rows. However, doing this preprocessing outside of repeated cross validation loops doesn't seem conceptually correct, as it would be like having access to "future" data to figure out the imputed values. 

This bug seems to be years old, and a number of StackOverflow questions have addressed this. Eg:

http://stackoverflow.com/questions/20054906/carettrain-values-not-imputed

http://stackoverflow.com/questions/39619913/missing-value-error-when-using-bagimpute-preprocessing-within-carettrain-funct

Is there a workaround? Any chance of getting a bug fix?

**Comment by topepo** [comment]
The answer in the [first link](http://stackoverflow.com/questions/20054906/carettrain-values-not-imputed) explains the issue and the solution (as does the man page for `predict.train`)

**Comment by adatum** [comment]
:) Remembering to include `na.action = na.pass` in `predict` works. I could have sworn I tried it... Thanks for the pre-emptive "bug fix". :D 

On a side note, is there a way to specify what data is used (or excluded) in preprocessing when it is done in `train`?

**Comment by topepo** [comment]
> On a side note, is there a way to specify what data is used (or excluded) in preprocessing when it is done in train?

If you mean which samples are used, then no. It uses the same resamples as the model. Did you mean which columns are pre-processed?

**Comment by adatum** [comment]
Yes, I mean selecting which columns are pre-processed. I.e. Is it possible to exclude some columns from pre-processing within `train` while pre-processing other columns, but still use all columns to train the models?

**Comment by topepo** [comment]
_Yes_, there is but it has not been extensively tested. You can use a list to make the specification:
```r
set.seed(100)
dat <- twoClassSim(100)

methods <- list(ignore = "Class",
                center = c("TwoFactor1", "TwoFactor2"),
                scale = c("Linear01", "Linear02"),
                spatialSign = c("Nonlinear1", "Nonlinear2", "Nonlinear3"))
pp <- preProcess(dat, method = methods)
pp

new_data <- predict(pp, dat)
head(dat)
head(new_data)
```
Use at your own risk and, if you do, please let me know if you see any weirdness or bugs

**Comment by adatum** [comment]
Fantastic! Can `train`'s `preProcess` argument also accept a similar list?

**Comment by topepo** [comment]
Yes. I meant to say that.

**Comment by adatum** [comment]
What would the syntax look like? This does not work:

```
set.seed(100)
dat <- twoClassSim(100)

methods <- list(ignore = "Class",
                center = c("TwoFactor1", "TwoFactor2"),
                scale = c("Linear01", "Linear02"),
                spatialSign = c("Nonlinear1", "Nonlinear2", "Nonlinear3"))
model <- train(Class ~ .,
               data = dat,
               preProcess = methods,
               method = "rf")
```

> Error in train.default(x, y, weights = w, ...) : 
>   pre-processing methods are limited to: BoxCox, YeoJohnson, expoTrans, invHyperbolicSine, center, scale, range, knnImpute, bagImpute, medianImpute, pca, ica, spatialSign, ignore, keep, remove, zv, nzv, conditionalX, corr

**Comment by topepo** [comment]
Small bug fix that I just fixed. Also, if you want to run that code, get rid of the `ignore = "Class"` line. Experimental!

**Comment by statisticsguru1** [comment]
For reasons known to the author, using preProcess inside the train functions,to impute your data,assumes that you want to impute your predictors(Just check the documentation of train function).

preProcess outside caret imputes the whole data including the response. I find this awkward at times, its less likely to find a data whose response has no missing values but the predictors has, in real life
