### ISSUE TITLE
Error: "too many ties in knn" when using `search = random` for tuning

### ISSUE THREAD

**Issue by adatum** [topepo/caret#582]
```
Error in { : task 1 failed - "too many ties in knn"
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In eval(expr, envir, enclos) :
  predictions failed for Fold01.Rep1: k=946 Error in knn3Train(train = structure(c(1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,  : 
  too many ties in knn
```

This error comes up only when I use `search = random` in `trainControl`. When using the default grid search, and also adaptive search, there is no problem. 

The part of the warning saying `k=946` caught my eye: is this k referring to the k neighbors in knn? If so, why is it choosing such a large number?  The other warnings all have large k values too, like 802, 829, 919, etc.

**Comment by topepo** [comment]
Can you provide a reproducible example and the results of `sessionInfo()`?

**Comment by adatum** [comment]
I tried several sample classification data sets like `iris`, `Sonar`, `scat`, `Sacramento`, but unfortunately I could not reproduce the issue for an example. It seems "too many ties in knn" issue can be specific to the data, but my surprise is that it happens (with my data) only with random search and not with grid search, and only with `knn`. With my same data, random search works fine for `rf`, `nnet`, `svmRadial`, `mlpML`.

Also the large k values listed in the warnings seem suspicious (if they are the k in knn). With grid search the final selected k values are small (i.e. k<10). Could you perhaps point me to the code for random search in knn3Train? Maybe that would give clues.

In case it's any help: my data has a 9-class response variable, and is being trained with six numerical predictors, one 2-level categorical predictor, and one 14-level categorical predictor. With the formula method for `train` automatically converting to dummy variables, I suspect that turns into 20 predictors (6 + (2-1) + (14-1)), so not too high in dimensions.

**Comment by topepo** [comment]
It could be that you have many predictors in your data with the exact same pattern so too many ties. 

For the large value of `k`, the knn code (adapted from the `class` package) will increase `k` when there are ties to find a tiebreaker. Take a look at `?knn3`, which describes an argument `use.all` that can be used to adjust the behavior. I've never used it, but it seems like it might help and you can pass it to `knn3` by passing it as an argument to `train`.

**Comment by adatum** [comment]
Passing the argument `use.all = TRUE` in `train` still resulted in the same error with high `k` values. 

How can I test if I have many predictors with the same pattern? I did check the correlations between the numerical predictors and none were above abs(0.6), most much lower.

Can random search be limited in the range of values it considers? Grid search chooses k=5... I think there was a previous feature request for combining grid and random searches.

**Comment by topepo** [comment]
> How can I test if I have many predictors with the same pattern? 

You can probably use `duplicated` on your predictor set

> Can random search be limited in the range of values it considers? 

Yes. The function creates a tuning grid using
```r
if(search == "grid") {
  out <- data.frame(k = (5:((2 * len)+4))[(5:((2 * len)+4))%%2 > 0])
} else {
  by_val <- if(is.factor(y)) length(levels(y)) else 1
  out <- data.frame(k = sample(seq(1, floor(nrow(x)/3), by = by_val), size = len, replace = TRUE))
}
out
```
You can create your own random grid in a similar way and pass it to `tuneGrid`.

**Comment by adatum** [comment]
Interesting. This explains how the large `k` values are obtained. I substituted some values like `nrow(x)` by `3000`, `by_val` by `9`, `len` by `15`. The result is:

```
set.seed(42)
data.frame(k = sample(seq(1, floor(3000/3), by = 9), size = 15, replace = TRUE))
```

>      k
> 1  919
> 2  937
> 3  289
> 4  838
> 5  640
> 6  523
> 7  739
> 8  136
> 9  658
> 10 703
> 11 460
> 12 721
> 13 937
> 14 253
> 15 460

Especially with large `nrow(x)`, large `k` might be expected. Is this the desired behavior?

Btw, `sum(duplicated(training))` resulted in just `1`.

**Comment by topepo** [comment]
> Is this the desired behavior?

Yes. I've had some problems that showed increasing performance as `k` increased into the hundreds. Again, YMMV so you can always use `tuneGrid` to create your own.

**Comment by adatum** [comment]
Ok, but why increase `k` with data set rows?

Also, why is `replace = TRUE`? When would re-testing the same `k` value make sense?

`tuneGrid` combined with adaptive resampling worked nicely, and this data set seems to like `k = 1` best.

**Comment by topepo** [comment]
`k` increases with n since the model has more capacity to fit. `replace = TRUE` is an oversight, probably from copy/paste. I'll fix that.

**Comment by adatum** [comment]
Thanks. I'll close this issue since 1) the large `k` values are intentional by design, 2) the errors are due to particularities of a specific data set, and 3) it is possible to work around issues with `tuneGrid`.
