### ISSUE TITLE
new model type - vsurf

### ISSUE THREAD

**Issue by smsaladi** [topepo/caret#591]
Have you considered adding VSURF (Variable Selection under Random Forests) to the available models in caret?

https://cran.r-project.org/web/packages/VSURF/VSURF.pdf

Is there a procedure to contribute something like this?

**Comment by topepo** [comment]
> Is there a procedure to contribute something like this?

I would suggested using github and making a pull request. 

For the model, you can look at the [existing model code](https://github.com/topepo/caret/tree/master/models/files) (esp the `rf.R` file) and modify an existing method.

**Comment by topepo** [comment]
I'll close this for now but please let me know if you have any issues with a PR.
