### ISSUE TITLE
Two-parameter Box-Cox for zero values?

### ISSUE THREAD

**Issue by amueller** [topepo/caret#594]
This is a question and not an issue but I though I'd rather drop you an issue than an email.
In your book and in carret it seems you're doing the one-parameter box-cox transformation. That doesn't work for zero values. I was wondering if you have any advice on what a good default strategy is for zero values and if you think the two-parameter box-cox transformation is a good way to deal with them.

I'm mostly asking for designing the box-cox transformation for scikit-learn (https://github.com/scikit-learn/scikit-learn/pull/6781) and I'd welcome your advice. Needing non-zero values will likely tempt users to add an epsilon, and I'm not sure if that's a good solution.

**Comment by topepo** [comment]
I would suggest using the Yeo-Johnson transformation (Yeo, I. K., and Johnson, R. A. (2000). A new family of power transformations to improve normality or symmetry. Biometrika). I discovered it about 2 weeks after the book was published =[

It is basically Box Cox but works for any real values. The likelihood is easy to optimize too. I almost never use Box-Cox anymore. `caret`'s `preProcess` function has a method called "YeoJohnson" for that.

**Comment by amueller** [comment]
Oh wow. Thank that's great advice! Glad I asked. Maybe I can put that into my lecture...
