### ISSUE TITLE
varImp inquiry

### ISSUE THREAD

**Issue by ronencozen** [topepo/caret#597]
Hi,

I am fitting some training data that originate from a data frame with the following structure:

df <- data.frame(
year = ordered(year, levels=2013:2016),
month = ordered(month, levels=c("Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")),
week = ordered(week, levels=1:53),
wday = ordered(wday, levels=c("Sun","Mon","Tues","Wed","Thurs","Fri","Sat")),
mday = ordered(mday, levels=1:31),
hour = ordered(hour, levels=0:23))
)

after running the varImp() function of the fitted model i am getting the following list:

         Overall
hour.L  100.0000
hour.C   75.6811
hour.Q   50.7864
hour^5   43.7292
hour^4   40.6021
year.L    3.6077
year.C    3.6077
year.Q    3.4412
hour^11   2.6553
hour^6    2.5910
month.L   1.4662
yday      1.4662
wday.Q    1.4597
week.L    1.4185
wday.L    1.4132
month.C   1.0193
mday.L    0.9569
mday^30   0.9106
month^5   0.8817
week^33   0.7985

why in some cases a period (.) is used to append the factor level to the variable name and in other cases the caret (^) is used.
Also some of the levels were decoded to letters, is it possible to avoid this and if not what is the mapping between letters and the actual numbers.

Thanks!

**Comment by topepo** [comment]
The issues is that they are ordered. See [this post](http://appliedpredictivemodeling.com/blog/2013/10/23/the-basics-of-encoding-categorical-data-for-predictive-models) about how R wants to encode ordered factors. I've never really felt that this was a great idea (especially for the types of examples that you have) so you might want to make them unordered factors to get more traditional dummy variables.

**Comment by ronencozen** [comment]
Thanks!
