### ISSUE TITLE
p parameter of create data partition to accept a vector

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#604]
Currently train index is used to split data between two set: train and test. If p could accept a vector, e.g., p=c(.8,.1), it could be possible to split data into train, validation and test (1-.8-.1) like in h2o's package splitFrame function. Is it possible to implement this?

**Comment by topepo** [comment]
I would suggest using the `modelr` function
```r
> modelr::resample_partition(mtcars, c(test = 0.3, train = 0.5, other = .2))
$test
<resample [9 x 11]> 3, 7, 18, 20, 22, 24, 28, 31, 32

$train
<resample [16 x 11]> 1, 4, 5, 6, 8, 9, 10, 12, 16, 21, ...

$other
<resample [7 x 11]> 2, 11, 13, 14, 15, 17, 19
```

**Comment by spedygiorgio** [comment]
Good suggestions, but it is a pity to load another package
