### ISSUE TITLE
Example were `findLinearCombos` does not find linear dependencies

### ISSUE THREAD

**Issue by hmf** [topepo/caret#607]
I am attempting  to port the code that identifies linear dependent columns to Java/Scala. More specifically I am coding the function `internalEnumLC` found in [findLinearCombos.R](https://github.com/topepo/caret/blob/master/pkg/caret/R/findLinearCombos.R). To test this I created a matrix with one column being the linear combination of another 3. More specifically I have: 

    v3 = (v1 * 56.03) + (v2 * 89.309) + (v5 * 0.9077)
 
I then executed my code that did indeed find these columns, but surprisingly Caret's implementation did not find the solution. I suspect it may be a case of numeric stability due to the QR decomposition algorithm used. I am using the [Java matrix toolkits](https://github.com/fommil/matrix-toolkits-java). This library uses the [Java netlib API](https://github.com/fommil/netlib-java) that calls the LAPACK/BLAS functions in [NetLib](http://netlib.org/). Initially I attempted to use the [Apache Math Commons library](http://commons.apache.org/proper/commons-math/apidocs/org/apache/commons/math4/linear/QRDecomp), but its implementation of the QR decomposition algorithm failed with the simple example shown in [Caret's documentation](http://topepo.github.io/caret/pre-processing.html#lindep]) - rank was incorrectly determined.

### Minimal, reproducible example:

As per the instruction I checked for the latest update used a new session.
  
#### Minimal dataset:
```{R}
library("caret")

deps = matrix(
  c(1.01,  0.03,  119.61,  1.00,  66.06,
    10.01,  0.04,  654.65,  0.00,  98.90,
    20.02,  0.02,  1221.51,  0.00,  107.71,
    300.03,  0.03,  16913.50,  1.00,  110.01,
    5.06,  0.04,  348.42,  0.00,  67.08,
    6.06,  0.06,  425.57,  0.00,  88.87), 6, 5, byrow = TRUE)
deps
```
which shows:

```{R}
       [,1] [,2]     [,3] [,4]   [,5]
[1,]   1.01 0.03   119.61    1  66.06
[2,]  10.01 0.04   654.65    0  98.90
[3,]  20.02 0.02  1221.51    0 107.71
[4,] 300.03 0.03 16913.50    1 110.01
[5,]   5.06 0.04   348.42    0  67.08
[6,]   6.06 0.06   425.57    0  88.87
```

#### Minimal, runnable code:

Note that column 3 is a linear combination of columns 1,2 and 5. So I think that at least one of the  following two calls should yield the expected result.  

```{R}
findLinearCombos(deps)
findLinearCombos(deps[,c(1,2,5)])
```
but I get 

``` {R}
$linearCombos
list()

$remove
NULL
```
To show that in fact we have a linear combination we calculate the values of column 3:

``` {R}
coeffs = matrix(c(56.03, 89.309, 0.9077), 3, 1)
deps[,c(1,2,5)] %*% coeffs
```
which gives us:

``` {R}
          [,1]
[1,]   119.2322
[2,]   654.2042
[3,]  1221.2751
[4,] 16913.2162
[5,]   347.9727
[6,]   425.5676
```

Not exactly the values we expect, but they seem quite close. To check how close I did:

``` {R}
deps[,3] - (deps[,c(1,2,5)] %*% coeffs)
```
and got:

``` {R}
         [,1]
[1,] 0.377768
[2,] 0.445810
[3,] 0.234853
[4,] 0.283753
[5,] 0.447324
[6,] 0.002361
```
### Session Info:
```{R}
> sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.2 LTS

locale:
 [1] LC_CTYPE=pt_PT.UTF-8       LC_NUMERIC=C               LC_TIME=pt_PT.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_PT.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=pt_PT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=pt_PT.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] caret_6.0-73    ggplot2_2.2.1   lattice_0.20-34

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9        magrittr_1.5       splines_3.3.2      MASS_7.3-45        munsell_0.4.3      colorspace_1.3-2  
 [7] foreach_1.4.3      minqa_1.2.4        stringr_1.2.0      car_2.1-4          plyr_1.8.4         tools_3.3.2       
[13] parallel_3.3.2     nnet_7.3-12        pbkrtest_0.4-6     grid_3.3.2         gtable_0.2.0       nlme_3.1-131      
[19] mgcv_1.8-16        quantreg_5.29      MatrixModels_0.4-1 iterators_1.0.8    lme4_1.1-12        lazyeval_0.2.0    
[25] assertthat_0.1     tibble_1.2         Matrix_1.2-8       nloptr_1.0.4       reshape2_1.4.2     ModelMetrics_1.1.0
[31] codetools_0.2-15   stringi_1.1.2      scales_0.4.1       stats4_3.3.2       SparseM_1.74      
```
So I have the following (related) questions:

1. Given the matrix I created can we expect to find the collinear columns (albeit with some error in reconstruction) as shown? Note that in my implementation I use is the LAPACK `dgeqp3` function and test for equality with an _eps_ of 1e-12.

2. In the Caret code we have:
```  
b <- qr.coef(b, Y)                # get regression coefficients of
# the dependent columns
```
Assuming the columns are correctly identified, do each of the `b` columns represent the coefficients of the linear combinations? I have done some test on simple matrices and it seems so, but for this case I get coefficients: 

```
 0,01
-0,01
-0,63
``` 

which is nothing like the values I used. Calculating the linear combination with these coefficients also does not yield the expected values (I check this in my code and it unexpectedly it passes - must be a bug on my side but cannot find it).  

3. Finally, is there any reference to an article or book that explains the algorithm used by Caret?
 
TIA

**Comment by hadjipantelis** [comment]
Hello @hmf, I think you are misinterpreting what `findLinearCombos` implements and how linear combinations are defined within its context. The matrix shown (`deps`) is [full-rank](https://en.wikipedia.org/wiki/Rank_%28linear_algebra%29) so the function correctly says that no linear combinations are present. The differences you quote (`deps[,3] - ( (deps[,1] * 56.03) + (deps[,2] * 89.309) + (deps[,5]* 0.9077))`) are actually "large" numerically speaking, given the magnitude of the other values in `deps`, you probably want differences way below 10e-10 to hit numerical issues there. Just to be clear, the matrix `deps` is [ill-conditioned](https://en.wikipedia.org/wiki/Condition_number) (ratio of the largest singular value of that matrix to the smallest singular value is quite large ~10e7) but otherwise it is fine numerically in terms of linear dependencies because it is full-rank; `findLinearCombos` does what is should do and there are not bugs/issues in this example.

**Comment by hmf** [comment]
In regards to question 2 above it seems like a numeric issue. For the record, I stated that the coefficients I got were:

```{R}
 0,01
-0,01
-0,63
```
If I use that to check if the linear combination is ok I do:
```{R}
ndep = matrix(c(
c(119.61,  66.06,  1.01),
c(654.65,  98.90,  10.01),
c(1221.51,  107.71,  20.02),
c(16913.50,  110.01,  300.03),
c(348.42,  67.08,  5.06),
c(425.57,  88.87,  6.06)), 6, 3, byrow = TRUE)

depc = matrix(c(0.03, 0.04, 0.02, 0.03, 0.04, 0.06), 6, 1)

ncoeffs = matrix(c(0.01, -0.01, -0.63), 3, 1)
(ndep %*% ncoeffs) - depc
```
where `ndep` are the independent columns and `depc` is the dependent column (values that I must get), I get:
```{R}
         [,1]
[1,]  -0.1308
[2,]  -0.7888
[3,]  -1.4946
[4,] -21.0140
[5,]  -0.4144
[6,]  -0.5108
```
Those errors are pretty high, hence my doubt if my implementation is in accordance with Caret's (Caret did not find a solution). But the values of `depc` are truncated (via the printing), so I now use the values at a higher precision:  

```{R}
ncoeffs = matrix(c(0.011197079801587299, -0.010163589335900749, -0.6273723812829365), 3, 1)
(ndep %*% ncoeffs) - depc
```
which gives me:

```{R}
             [,1]
[1,] 4.229898e-03
[2,] 4.991770e-03
[3,] 2.629668e-03
[4,] 3.177205e-03
[5,] 5.008723e-03
[6,] 2.643631e-05
```
better but I expected errors less that 1e-12.

**Comment by hmf** [comment]
@hadjipantelis thanks for taking the time to answer. Finally figured it out. From my checks in my last comment and your input I see now the problem is that I am not printing the values to full precision. Once I do that, all is ok:

```{R}
deps = matrix(c(
  c(1.012000000000000000000000000000, .033000000000000000000000000000, 119.612219000000010000000000000000, 1.000000000000000000000000000000, 66.060000000000000000000000000000), 
  c(10.010000000000000000000000000000, .045000000000000000000000000000, 654.650735000000000000000000000000, .000000000000000000000000000000, 98.900000000000000000000000000000), 
  c(20.021100000000000000000000000000, .022000000000000000000000000000, 1221.512674900000000000000000000000, .000000000000000000000000000000, 107.707000000000000000000000000000), 
  c(300.030300000000000000000000000000, .033000000000000000000000000000, 16913.502707630003000000000000000000, 1.000000000000000000000000000000, 110.011900000000000000000000000000), 
  c(5.060000000000000000000000000000, .045000000000000000000000000000, 348.419221000000000000000000000000, .000000000000000000000000000000, 67.080000000000000000000000000000), 
  c(6.060000000000000000000000000000, .060000000000000000000000000000, 425.567639000000000000000000000000, .000000000000000000000000000000, 88.870000000000000000000000000000)), 
  6, 5, byrow = TRUE)

findLinearCombos(deps)
```
gives me:
```{R}
$linearCombos
$linearCombos[[1]]
[1] 5 1 2 3


$remove
[1] 5
```
And your code:

```{R}
(deps[,3] - ( (deps[,1] * 56.03) + (deps[,2] * 89.309) + (deps[,5]* 0.9077))) 
```
gives me 
```
[1] 0 0 0 0 0 0
```
which is equivalent to the code I used:

```{R}
coeffs = matrix(c(56.03, 89.309, 0.9077), 3, 1)
deps[,3] - (deps[,c(1,2,5)] %*% coeffs)
```
which gives me:
```
             [,1]
[1,] 1.421085e-14
[2,] 0.000000e+00
[3,] 0.000000e+00
[4,] 0.000000e+00
[5,] 0.000000e+00
[6,] 0.000000e+00
```
Anyway you can close this issue?

Thanks once again.

**Comment by hadjipantelis** [comment]
You have to close the issue yourself; I cannot unfortunately. 

Regarding a reference: I think it will be hard to find because in general rank deficient matrices are considered almost be definition to be matrices where the columns are linear combinations of each other (or they have zero singular values). All these are considered almost equivalent so the search will be a bit tautological. The algorithm to "resolve" linear combinations is a simple iterative procedure where the columns are iteratively removed and the matrix rank is rechecked, I doubt that someone has actually written down this in a paper. Maybe @topepo (Max Kuhn) has come across something, you might try asking this in [CrossValidated](http://stats.stackexchange.com/) as a reference request question. More eyeballs, more chances someone has come across a reference.

**Comment by hmf** [comment]
@hadjipantelis Thank you
