### ISSUE TITLE
Does caret not play well with tibbles?

### ISSUE THREAD

**Issue by rsangole** [topepo/caret#611]
I found that passing a tibble dataframe to functions in caret (I've used preProcess and Train so far) results in bad things.

For example, `preProcess(mtcars,method = 'BoxCox')` works perfectly.

> Created from 32 samples and 9 variables
> Pre-processing:
>   - Box-Cox transformation (9)
>   - ignored (0)
> Lambda estimates for Box-Cox transformation:
> 0, 1, 0.2, 0.1, -0.1, 0.5, -0.2, -1.5, 0.1`

But, 
`df <- tbl_df(mtcars)`
`preProcess(df,method = 'BoxCox')` fails:

> Error in predict.BoxCoxTrans(bc[[i]], x[, i]) : 
>   newdata should be a numeric vector

I almost exclusively use tibbles and the tidyverse. I can convert using `data.frame(df)`, but is this an expected behavior, or am I doing something wrong?

**Comment by cbonsig** [comment]
I discovered the same issue with gbm, when applying the methods explained here http://amunategui.github.io/binary-outcome-modeling/ with my own (tidyverse managed) data. This problem is discussed in issue 145 https://github.com/topepo/caret/issues/145 ... tl;dr: just coerce to a standard data.frame

**Comment by rsangole** [comment]
Thanks @cbonsig . Closing the issue based on the discussion you've pointed me to.
