### ISSUE TITLE
Install warning in knn3 function (unused index)

### ISSUE THREAD

**Issue by RobertKomara** [topepo/caret#616]
Caret install warning: function knn3
================

Running Dev Caret 6.0-75
------------------------

Hi! I am getting this install warning when installing the dev version from Github:
**In function 'knn3':...: warning: variable 'index' set but not used**. This was mentioned in issue #271, but closed because of lack of error documentation. I do not use `knn3` and thus do not know if this effects the function or not, but thought I would mention it again with a example. If this is still deemed a non-issue please close this at will. 

``` r
remove.packages('caret')
```

    ## Removing package from 'C:/Users/*******/Documents/R/win-library/3.3'
    ## (as 'lib' is unspecified)

``` r
devtools::install_github('topepo/caret/pkg/caret')
```

    ## Downloading GitHub repo topepo/caret@master
    ## from URL https://api.github.com/repos/topepo/caret/zipball/master

    ## Installing caret

    ## "C:/PROGRA~1/MIE74D~1/MRO-33~1.2/bin/x64/R" --no-site-file --no-environ  \
    ##   --no-save --no-restore --quiet CMD INSTALL  \
    ##   "C:/Users/*******/AppData/Local/Temp/RtmpSkBTJr/devtoolsb3ac306e166/topepo-caret-539d5d2/pkg/caret"  \
    ##   --library="C:/Users/*******/Documents/R/win-library/3.3"  \
    ##   --install-tests

    ## * installing *source* package 'caret' ...
    ## ** libs
    ## c:/Rtools/mingw_64/bin/gcc -m64 -I"C:/PROGRA~1/MIE74D~1/MRO-33~1.2/include" -DNDEBUG     -I"C:/swarm/workspace/External-R-3.3.2/vendor/extsoft/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c caret.c -o caret.o
    ## caret.c: In function 'knn3':
    ## caret.c:23:14: warning: variable 'index' set but not used [-Wunused-but-set-variable]
     int   i, index, j, k, k1, kinit = *kin, kn, l = *lin, mm, npat, ntie,
              ^
    ## c:/Rtools/mingw_64/bin/gcc -m64 -shared -s -static-libgcc -o caret.dll tmp.def caret.o -LC:/swarm/workspace/External-R-3.3.2/vendor/extsoft/lib/x64 -LC:/swarm/workspace/External-R-3.3.2/vendor/extsoft/lib -LC:/PROGRA~1/MIE74D~1/MRO-33~1.2/bin/x64 -lR
    ## installing to C:/Users/*******/Documents/R/win-library/3.3/caret/libs/x64
    ## ** R
    ## ** data
    ## ** inst
    ## ** tests
    ## ** preparing package for lazy loading
    ## ** help
    ## *** installing help indices
    ## ** building package indices
    ## ** installing vignettes
    ## ** testing if installed package can be loaded
    ## * DONE (caret)
    ## Reloading installed caret
    ## Attaching package: ‘caret’

    ## The following object is masked from ‘package:survival’:

    ##     cluster

``` r
library(caret)
```

    ## Loading required package: lattice

    ## Loading required package: ggplot2

### Session Info:

``` r
sessionInfo()
```

    ## R version 3.3.2 (2016-10-31)
    ## Platform: x86_64-w64-mingw32/x64 (64-bit)
    ## Running under: Windows 10 x64 (build 10586)
    ## 
    ## locale:
    ## [1] LC_COLLATE=English_United Kingdom.1252 
    ## [2] LC_CTYPE=English_United Kingdom.1252   
    ## [3] LC_MONETARY=English_United Kingdom.1252
    ## [4] LC_NUMERIC=C                           
    ## [5] LC_TIME=English_United Kingdom.1252    
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] caret_6.0-75         ggplot2_2.1.0        lattice_0.20-34     
    ## [4] RevoUtilsMath_10.0.0
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] Rcpp_0.12.7        nloptr_1.0.4       formatR_1.4       
    ##  [4] git2r_0.15.0       plyr_1.8.4         iterators_1.0.8   
    ##  [7] tools_3.3.2        digest_0.6.10      lme4_1.1-12       
    ## [10] evaluate_0.10      memoise_1.0.0      gtable_0.2.0      
    ## [13] nlme_3.1-128       mgcv_1.8-15        Matrix_1.2-7.1    
    ## [16] foreach_1.4.3      parallel_3.3.2     curl_2.2          
    ## [19] yaml_2.1.13        SparseM_1.72       withr_1.0.2       
    ## [22] httr_1.2.1         stringr_1.1.0      knitr_1.14        
    ## [25] MatrixModels_0.4-1 RevoUtils_10.0.2   devtools_1.12.0   
    ## [28] stats4_3.3.2       rprojroot_1.1      grid_3.3.2        
    ## [31] nnet_7.3-12        R6_2.2.0           rmarkdown_1.3     
    ## [34] minqa_1.2.4        reshape2_1.4.2     car_2.1-3         
    ## [37] magrittr_1.5       splines_3.3.2      backports_1.0.4   
    ## [40] scales_0.4.0       codetools_0.2-15   ModelMetrics_1.1.0
    ## [43] htmltools_0.3.5    MASS_7.3-45        pbkrtest_0.4-6    
    ## [46] colorspace_1.2-7   quantreg_5.29      stringi_1.1.2     
    ## [49] munsell_0.4.3

**Comment by topepo** [comment]
What is strange is that lines 110-128 have
```c
	if (l > 0)
	    mm = l - 1 + extras;
	else
	    mm = 0;
	index = 0;
	for (i = 1; i <= *nc; i++){
	    if (votes[i] > mm) {
		ntie = 1;
		index = i;
		mm = votes[i];
	    } else if (votes[i] == mm && votes[i] >= l) {
		if (++ntie * UNIF < 1.0)
		    index = i;
	    }

		all_vote[npat*(*nc) + (i-1)] = (double)votes[i]/(kinit+extras);
	}
	
    }
```

**Comment by RobertKomara** [comment]
It's clearly in the code. Are there any messages related to this when you make and test the package? If not that may suggest it is some esoteric installation compiler problem. I am grasping at straws here.

**Comment by topepo** [comment]
I'm going to close this. I get the same warning on `R CMD check` and will just assume that it is a false alarm.

**Comment by RobertKomara** [comment]
Sounds reasonable. Thanks for looking into it.
