### ISSUE TITLE
boot632 working with index, indexOut and indexFinal?

### ISSUE THREAD

**Issue by slfan2013** [topepo/caret#617]
I found that the `indexOut` and `index` are not working well with `boot632`. Seems `boot632` always uses the full set as hold-out, even I set `indexOut`. `cv` is fine.

Please fun following code.
```
pacman::p_load(R.utils, caret, doParallel)

cl <- makeCluster(8, outfile="")
registerDoParallel(cl)

set.seed(2)
dat <- twoClassSim(48842)
fit_on <-  list(rs1 = 1:1300, rs2 = 4:1600,         rs3 = 7:9000)
pred_on <- list(rs1 = 4:9, rs2 = c(1:3, 7:9), rs3 = 1:6)
indexFinal = 1:1000

fitControl <- trainControl(method = "boot632",number=1,repeats=1
                           , classProbs = TRUE,summaryFunction = twoClassSummary,
                           index= fit_on, indexOut = pred_on,
                           indexFinal = indexFinal,
                           verboseIter = TRUE,
                           savePredictions = TRUE
                           )
  
  model = train(Class ~ ., data = dat, 
        method = "rf",
        preProcess=c("center","scale"),
        trControl = fitControl,
        tuneLength = 10)

  model$pred

stopCluster(cl)
```
As you can see, the `model$pred`'s `Resample` is `Alldata`. If you change the `"boot632"` to`"cv"`, then the result changes to `rs1`, `rs2` and `rs3`, which is desired.

**Comment by topepo** [comment]
To compute that bootstrap estimator, one extra model must be created using the full training set. I wouldn't mess with the `index` options for this particular resampling method.

**Comment by slfan2013** [comment]
Thank you @topepo .

I have one more thing that I don't fully understand about the `index` and `indexFinal`. When `preProcess=c("center","scale","zv")`, does this pre-processing procedure influence **both** `index` and `indexFinal`? Does the information of  `Pre-processing: centered (61), scaled (61), remove (39) ` come from the `indexFinal`?

**Comment by topepo** [comment]
>  does this pre-processing procedure influence both `index` and `indexFinal`

The don't really affect those. The preprocess is executed by whatever data points are captured by `index` and later applied to that set as well as those generated by `indexFinal`. 

>  Does the information of `Pre-processing: centered (61), scaled (61), remove (39)` in the output come from the` indexFinal`?

Yes.

**Comment by slfan2013** [comment]
Thanks Max.
