### ISSUE TITLE
How to build model with RFE?

### ISSUE THREAD

**Issue by gezmi** [topepo/caret#619]
I am not sure, whether I have understood RFE correctly. If I use RFE with traincontrol and RFE control, I get a model object (let's say, rfe). However, rfe$finalModel is NULL. 
Do I have to extract rfe$optVariables and train a a new model to get a usable SVM model?

Thank you!

**Comment by topepo** [comment]
Providing a small, reproducible example and the results of `sessionInfo()` would help answer the question.

**Comment by topepo** [comment]
Please reopen this when you can share some data to troubleshoot.
