### ISSUE TITLE
Mutiprocessing training with doMC failing

### ISSUE THREAD

**Issue by hjpbarcelos** [topepo/caret#62]
I'm running `R version 3.1.1 (2014-07-10)` with `caret@6.0-35` for training a model.

I have a huge database (over 160k lines) and I need to run this as multicore otherwise it wold take too much time to complete the tasks.

This is the script I'm running.

``` R
library(doMC)
registerDoMC(cores = 4)
ctrl <- trainControl(method="repeatedcv", repeats = 3, classProbs = T)
plsFit <- train(class ~ ., data=training, method="pls", tuneLength = 15, trControl = ctrl, metric="ROC", preProc = c("center","scale"))
```

At the end of the training proccess (after more than 30 minutes), I get the following message:

> Error in names(resamples) <- gsub("^\.", "", names(resamples)) : 
>   attempt to specify an attribute in a NULL

I have tried with different kinds of algorithms with MC and always ended up with this error. Some days ago I was running without the MC library and didn't see anything like that.

**Comment by kelaub** [comment]
Same problem occurred for me using RStudio Server on Ubuntu. However, restarting the r session helped for me.

**Comment by edumucelli** [comment]
I had the exact issue several times until recently. I am using the latest version of caret. It appeared randomly. For instance, it produced the aforementioned error for an execution of the training, but not for the next one using the same training code + data (i.e., after the error occurred I would just type up-arrow -- to get the previous command again -- and execute flawlessly).

One thing I have seen is that it happens when I am training with a lot of data using `doMC`, e.g., millions of rows, even though the number of features is small (~ 20).

What seems like to have fixed it is to use `doParallel` library instead of `doMC`, e.g., 

```
library(doParallel)
registerDoParallel(cores=6)
```

**Comment by AghaMehrdad** [comment]
Hi Zach and Max,

I use doAzureParallel and got the same error when trainning the model with CARET: 
Error in names(resamples) <- gsub("^\\.", "", names(resamples)) 

The code has nothing special, it loads a relatively large dataset (2Million rows and 33 predictors), and pass it to train function, BreakStatus is binary target value:

GeoSat <- train( BreakStatus ~ ., tuneLength=5, method = "ranger", data=newtrain, 
                    trControl = trainControl(method="cv", number= 5, summaryFunction = twoClassSummary, classProbs = TRUE,verboseIter = TRUE),
                    preProcess=c("pca","zv","center","scale")
)


I have followed the steps in the doAzureParallel and repeated it in two machines. The process begins and it runs for 7 minutes and then it breaks. It runs on an 8 or 4 core computer (local) and the Azure nodes are around 4 in the beginning (They may grow up to 60).

What additional information do you need? Do you want the dataset or a special report? Please let me know. If you have a big dataset, please pass it to me to try on my side and confirm that still there is an error before you would try.

Best regards,

Mehrdad

**Comment by topepo** [comment]
The issue template has detailed descriptions of what would be helpful. What version of `caret` did you use?

**Comment by AghaMehrdad** [comment]
Hi Max, May I ask where I can find the "issue template"?

**Comment by topepo** [comment]
When you start a new issue, there is a template for providing a good submission. The markdown is [here](https://github.com/topepo/caret/blob/master/.github/ISSUE_TEMPLATE.md).

**Comment by kchaitanyabandi** [comment]
I have the same problem as @Mehrdad Varedi had. I am running train function for gbm. It works fine if I have a normal parallel backend like doSNOW or doParallel. But it fails with the same error while I run it with azureBatch and doAzureParallel on R. Could anybody please provide a fix for this ?

**Comment by topepo** [comment]
@kchaitanyabandi I don't have a way to test `doAzureParallel`

**Comment by kchaitanyabandi** [comment]
@topepo  Could you please tell me why this error occurs and when does this occur usually in your source code? I' have been unable to understand the issue to debug this error. Any help would be greatly appreciated.

**Comment by topepo** [comment]
I have no idea. I've never used `doAzureParallel` nor do I have access to it. 

My suggestion is to try the devel version (that I just sent to CRAN) to start and, if that fails, start a _new_ issue on this repo, and fill out the github issue form.
