### ISSUE TITLE
Inconsistency in calculation of confusion matrix?

### ISSUE THREAD

**Issue by Wytz** [topepo/caret#622]
Hi Max, 

I'm greatly enjoying using your caret package, so first of all I would like to extend my compliments. 

However, there is one inconsistency within the calculation of the confusion matrix, which I cannot wrap my head around. I have tried to search for a logical explanation for this in the documentation, but I have failed to find one. In short, I'm comparing the calculation of the confusion matrix provided by the "train" function itself, to the calculation with the "confusionMatrix" function based on the raw data, as contained in the "model$pred" table. 

The example code below should clarify the issue: 

```
set.seed(1)
require(caret)
require(mlbench)

data("Sonar")

model = train(Class ~., data = Sonar, method = "rf", 
              trControl=trainControl(method="cv", number=10, classProbs = TRUE, 
savePredictions = "final", summaryFunction = twoClassSummary), metric = "ROC")
print(model$finalModel)
```
```
> Call:
>  randomForest(x = x, y = y, mtry = param$mtry) 
>                Type of random forest: classification
>                      Number of trees: 500
> No. of variables tried at each split: 2
> 
>         OOB estimate of  error rate: 15.38%
> Confusion matrix:
>     M  R class.error
> M 103  8  0.07207207
> R  24 73  0.24742268
```
```
prediction_data = model$pred[model$pred$mtry == model$finalModel$mtry, ]
print(confusionMatrix(prediction_data$pred, prediction_data$obs))
```
```
> Confusion Matrix and Statistics
> 
>           Reference
> Prediction   M   R
>          M 102  23
>          R   9  74
>                                           
>                Accuracy : 0.8462          
>                  95% CI : (0.7898, 0.8923)
>     No Information Rate : 0.5337          
>     P-Value [Acc > NIR] : < 2e-16         
>                                           
>                   Kappa : 0.6881          
>  Mcnemar's Test P-Value : 0.02156         
>                                           
>             Sensitivity : 0.9189          
>             Specificity : 0.7629          
>          Pos Pred Value : 0.8160          
>          Neg Pred Value : 0.8916          
>              Prevalence : 0.5337          
>          Detection Rate : 0.4904          
>    Detection Prevalence : 0.6010          
>       Balanced Accuracy : 0.8409          
>                                           
>        'Positive' Class : M      
```
As you can see, the numbers within the two confusion matrices are different, where you would expect them to be the same. 

SessionInfo is provided below: 
```
> R version 3.3.1 (2016-06-21)
> Platform: x86_64-apple-darwin13.4.0 (64-bit)
> Running under: OS X 10.12.3 (Sierra)
> 
> locale:
> [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8
> 
> attached base packages:
> [1] stats     graphics  grDevices utils     datasets  methods   base     
> 
> other attached packages:
> [1] randomForest_4.6-12 mlbench_2.1-1       caret_6.0-73        ggplot2_2.1.0       lattice_0.20-33    
> 
> loaded via a namespace (and not attached):
>  [1] Rcpp_0.12.7        magrittr_1.5       splines_3.3.1      MASS_7.3-45        munsell_0.4.3     
>  [6] colorspace_1.2-7   foreach_1.4.3      minqa_1.2.4        stringr_1.1.0      car_2.1-3         
> [11] plyr_1.8.4         tools_3.3.1        nnet_7.3-12        pbkrtest_0.4-6     parallel_3.3.1    
> [16] grid_3.3.1         gtable_0.2.0       nlme_3.1-128       mgcv_1.8-12        quantreg_5.29     
> [21] e1071_1.6-7        class_7.3-14       MatrixModels_0.4-1 iterators_1.0.8    lme4_1.1-12       
> [26] Matrix_1.2-6       nloptr_1.0.4       reshape2_1.4.1     ModelMetrics_1.1.0 codetools_0.2-14  
> [31] stringi_1.1.2      compiler_3.3.1     scales_0.4.0       stats4_3.3.1       SparseM_1.72   
```
I hope you can help me with this!

**Comment by topepo** [comment]
I wouldn't expect them to be the same in this instance. The confusion matrix reported by `print(model$finalModel)` is based on the 500 out-of-bag predictions that are internal to the final random forest model. The confusion matrix results that you report from `confusionMatrix` are based on the 10 cross-validation holdout sets (from 10 different random forest models). 

That said, they are not wildly different for these data.

**Comment by Wytz** [comment]
Thanks for the rapid response and the help! I cross checked the outcomes of the confusion matrix with the command below, and the outcomes indeed do correspond. I assume this is the correct procedure, so I'll close the ticket. If this turns out to be incorrect, please reopen it. 

`confusionMatrix(model$finalModel$predicted, model$finalModel$y)`

> Confusion Matrix and Statistics
> 
>                        Reference
> Prediction      M   R
>                M 103  24
>                R      8  73
>                                           
>                Accuracy : 0.8462          
>                  95% CI : (0.7898, 0.8923)
>     No Information Rate : 0.5337          
>     P-Value [Acc > NIR] : < 2e-16         
>                                           
>                   Kappa : 0.6877          
>  Mcnemar's Test P-Value : 0.00801         
>                                           
>             Sensitivity : 0.9279          
>             Specificity : 0.7526          
>          Pos Pred Value : 0.8110          
>          Neg Pred Value : 0.9012          
>              Prevalence : 0.5337          
>          Detection Rate : 0.4952          
>    Detection Prevalence : 0.6106          
>       Balanced Accuracy : 0.8403          
>                                           
>        'Positive' Class : M

**Comment by t31415** [comment]
Hello I have a similar question about inconsistency between model$results and confusionMatrix performances:
I noticed that the results in my models obtained from caret:train , as in 

fitCtrl<-trainControl(method='repeatedcv',num=10,repeats=5,savePredictions=TRUE,classProbs=TRUE,summaryFunction=BalAc)
model<-train(Y~.,data=data1,metric='OptBalAcc',method='qda',trControl=fitCtrl)
model$results

are much more optimistic than what I get from

confusionMatrix(model$pred$pred,model$pred$obs)

, where I had expected these to be the same. Or at least for the latter (which I thought were the predictions made by the best model when it is applied again to all of the folds together?) to be at least as good as the former (which I thought is the mean of the holdout performances for each fold/repeat and thus a little less subject to overfitting due to being held out each time when the fit takes place?)
 
So I'm trying to understand how its possible that Confusionmatrix is always the more pessimistic one, when it is just the training error made when the same best model is used to predict all the data? Or is this not the case? Thanks

**Comment by t31415** [comment]
Sorry I should probably have opened another ticket, will do that now.
