### ISSUE TITLE
Inclusion of preproessing outcomes in the caret documentation

### ISSUE THREAD

**Issue by antaesoo2** [topepo/caret#627]
**Is there a way I can find out which variables it preprocessed rather than going to individual variables to see what occurred?

How can i find out which power it used for Yeo Johnson transformation for each variable?**

Max's answer:
If you are using the preprocessing inside of train, you can access the preProcess object:
> mod <- train(Sepal.Width ~ ., data = iris, method = "lm", preProc = c("center", "scale", "YeoJohnson"))
> mod$preProcess
Created from 150 samples and 5 variables

Pre-processing:
  - centered (5)
  - ignored (0)
  - scaled (5)
  - Yeo-Johnson transformation (3)

Lambda estimates for Yeo-Johnson transformation:
-0.32, 1.09, 0.84

You can get the specific variables using:
> mod$preProcess$method
$center
[1] "Sepal.Length"      "Petal.Length"      "Petal.Width"       "Speciesversicolor" "Speciesvirginica"   

$scale
[1] "Sepal.Length"      "Petal.Length"      "Petal.Width"       "Speciesversicolor" "Speciesvirginica"   

$YeoJohnson
[1] "Sepal.Length" "Petal.Length" "Petal.Width"   

$ignore
character(0)

There are objects for each preprocessing operation too. For example:
> mod$preProcess$yj
$Sepal.Length
Estimated transformation parameters   
    Y1   
-0.321   

$Petal.Length
Estimated transformation parameters   
  Y1   
1.09   

$Petal.Width
Estimated transformation parameters   
  Y1   
0.84

**Comment by topepo** [comment]
I don't think that I'll create a method for this but this code can be used to get the information:
```r
pp2df <- function(object, ...) {
  vars <- unlist(object$method)
  nums <- vapply(object$method, length, c(num = 0))
  meth <- rep(names(nums), nums)
  data.frame(method = meth, variable = unname(vars))
}
```
