### ISSUE TITLE
final tuning parameters could not be determined for svm regression

### ISSUE THREAD

**Issue by anadiedrichs** [topepo/caret#628]
I'm trying to use SVM for regression but CARET returns NA values in metric RMSE for each training phase (combination of parameters).

**ERROR**

```
Error in train.default(x, y, weights = w, ...) : 
  final tuning parameters could not be determined
```
I didn't find clear examples about using support vector regression or documentation in CARET about this topic. Maybe I could be using the library in a wrong way, or it could be a CARET issue.
### Minimal, reproducible example:

```{R}
#' Testing svm regression using caret
#' 
#' 
x <- seq(from=0,to=4*pi,by=0.01)
y <- sin(x)
#y2 <- y[2:length(y)]
plot(cbind(x,y))
data <- cbind(x,y) #y[1:length(y2)],y2)
colnames(data) <- c("x","y")
train <- data[1:880,]
test <- data[881:nrow(data),]
VERBOSE <- TRUE
library(caret)
#library("e1071")
library("kernlab")
#' use all the cores from the processor
#library(doMC)
#registerDoMC(cores = as.integer(CORES))
set.seed(123)
train.control <- trainControl(method="timeslice",initialWindow = 1, horizon = 1, fixedWindow = TRUE)

models <- c("svmRadial","svmLinear") 
my.metric <- "RMSE"

svmLinearTuneGrid <- expand.grid(C=2^(-2:7))
svmRadialTuneGrid <- expand.grid(C=2^(-2:7), sigma = seq(from=0.5,to=0.1,by=-0.1) )
model.name <- models[1]
#for(m in 1:length(models))
#{  
  #model.name <- models[m]
  #print(model.name)
  head(data)
  model <- NULL
  grid <- NULL
  if(model.name %in% c("svmLinear")){
    grid <- svmLinearTuneGrid
    if(VERBOSE) cat("model svmLinear training")
  }else{
    grid <- svmRadialTuneGrid
    if(VERBOSE) cat("model svmRadial training")
  }
    model<- train(y~.,data=train,method=model.name,
                  metric=my.metric,
                  trControl=train.control,
                  tuneGrid=grid, verbose=VERBOSE)  #<- error thrown:
    #Error in train.default(x, y, weights = w, ...) : 
    #final tuning parameters could not be determined
    #In addition: There were 50 or more warnings (use warnings() to see the first 50)
    

#}

```

### Session Info:
```{R}
>sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.5 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=es_AR.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=es_AR.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=es_AR.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=es_AR.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] e1071_1.6-4     doMC_1.3.3      iterators_1.0.7 foreach_1.4.2   kernlab_0.9-20  caret_6.0-41   
[7] ggplot2_2.1.0   lattice_0.20-34

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7         splines_3.3.2       MASS_7.3-44         munsell_0.4.2      
 [5] colorspace_1.2-4    minqa_1.2.4         stringr_0.6.2       car_2.0-24         
 [9] plyr_1.8.1          tools_3.3.2         nnet_7.3-12         pbkrtest_0.4-2     
[13] grid_3.3.2          gtable_0.1.2        nlme_3.1-128        mgcv_1.8-16        
[17] quantreg_5.11       class_7.3-14        gtools_3.4.1        lme4_1.1-7         
[21] Matrix_1.2-7.1      nloptr_1.0.4        reshape2_1.4.1      codetools_0.2-15   
[25] compiler_3.3.2      BradleyTerry2_1.0-6 scales_0.4.0        SparseM_1.6        
[29] brglm_0.5-9
```

**Comment by topepo** [comment]
The problem is that your resampling specification creates a training set with a single data point for the training set. Change the `initialWindow` argument.

**Comment by anadiedrichs** [comment]
So, it's not clear for me initialWindow and windowSize parameters.
How should I configure them if I would like to have a trainingset in the following way:
input Xt-1 output Xt=y_1
input Xt output Xt+1=y_2 and so on.
?
Thanks in advanced.

**Comment by topepo** [comment]
> It means, why I can't use a initialWindow size of one? It's the case when you want only one previous value. Isn't it?

The window size affects the size of the data used to build a model. Your code was fitting a model with _n_=1 and I don't know of any models that do that. Have you read [the documentation](https://topepo.github.io/caret/data-splitting.html)?

**Comment by anadiedrichs** [comment]
Thanks for your answer.

Yes I read the doc, but there wasn't a mention or warning about "please use initial window size >1". 
IMHO I consider it a bug, at least caret documentation change including the limitations. During time series prediction training, usually, we train different setups, because we want to know how much information from the past (initial window size) would be needed to predict/improve my model, so on, in addition to some feature engineering to decide how many variables in X (input) to use.

The literature is plenty of models that use the information of previous day to predict the next state, e.g, weather prediction.

Another question: why it seems to work for nnet but not for svm?

`library(caret)
library("kernlab")
library("nnet")
x0 <- seq(from=0,to=4*pi,by=0.01)
x1 <- sin(x0)
x2 <- cos(x0)
y <- sin(x0) * cos(x0)
data <- cbind(x1,x2,y) #y[1:length(y2)],y2)
colnames(data) <- c("sin","cos","y")
train <- data[1:880,]
test <- data[881:nrow(data),]
VERBOSE <- TRUE

train.control <- trainControl(method="timeslice",initialWindow = 1, horizon = 1, fixedWindow = TRUE)

models <- c("nnet","svmRadial","svmLinear") 
my.metric <- "RMSE"

nnet.tune.grid <-  as.data.frame(expand.grid(size=seq(3,10,by=1), decay=0.0001))
svmLinearTuneGrid <- expand.grid(C=2^(-2:7))
svmRadialTuneGrid <- expand.grid(C=2^(-2:7), sigma = seq(from=0.5,to=0.1,by=-0.1) )

for(m in 1:length(models))
{  
  print(models[m])
  head(data)
  model <- NULL
  grid <- NULL
  
  if(models[m] %in% c("svmLinear")){
    
    grid <- svmLinearTuneGrid
    if(VERBOSE) cat("training model svmLinear")
    
  }else if(models[m] %in% c("svmRadial")){
    
    grid <- svmRadialTuneGrid
    if(VERBOSE) cat("training model svmRadial")
    
  }else
  {
      grid <- nnet.tune.grid
  }
    set.seed(123)
    model<- train(y~.,data=train,method=models[m],
                  metric=my.metric,
                  trControl=train.control,
                  tuneGrid=grid, verbose=VERBOSE)  #<- error thrown
    summary(model)

}`

**Comment by topepo** [comment]
>  During time series prediction training, usually, we train different setups, because we want to know how much information from the past (initial window size) would be needed to predict/improve my model, so on, in addition to some feature engineering to decide how many variables in X (input) to use.

Agreed but I disagree that a _modeling set_ with a single data point is at all feasible. A single _holdout_ makes sense and works here using the `horizon` option.
