### ISSUE TITLE
Train function is not working

### ISSUE THREAD

**Issue by anneawan** [topepo/caret#634]
If you are making a feature request or starting a discussion, you can ignore everything below and go wild =D

If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [c ] Start a new R session
- [ c] Install the latest version of caret: `update.packages(oldPkgs="caret", ask=FALSE)`
- [ c] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [c ] run `sessionInfo()`

### Minimal, reproducible example:

__Please read this page__: [reprex = {repr}oducible {ex}ample](https://github.com/jennybc/reprex#what-is-a-reprex) 

Text and example code modified from [the R FAQ on stackoverflow](http://stackoverflow.com/a/5963610)

#### Minimal dataset:
```{R}
library(caret)
set.seed(1)
dat <- twoClassSim(100)
X <- dat[,1:5]
y <- dat[["Class"]]

```
If you have some data that would be too difficult to construct using `caret::twoClassSim` or `caret::SLC14_1`, then you can always make a subset of your original data, using e.g. `head()`, `subset()` or the indices. Then use e.g. `dput()` to give us something that can be put in R immediately, e.g. `dput(head(iris,4))`

If you must use `dput(head())`, please first remove an columns from your dataset that are not necessary to reproduce the error.

If your data frame has a factor with many levels, the `dput` output can be unwieldy because it will still list all the possible factor levels even if they aren't present in the the subset of your data. To solve this issue, you can use the `droplevels()` function. Notice below how species is a factor with only one level: `dput(droplevels(head(iris, 4)))`

#### Minimal, runnable code:
```{R}
model_class <- train(
  X, y, 
  metric='ROC',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=twoClassSummary,
    savePredictions="final")
)
print(model_class)
```

### Session Info:
```{R}
>sessionInfo()

```

You can delete the text in each section that explains how to do it correctly.
Be sure to test your 2 chunks of code in an empty R session before submitting your issue!

**Comment by anneawan** [comment]
i ma new to r and machine learning and i have to make an urgent project . I have this code please tell me what i am doing wrong
bomb <- read.csv("abc.csv")
str(abc)
data(abc)
x = abc[,-12]
y =abc$City
set.seed(110)
inTraining <- createDataPartition(abc$Class, p = .75, list = FALSE)
library(caret)
install.packages("klaR")
install.packages("MASS")
install.packages("caret")
model = train(x,y',abc',trControl=trainControl(method='cv',number=10))
model
predict(model$finalModel,x)
table(predict(model$finalModel,x)$class,y)
naive_abc <-c NaiveBayes(abc$City ~ ., data = abc)
plot(naive_abc)

**Comment by topepo** [comment]
Try avoiding using `predict` on `model$finalModel` at all costs. Use `predict(model,x)` and let us know if that works. 

Also, we can't reproduce the issue if the data are not available.

**Comment by anneawan** [comment]
Hi @topepo !
I made the changes as u suggested but its still not working. Plz help

**Comment by anneawan** [comment]
Hi Max Kuhn!

You wrote the solution but i couldn't get it.
Max i am making a project that will predict the next city in which blast
can occur.
Plz help me  i am running short of time. I have to show it to my teacher it
till Monday,2 May,2017.
I am attaching my data so that you can better understand it.
I really need your help otherwise i will not be able to pass.

Waiting for your reply anxiously.
Thank you!
