### ISSUE TITLE
Why grid search for svmLinear model fix C to 1?

### ISSUE THREAD

**Issue by ajing** [topepo/caret#636]
I just want to know for linear SVM model, does tuning C have no effect on the performance?

In the model spec for svmLinear, C is fixed at 1 in grid search. Is there any reference for this setting?

**Comment by topepo** [comment]
It's just a default but I generally found that, for my problems, the cost parameter had now meaningful impact. This is most likely due to the linear boundary not being able to adapt and flex to fit complicated patterns.

**Comment by ajing** [comment]
I was thinking smaller C will have larger regularization effect and more coefficients will be close to 0.

**Comment by topepo** [comment]
It might. You can always pass a grid to `tuneGrid`.

**Comment by ajing** [comment]
Thanks for clarification!

**Comment by ajing** [comment]
Is also impossible to check variable importance for SVM linear model, right?

**Comment by topepo** [comment]
It can be done. The prediction equation _can_ be written in the traditional form using `x`'s and `beta`'s but it is usually parameterized in the SVM `alpha` parameters and the kernel matrix. 

There is some linear algebra that can be used to go between the two formulations but I haven't put it in yet. I'll add a separate issue to do that.

**Comment by topepo** [comment]
It can be done. The prediction equation _can_ be written in the traditional form using `x`'s and `beta`'s but it is usually parameterized in the SVM `alpha` parameters and the kernel matrix. 

There is some linear algebra that can be used to go between the two formulations but I haven't put it in yet. I'll add a separate issue to do that.
