### ISSUE TITLE
ab-initio.mit.edu down --> caret installation gets stucked

### ISSUE THREAD

**Issue by ross85** [topepo/caret#640]
Hello,
I am trying to install caret using install.packages("caret") but one dependency is offline so I get the following error:

* installing *source* package ‘nloptr’ ...
** package ‘nloptr’ successfully unpacked and MD5 sums checked
...
configure: Need to download and build NLopt
trying URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'
Error in download.file(url = "http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz",  : 
  cannot open URL 'http://ab-initio.mit.edu/nlopt/nlopt-2.4.2.tar.gz'

I know I can probably install NLopt manually, but this could create some troubles.

**Comment by topepo** [comment]
Try using a different mirror (maybe `cran.r-project.org` or `cran.rstudio.com`)

**Comment by ross85** [comment]
Now it's online again, but whichever mirror you use it goes to http://ab-initio.mit.edu to download NLopt (it's not an R package).

**Comment by topepo** [comment]
What OS are you on?

**Comment by ross85** [comment]
Ubuntu 16.04

**Comment by topepo** [comment]
Try using `sudo apt-get install libnlopt-dev`

**Comment by topepo** [comment]
Also, [this link](http://ab-initio.mit.edu/wiki/index.php/NLopt) gets you to the sources

**Comment by ross85** [comment]
That's fine, as I pointed out in the original post I know I can install the library before (and setting paths and env variables), but I guess a lot of people will have trouble installing CARET if that dependency goes down again.

**Comment by topepo** [comment]
Okay, now it's really getting on my nerves. 

`caret` gets it though the dependency on `car` (`caret` -> `car` -> `pbkrtest` -> `lme4` -> `nloptr`)

I use `car` for the Yeo-Johnson transformation but I recently [wrote that from scratch](https://github.com/topepo/recipes/blob/master/R/YeoJohnson.R) for another package. I'd rather move that code into `caret` than keep the `car` dependency.

**Comment by sinkagergo** [comment]
When I am trying to install, I get the below message:

> devtools::install_github('topepo/caret/pkg/caret')
Downloading GitHub repo topepo/caret@master
from URL https://api.github.com/repos/topepo/caret/zipball/master
Error: running command '"C:/PROGRA~1/R/R-34~1.1/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD config CC' had status 127

Any ideas why?

Thanks!

**Comment by topepo** [comment]
No idea. Can you send `sessionInfo()`?

**Comment by topepo** [comment]
Also, try [this](https://github.com/catavallejos/BASiCS/issues/9)
