### ISSUE TITLE
missing values in object

### ISSUE THREAD

**Issue by anneawan** [topepo/caret#642]
If you are making a feature request or starting a discussion, you can ignore everything below and go wild =D

If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [ ] Start a new R session
- [ ] Install the latest version of caret: `update.packages(oldPkgs="caret", ask=FALSE)`
- [ ] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [ ] run `sessionInfo()`

### Minimal, reproducible example:

__Please read this page__: [reprex = {repr}oducible {ex}ample](https://github.com/jennybc/reprex#what-is-a-reprex) 

Text and example code modified from [the R FAQ on stackoverflow](http://stackoverflow.com/a/5963610)

#### Minimal dataset:
```{R}
library(caret)
set.seed(1)
dat <- twoClassSim(100)
X <- dat[,1:5]
y <- dat[["Class"]]

```
If you have some data that would be too difficult to construct using `caret::twoClassSim` or `caret::SLC14_1`, then you can always make a subset of your original data, using e.g. `head()`, `subset()` or the indices. Then use e.g. `dput()` to give us something that can be put in R immediately, e.g. `dput(head(iris,4))`

If you must use `dput(head())`, please first remove an columns from your dataset that are not necessary to reproduce the error.

If your data frame has a factor with many levels, the `dput` output can be unwieldy because it will still list all the possible factor levels even if they aren't present in the the subset of your data. To solve this issue, you can use the `droplevels()` function. Notice below how species is a factor with only one level: `dput(droplevels(head(iris, 4)))`

#### Minimal, runnable code:
```{R}
model_class <- train(
  X, y, 
  metric='ROC',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=twoClassSummary,
    savePredictions="final")
)
print(model_class)
```

### Session Info:
```{R}
>sessionInfo()

```

You can delete the text in each section that explains how to do it correctly.
Be sure to test your 2 chunks of code in an empty R session before submitting your issue!

**Comment by anneawan** [comment]
Hi!
Thanks for the help but i still have some issues:
i am running this code :bomb <- read.csv("bomb.csv")
str(bomb)
set.seed(200)
validation_index <- createDataPartition(bomb$City, p=0.70, list=FALSE)
validation <- bomb[-validation_index,]
training <- bomb[validation_index,]
control <- trainControl(method="cv", number=10)
but getting "Error in na.fail.default(list(City = c(23L, 27L, 64L, 66L, 66L, 29L, 29L,  : 
  missing values in object"

**Comment by topepo** [comment]
As with the other issue that you reported, I cannot reproduce this problem. Please make sure that your posted code matches the code that you executed.
