### ISSUE TITLE
Predict is not woring

### ISSUE THREAD

**Issue by anneawan** [topepo/caret#643]
Hi!This is my second post.
Thanks for the help Github team.
I have to make a predictive model to predict the city in which next bomb blast can occur. 
 I have this code please tell me what is wrong here
bomb <- read.csv("abc.csv")
str(abc)
data(abc)
x = abc[,-12]
y =abc$City
set.seed(110)
inTraining <- createDataPartition(abc$Class, p = .75, list = FALSE)
library(caret)
install.packages("klaR")
install.packages("MASS")
install.packages("caret")
model = train(x,y',abc',trControl=trainControl(method='cv',number=10))
model
predict(model,x)
table(predict(model,x))$class,y)
naive_abc <-c NaiveBayes(abc$City ~ ., data = abc)
plot(naive_abc)

I got the data from this link [:](https://www.kaggle.com/zusmani/pakistansuicideattacks)

If you are making a feature request or starting a discussion, you can ignore everything below and go wild =D

If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [x] Start a new R session
- [x] Install the latest version of caret: `update.packages(oldPkgs="caret", ask=FALSE)`
- [x] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [x] run `sessionInfo()`

### Minimal, reproducible example:

__Please read this page__: [reprex = {repr}oducible {ex}ample](https://github.com/jennybc/reprex#what-is-a-reprex) 

Text and example code modified from [the R FAQ on stackoverflow](http://stackoverflow.com/a/5963610)

#### Minimal dataset:
```{R}
library(caret)
set.seed(1)
dat <- twoClassSim(100)
X <- dat[,1:5]
y <- dat[["Class"]]

```
If you have some data that would be too difficult to construct using `caret::twoClassSim` or `caret::SLC14_1`, then you can always make a subset of your original data, using e.g. `head()`, `subset()` or the indices. Then use e.g. `dput()` to give us something that can be put in R immediately, e.g. `dput(head(iris,4))`

If you must use `dput(head())`, please first remove an columns from your dataset that are not necessary to reproduce the error.

If your data frame has a factor with many levels, the `dput` output can be unwieldy because it will still list all the possible factor levels even if they aren't present in the the subset of your data. To solve this issue, you can use the `droplevels()` function. Notice below how species is a factor with only one level: `dput(droplevels(head(iris, 4)))`

#### Minimal, runnable code:
```{R}
model_class <- train(
  X, y, 
  metric='ROC',
  trControl=trainControl(
    method="cv", 
    number=5,
    classProbs=TRUE, 
    summaryFunction=twoClassSummary,
    savePredictions="final")
)
print(model_class)
```

### Session Info:
```{R}
>sessionInfo()

```

You can delete the text in each section that explains how to do it correctly.
Be sure to test your 2 chunks of code in an empty R session before submitting your issue!

**Comment by topepo** [comment]
Please re-read the template. You left out the link, session info and other items that would help us help you. There are also typos in your code so please make sure that it runs up to the error.

**Comment by anneawan** [comment]
I am not using built in data. so how can i send you my data .
Topepo i sent you a mail with my data. 
I pasted my code as it is and having  the error in
 model = train(x,y',abc',trControl=trainControl(method='cv',number=10))
and cant run my code further.

**Comment by anneawan** [comment]
Can u check your email and help me as its very urgent

**Comment by anneawan** [comment]
[abc.xlsx](https://github.com/topepo/caret/files/966752/abc.xlsx)
Here is my data  . Now i finally giving you my data and code has also been entered in code section .
I hope now you will be able to help me

**Comment by anneawan** [comment]
Waiting for your solution now!
I hope all is clear from my side. I have shared every thing regarding my project. Please help me now

**Comment by topepo** [comment]
Your code is not reproducible (or even correct syntax). I can't really spend time on this if you cannot provide a reproducible example.
