### ISSUE TITLE
prSummary and "undefined columns" error

### ISSUE THREAD

**Issue by codingbutstillalive** [topepo/caret#651]
I am trying to set up my training like this:

```
trainControl <- trainControl(method = "cv",
                           number = 10,
                           # Compute Recall, Precision, F-Measure
                           summaryFunction = prSummary)

modelFit <- train(Response ~ . -Id, data = train.scaled, 
                method = "gbm",
                trControl = trainControl,
                metric = "F", # Optimize model by F-measure
                verbose = F)
```

However, this runs into the following error message:

> Error: in `[.data.frame`(data, , lev[1]) : undefined columns selected

The problem is related to prSummary, as the code runs smoothly when taking "twoClassSummary" instead. What is the problem here?

Note: I made sure that MLmetrics is installed!

**Comment by codingbutstillalive** [comment]
I see: I needs "classProbs = T".

Well, I would have appreciated a more elaborated error message in that case :(

**Comment by topepo** [comment]
> I would have appreciated a more elaborated error message in that case :(

True, but we'd appreciate people reading the documentation too =]

**Comment by codingbutstillalive** [comment]
Alright, challenge accepted :) So tell me where I would have found this description. I have read the documentation.

So, now I googled and again found nothing. See here, for example:

https://rdrr.io/cran/caret/man/postResample.html

It says:

"To use twoClassSummary and/or mnLogLoss, the classProbs argument of trainControl should be TRUE. multiClassSummary can be used without class probabilities but some statistics (e.g. overall log loss and the average of per-class area under the ROC curves) will not be in the result set."

No word about about prSummary, although this function is explained there. So it wasn't obvious to me that it computes AUC as well, thus needing this argument set to True.

**Comment by topepo** [comment]
Ah, busted! I didn't update it to say `twoClassSummary` and `prSummary`. I'll do that.

**Comment by codingbutstillalive** [comment]
Thanks :-)
