### ISSUE TITLE
R crashes while using e1071 SVM classification

### ISSUE THREAD

**Issue by neerajmalpani1** [topepo/caret#652]
Hi,
 Currently i am working to create an SVM machine learning model in R (e1071) for Text classification using 78000 rows of training data. The training data has only 2 variables, X and Y.
I started svm training using 25% of the data which yielded me  a SVM model 6.9 GB. But when i started increasing the % data to train, R gets crashed. And when i saw the error report in Window manager, it show fatal error in e1071.dll

I have 64Gb of RAM, hence the out of memory is definitely not the problem.
Have had this problem both on RStudio and R console. Currently using the latest versions of both - 64bit.

Can anyone help me out on this??

**Comment by topepo** [comment]
Have you tried running the model directory on the e1071 function to see if it fails there? 

Also, _please read the issue template_; there is more information that you don't provide (including code) that might help us. 

Also also, try creating a small example to see if there is some issue apart from the data set size at work.
