### ISSUE TITLE
M5 is not in Caret's built-in library

### ISSUE THREAD

**Issue by ianepomuceno** [topepo/caret#659]
I am unable to make M5 run it gives the following error: "Model M5 is not in Caret's built-in library"

I test that I can use the RWeka package and I run next code:

```{R}
library(RWeka)
df3 <- read.arff(system.file("arff","cpu.arff", package="RWeka"))
m3 <- M5P(class ~ ., data = df3)
```
I obtained next error: 
"ADVERTENCIA: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS"

and I run a second time the last line of the code and the model is generated

I tried with this dataset used caret packaged:
```{R}
 model_m5 <- train(
     class ~ .,data=df3,
     method = "m5",
     trControl = myControl_reg
 )
```
and I obtained the same error "Model M5 is not in Caret's built-in library"

Someone know how I can solve it?

**Comment by topepo** [comment]
"M5" is there, but "m5" is not =[
```r
> names(getModelInfo("M5"))
[1] "M5"      "M5Rules"
```

**Comment by ianepomuceno** [comment]
Ups!!!!!! 

and thanks a lot
