### ISSUE TITLE
Quantile Regression Forest Not Predicting Quantiles

### ISSUE THREAD

**Issue by prescient** [topepo/caret#660]
I believe this line in the train function for the quantile regression forest needs to be changed:

https://github.com/topepo/caret/blob/master/models/files/qrf.R
`out <- predict(modelFit, newdata, quantiles = .5)`

to:
`out <- predict(modelFit, newdata, what= .5)`

Example:

```
require(caret)
data(mtcars)

mdl <- train(mpg ~ cyl,
             data = mtcars,
             method = 'qrf')

tst_quantiles_05 <- predict(mdl, mtcars, quantiles = .05)
tst_quantiles_95 <- predict(mdl, mtcars, quantiles = .95)
tst_what_05 <- predict(mdl, mtcars,  what = .05)
tst_what_95 <- predict(mdl, mtcars, what = .95)
tst <- predict(mdl$finalModel, mtcars, what=c(.05, .5, .95))
tst <- predict(mdl$finalModel, mtcars, what=.5)
```

**Comment by topepo** [comment]
Right now, it only predicts the median. You can use the predict method on the `finalModel` object but avoid using the `preProcess` option in doing so.

**Comment by Steviey** [comment]
+1

**Comment by umbe1987** [comment]
> Right now, it only predicts the median. You can use the predict method on the `finalModel` object but avoid using the `preProcess` option in doing so.

Very useful information, thank you so much!
