### ISSUE TITLE
new preprocessing function proposal

### ISSUE THREAD

**Issue by spedygiorgio** [topepo/caret#662]
It could be nice the caret package to offer a function to bin continuous variable into quantiles, like Hmisc cut2, but that can keep bins to apply the same on a untrained dataset (testSet)

**Comment by zachmayer** [comment]
I would suggest writing an S3 class to do the cutting, with a predict method for new data.  Be sure to think about cases with `NA`, `NaN`, `-Inf`, `Inf`, and values outside the range of the training data.

If you write the class (preferably with no outside dependencies), we can help you plug it into the right place in https://github.com/topepo/caret/blob/master/pkg/caret/R/preProcess.R

**Comment by topepo** [comment]
I'm in the process of adding a `train` methods for [recipes](https://topepo.github.io/recipes/). That should greatly broaden the types of preprocessing that we can do. There is a [`discretize`](https://topepo.github.io/recipes/reference/discretize.html) method in `recipes` right now that does simple percentile binning. 

Although this is my main priority for `caret` right now, it is taking me a bit to do some refactoring along the way. Volunteers are always welcome!

**Comment by ajing** [comment]
Volunteers for refactoring?

**Comment by topepo** [comment]
Here is what the api will look like:
```r
rec <- recipe(Class ~ ., data = dat) %>%
  step_center(all_predictors())  %>%
  step_scale(all_predictors()) 

set.seed(111)
mod <- train(recipe = rec,
             data = dat,
             method = "glm")
## directs to `train.recipe`
```
The `preProc` arguments are gone (and would be ignored if anyone specifies them). One cool thing about this is that arbitrary columns of the data set will be exposed to the summary function (topepo/caret#606, topepo/caret#407, topepo/caret#478) 

I've created a new branch and gotten pretty far (I'm really productive on long plane flights). I'll check in code in the next day or so). 

If anyone wants to contribute, help would be great for

 * further refactoring on the `train` validity checks (see topepo/caret#633).
* testing and adding test cases to the `RegressionTests` directory. 
*  a recipe method for `rfe` (see topepo/caret#670)

**Comment by topepo** [comment]
[New branch](https://github.com/topepo/caret/tree/recipe_integration)

**Comment by topepo** [comment]
This branch will be merged in soon. I'll close this but please add comments in a new issue on on the [project page](https://github.com/topepo/caret/projects/1).
