### ISSUE TITLE
Caret custom metric with class probs in parallel: data really scrambled?

### ISSUE THREAD

**Issue by Wermeling** [topepo/caret#663]
Attached is an example of Caret with custom metric focussing on class probabilities. (rank prob score)
The printout of data in defaultsummary2 looks scrambled if run in parallel. Please compare both situations for allowParallel=T and =F.
By the way: the results of nnet are comparable in this case for the giving dataset. So it's scrambled but ok?

library(caret)
library(doParallel)

trainModel <- function(training) {
  defaultsummary2 <- function (data, lev = NULL, model = NULL)
  {
    print(data)
    #readline(prompt="Press [enter] to continue")
    obs <- as.vector(as.numeric(data$obs))
    pred <- as.matrix(subset(data, select = levels(data$obs)))
    rpsr <- verification::rps(obs, pred)
    rpsScore <- 1 - rpsr$rps
    names(rpsScore) <- "rpsScore"
    return(rpsScore)
  }
  
  
  fitControl <- trainControl(
    method = "repeatedcv",
    number = 10,
    repeats = 5,
    savePredictions = "all",
    classProbs = TRUE,
    summaryFunction = defaultsummary2,
    allowParallel = F
  )
  
  #myTuneGrid <- expand.grid(n.trees = 1:150,interaction.depth = 1:5,shrinkage = 0.1, n.minobsinnode=10)
  
  
  modelFit <- train(
    Species ~ .,
    data = iris,
    method = "nnet",
    metric = "rpsScore",
    preProcess = c("center", "scale", "pca"),
    trControl = fitControl
  )
  return (modelFit)
}
cl <- makeCluster(6)
registerDoParallel(cl)
trainModel(iris)
stopCluster(cl)

**Comment by topepo** [comment]
When `train` first runs, it scrambles the data and evaluates the summary function to make sure that it works and to know the names of the summary statistics that get computed. After the first evaluation, the data are not permuted This happens whether you are running in parallel or not.

**Comment by Wermeling** [comment]
Thanks for clarifying.

 

Von: Max Kuhn [mailto:notifications@github.com] 
Gesendet: Donnerstag, 25. Mai 2017 14:54
An: topepo/caret <caret@noreply.github.com>
Cc: Wermeling <christian.waldow@googlemail.com>; Author <author@noreply.github.com>
Betreff: Re: [topepo/caret] Caret custom metric with class probs in parallel: data really scrambled? (#663)

 

When train first runs, it scrambles the data and evaluates the summary function to make sure that it works and to know the names of the summary statistics that get computed. After the first evaluation, the data are not permuted This happens whether you are running in parallel or not.

**Comment by topepo** [comment]
No problem
