### ISSUE TITLE
Question about imputation using preProcess

### ISSUE THREAD

**Issue by ajing** [topepo/caret#665]
When using preProcess to imputation (i.e. knnImpute), is that possible to disable "center" and "scale"?

**Comment by topepo** [comment]
Not right now. However, I'm writing another interface to `train` using [`recipes`](https://topepo.github.io/recipes/) that would get around that issue and keep the predictors in their original units (see [`step_knnimpute`](https://topepo.github.io/recipes/reference/step_knnimpute.html)).

**Comment by ajing** [comment]
Thanks!
