### ISSUE TITLE
Sub-Model Trick Availability

### ISSUE THREAD

**Issue by larry77** [topepo/caret#666]
Hello,
More of a question than an issue really.
I see from time to time requests for the sub model trick to several models for which it is suitable.
My question is if I can find somewhere a list of models for which the submodel trick has been implemented already.
Cheers

**Comment by RobertKomara** [comment]
They are listed in the documentation: http://topepo.github.io/caret/random-hyperparameter-search.html

 ada, AdaBag, AdaBoost.M1, bagEarth, blackboost, blasso, BstLm, bstSm, bstTree, C5.0, C5.0Cost, cubist, earth, enet, foba, gamboost, gbm, glmboost, glmnet, kernelpls, lars, lars2, lasso, lda2, leapBackward, leapForward, leapSeq, LogitBoost, pam, partDSA, pcr, PenalizedLDA, pls, relaxo, rfRules, rotationForest, rotationForestCp, rpart, rpart2, rpartCost, simpls, spikeslab, superpc, widekernelpls, xgbTree

**Comment by topepo** [comment]
You can also look using this code: 
```r
> has_submods <- vapply(getModelInfo(), function(x) !is.null(x$loop), c(TRUE))
> head(has_submods)
        ada      AdaBag AdaBoost.M1    adaboost       amdai       ANFIS 
       TRUE        TRUE        TRUE       FALSE       FALSE       FALSE 
```
