### ISSUE TITLE
timeslice conserving a grouping variable (id)

### ISSUE THREAD

**Issue by ciflikli** [topepo/caret#668]
Hello,

First things first - amazing package! Big fan.

We have recently switched from survival analysis to logistic regression in order to better deal with time-varying covariates in our data using ML (so we don't really have ts data but seems like this is not an issue). The problematic nature of using regular CV methods with TVCs led us to the timeslice option in `trainControl`. However, our data is also grouped by an id variable, which needs to preserved in addition to the progression of time. An example would be 8 rows/years for England, followed by 5 years for Germany etc. - we don't want the CV method to use partial durations, cutting any spell in the middle.

Given the arguments for timeslice (initialWindow and horizon) accepts numeric values, is there a way around this? Basically, what we need is a dynamic horizon function if possible at all - we can set up the initialWindow manually. However, horizon would take different lengths at each iteration, so any thoughts on that is appreciated.

Cheers,

Gokhan

**Comment by topepo** [comment]
> Given the arguments for timeslice (initialWindow and horizon) accepts numeric values, is there a way around this? 

No, not really. The good news is that [the function](https://github.com/topepo/caret/blob/master/pkg/caret/R/createDataPartition.R#L246) is not that long so you should be able to adapt it for your situation.
