### ISSUE TITLE
RFE: custom preProcessing

### ISSUE THREAD

**Issue by rareitmeyer** [topepo/caret#670]
Please extend preProcessing to accept "unknown" preprocessing methods. (Or better document how to do it with current caret.)

As a motivational example, I'd like to have a preprocessing step where factors with large numbers of values would be replaced by a new column: The median value of the response for the train data for the subset of the train data with the same factor level. This will depend on the training data, and when using a basic train/validation split with createDataPartition, the median would be calculated on just the train subset. But when using caret's cross validation, it's currently impossible to make this preprocessing happen on the right data subsets.

Suggested interface:

Add a new function in caret to define a custom preProcessing step. User would provide a pair of functions (processing on the train, and application of the resulting obj on the used data), and would get back something they could name in the environment --- a list-as-object or something snazzier.

Enhance the current preProcess code to search the parent environment(s) for any unrecognized method names, to be run after all current preprocessing steps (*).

As a final enhancement, extend the current preProcesss to take an method_order variable that specifies the order to attempt things, with the default value matching the current preProcess code, and all unknown values happening subsequently. This would allow someone to center or rescale the output of a custom preProcessor.

The way the mlr package handles this (https://mlr-org.github.io/mlr-tutorial/devel/html/preproc/index.html) might also be worth a look.

**Comment by topepo** [comment]
This will be better handled by the [`recipe`](https://github.com/topepo/recipes) interface that is in-process.
