### ISSUE TITLE
Preprocessing only certain columns?

### ISSUE THREAD

**Issue by gezmi** [topepo/caret#672]
Hi!

I would like to propose a new feature to preProcess option.
It would be nice, if I could give a list of columns that I would like to preprocess. I had/have some datasets when I have many binary (>1000) features with a few continuous one. Binary features should work without standardizing, however the rest requires it. 
Now, if I tune parameters via CV, it always standardize all features that takes a long time. I could do standardizing before CV, however as far as I know, I should not, because that way that training and test sets "see" each other.
Maybe, I am just unaware that I could do this already. If not, is it possible to request such a feature - or maybe this is too complicated?

Thanks for the answers!

**Comment by topepo** [comment]
There is an undocumented feature in `caret` that I was still testing that will let you do this:
```r
> library(caret)
> pp <- preProcess(iris, 
+                  method = list(center = "Sepal.Length", 
+                                scale = grep("Petal", names(iris), value = TRUE)))
> pp
Created from 150 samples and 4 variables

Pre-processing:
  - centered (1)
  - ignored (1)
  - scaled (2)
```
You can pass a list like this one to the `preProcess` argument of `train`. 

I haven't had any issues with this (and no bug reports on it) so it should work for you.

**Comment by gezmi** [comment]
That's wonderful, thank you! And as I can see, I can give a list of column names as well. It makes my life a lot easier!

**Comment by topepo** [comment]
Thanks

**Comment by joaopcnogueira** [comment]
Is there any better documentation than this issue about this feature?

**Comment by topherhuebel** [comment]
What about instead and argument "ignore = c("V1", "V2") were you can specify the variables that should be ignored?
