### ISSUE TITLE
createFolds does not return equally sized folds or even requested number of folds

### ISSUE THREAD

**Issue by hhoeflin** [topepo/caret#675]
If you are making a feature request or starting a discussion, you can ignore everything below and go wild =D

If you are filing a bug, make sure these boxes are checked before submitting your issue— thank you!

- [x ] Start a new R session
- [x ] Install the latest version of caret: `update.packages(oldPkgs="caret", ask=FALSE)`
- [ x] [Write a minimal reproducible example](http://stackoverflow.com/a/5963610)
- [ x] run `sessionInfo()`

### Minimal, reproducible example:

``` r
set.seed(3)
library(caret)
#> Warning: package 'caret' was built under R version 3.3.3
#> Loading required package: lattice
#> Loading required package: ggplot2
#> Warning: package 'ggplot2' was built under R version 3.3.3
subjects <- paste0("SUBJECT", 1:17)
createFolds(subjects, k=10)
#> $Fold1
#> [1]  8 14
#> 
#> $Fold2
#> [1] 15
#> 
#> $Fold3
#> [1] 10 11
#> 
#> $Fold4
#> [1]  2  3  4  5 16
#> 
#> $Fold5
#> [1] 12 13 17
#> 
#> $Fold6
#> [1] 9
#> 
#> $Fold7
#> [1] 1 6 7
```

As you can see - instead of the requested 10 folds, only 7 are being returned. In addtion, the number of elements per fold is not the same (or only different by 1 as necessary to distribute all items across folds). Instead, Fold4 has 5 items, while Fold2 only has 1. This is counter-intuitive to my understanding of Cross-Validation, where folds are intended to be of equal size (or as close to equal as possible if you can't divide the number of samples by the number of folds without remainder).

### Session Info:
```{R}
>sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] caret_6.0-76    ggplot2_2.2.1   lattice_0.20-34 reprex_0.1.1   

loaded via a namespace (and not attached):
 [1] codetools_0.2-15   minqa_1.2.4        digest_0.6.12      htmltools_0.3.6   
 [5] splines_3.3.2      ModelMetrics_1.1.0 MatrixModels_0.4-1 scales_0.4.1      
 [9] rprojroot_1.2      grid_3.3.2         stringr_1.2.0      whisker_0.3-2     
[13] knitr_1.16         lme4_1.1-13        munsell_0.4.3      tibble_1.3.3      
[17] nnet_7.3-12        foreach_1.4.3      iterators_1.0.8    mgcv_1.8-15       
[21] clipr_0.3.3        Matrix_1.2-7.1     MASS_7.3-45        plyr_1.8.4        
[25] stats4_3.3.2       stringi_1.1.5      pbkrtest_0.4-7     magrittr_1.5      
[29] car_2.1-4          reshape2_1.4.2     rmarkdown_1.6      evaluate_0.10.1   
[33] gtable_0.2.0       rlang_0.1.1        colorspace_1.3-2   tools_3.3.2       
[37] parallel_3.3.2     callr_1.0.0        nloptr_1.0.4       nlme_3.1-128      
[41] quantreg_5.33      lazyeval_0.2.0     backports_1.1.0    Rcpp_0.12.11      
[45] SparseM_1.77      

```

**Comment by topepo** [comment]
It is trying to do the splitting within each value of subject and then pools the splitting indicies. Since there is no replication within subject, it is failing to give you what you expect. 

You should not expect equal sized folds; 10-fold with 17 samples will, on average, leave 1.7 out. Sometimes you will get one left out, other times it will be two. 

I would not use k-fold CV for this but would instead suggest bootstrapping or, if you have to, leave-one-out. You could always just to `createFolds(rnorm(17), k=10)` to get 10-fold without stratification but I don't advise it.

**Comment by hhoeflin** [comment]
Thanks for the explanation. I guess I am just not familiar with this type of cross-validation.

If I do the same example with 20 subjects, the same issue occurs. Instead of leaving out 2 subjects in each fold, it leaves out an arbitrary number. May I ask why createFolds tries to create the folds based on outcome value? Why would it expect replication in the subjects?

Thanks for your help!

**Comment by topepo** [comment]
> why createFolds tries to create the folds based on outcome value? 

Stratified random sampling is a pretty normal thing. If you want to preserve the distribution in the _outcome_ between the data splits, that is what you would do. The documentation has `y` being "a vector of outcomes."

> Why would it expect replication in the subjects?

It wouldn't because most of the time you would not give it the subject identifiers. It sounds like you want something like the `groupKFold` function.

**Comment by hhoeflin** [comment]
Sorry if my second comment was a little negative, let me back off a bit and explain my concern a bit

1) Yes, you decribe y as an outcome, but you don't ever say that you are doing stratified cross-validation. You could make that clear in the documentation.
2) In trainControl, the methods you offer are "cv" and "repeatedcv", when you seem to be doing "stratifiedcv" and "repeatedstratifiedcv", Straight regular CV is I think not a direct option? That is fine, of course, but documenting it would be helpful. I didn't understand this until I dug deeper into your code.
3) When someone asks a cross-validation function for 10 folds, and it is not returning 10 folds, I think it would be helpful to send a warning.
4)Maybe this can be fixed so that you get the number of folds and size of each fold that one would expect while still doing stratified cross-validation. Sorry, I haven't had the time to test it and am off on vacation, so just throwing the code piece below in here as a suggestion. May also be worthwhile to look into what other packages use as a strategy e.g. scikitlearn has stratifiedKFold.

createFolds <- function(strat_id, k) {
	if(k > length(strat_id)) {
		k <- length(strat_id)
	}	
	perm <- sample(length(strat_id))
	strat_id <- factor(strat_id, levels=sample(unique(strat_id)))
	
	strat_order <- order(strat_id[perm])
	
	num_item_per_fold_ceil <- ceiling(length(strat_id) / k)
	
	fold_ids <- unlist(lapply(rep(k, num_item_per_fold_ceil), sample, size=k))
	fold_ids <- fold_ids[seq_along(strat_id)]

	folds <- split(perm[strat_order], fold_ids)
	names(folds) <- paste0("Fold", seq_len(k))	
	return(folds)
}

Curious what you think. Thanks
