### ISSUE TITLE
data corresponding to finaModel 

### ISSUE THREAD

**Issue by srinivasan3** [topepo/caret#690]
I have a question regarding the data corresponding to the finalModel in caret package. 

For instance:
ctrl <- trainControl(method = "repeatedcv", repeats = 4,number=5,
                       classProbs = TRUE,
                       summaryFunction = twoClassSummary,
                       ## new option here:
                       sampling = "down",
                       savePredictions=TRUE,
                       verboseIter=FALSE,allowParallel = TRUE)
  levels <- unique(y)
  targ <- factor(y, labels=make.names(levels))
  
  objModel     <- train(x,targ,  
                        method="rf",metric = "ROC",
                        trControl=ctrl,ntree = 600)
  bestmodel = objModel$finalModel

Is the data corresponding to finalModel is one realization of the many down sampled data that has the best ROC ? Or is the data corresponding to the finalModel is all data (x in this case) with optimal parameters chosen based on the cross validation

**Comment by topepo** [comment]
It think that I might have answered this in email but here it is in a nutshell: for this specification, the downsampling is done once in each resample and on the entire training set (for the final model). The resampling helps choose the parameters and those are applied to the final model.
