### ISSUE TITLE
Extract hyperparameters bounds used in random grid generation

### ISSUE THREAD

**Issue by MassimilianoGrassiDataScience** [topepo/caret#692]
For each hyperparameter used in a modeI, I would like to extract the min and max bound values considered while the random grid is generated. How this can be done for all models included in caret?

Thank you!

**Comment by topepo** [comment]
Some of them are conditional on the data set. For example, the number of PLS or PCA components depends on the number of linearly independent columns, etc. 

You could do it via simulation:
```r
set.seed(133)
dat <- twoClassSim(100)

func <- getModelInfo("kknn", regex = FALSE)[[1]]$grid

sim_values <- func(x = dat[, names(dat) != "Class"],
                   y = dat$Class, 
                   len = 100,
                   search = "random")
summary(sim_values)
```
For this model, if you look at what is in `func`you'll see that I've capped the maximum number of neighbors at `floor(nrow(x)/3)`. It is really subjective. Also, there isn't really a definitive range for some models. For example, the number of boosting iterations, SVM cost parameter, and other have no real upper bound. 

I have been putting together requirements for a more tidy modeling package that will have a better system for generating random tuning parameter values (as would be needed for something like GAs or Bayesian optimization). It won't be ready anytime this year though (as an estimate).

**Comment by MassimilianoGrassiDataScience** [comment]
Perfect, I will do it with simulation.

The question came exactly because I've implemented Bayesian optimization starting from your [post](http://blog.revolutionanalytics.com/2016/06/bayesian-optimization-of-machine-learning-models.html) and I'm trying to make a fast-to-use function working with all models before I will eventually proceed with manual fine tuning of Bayesian optimization parameters. I think that the current implemented bounds are more than ok for a very first attempt.

Thank you Max!

**Comment by topepo** [comment]
I know that the `mlr` people have a package for that type of optimization. I hope to have something next year that is more in line with tidy modeling. 

Keep in mind that any search/optimization method might not be helpful for a lot of models. Many/most only have a single parameter:
```r
> mods <- getModelInfo()
> get_param <- function(x) 
+   nrow(x$param) - sum(x$param$label == "parameter")
> 
> num_param <- vapply(mods, get_param, c(int = 1))
> table(num_param)
num_param
 0  1  2  3  4  5  6  7  8 
17 78 83 38  6  6  1  1  1 
```
Also, the "submodel-trick" that `train` uses is really efficient for grid search for a lot of models. Search procedures will do a better job at exploring the space that grid search but it might be slower. 

Anyway, let me know what you come up with!

**Comment by MassimilianoGrassiDataScience** [comment]
Thank you and l let you know for sure! I actually have another question regarding the submodel trick but I will open another thread to make this conversation clean.
