### ISSUE TITLE
feature request: train null model

### ISSUE THREAD

**Issue by kohleth** [topepo/caret#694]
Hi there,
I am aware of the nullModel function.
But it would be good if there is a caret method called `"nullModel"` which works with the `train` function.
This is so that 1) the comparison it makes with other real models will be fair because of the resampling scheme, and 2) the syntax for training model stays consistent.

**Comment by topepo** [comment]
Good point. I'll put one together for the next release.

**Comment by topepo** [comment]
I just called it "null". Let me know if you have an issues with it.
