### ISSUE TITLE
catboost in caret

### ISSUE THREAD

**Issue by hadjipantelis** [topepo/caret#695]
Mostly a documentation feature probably: 
[catboost](https://catboost.yandex/) is an open-source gradient boosting library from Yandex. Their devs have provided an R-package and the R-package actually has a `catboost.caret` wrapper already. 🎆 
Should this be added to available methods somehow or not? (Issue is minor/ a nice problem to have, so please free to close it as soon as you want. No direct action is expected.)

**Comment by schelhorn** [comment]
I'd would be interesting to compare this to the `lightgbm` the implementation that is also a requested feature here.

**Comment by topepo** [comment]
Added a card to the [new models project page](https://github.com/topepo/caret/projects/2) instead of using issues.

**Comment by hadjipantelis** [comment]
Great! So what does "*added a card*" mean? :D 
Earlier today I made some PR about adding looping capabilities to the native `catboost.caret` wrapper. I have made some quick tests and seems to be working fine. Other users took care of early stage bugs and I generally suspect that some ironing out of the formula based interface might be in order... In light of that: should `catboost` be moved to 'In Process' or maybe removed entirely? I am not sure how this functionality should be incorporated with `caret`. 

Is `CRAN` presence a must for a model to be finished? In that case `mxnet`,`lightgbm` and `catboost` cannot be finished...

**Comment by topepo** [comment]
> Great! So what does "added a card" mean? :D

I wanted to move new model requests out of issues and into the new project page. The link shows entires for different models. You can always submit issues for specific questions related to developing a new model. 

> should `catboost` be moved to 'In Process' or maybe removed entirely? 

I would put it into the "in process" column just so people know that something is happening. 

> Is CRAN presence a must for a model to be finished? 

No. There are a few models still in `caret` on archived packages, accessed through python, or are just on github. I would add a comment in the `notes` field of the model to give a link to the repo if it isn't on CRAN.

**Comment by topepo** [comment]
@schelhorn Resources aren't too big of a deal once the model code is written. In the case of `lightgbm` I'll just need to get the damn thing installed on my testing machine.

**Comment by hadjipantelis** [comment]
@topepo Thank you for the clarifications, all very  sensible.
