### ISSUE TITLE
Add Nested Cross-Validation

### ISSUE THREAD

**Issue by topepo** [topepo/caret#70]
See [http://www.biomedcentral.com/1471-2](http://www.biomedcentral.com/1471-2)

**Comment by ck37** [comment]
Looks like this link no longer works, but maybe this was the article? http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3994246/
"Cross-validation pitfalls when selecting and assessing regression and classification models"

**Comment by enissay14** [comment]
http://stats.stackexchange.com/questions/189364/caret-repeated-k-fold-cross-validation-vs-nested-k-fold-cross-validation-repe

**Comment by jorjasso** [comment]
I think would be nice if some checks are added for nested cross-validation
- stability of the predictions across the best models in the outer loop
- stability of the hyperparameters
Take a look in these links:
http://jmlr.org/papers/v11/cawley10a.html

http://stats.stackexchange.com/questions/65128/nested-cross-validation-for-model-selection/65156#65156

**Comment by achekroud** [comment]
just curious, is the nested CV feature still on the cards? I think this would be awesome

**Comment by jesalo** [comment]
Nested CV would be a very useful - in particular for cases with small amounts of data. Is the feature clashing with the structure of caret?

**Comment by topepo** [comment]
Nested resampling would require a pretty substantial workflow that needs to be created and it is on the back-burner right now. However, [`rsample`](https://topepo.github.io/rsample/index.html) can generate the resampling indices. I'll try to take a simple example and make a vignette for that package.

**Comment by topepo** [comment]
I did a [blog post](http://appliedpredictivemodeling.com/blog/2017/9/2/njdc83d01pzysvvlgik02t5qnaljnd) instead.

**Comment by topepo** [comment]
This will not be implemented.
