### ISSUE TITLE
RFE dummy variable error

### ISSUE THREAD

**Issue by ashvin-p** [topepo/caret#704]
Hi, 

I made dummy variables from my dataset, which contain categorical and numerical values. I want to do feature selection with the dummified data. When I use the lmFuncs in the rfeControl function, I get the following error: `Error in { : 
  task 1 failed - "rfe is expecting 27 importance values but only has 26. This may be caused by having zero-variance predictors, excessively-correlated predictors, factor predictors that were expanded into dummy variables or you may have failed to drop one of your dummy variables."` 

I removed the zero-variance, near-zero-variance and highly correlated predictors. However, i don't understand the "you may have failed to drop one of your dummy variables" part of the error. Can anybody tell me how and which dummy variable i should remove or even how to fix this missing importance value issue. 

caret: 6.0.70
`dummy_training <- `training_reduced_CADD_na_imputed[,7:51]`
`dmy` <- dummyVars(" ~ .", data = dummy_training)`
`trsf_sub <- data.frame(predict(dmy, newdata = dummy_training))`
`zero_variation_sub <- apply(trsf_sub, 2, function(x) length(unique(x)) == 1)`
`trsf_sub_zv <- trsf_sub[,!zero_variation_sub]`
`n <- length(colnames(trsf_sub_zv))`
`correlationMatrix <- cor(trsf_sub_zv[,1:n],use="complete.obs")`
`highlyCorrelated <- findCorrelation(correlationMatrix, cutoff=(0.7),verbose = FALSE)`
`important_var_sub <- colnames(trsf_sub_zv[,-highlyCorrelated])`
`x = nearZeroVar(trsf[,important_var_sub], saveMetrics = TRUE)`
`b <- x[x[,"zeroVar"] ==FALSE & x[,"nzv"] == FALSE, ] `
`ctrl <- rfeControl(functions = lmFuncs, method = "repeatedcv", repeats = 1, verbose = FALSE)
		lmProfile <- rfe(trsf_sub_zv[,rownames(b), training_reduced_CADD_na_imputed[index[[1]],55], sizes = seq(10,100,10), rfeControl = ctrl)`
`

**Comment by topepo** [comment]
I'll need a small reproducible example to look into this (see the issue template).
