### ISSUE TITLE
predict.list simplification

### ISSUE THREAD

**Issue by grayskripko** [topepo/caret#709]
```
caret:::predict.list
{
    out <- lapply(object, predict, ... = ...)
    if (!is.null(names(object))) 
        names(out) <- names(object)
    out
}
```
I'm not sure but as far as I know, ```lapply``` always creates names if ```object``` has.
I think, it would be better to define ```predict.list``` function as ```lapply(object, predict, ... = ...)```

**Comment by topepo** [comment]
I had a reason for doing that but it is lost to time. It is a good point but I'd rather leave the one line in for risk reduction.
