### ISSUE TITLE
defaultSummary Link Target Page Has No Function Prototype

### ISSUE THREAD

**Issue by DarioS** [topepo/caret#712]
On the help page of `train`, the parameter `summaryFunction` makes reference to a function `defaultSummary` and the link goes to a help page of `postResample` however the function specification of `defaultSummary` is not in the Usage section and there's only one sentence about it in Details section, so the user does not know the function's [prototype](https://www.pcmag.com/encyclopedia/term/43583/function-prototype).

Perhaps also adding an example using a custom summary function, of which there currently are none, to the Examples section of `train` help would be useful for readers, with a simple example such as a function for [balanced error rate](http://www.modelselect.inf.ethz.ch/evaluation.php).

**Comment by topepo** [comment]
> Perhaps also adding an example using a custom summary function, of which there currently are none, to the Examples section of `train` help would be useful for readers

There already is one:
```r
madSummary <- function (data,
                        lev = NULL,
                        model = NULL) {
  out <- mad(data$obs - data$pred,
             na.rm = TRUE)
  names(out) <- "MAD"
  out
}

robustControl <- trainControl(summaryFunction = madSummary)
```
There is a little more information [here](https://topepo.github.io/caret/model-training-and-tuning.html#alternate-performance-metrics):

> If none of these parameters are satisfactory, the user can also compute custom performance metrics. The `trainControl` function has a argument called `summaryFunction` that specifies a function for computing performance. The function should have these arguments:
>
> - `data` is a reference for a data frame or matrix with columns called `obs` and `pred` for the observed and predicted outcome values (either numeric data for regression or character values for classification). Currently, class probabilities are not passed to the function. The values in data are the held-out predictions (and their associated reference values) for a single combination of tuning parameters. If the `classProbs` argument of the `trainControl` object is set to `TRUE`, additional columns in `data` will be present that contains the class probabilities. The names of these columns are the same as the  class levels. Also, if `weights` were specified in the call to `train`, a column called `weights` will also be in the data set.
> - `lev` is a character string that has the outcome factor levels taken from the training data. For regression, a value of `NULL` is passed into the function.
> - `model` is a character string for the model being used (i.e. the value passed to the  `method` argument of `train`).
>
>The output to the function should be a vector of numeric summary metrics with non-null names. By default, `train` evaluate classification models in terms of the predicted classes. Optionally, class probabilities can also be used to measure performance. To obtain predicted class probabilities within the resampling process, the argument `classProbs` in `trainControl` must be set to `TRUE`. This merges columns of probabilities into the predictions generated from each resample (there is a column per class and the column names are the class names).

(an example follows)

The `defaultSummary` help page could use more.  

Would you like to submit a PR?

**Comment by DarioS** [comment]
I made #716 in which I described `model` as being ignored, because it's not used inside the function.

**Comment by topepo** [comment]
`model` just isn't used in any functions in the package. I know of at least one person that uses that argument. 

Also, please move those changes to the R file:

> % Generated by roxygen2: do not edit by hand
> % Please edit documentation in R/postResample.R, R/prec_rec.R

Thanks
