### ISSUE TITLE
Model Lookup Returns Empty Labels

### ISSUE THREAD

**Issue by DarioS** [topepo/caret#714]
For example:

```
> modelLookup("slda")
  model parameter label forReg forClass probModel
1  slda parameter  none  FALSE     TRUE      TRUE
```

But, a more informative name than just "none" is retrieved by `getModelInfo`.

```
> getModelInfo("slda")
$slda
$slda$label
[1] "Stabilized Linear Discriminant Analysis"
...                ...
```

parameter being parameter also looks wrong.

**Comment by topepo** [comment]
This is a misnomner. `label` in `modelLookup` is a label for the tuning parameter. For example: 
```r
> modelLookup("pls")
  model parameter       label forReg forClass probModel
1   pls     ncomp #Components   TRUE     TRUE      TRUE
```
For `getModelInfo`, `label` is for the model and `$parameter$label` is the tuning parameter label:
```r
> getModelInfo("pls", FALSE)[[1]]$parameter
  parameter   class       label
1     ncomp numeric #Components
```

> parameter being parameter also looks wrong.

It does but isn't. That is the convention when a model has no parameters.
```r
> sum(vapply(getModelInfo(), function(x) any(x$parameter$label == "parameter"), logical(1)))
[1] 18
```
