### ISSUE TITLE
Documentation bug in The caret package: 3.6 Centering and Scaling

### ISSUE THREAD

**Issue by Triamus** [topepo/caret#724]
In [The caret package: 3.6 Centering and Scaling](https://topepo.github.io/caret/pre-processing.html) you say the following:
`The  preProcess  option  "ranges"  scales the data to the interval between zero and one.`
I think it should rather be
`The  preProcess  option  "range"  scales the data to the interval between zero and one.`
So the option is `range`.

**Comment by topepo** [comment]
Thanks!
