### ISSUE TITLE
Transparency and figures in the documentation

### ISSUE THREAD

**Issue by AndrewLawrence** [topepo/caret#728]
I just spotted some display problems in the [visualizations section](http://topepo.github.io/caret/visualizations.html) of the documentation.

The figures aren't displaying the glyphs (e.g. scatterplot points). They show axes, ticks and other display elements OK though. The following warning is produced after most figures:
\#\# Warning in grid.Call.graphics(C_points, x$x, x$y, x$pch, x$size): semi-
\#\# transparency is not supported on this device: reported only once per page

**Comment by topepo** [comment]
I'm about to rerun them for the new CRAN version. I'll fix it then. Thanks
