### ISSUE TITLE
Inactive unit tests

### ISSUE THREAD

**Issue by sergeykorop** [topepo/caret#729]
Some unit test files in [caret/pkg/caret/tests/testthat](https://github.com/topepo/caret/tree/master/pkg/caret/tests/testthat) have names without `test_` prefixes which are [required](http://r-pkgs.had.co.nz/tests.html) by `testthat` framework:

> Test structure
> A test file lives in tests/testthat/. Its name must start with test.

As a consequence, such files (e.g. [preProcess_methods.R](https://github.com/topepo/caret/blob/master/pkg/caret/tests/testthat/preProcess_methods.R)) are skipped when running the test suite with `devtools::test`.

**Comment by topepo** [comment]
Thanks. Made the change.
