### ISSUE TITLE
dummyVars transformation should ignore binary variables

### ISSUE THREAD

**Issue by sizhky** [topepo/caret#731]
When I apply dummy vars on the following data - 
```R
customers <- data.frame( id=c(10,20,30,40,50), gender=c('male','female','female','male','female'), mood=c('happy','sad','happy','sad','happy'), outcome=c(1,1,0,0,0))  
dmy <- dummyVars('~.', data=customers)
predict(dmy, customers)
```

```R
  id gender.female gender.male mood.happy mood.sad outcome
1 10             0           1          1        0       1
2 20             1           0          0        1       1
3 30             1           0          1        0       0
4 40             0           1          0        1       0
5 50             1           0          1        0       0
```

I obtain dummies for all the categorical attributes. But should there be a background check on if an attribute has only two levels? Why does one need dummies for gender.male and gender.female separately?

**Comment by topepo** [comment]
You have the option to get all of them of all but one. In `?dummyVars`:

> `fullRank`  A logical; should a full rank or less than full rank parameterization be used? If `TRUE`, factors are encoded to be consistent with `model.matrix` and the resulting there are no linear dependencies induced between the columns.
