### ISSUE TITLE
[Documentation] What's the meaning of `postResample`?

### ISSUE THREAD

**Issue by LaDilettante** [topepo/caret#738]
The [help page](https://rdrr.io/rforge/caret/man/postResample.html) describes `postResample(observed, predicted)` as

> Given two numeric vectors of data, the mean squared error and
> R-squared are calculated. For two factors, the overall agreement rate
> and Kappa are determined.

I don't understand how the name `postResample` makes sense here. I'd be happy to PR to clarify the documentation once I understand it.

1. What does `post` stand for? 

2. Why is there `Resample` in the name when we simply compare two vectors `observed` and `predicted` without any resampling?

**Comment by topepo** [comment]
That was never a very good name. 😩

The idea was that, after you've resampled the model, you have the observed and predicted values and the next step would be to summarize the results. So after (i.e. post) resampling, this would be what would happen.

**Comment by LaDilettante** [comment]
I usually understand `resampling` as cross-validation, bootstrap, etc. (Chapter 4.4 of your book "Resampling techniques" also supports this interpretation.)

But it seems like `resampling` means `predicting` here? How come "after you've resampled the model, you have the observed and predicted values"?

Thanks a lot for clarifying!

**Comment by topepo** [comment]
> But it seems like resampling means predicting here? 

Resampling is generally used in (at least) two ways. Traditional use of the bootstrap is to compute the sampling distribution of some statistic. For predictive modeling, resampling techniques are used to understand how well the model is doing without involving the test set. 

> How come "after you've resampled the model, you have the observed and predicted values"?

Technically you resample the data. For each resample, the model is built on one part of the split and evaluated on the other. For predictive modeling, "evaluate" means to compute some measure of model performance and this involves the predicted values.
