### ISSUE TITLE
bartmachine serialization

### ISSUE THREAD

**Issue by jasonqiangguo** [topepo/caret#739]
Hi Topepo,

I have a problem when applying train() with bartMachine model regarding serialization. Even if I set serialize = T in the function, the resulting model was not serialized.  See the following code. Is there any solution to this? 

```{R}
bartGrid <- expand.grid(num_trees = c(500, 1000), k = 2, alpha = 0.95, beta = 2, nu = 3)
model.bt <- train(as.factor(warstds)~., data=data.full, 
                            metric = "ROC", method = "bartMachine", 
                            tuneGrid = bartGrid, trControl = tc,  
                            num_burn_in = 2000, num_iterations_after_burn_in = 2000,
                            serialize = T)

pd_plot(model.bt, "gdpgrowth")

Error in check_serialization(bart_machine) : 
  This bartMachine object was loaded from an R image but was not serialized.
  Please build bartMachine using the option "serialize = TRUE" next time.
```
Thank you
Jason

**Comment by topepo** [comment]
__Please read this page__: [reprex = {repr}oducible {ex}ample](https://github.com/jennybc/reprex#what-is-a-reprex) 

Otherwise, it is difficult to help.

**Comment by jasonqiangguo** [comment]
Hi, I have updated the code, can you help to take a look at the problem? Thank you.

**Comment by topepo** [comment]
For it to be reproducible, I need a small data set to test with in the example and all of the objects references in the code.

**Comment by hadjipantelis** [comment]
@jasonqiangguo: `pd_plot` expects an object of class `bartMachine`. `model.bt` is of class `train`. The fact that `pd_plot` is not working seems expected. Please check the package `pdp`([R Journal link](https://journal.r-project.org/archive/2017/RJ-2017-016/index.html)); it accepts `caret`'s `train` object natively.

**Comment by jasonqiangguo** [comment]
pdp also has this problem of not being able to show the credible interval of probabilities for bartMachine. bartMachine is a strange case here as it is a classification but it also has probability predictions.

**Comment by jasonqiangguo** [comment]
@topepo Sorry that I did not come up with an example previously. 

Here is the toy example of the error:
```{R}
tc<-trainControl(method="cv",
                 number=2,#creates CV folds - 5 for this data
                 summaryFunction=twoClassSummary, # provides ROC summary stats in call to model
                 classProb=T)

x <- rpois(500, 30)
b <- rnorm(500, 0.02, 0.04)
y <- rbinom(500, 1, prob = pnorm(x * b))

dt <- as.data.frame(cbind(y, x))
dt$y<-factor(dt$y, levels=c(0,1),
             labels=c("peace", "war"))

bartGrid <- expand.grid(num_trees = c(500, 1000), k = 2, alpha = 0.95, beta = 2, nu = 3)
model.bt <- train(as.factor(y)~x, data=dt, metric = "ROC", method = "bartMachine",
                  tuneGrid = bartGrid, trControl = tc,  num_burn_in = 100, num_iterations_after_burn_in = 100, serialize = T)

pd_plot(model.bt, "x")

Error in check_serialization(bart_machine) : 
  This bartMachine object was loaded from an R image but was not serialized.
  Please build bartMachine using the option "serialize = TRUE" next time.
```

**Comment by topepo** [comment]
I can reproduce that the `pd_plot` call fails, even using `pd_plot(model.bt$finalModel, "x")`, but the model seems serialized:
```r
bartMachine:::check_serialization(model.bt$finalModel)
```
Looking more, it appears that it might be a bug in `pd_plot`. Around line 33 of that function, they have:
```r
    test_data = bart_machine$X[indices, ]
    test_data[, j] = rep(x_j_quants[q], n_pd_plot)
```
For these data at least, `bart_machine$X` has one column and subsetting without `drop = FALSE` reduces that to a vector:
```r
Browse[2]> str(bart_machine$X[indices,])
 num [1:500] 29 33 26 28 31 30 31 29 22 24 ...
```
and the next line subsets assuming that it is still a data frame `test_data[, j] ` and that fails. 

This mistake happens all the time and I think that everyone [regrets](https://stat.ethz.ch/pipermail/r-help/2002-July/023447.html) that choice now since:

> The reason is that `drop=` (however neat it seemed way back when we
invented it) messes up the ability to handle the object returned from
"`[`", because now we don't know what class of object will be returned,
even when we know the class of the argument(s).
