### ISSUE TITLE
Bug in TwoClassSim

### ISSUE THREAD

**Issue by wmuhanna** [topepo/caret#744]
https://github.com/topepo/caret/blob/87c1ac581d14c91cf2798b382ab233939ed2ca25/pkg/caret/R/twoClassSim.R#L219

Variable "j" undefined.  Line should be changed to:
shuffle <- sample(1:nrow(tmpData), floor(nrow(tmpData)*mislabel))

**Comment by topepo** [comment]
Oy! Yes, thanks for seeing that.
