### ISSUE TITLE
PCA as a preProcess option with time slicing

### ISSUE THREAD

**Issue by LJStroemsdoerfer** [topepo/caret#749]
Hi topepo, 

I am using PCA as a preProcess option in combination with the time slicing method as follows:

```{R}
set.seed(123)
seeds <- vector(mode = "list", length = 108)
for(i in 1:108) seeds[[i]] <- sample.int(1000, 5)
seeds[[109]] <- sample.int(1000, 1)

myTimeControl <- trainControl(method = "timeslice",
                                  initialWindow = 108,
                                  horizon = 1,
                                  fixedWindow = FALSE,
                                  allowParallel = FALSE,
                                  verboseIter = TRUE,
                                  seeds = seeds,
                                  preProcOptions = list(thresh = 0.85))

tuneLength.num <- 5

glmnet <- train(target ~ .,
                data = df_model,
                method = "lm",
                trControl = myTimeControl,
                preProcess = c("pca"),
                na.remove = TRUE,
                tuneLength = tuneLength.num)
```
My question is how the PCA works together with time slicing. Is it the case that:

(a) a PCA is applied to each resampling step individually; or 
(b) there is only one PCA applied to the full data set?

Thank you very much for your help and your great package.
Lukas

**Comment by topepo** [comment]
For (a), it will apply PCA to the resampled version of the data (used to fit the model) and then apply those loadings to the same data set as well as the holdout data set (used for prediction). This happens separately for each iteration of resampling. 

For (b), yes, once we get to the final model (on the whole training set), the PCA is done on the entire training set before served to the model fit function.

**Comment by LJStroemsdoerfer** [comment]
Thank you very much.

Best,
Lukas
