### ISSUE TITLE
gafs too slow

### ISSUE THREAD

**Issue by tinhb92** [topepo/caret#752]
Hi I'm trying to use gafs for feature selection and it's really too slow. I want to know the speed of others to check whether it is the package's fault.

Also it would be great if there's a counter to print out the current iteration so I can know the current progress.

**Comment by topepo** [comment]
"really too slow" doesn't really mean anything to me. You haven't shown any details of what you are analyzing, with what code, versions, operating system etc. Who knows?

> "Also it would be great if there's a counter to print out the current iteration so I can know the current progress."

If you look at the documentation, there is a who section about the output, such as:
```
This is an example of the output produced when gafsControl(verbose = TRUE) is used:

Fold2 1 0.715 (13) 
Fold2 2 0.715->0.737 (13->17, 30.4%) *
Fold2 3 0.737->0.732 (17->14, 24.0%) 
Fold2 4 0.737->0.769 (17->23, 25.0%) *
```
