### ISSUE TITLE
Typo in pkg/caret/R/resamples.R

### ISSUE THREAD

**Issue by benoit-vinsonneau-mpf** [topepo/caret#757]
Hi,

There is a typo in pkg/caret/R/resamples.R and I first saw the problem when I switch from R.3.3.x to R.3.4.2. Here is the fix (I believe the typos are self-explanatory e.g. "time" -> "times"). Producing a test-case would be quite cumbersome but I can do if required. 

$ git diff HEAD^^ HEAD pkg/caret/R/resamples.R
diff --git a/pkg/caret/R/resamples.R b/pkg/caret/R/resamples.R
index 691be39..7f4108c 100644
--- a/pkg/caret/R/resamples.R
+++ b/pkg/caret/R/resamples.R
@@ -129,9 +129,9 @@ resamples.default <- function(x, modelNames = names(x), ...) {
   getTimes <- function(x){
     out <- rep(NA, 3)
     if(all(names(x) != "times")) return(out)
-    if(any(names(x$times) == "everything")) out[1] <- x$time$everything[3]
-    if(any(names(x$times) == "final")) out[2] <- x$time$final[3]
-    if(any(names(x$times) == "prediction")) out[3] <- x$time$prediction[3]
+    if(any(names(x$times) == "everything")) out[1] <- x$times$everything[3]
+    if(any(names(x$times) == "final")) out[2] <- x$times$final[3]
+    if(any(names(x$times) == "prediction")) out[3] <- x$times$prediction[3]
     out
   }

**Comment by topepo** [comment]
Got it. Thanks!
