### ISSUE TITLE
could not find function "kernlab::vanilladot"

### ISSUE THREAD

**Issue by vermouthmjl** [topepo/caret#762]
Hi,

I stumbled on "Stopping" when doing something similar to this:
```
require(caret)
set.seed(42)
data_temp = data.frame(yvalue = rnorm(50),
                       X = rnorm(50))

temp = caret::train(
  form = yvalue~X , data = data_temp, 
  method = "gaussprLinear", 
  trControl = caret::trainControl(method = "cv"))
```
This code gives several warnings like
```
10: model fit failed for Fold10: parameter=none Error in `kernlab::vanilladot`() : 
  could not find function "kernlab::vanilladot"
```

By comparing the other places in the package where vanilladot is used, I think there might just need a parenthesis in this line:
https://github.com/topepo/caret/blob/6adf7faa6a9c3d7f50be415dda79e1273d9b1463/models/files/gaussprLinear.R#L11

**Comment by ThorstenDP** [comment]
Hi all,
I just installed caret via `devtools::install_github('topepo/caret/pkg/caret')` but only gaussprPoly seems to work. For for gaussprLinear and gaussprRadial get the folloing errors:

```
1: model fit failed for Fold01: parameter=none Error in `kernlab::vanilladot`() : 
  could not find function "kernlab::vanilladot"
...
```
```
1: model fit failed for Fold01: sigma=0.003597 Error in `kernlab::rbfdot`(sigma = 0.00359655918006055) : 
  could not find function "kernlab::rbfdot"
...
```
Cheers,
Thorsten

**Comment by vermouthmjl** [comment]
Hi Thorsten,
This problem was fixed in the pull request mentioned above. Try install the
dev version from github by doing
`devtools::install_github('topepo/caret')`.

Jiali

Thorsten <notifications@github.com>于2017年11月3日 周五下午11:24写道：

**Comment by ThorstenDP** [comment]
Hi Jiali,

thanks for for fast reply!

When I run:
`> devtools::install_github('topepo/caret')`

I get:
`Downloading GitHub repo topepo/caret@master
from URL https://api.github.com/repos/topepo/caret/zipball/master
Installation failed: Does not appear to be an R package (no DESCRIPTION)`

Anything else I can try?

Thanks a lot in advance!
Thorsten

**Comment by vermouthmjl** [comment]
actually it is

devtools::install_github('topepo/caret/pkg/caret')

**Comment by ThorstenDP** [comment]
This is what I tried first. Unfortunately, the version at "topepo/caret/pkg/caret" is one day older than your commit.

**Comment by vermouthmjl** [comment]
Okay. I seem to understand what the problem is. When I had the issue, I actually just used an earlier version from CRAN. If you really need the new version, maybe you could try something like in https://github.com/topepo/caret/tree/master/release_process.

**Comment by ThorstenDP** [comment]
OK ... Any idea when there will be a new version in pkg/caret ? ;-) 
Thanks again!

**Comment by topepo** [comment]
I'm shooting for the end of the month.

**Comment by ThorstenDP** [comment]
Thanks Max!
Looking forward to it!

**Comment by topepo** [comment]
I'll close this but comment more if there are issues.
