### ISSUE TITLE
createDataPartition and create Functions Inconsistent Documentation

### ISSUE THREAD

**Issue by DarioS** [topepo/caret#764]
If using `?createResample`, the `createDataPartition` help page is loaded. However, the Usage section does not specify the format of the function. It should be `(y, times = 10, list = TRUE)`. There's an example of it in the Examples section so I think the function should be formally defined in the Usage section.

Also, Section 5.3 of the documentation website states 

> By default, simple bootstrap resampling is used for line 3 in the algorithm above, which is `inTraining <- createDataPartition(Sonar$Class, p = .75, list = FALSE)`.

I find this to not be true, as every selection by `createDataPartition` has unique selections rather than what would be expected by resampling with replacement.

```
library(mlbench)
data(Sonar)

anyDuplicates <- sapply(1:1000, function(iteration)
{
  inTraining <- createDataPartition(Sonar$Class, p = 0.50, list = FALSE)
  any(table(inTraining) > 1)
})

> table(anyDuplicates)
anyDuplicates
FALSE 
 1000
```

It seems like there was some incomplete refactoring in the past. It's unclear how these two functions should be used by the end-user.

**Comment by topepo** [comment]
> If using ?createResample, the createDataPartition help page is loaded. However, the Usage section does not specify the format of the function. It should be (y, times = 10, list = TRUE). There's an example of it in the Examples section so I think the function should be formally defined in the Usage section.

The change to Roxygen documentation looks like it orphaned that function from usage. That's an easy fix. 

> Also, Section 5.3 of the documentation website states 
>
> > By default, simple bootstrap resampling is used for line 3 in the algorithm above, which is `inTraining <- createDataPartition(Sonar$Class, p = .75, list = FALSE)`.
> 
> I find this to not be true, as every selection by `createDataPartition` has unique selections rather than what would be expected by resampling with replacement.

You've misunderstood. The comment has "used for line 3 in the **algorithm** above" and not the code chunk above. It is referring to the [algorithm shown in section 5.1](https://topepo.github.io/caret/premade/TrainAlgo.png). 

The default resampling option is echoed in `?trainControl` if you ever need the official definition.
