### ISSUE TITLE
Issue Loading Package

### ISSUE THREAD

**Issue by bwnuo** [topepo/caret#766]
When I try to load the package there is the following error.

"Error: package or namespace load failed for ‘caret’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘robustbase’"

R version 3.4.2 (2017-09-28)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS Sierra 10.12.6

**Comment by victorgnnl** [comment]
I get the same error :

> library(caret)
Error: package or namespace load failed for ‘caret’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘robustbase’

R version 3.4.2
Windows 10, Version 10.0.16299 Build 16299
X64-based PC, AMD Ryzen 7 1700

**Comment by topepo** [comment]
Can you install `robustbase` and try again? I've noticed in the last year or so that, if you have multiple R sessions open and some packages open, you might not get them all installed.

**Comment by victorgnnl** [comment]
Thank you. Works. 
install.packages(c("robustbase"))

**Comment by dadashkarimi** [comment]
install fortran complier first and then install.packages("caret", dependencies = TRUE)
