### ISSUE TITLE
Number of learners crash R, many more always fail.

### ISSUE THREAD

**Issue by ran88dom99** [topepo/caret#772]
I'm a beginner working on https://github.com/ran88dom99/GeneratedRegMLBenchmark/wiki. 
bad.models=c("leapSeq","brnn","gamLoess","ANFIS","FIR.DM","FS.HGD","nodeHarvest","mlpWeightDecayML","monmlp","mlp","mlpWeightDecay","mlpSGD","rbf","rbfDDA","rfRules","GFS.FR.MOGUL","mlpML","HYFIS","GFS.THRIFT" ,"GFS.LT.RS")
Many of these crash R. Always Windows, R version 3.3.2.  Many more fail. [See bottom.](https://github.com/ran88dom99/GeneratedRegMLBenchmark/blob/master/7%20to%2010%20range%20asis%20cvhp%20first%20mlr%20importance/9th%20lcv%20hhp%20with%20reset%20n%20java%20n%20refail/9th%20lcv%20hhp%20with%20reset%20n%20java%20n%20refailFails.csv)

Am I doing something fundamentally wrong? Especially the crashes.

**Comment by hadjipantelis** [comment]
They are too many things that might have gone wrong. I do not think you can get any reasonable answers. Off the top of my head:
1. Maybe a model's formula or matrix interface was never properly working (*caret*-related issue), 
2. maybe the data you have, are not encoded correctly for one particular model (*application*-specific issue), 
3. maybe you are using an older (or newer) version of the packages associated with the model and the functions interface changed (*application*-specific issue), 
4. maybe you are using an older (or newer) version of the packages associated with the model and the older (or newer) versions have bugs (*third party*-specific issue), 
5. maybe `caret` introduced a bug that was not caught (*caret*-related issue).

Please try to narrow down to a specific model and then try to detect your problem in more detail. There might be an easy immediate work-around. For example the `gamLoess` fails to properly load the `gam` package beforehand so the loess fit fails as `lo` cannot be found. This is a *caret*-related issue but you could solve this issue it by calling `library(gam)` before running the model.

Please give accurate description of your system (output of `sessionInfo`) and code to reproduce the error you experience. You have linked against a 200k+ lines repo with literally hundreds of files.

**Comment by topepo** [comment]
I agree. These would be helpful if you use the current devel version and fill out an issue for each one, sticking as close to the repex template as possible. Otherwise, there really isn't much to do.
