### ISSUE TITLE
The confuse details of findCorrelation() when setting exact=True

### ISSUE THREAD

**Issue by zero-jack** [topepo/caret#785]
I first put up this question on [stackoverflow](https://stackoverflow.com/questions/47361025/r-the-confuse-details-of-findcorrelation-caret-package-when-setting-exact-t). The details is in it. In addition, I also have no idea the second example from [findCorrelation() document ](https://www.rdocumentation.org/packages/caret/versions/6.0-77/topics/findCorrelation) i.e.  

why there are first compared row 3 and column 2 instead of row 1 and column4 (since there is high correlation), and how the mean is calculated(0.35 vs 0.215) . Could it explain in details? It's hard to understand based on source code.

```
R2 <- diag(rep(1, 5))
R2[2, 3] <- R2[3, 2] <- .7
R2[5, 3] <- R2[3, 5] <- -.7
R2[4, 1] <- R2[1, 4] <- -.67

> findCorrelation(R2, cutoff = .65,verbose = TRUE)
Compare row 3  and column  2 with corr  0.7 
  Means:  0.35 vs 0.215 so flagging column 3 
Compare row 1  and column  4 with corr  0.67 
  Means:  0.223 vs 0.074 so flagging column 1 
[1] 3 1
```

**Comment by topepo** [comment]
I added a response to the SO post.

**Comment by zero-jack** [comment]
@topepo Thanks. But is there any paper describing why using this algorithm? For example, why are there two methods to remove high correlated variables ? (`re-evaluate the average correlations at each step` and `uses all the correlations regardless of whether they have been eliminated or not` ). Is it based on experience or mathematical reason?

**Comment by topepo** [comment]
This was something a computational chemist that I used to work with came up with. I"m not sure if there was an original reference. 

`exact` controls whether a computational shortcut should be used. I haven't seen a case where the shortcut fails but can't guarantee that there isn't one out there.
