### ISSUE TITLE
dummyVars on mixed dataframes

### ISSUE THREAD

**Issue by akrsrivastava** [topepo/caret#792]
Is it possible for dummyVars to work with dataframes with mixed data types, e.g those having factor as well as numeric variables. dummyVars should optionally automatically select all the factor variables and "dummyfy" them. On applying to the data frame, predict should return all dummyfied columns as well as the other remaining columns unchanged. I have used the dummies package and decided to try out caret::dummyVars but this is a feature I am missing.
Also, the help files suggest "The predict function produces a data frame." But I have found it to return a matrix.

**Comment by topepo** [comment]
Perhaps I'm not understanding your question:
```r
> obj <- dummyVars(~., data = iris)
> obj
Dummy Variable Object

Formula: ~.
5 variables, 1 factors
Variables and levels will be separated by '.'
A less than full rank encoding is used
> head(predict(obj, iris))
  Sepal.Length Sepal.Width Petal.Length Petal.Width Species.setosa Species.versicolor Species.virginica
1          5.1         3.5          1.4         0.2              1                  0                 0
2          4.9         3.0          1.4         0.2              1                  0                 0
3          4.7         3.2          1.3         0.2              1                  0                 0
4          4.6         3.1          1.5         0.2              1                  0                 0
5          5.0         3.6          1.4         0.2              1                  0                 0
6          5.4         3.9          1.7         0.4              1                  0                 0
```

**Comment by akrsrivastava** [comment]
It seems there was some confusion on my part. dummyVars is indeed working as per expectation. Closing this issue.
