### ISSUE TITLE
Error when training a ranger model with factor variables (with solution)

### ISSUE THREAD

**Issue by jgellar** [topepo/caret#794]
I've been trying to train a model with `method="ranger"` and was getting the following error:

```
fit <- train(fmla, mydata, method = "ranger", trControl = ctrl1, tuneLength = 3, metric = "ROC")
Error in `[.data.frame`(data, , independent_vars, drop = FALSE) : 
  undefined columns selected
```

Took me awhile to figure out, but I found the cause (and solution), which I wanted to share. The error was related to some of the factor variables in my data. There were two issues that had to be fixed with the factor variables:

1. I had some factor variables that had levels with counts of 0. I had to make sure to drop those levels from the factor.
2. Some of the levels of my factor had characters that were not alpha-numeric, which were causing problems. I'm not sure exactly what characters were causing the problems, it might have just been white space. But when I stripped the factor levels of all non-alphanumeric characters with the following code, everything worked:

```
levels(x) <- gsub(pattern = "[^A-Z,a-z,0-9]", replacement = "", levels(x))
```

I was not getting the error when I fit the model directly using `ranger()`, so it must be somewhere in the pre-processing. I also was not getting the error when I ran some other models, including `rf`, so it seems specific to `ranger`.

Of the two issues above, the first is not as important... that's probably on me for providing bad data. However, it's notable that this only causes a problem when using `ranger` through `train`, so perhaps it should be fixed. The second one I think is more essential to be fixed.

Sorry for not posting a MRE, but since I have a solution, this is more of a "feature request" than a "bug report". Let me know if you have problems reproducing the error on your end.

**Comment by topepo** [comment]
You'll need to send along a small reproducible example along with the results of `sessionInfo()` for me to troubleshoot more.

Please see the issue template for how to do that.

**Comment by jgellar** [comment]
As I mentioned, I have found a work-around, so there's nothing motivating me to dig into this anymore. But it is a bug that you probably should look into.
