### ISSUE TITLE
rfe with NA's and ROC metric

### ISSUE THREAD

**Issue by efh0888** [topepo/caret#795]
Having two issues and trouble finding discussions about either:

1. Want to use the RFE function, but my data has NA's.  There doesn't seem to be any mechanism for handling this.  Is row deletion my only option?
2. Also would like to use ROC instead of Accuracy, so I set the summary element in the functions list to be twoClassSummary.  Still getting the warning "Metric 'ROC' is not created by the summary function; 'Accuracy' will be used instead."

This is what I've tried so far...
```
rfe_funcs <- rfFuncs
rfe_funcs$summary <- twoClassSummary
rfe_ctrl <- rfeControl(functions = rfFuncs, method = 'cv', number = 5, verbose = TRUE)
rfe_profile <- rfe(x = predictors, y = response, rfeControl = rfe_ctrl, metric = 'ROC', na.action = na.pass, preProcess = 'medianImpute')
```

**Comment by topepo** [comment]
For the first problem, your best option is to do imputation (or any other approach) inside of the `fit` component and attach any required objects to the model object. 

For the second, use `functions = rfe_funcs ` instead of `functions = rfFuncs`

**Comment by efh0888** [comment]
Hey Max, I never circled back to this at the time, but am now working on another project where I'd like to utilize this. I did what you said regarding the first problem. But for the second issue, even though now I'm using rfe_funcs, I'm getting an error saying I need to set classProbs = TRUE. However, it's not an available argument in rfeControl. Is there a way around this? Thanks.
