### ISSUE TITLE
Feature request : Adding a 2nd hidden layer in Multilayer perceptron (monmlp)

### ISSUE THREAD

**Issue by wbsb1234** [topepo/caret#798]
As of today, using "monmlp" method, it's only possible to add a single hidden layer via Caret.

I'd like to suggest to add a "hidden2" hyperparameter to "monmlp" method for multilayer perceptron.

For info, this option is already present in the "monmlp" original package. 

Thank you for your help

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
