### ISSUE TITLE
Multiclass prediction w/ svmRadial

### ISSUE THREAD

**Issue by monogenea** [topepo/caret#800]
R version 3.4.2 (2017-09-28) -- "Short Summer"

Hi Max, one year ago I had a script that modelled radial SVMs, among other models. Recently I re-ran the code and found that the radial SVM results were not reproduced - Acc/Kappa were systematically constant (Kappa specifically was null) across a wide range of independent prediction problems.

```{R}
library(caret)
X <- matrix(rnorm(251*272), 251, 272)
colnames(X) <- 1:272
Y <- sample(c("A","B","C","D","E"), 251, replace = T)
stratFolds <- createMultiFolds(Y, k = 3, times = 5)
ctrl <- trainControl(method = "repeatedcv", index = stratFolds)
svmFit <- train(x = X, y = Y,
                      method = "svmRadial",
                      metric = "Kappa",
                      trControl = ctrl,
                      tuneLength = 15)
```
No matter what the seed is, the output is always the same - constant accuracy and Kappa. Maybe something to do with memory or max iterations from `kernlab`? Cheers

**Comment by topepo** [comment]
It's a bug in `caret`; use the devel version (which has been waiting for CRAN approval for about a week)

**Comment by monogenea** [comment]
That's a big relief, for a moment I thought I messed up with the data. Thanks a lot for replying in such short notice. Keep up the excellent work!
