### ISSUE TITLE
Trying logLoss : Error in ctrl$summaryFunction(testOutput, lev, method) :   

### ISSUE THREAD

**Issue by oipa00** [topepo/caret#810]
Hello,

I'm trying to test different machine learning models using a dataset from kaggle (https://www.kaggle.com/uciml/mushroom-classification) with caret and I'm running into an error I don't know how to solve:

Error in ctrl$summaryFunction(testOutput, lev, method) : 
  'data' should have columns consistent with 'lev'

I need to use LogLoss metric. The thing is that when I use train() with 'logitBoost' it works fine, but when I change the method for example to 'lssvmRadial' or 'knn' I get this error and there is no modifications in the dataset.... I cannot understand why this is happening.

I attach you the .R file,  I will be very happy if you could help me
[mushroom.txt](https://github.com/topepo/caret/files/1604459/mushroom.txt)

Thank you in advance!

**Comment by oipa00** [comment]
I have also try with ROC metric by changing the 'metric' parameter and setting a new trainControl but without success,  now I'm obtaining a new different error:

```{r}
control3 <- trainControl(method="repeatedcv",summaryFunction=twoClassSummary, 
                        number=10, repeats=3,verboseIter=TRUE, classProbs=TRUE)
metric="ROC"

start.time <- Sys.time()
set.seed(seed)
svm_mod <- train(class ~ ., data=training,method="lssvmRadial",
                 trControl=control3, metric = metric,
                 maximize = FALSE)
end.time <- Sys.time()
svm_time <- end.time - start.time
```



Error in evalSummaryFunction(y, wts = weights, ctrl = trControl, lev = classLevels,  : 
  train()'s use of ROC codes requires class probabilities. See the classProbs option of trainControl()
In addition: Warning message:
In train.default(x, y, weights = w, ...) :
  Class probabilities were requested for a model that does not implement them

I suppose this is a problem with the levels of training$class so I have tried this:

```{r}
feature.names=names(training)

for (f in feature.names) {
  if (class(training$class)=="factor") {
    levels <- unique(c(training$class))
    training$class <- factor(training$class,
                         labels=make.names(levels))
  }
}
```

I also tried making training$class 0/1  and Yes/No but a cannot figured out what I'm doing wrong, I don't achieve any good results....

Looking forward to your response...

**Comment by topepo** [comment]
> Class probabilities were requested for a model that does not implement them

> `train()`'s use of ROC codes requires class probabilities.

That particular model doesn't produce class probabilities so the area under the ROC curve can't be calculated.
