### ISSUE TITLE
Training using awtan method fails with error Error : 'lpawnb' is not an exported object from 'namespace:bnclassify'

### ISSUE THREAD

**Issue by crazybilly** [topepo/caret#815]
When trying to train a model using the awtan method, `caret::train()` fails with the following error(s):

    model fit failed for Resample04: score=bic, smooth=1 Error : 'lpawnb' is not an exported object from 'namespace:bnclassify'

See [my question on StackOverflow](https://stackoverflow.com/questions/48306658/awtan-method-in-carettrain-fails-with-error-lpawnb-is-not-an-exported-objects) for a reproducible example. 

Based on the [release notes](https://github.com/bmihaljevic/bnclassify/releases) for bnclassify v0.3.2, it appears that bnclassify has replaced `lpawnb()` with `lp()`. 

Currently `getModelInfo('awtan') defines $awtan$fit as:

    function (x, y, wts, param, lev, last, classProbs, ...) 
    {
        dat <- if (is.data.frame(x)) 
            x
        else as.data.frame(x)
        dat$.outcome <- y
        struct <- bnclassify::tan_cl(class = ".outcome", dataset = dat, 
            score = as.character(param$score))
        bnclassify::lpawnb(struct, dat, smooth = param$smooth, trees = 10, 
            bootstrap_size = 0.5, ...)
    }

**Comment by topepo** [comment]
Their [news file](https://github.com/bmihaljevic/bnclassify/blob/master/NEWS.md) has it as deprecated. I'll have to write a new method.
