### ISSUE TITLE
Feature Request: Support for multivariate Y

### ISSUE THREAD

**Issue by jcpetkovich** [topepo/caret#816]
From what I can tell, the `caret` framework does not support multivariate `y` targets for regression. This is a subject I'm currently working with.

Is there any reasonable path to adding this functionality to caret? It's almost exactly what I wanted for comparing multivariate regression models, but now that I realized that it doesn't support this type of model, I'm waffling between implementing it myself, and contributing to caret to get it done. For the latter, I'm just not quite sure where to start.

What do you think?

**Comment by schelhorn** [comment]
Concerning models, I can recommend https://cran.r-project.org/web/packages/mvtboost/index.html (latest dev version from GitHub) and https://cran.r-project.org/web/packages/randomForestSRC/index.html for that purpose.

**Comment by topepo** [comment]
> Is there any reasonable path to adding this functionality to caret? 

No, not without some invasive changes. 

The system that I'm designing now to work more like `dplyr` will handle this (as `recipes` easily accommodates multivariate outcomes). You would have to write some code, you you can do it with [`rsample`](https://topepo.github.io/rsample/index.html) right now. Do you have an example with a public data set? I could prototype it and use it as another example.

**Comment by jcpetkovich** [comment]
Unfortunately the datasets I'm working with are locked up under an NDA. However, the datasets and examples in the packages linked by @schelhorn are conceptually similar if you're looking for examples.

**Comment by topepo** [comment]
I cooked [this up](https://topepo.github.io/recipes/articles/articles/Multivariate_PLS.html) (not the best example) that should give you an idea on how to work with multivariate outcomes with those packages. 

The API is low-level (for now) but there are other examples of tuning models this way. My Rstudio conference workshop has a lot of examples and those materials will be available on GihHub next week.

**Comment by jcpetkovich** [comment]
Very cool! I look forward to reading through them!

**Comment by topepo** [comment]
[https://github.com/topepo/rstudio-conf-2018](https://github.com/topepo/rstudio-conf-2018). Video will be available at some point.
