### ISSUE TITLE
ggplot.train attempts to use shape aesthetic for geom_line

### ISSUE THREAD

**Issue by ray-p144** [topepo/caret#818]
When using ggplot to plot a `train` object with 2 or more varying tuning parameters, the function attempts to use a `shape` aesthetic for geom_line which is not recognized by ggplot and throws the warning
```Warning: Ignoring unknown aesthetics: shape```
The line causing the issue is [here](https://github.com/topepo/caret/blob/b2b0d68356fe0a2047f625bde37629f3f1dee085/pkg/caret/R/ggplot.R#L102).

Minimum reproducible example:
```
library(caret)
data(iris)
TrainData <- iris[,1:4]
TrainClasses <- iris[,5]
fit <- train(TrainData, TrainClasses,
                 method = "ranger",
                 preProcess = c("center", "scale"),
                 tuneLength = 10,
                 trControl = trainControl(method = "cv"),
                 tuneGrid = expand.grid(mtry = 1:3,
                                        splitrule = c("gini"),
                                        min.node.size = c(1:5)))
ggplot(fit)
```

I would suggest the `shape` aesthetic be dropped from the line linked above or be changed to ```linetype```

**Comment by topepo** [comment]
Thanks. I just removed the shape aesthetic.
