### ISSUE TITLE
Use LOOCV performance function for repeatedcv in caret train

### ISSUE THREAD

**Issue by BU-1** [topepo/caret#824]
Is there a way to use the LOOCV performance function (combine all of the hold-out predictions) instead of the typical repeatedcv performance function (take the average of the hold-out predictions on each fold/repeat) to determine the best tuning parameter in repeatedcv? This would change the data frame of tuning parameters that gets passed to the selectionFunction.

**Comment by topepo** [comment]
`method = "LOOCV"` is an option in `trainControl`.

**Comment by BU-1** [comment]
I have used both "LOOCV" and "repeatedcv"
