### ISSUE TITLE
Feature request: metric = "deviance" when running logistic regression via glmnet

### ISSUE THREAD

**Issue by MarkusTMattsson** [topepo/caret#830]
The title says it all: I would really appreciate the implementation of deviance as a metric for logistic regression, i.e. I would like to be able to say:

train(y ~., data = training2,
                             method = "glmnet",
                             family = "binomial",
                             metric = "deviance",
                             trControl = caretTraining,
                             tuneGrid = toyGrid,
                             standardize = TRUE)

Thank you for your hard work!

**Comment by topepo** [comment]
log-loss is already that. IIRC deviance is just -2LL
