### ISSUE TITLE
Caret/ggplot2 issue?

### ISSUE THREAD

**Issue by sgoodm8** [topepo/caret#840]
Hey everyone,

Fairly new programmer working on a project for school, trying to do some data set preprocessing before running various regressions and neural networks.

Trying to install the library(caret) package to use the preProcess function but doesn't seem to be working. Code and error message are the following:

> library(caret)
Loading required package: ggplot2
Error: package or namespace load failed for ‘ggplot2’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 namespace ‘pillar’ 1.0.1 is being loaded, but >= 1.1.0 is required
Error: package ‘ggplot2’ could not be loaded
> 

Tried uninstalling my previously installed ggplot2 package and re-installing using install.packages("ggplot2", dep=TRUE) and the same problem persisted. If anyone has any answers, it'd be much appreciated!

**Comment by topepo** [comment]
I've seen this occur when people have R sessions going where those packages are already loaded. Try closing any open sessions and reinstalling. 

I spoke to people in our group to figure out why this occurs but it looks like there are a lot of ways that this can happen. 

We are developing a potential solution that you could try out:
```r
devtools::install_github("r-lib/pkgman")
library(pkgman)
pkg_install("ggplot2")
```
