### ISSUE TITLE
`binaryEncoding` and/or `numericalEncoding` in `preProcess`.

### ISSUE THREAD

**Issue by hadjipantelis** [topepo/caret#842]
This may be a huge can of worms as it relates to `preProcess` but is it worth to consider the option to allow for `binaryEncoding` and/or `numericalEncoding` of categorical variables? 
Transforming nominal variables to numerical variables seems to helpful in certain cases. For example `catboost` is actively considering it ( https://tech.yandex.com/catboost/doc/dg/concepts/algorithm-main-stages_cat-to-numberic-docpage/ ) and a benchmark I saw around the net ( https://medium.com/data-design/visiting-categorical-features-and-encoding-in-decision-trees-53400fa65931 ) seems to be indicate that it can be helpful. 

I would probably consider putting it under `recipes` appropriate. 

Just an idea!

Pantelis

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
