### ISSUE TITLE
How to recommend new algorithms...

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#843]
Hi Max,

How do we proceed to recommend new algorithms to be consider for `caret`?.
Should we open an issue here?

I know that you keep this [page](https://github.com/topepo/caret/projects/2) in a kanban. Just in case, we could include them in this page.

Thanks,
Carlos.

**Comment by topepo** [comment]
The project page is best (and maybe send me an email to make sure that I see it).

**Comment by coforfe** [comment]
OK. Thanks.
I have just been seeing how to include a new issue/request in the project page, but sorry I could not find the way to do that... 

I am going to open a new issue while I understand how to do that.

Thanks.
Carlos.
