### ISSUE TITLE
[New Model]: liquidSVM

### ISSUE THREAD

**Issue by coforfe** [topepo/caret#844]
`liquidSVM` is already a quite stable package that enhances how to deal with SVM on high dimensional and large datasets in a very novel way. Overcoming the speed limitations that SVM has for this kind of datasets.

**[liquidSVM](https://cloud.r-project.org/web/packages/liquidSVM/index.html)**

Thanks,
Carlos.

**Comment by topepo** [comment]
This is a good idea and is implemented in `parsnip`. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
