### ISSUE TITLE
plot.train custom method plotting

### ISSUE THREAD

**Issue by ck2136** [topepo/caret#846]
Hello!

After starting a new R session and installing the latest version... I couldn't get the plotting to work so I'm asking for help.

I suppose the plotting is not working because I've set up a new method. Here is the minimal example

```{R}
# load mtcars data as example
data("mtcars")

# create our custom method to have minsplit added to the cross validation 
rpart_ck <- getModelInfo("rpart", regex = FALSE)[[1]]

# add minsplit parameter
rpart_ck$parameters <- data.frame(parameter = c("cp", "minsplit"),
                                  class = rep("numeric",2),
                                  label = c("Complexity","MinimumSplit"))

# modify grid function
rpart_ck$grid <- function(x, y, len = NULL, search = "grid") {
  library(rpart)
  
  dat <- if(is.data.frame(x)) x else as.data.frame(x)
  dat$.outcome <- y
  
  initialFit <- rpart::rpart(.outcome ~ .,
                             data = dat,
                             control = rpart::rpart.control(cp = 0,
                                                            minsplit = 1))$cptable
  initialFit <- initialFit[order(-initialFit[,"CP"]), , drop = FALSE]
  if(search == "grid") {
    if(nrow(initialFit) < len) {
      tuneSeq <- expand.grid(cp = seq(min(initialFit[, "CP"]),
                                      max(initialFit[, "CP"]),
                                      length = len),
                             minsplit = seq(1,
                                            nrow(dat)/2,
                                            length = len))
    } else tuneSeq <-  expand.grid(cp = initialFit[1:len,"CP"],
                                   minsplit = seq(1:nrow(dat), length = len))
    colnames(tuneSeq) <- c("cp","minsplit")
  } else {
    tuneSeq <- expand.grid(cp = unique(sample(initialFit[, "CP"], size = len, replace = TRUE)),
                           minsplit = unique(sample(nrow(dat)/2, size = len, replace = TRUE)))
  }
  
  tuneSeq
}

rpart_ck$fit <- function(x, y, wts, param, lev, last, classProbs, ...) {
  cpValue <- if(!last) param$cp else 0
  minsplitValue <- if(!last) param$minsplit else 0
  theDots <- list(...)
  if(any(names(theDots) == "control"))
  {
    theDots$control$cp <- cpValue
    theDots$control$minsplit <- minsplitValue
    theDots$control$xval <- 0
    ctl <- theDots$control
    theDots$control <- NULL
  } else ctl <- rpart::rpart.control(cp = cpValue, minsplit = minsplitValue, xval = 0)
  
  ## check to see if weights were passed in (and availible)
  if(!is.null(wts)) theDots$weights <- wts
  
  modelArgs <- c(list(formula = as.formula(".outcome ~ ."),
                      data = if(is.data.frame(x)) x else as.data.frame(x),
                      control = ctl),
                 theDots)
  modelArgs$data$.outcome <- y
  
  out <- do.call(rpart::rpart, modelArgs)
  
  if(last) out <- rpart::prune.rpart(out, cp = param$cp)
  out
}

set.seed(123)
cvCtrl <- trainControl(method = "repeatedcv",
                       # 5-cv...
                       number = 3,
                       # repeat 2 times
                       repeats = 3,
                       summaryFunction = twoClassSummary
                       ,
                       classProbs = TRUE,
                       sampling = "up"
)

tuneGrid <- expand.grid(cp = seq(0, 0.1, length.out = 10),
                        minsplit = seq(10, 50, by = 10))

# change am variable to character
mtcars$am <- ifelse(mtcars$am == 1, "Man", "AM")

rpart_ck_prof <- caret::train(am ~ ., data = mtcars,
                              method = rpart_ck,
                              #tuneLength = 10,
                              trControl = cvCtrl,
                              tuneGrid = tuneGrid,
                              metric = 'ROC',
                              preProc = c("center","scale","nzv"))


plot(rpart_ck_prof, metric = "ROC", highlight = TRUE)

### session info
sessionInfo()
```

Here is the plot I get
![plot_train](https://user-images.githubusercontent.com/21317713/36769722-60cfa8fa-1c03-11e8-8e13-8ec6908867aa.png)

The plot that I would like is multiple lines that depict the minimum split. The example I have is multiple lines of the regularization parameter (using glmnet method)
![caret_plotwant](https://user-images.githubusercontent.com/21317713/36769782-b5e97bb8-1c03-11e8-8e80-caea4de60cff.png)

Thanks!

Here is the session info:
R version 3.4.2 (2017-09-28)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] mlbench_2.1-1   bindrcpp_0.2    dplyr_0.7.4     caret_6.0-78   
[5] ggplot2_2.2.1   lattice_0.20-35 RANN_2.5.1     

loaded via a namespace (and not attached):
 [1] purrr_0.2.3        reshape2_1.4.2     kernlab_0.9-25    
 [4] splines_3.4.2      colorspace_1.3-2   stats4_3.4.2      
 [7] survival_2.41-3    prodlim_1.6.1      rlang_0.1.2       
[10] ModelMetrics_1.1.0 withr_2.0.0        glue_1.1.1        
[13] foreach_1.4.3      plyr_1.8.4         bindr_0.1         
[16] dimRed_0.1.0       lava_1.5.1         robustbase_0.92-7 
[19] stringr_1.2.0      timeDate_3012.100  munsell_0.4.3     
[22] gtable_0.2.0       recipes_0.1.0      codetools_0.2-15  
[25] parallelMap_1.3    parallel_3.4.2     class_7.3-14      
[28] DEoptimR_1.0-8     Rcpp_0.12.13       scales_0.5.0      
[31] backports_1.1.1    checkmate_1.8.4    ipred_0.9-6       
[34] CVST_0.2-1         stringi_1.1.5      BBmisc_1.11       
[37] RcppRoll_0.2.2     ddalpha_1.3.1      grid_3.4.2        
[40] tools_3.4.2        magrittr_1.5       lazyeval_0.2.0    
[43] glmnet_2.0-13      tibble_1.3.4       mlr_2.11          
[46] DRR_0.0.2          pkgconfig_2.0.1    MASS_7.3-47       
[49] Matrix_1.2-11      data.table_1.10.4  ParamHelpers_1.10 
[52] lubridate_1.6.0    gower_0.1.2        assertthat_0.2.0  
[55] iterators_1.0.8    R6_2.2.2           rpart_4.1-11      
[58] sfsmisc_1.1-1      nnet_7.3-12        nlme_3.1-131      
[61] compiler_3.4.2

**Comment by topepo** [comment]
To make it work, you would have to modify the `loop` element of the `rpart` code too. The easiest thing would be to remove it using 
```r
rpart_ck$loop <- NULL
```
You would lose some optimizations but `rpart` is pretty fast regardless. If you want to modify it, take a look [here](https://topepo.github.io/caret/using-your-own-model-in-train.html#Components).
