### ISSUE TITLE
Caret mvrValstats Error Message

### ISSUE THREAD

**Issue by jahneldardavik** [topepo/caret#848]
I try to run caret, but get an error messge:
Error in mvrValstats(object = object, estimate = "train") : 
  could not find function "mvrValstats"

Here is what I do:

arcene <- read.table('http://archive.ics.uci.edu/ml/machine-learning-databases/arcene/ARCENE/arcene_train.data', sep =' ',colClasses = c(rep('numeric',10000),'NULL'))
#head(arcene)
#dim(arcene)
#head[1:4, 1:20]
str(arcene)
arcene$class <- factor(scan('https://archive.ics.uci.edu/ml/machine-learning-databases/arcene/ARCENE/arcene_train.labels', sep = '\t'))

any(is.na(arcene))

set.seed(100)
myfolds <- createMultiFolds(arcene$class, k = 5, times = 10)
control <- trainControl('repeatedcv', index = myfolds, selectionFunction = 'oneSE')

mod1 <- train(class ~ ., data = arcene, method = 'pls', metric = 'Accuracy', tuneLength = 20, trControl = control, preProc = c('zv','center','scale'))
plot(mod1)
plot(varImp(mod1),10, main = 'PLS')

The last plot statement results in this error message:
Error in mvrValstats(object = object, estimate = "train") : 
  could not find function "mvrValstats" 

Advice is greatly appreciated.

Thank you
jahn davik

**Comment by topepo** [comment]
It is a bug that I'll fix in the upcoming release. In the meantime, load the `pls` package before computing the importances.

**Comment by jahneldardavik** [comment]
OK.
Thank you.
Which release can I go back to in order to avoid the error?

jahn

Fra: Max Kuhn [mailto:notifications@github.com]
Sendt: 1. mars 2018 23:48
Til: topepo/caret <caret@noreply.github.com>
Kopi: Jahn Davik <jahn.davik@nibio.no>; Author <author@noreply.github.com>
Emne: Re: [topepo/caret] Caret mvrValstats Error Message (#848)


It is a bug that I'll fix in the upcoming release. In the meantime, load the pls package before computing the importances.

**Comment by topepo** [comment]
No need to change versions. Just load the `pls` package before you do the importance calculations.
