### ISSUE TITLE
extractProb Incorrect dimensions when X Has One Column

### ISSUE THREAD

**Issue by ray-p144** [topepo/caret#849]
When using the `extractProb` function on a model that was trained with only one column in `X`, the following error is thrown:
```
Error in newdata[, object$method$center, drop = FALSE] : 
  incorrect number of dimensions
```

The problem seems to be caused by this [line](https://github.com/topepo/caret/blob/0e6aa496bf9f01b478ceca596c0d5a1a21f1497f/pkg/caret/R/extractProb.R#L23) when the `data.frame` is turned into a `vector`.

Minimum reproducible example:
```
library(caret)
TrainData <- data.frame(x = runif(100))
TrainClasses <- sample(c("Y", "N"), 100, TRUE)
fit <- train(TrainData, TrainClasses,
             method = "glm",
             preProcess = c("center", "scale"),
             trControl = trainControl(method = "cv", classProbs = TRUE))
extractProb(list(fit))
```

I would suggest adding the argument `drop = FALSE` like the `extractPrediction` function has in this [line](https://github.com/topepo/caret/blob/0e6aa496bf9f01b478ceca596c0d5a1a21f1497f/pkg/caret/R/extractPrediction.R#L15)

**Comment by topepo** [comment]
Yep! That bug has been around for _more+ than 
```r
> difftime(now(), ymd_hm("2007-10-05 12:21"), units = "weeks")
Time difference of 542.9203 weeks
```
