### ISSUE TITLE
Fixing some hyperparameters

### ISSUE THREAD

**Issue by jgonzalezab** [topepo/caret#851]
Hey there!

While working with caret I had this doubt/suggestion,
Is there any way to fix some hyperparameters while searching by random (search = 'random') over others?

I was trying to fit a weighted K-nearest neighbour model to my data with the 'random' option on, the problem was that sometimes the value of k (the number of neighbours) was randomly selected to be a high value (in some cases this has no much sense). I suspect that this can happen also with other hyperparameters for different kind of models. Is there a solution for this?

Thanks in advance.

P.D. I really love Caret!

**Comment by topepo** [comment]
The best that I can think of is to pre-generate the random grid and then change the value ranges to something that is better. For example:

```r
> kknn_code <- getModelInfo("kknn")[[1]]$grid
> 
> set.seed(555)
> r_grid <- kknn_code(iris[, 1:4], iris$Species, len = 20, search = "random")
> summary(r_grid)
      kmax          distance              kernel 
 Min.   : 1.00   Min.   :0.1699   triangular :5  
 1st Qu.:16.75   1st Qu.:0.6078   biweight   :3  
 Median :29.50   Median :0.7547   rectangular:3  
 Mean   :27.55   Mean   :0.9703   cos        :2  
 3rd Qu.:40.75   3rd Qu.:1.2287   gaussian   :2  
 Max.   :49.00   Max.   :2.7040   inv        :2  
                                  (Other)    :3  
> 
> r_grid$kmax <- sample(1:20, size = nrow(r_grid), replace = TRUE)
> summary(r_grid)
      kmax          distance              kernel 
 Min.   : 1.00   Min.   :0.1699   triangular :5  
 1st Qu.: 6.75   1st Qu.:0.6078   biweight   :3  
 Median : 9.00   Median :0.7547   rectangular:3  
 Mean   : 9.40   Mean   :0.9703   cos        :2  
 3rd Qu.:13.00   3rd Qu.:1.2287   gaussian   :2  
 Max.   :18.00   Max.   :2.7040   inv        :2  
                                  (Other)    :3  
```

**Comment by jgonzalezab** [comment]
Thank you for the response, I think I'll do something similar to your approach
