### ISSUE TITLE
segfault in R3.4.3 on Mac

### ISSUE THREAD

**Issue by vnijs** [topepo/caret#852]
Myself and my students using macOS are not able to use caret with `metric = "ROC"` as it produces a segfault. Example code shown below. I have been able to reproduce on multiple different datasets and estimation algorithms. The segfault message refers to ModelMetrics_auc. I posted an issue for ModelMetrics but have not had a response yet. Do you have suggestions for a work-around?

See original issue: https://github.com/JackStat/ModelMetrics/issues/23

```
## loading libraries
library(ranger)
library(caret)

dat <- mtcars
dat$vs <- factor(ifelse(dat$vs == 1, "yes", "no"))
sapply(dat, class)

ranger(
  vs ~ ., 
  data = dat, 
  probability = TRUE, 
  num.trees = 50, 
  mtry = 3
)

set.seed(1234)
grid <- expand.grid(mtry = 3:4, splitrule = "gini", min.node.size = 1)
ctrl <- trainControl(
  method = "cv", 
  number = 5, 
  classProbs = TRUE, 
  summaryFunction = twoClassSummary, 
  verboseIter = TRUE
)

result <- train(
  vs ~ ., 
  data = dat,
  method = "ranger", 
  trControl = ctrl, 
  tuneGrid = grid, 
  metric = "ROC", 
  verbose = FALSE
)
```

**Comment by topepo** [comment]
Please don't open duplicate issues. I'll take a look at the other one.
