### ISSUE TITLE
Discussion: Multi-class, imbalanced data set, with high penalty for false positives

### ISSUE THREAD

**Issue by BU-1** [topepo/caret#857]
I am looking for some guidance on what I should try to improve my model performance. I am working with a multi-class data set (A, B, and C) that is imbalanced (A ~ 7%, B ~ 7%, C ~ 86%). For my problem, a false positive is much more costly than a false negative so I have been using the following penalty matrix in a custom `summaryFunction` to select the best tuning parameters:
`PenaltyMatrix = matrix(c(0,2,4,1,0,2,2,1,0), byrow = TRUE, nrow = 3)`

However, I would still like to use my penalty matrix in the "internal" model learning. I have been passing my penalty matrix to `rpart` and `C5.0`, but they do not perform nearly as well as `xgbTree` (which doesn't allow you to use a cost matrix). Is there a boosted tree model that takes a custom cost matrix? I am open to any other suggestions, really just looking for some new options to explore.

Thanks!

**Comment by topepo** [comment]
> Is there a boosted tree model that takes a custom cost matrix? 

I don't know of any others. You can try bagging the CART model with costs by passing the cost argument in `ipred`'s bagging function. I've gotten worse results by doing that. It's worth a try though. You could also try class weights in SVM and neural network models too (`svmLinearWeights`, `svmRadialWeights`, and `mlpKerasDropoutCost`). See the section on [cost-sensitive learning](https://topepo.github.io/caret/train-models-by-tag.html#cost-sensitive-learning).  

The original CART book noted that, when using costs, the trees tended to favor smaller and simpler models and I've seen that too.
