### ISSUE TITLE
optimism_boot error still appears if train.recipe() is used with doParallel on windows

### ISSUE THREAD

**Issue by o1iv3r** [topepo/caret#860]
Hi,

I the optimism_boot error occurs whenever I use train.recipe() and doParallel on windows. I posted a question on stackoverflow that inlcudes a reproducible example:

https://stackoverflow.com/questions/49366115/caret-error-if-doparallel-and-recipes-is-used

Perhaps the error was only fixed for the other train interfaces?

Thanks!

PS: This issue aside, I'm a huge fan of recipes and its integration in caret!

**Comment by topepo** [comment]
Install the devel version:

```r
devtools::install_github('topepo/caret/pkg/caret')
```

which is going to CRAN today.

**Comment by o1iv3r** [comment]
Thanks for the quick reply. Installed the new version from github using zip-download and devtools::install("caret-master/pkg/caret") since I am behind a firewall. Now I receive a different error on my stackoverflow example:

     Error in { : task 1 failed - "konnte Funktion "wt_rmse" nicht finden"

**Comment by topepo** [comment]
Unfortunately, your timing is bad in that there is a version waiting for CRAN approval (the devel version that you installed) and updated documentation. The documentation doesn't go live until the new version is on CRAN. 

The [difference in the documentation](https://github.com/topepo/caret/commit/c0b94dc3a731d61b6a5ec14728d064ae0ff1f9f2#diff-adfc9c815ccf21ae160019a7721fe7da) has the answer but it boils down to this:

_some_ parallel processing technologies don't give you access to all of the functions in some environments or packages. When we define `wt_rmse` in the global environment, the parallel workers can't see it. It is hard to pipe a list of objects that you want to see to the workers. 

The solution is to define the functions inside of the summary statistic code, such as 

```r
model_stats <- function(data, lev = NULL, model = NULL) {
  
  stats <- defaultSummary(data, lev = lev, model = model)
  
  wt_rmse <- function (pred, obs, wts, na.rm = TRUE) 
     sqrt(weighted.mean((pred - obs)^2, wts, na.rm = na.rm))
  
  res <- wt_rmse(pred = data$pred,
                 obs = data$obs, 
                 wts = data$manufacturability)
  c(wRMSE = res, stats)
}
```

That's what the new documentation will say once the new version is on CRAN.

**Comment by o1iv3r** [comment]
So many things I don't know about parallel processing ;)

Thanks, that solves it for me.
