### ISSUE TITLE
survival analysis situation

### ISSUE THREAD

**Issue by csetraynor** [topepo/caret#873]
Hi,

I enjoy very much the functionality of the caret package, for instance was the first step towards data science and ML in my career. Nowadays, I am working mostly in survival analysis and I have created a developer package to do so for my analysis, including S3 methods. However I would like to have the tools that caret package offer in my daily work.  I have found that the issue stated in this post from StackOverflow is still not resolved:

![image](https://user-images.githubusercontent.com/33321804/38993727-4da15462-43dc-11e8-8130-7c28faec65d2.png)

is it? If no, I would like to offer my help in testing and as a I said I have started working with S3 methods therefore I believe I could help also in the development as welll.

**Comment by topepo** [comment]
That was the plan before I joined RStudio. The changes would be fairly invasive to `caret` but are easy to make with the new set of modeling packages that I'm working on ([`recipes`](https://topepo.github.io/recipes/), [`rsample`](https://topepo.github.io/rsample/), [`yardstick`](https://topepo.github.io/yardstick/) and so on).  More information on these can be found [here](https://github.com/rstudio/rstudio-conf/tree/master/2018/Modeling_in_the_Tidyverse--Max_Kuhn) and [here](https://github.com/topepo/rstudio-conf-2018/tree/master/Materials). 

These don't have the high level api that `caret` does (yet) but could be used to fit and tune survival models. [This page](https://topepo.github.io/rsample/articles/Applications/Survival_Analysis.html) has an example. 

If you like to help there, it would be great. The first thing that I need is more performance metrics relative to survival analysis in `yardstick`. There is a [PR](https://github.com/topepo/yardstick/pull/15) that uses a really old R package, but if you wanted to [add more metrics](https://github.com/topepo/yardstick/issues/6), that would go a long way. 

`caret` is't going away and is still being developed but there is a lot moe that we will be able to do with these packages.

**Comment by csetraynor** [comment]
Hi topepo thank you for the links they are super!

Ok as far as I know there are 4 or 5 metrics that are generally accepted in survival. In my opinion, from less to more interesting are: log-rank test, deviance, concordance, survROC,  and pec(Brier). But all five have their pros and cons.
A goal that is not yet fully solved is how to use and implement metrics for models with time dependent covariates. In fact this is one of my next milestons.

carlos,
