### ISSUE TITLE
no slot of name "bestBinary" for this object of class "ga".

### ISSUE THREAD

**Issue by Kay9Man** [topepo/caret#877]
library(caret)
library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(GA)
library(latticeExtra)
library(pROC)
library(doMC)
registerDoMC(4)

set.seed(468)
training <- twoClassSim(  500, noiseVars = 100, corrVar = 100, corrValue = .75)
testing  <- twoClassSim(  200, noiseVars = 100, corrVar = 100, corrValue = .75)
large    <- twoClassSim(10000, noiseVars = 100, corrVar = 100, corrValue = .75)
cvIndex <- createMultiFolds(training$Class, times = 2)
ctrl <- trainControl(method = "repeatedcv",
                     repeats = 2,
                     classProbs = TRUE,
                     summaryFunction = twoClassSummary,
                     allowParallel = FALSE,
                     index = cvIndex)

ROCcv <- function(ind, x, y, cntrl)
{
        library(caret)
        library(MASS)
        ind <- which(ind == 1)
        ## In case no predictors are selected:
        if(length(ind) == 0) return(0)
        out <- train(x[,ind], y, method = "qda",
                     metric = "ROC", trControl = cntrl)
        caret:::getTrainPerf(out)[, "TrainROC"]
}

# GA to select features 

set.seed(137)

ga_resampled <- ga(type = "binary",
                   fitness = ROCcv,
                   min = 0, max = 1,
                   maxiter = 400,
                   nBits = ncol(training) - 1,
                   names = names(training)[-ncol(training)],
                   x = training[,-ncol(training)],
                   y = training$Class,
                   cntrl = ctrl,
                   keepBest = TRUE,
                   parallel = TRUE)

# ga_resampled 

resamp_results <- lapply(ga_resampled@bestBinary, 
                         getLarge, 
                         x = training[,-ncol(training)], 
                         y = training$Class, 
                         large = large, 
                         test = testing,  
                         cntrl = ctrl)

# Error in lapply(ga_resampled@bestBinary, getLarge, x = training[, -ncol(training)],
#:no slot of name "bestBinary" for this object of class "ga".

**Comment by topepo** [comment]
The `ga` function is not in `caret`. `gafs` is and the documentation on how to use it is [here](https://topepo.github.io/caret/feature-selection-using-genetic-algorithms.html).
