### ISSUE TITLE
using genetic algorithms for feature selection

### ISSUE THREAD

**Issue by Victorfy** [topepo/caret#885]
I am solving a classification problem, about 80 features to use.
Before building randomforest model or other tree based model, I used genetic algorithms (gafs)to select features, then,  put selected features to my model, but performance doesn't improved compared to my random selection, what may be the reason? 

looking forward to your reply.

**Comment by topepo** [comment]
I have no idea since you haven't said much about the data or the model or how you fit it or the software versions that you've used. Also, you are not guaranteed to get an improvement, especially form a model that already does feature selection (random forests)
