### ISSUE TITLE
Documentation of recall wrong?

### ISSUE THREAD

**Issue by sandroraabe** [topepo/caret#889]
To my mind there might be a mistake in the documentation for `recall`. It reads:

```
The recall (aka specificity) is defined as the proportion of relevant results out of the number of samples which were actually relevant.
```

Is is indeed the definition of recall, but not of specificity. Recall = Sensitivity. Specificity, in your example, would be D/(B+D)

**Comment by hadjipantelis** [comment]
Yeap, you are obviously right that Recall is Sensitivity rather than Specificity. Thanks for point it out, I made a relevant PR (#891).

**Comment by topepo** [comment]
Thanks for seeing this and fixing it. Thankfully it is correct on the website and book.
