### ISSUE TITLE
feature request: warning for boundary tuning parameters

### ISSUE THREAD

**Issue by kaurao** [topepo/caret#892]
It will be extremely useful if caret threw a warning if the best tuning parameters selected for building the final model happen to be at the boundary of the search grid.

For example if the grid for svmLinear 2 is the cost hyperparameter c(1, 10, 100) and 1 (or 100) is selected after the tuning process then caret can show a warning. This will be very useful to spot likely sub-optimal models.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
