### ISSUE TITLE
running train with nnet in the linout configuration does not work 

### ISSUE THREAD

**Issue by tobiaspiechowiak** [topepo/caret#901]
```

 d1 <- data.frame(sample(40),sample(40))
 d2 <- data.frame(sample(40),sample(40))
 fit <- train(d1,d2,
 method = 'nnet',
 linout = T)
```
Is there something wrong or does it only work for classification?

**Comment by topepo** [comment]
```r
>  d1 <- data.frame(sample(40),sample(40))
>  d2 <- data.frame(sample(40),sample(40))
>  fit <- train(d1,d2,
+  method = 'nnet',
+  linout = T)
Error: Please make sure `y` is a factor or numeric value.
```

The issue here is that you are passing a data frame in for the response.

**Comment by tobiaspiechowiak** [comment]
Hi, 
sorry for maybe posing a question which answer might be obvious but how would you then use train with nnet as a regression model? Does y have to be a matrix then as input? nnet itself works with data frames as input... 

Great book by the way.

**Comment by topepo** [comment]
`caret` isn't setup to handle multiple numeric outcomes. :-(

> Great book by the way.

Thanks!
