### ISSUE TITLE
hi everyone,  I am running MARS recursive model with caret, for 3 different y values, 2 of them work fine but the last one gives me error, yet I follow the same methodology :: any idea? Error in "undefined columns selected"

### ISSUE THREAD

**Issue by seymakalay** [topepo/caret#903]
xxx_I1 <- combined_AML_Train [,c(7:17,21:42,44)]
yyy_I1 <- combined_AML_Train$index.oninvestment

predVars.I1 <- names(combined_AML)[!(names(combined_AML) %in% c( "index.oninvestment",
                                                                     "some character columns which I removed" ))]
varSeq <- seq(1,length(predVars.I1)-1,by=2)
indexx <- createMultiFolds(yyy_I1,times = 5)

#set mars
marsFuncs <- caretFuncs
marsFuncs$summary <- defaultSummary

ctrl.rcrsive.I1.mars <- rfeControl(method = "repeatedCV",
                                       repeats = 5, verbose = T,
                                       functions = marsFuncs,
                                       index = indexx )
set.seed(87)
marsRFE.I1 <- rfe(xxx_I1,yyy_I1,
               sizes = varSeq,
               rfeControl = ctrl.rcrsive.I1.mars,
               method="earth", tuneLength=10,
               preProcess = c("knnImpute","center","scale"))
marsRFE.I1

**Comment by topepo** [comment]
I will again repeat what I said to you last: 

> please start a new issue and follow the issue template to help get this answered. Referencing a data set that we don't have access to doesn't help.

Take a look at what you have submitted in this issue. Does it match this (or the issue template)?

**Comment by seymakalay** [comment]
yeah I guess next time :) I run MARS 4rd time on another R script it worked fine,
yet MARS recursive model  gave me i    1- Error in 3 task failed undefined columns selected,
                                                             2-Error in 22 task failed undefined columns selected,
                                                             3-Error in 8 task failed undefined columns selected,
                                                             4- run the same thing on another script work,,,

many thanks Max,
loving caret

**Comment by hadjipantelis** [comment]
@seymakalay: Can you please : 1. edit the title of your issue to something small and concise and then  2. provide details and reproducible steps in your main post? As it stands your issue cannot be reproduced (and thus be solved).
