### ISSUE TITLE
regression model with 'gbm_h2o' produce error:"Something is wrong; all the RMSE metric values are missing:"

### ISSUE THREAD

**Issue by vmorozov** [topepo/caret#906]
train regression model with 'gbm_h2o' produce error:"Something is wrong; all the RMSE metric values are missing:"
I am getting this error on Ubuntu and RHEL7

> train(Sepal.Length~.,iris[,1:4],tuneLength=2,method='gbm_h2o') Something is wrong; all the RMSE metric values are missing:       RMSE        Rsquared        MAE       Min.   : NA   Min.   : NA   Min.   : NA    1st Qu.: NA   1st Qu.: NA   1st Qu.: NA    Median : NA   Median : NA   Median : NA    Mean   :NaN   Mean   :NaN   Mean   :NaN    3rd Qu.: NA   3rd Qu.: NA   3rd Qu.: NA    Max.   : NA   Max.   : NA   Max.   : NA    NA's   :4     NA's   :4     NA's   :4     Error: Stopping In addition: There were 50 or more warnings (use warnings() to see the first 50) > sessionInfo() R version 3.5.0 (2018-04-23) Platform: x86_64-pc-linux-gnu (64-bit) Running under: Ubuntu 18.04 LTS  Matrix products: default BLAS: /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1 LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1  locale:  [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8        LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8     [6] LC_MESSAGES=C.UTF-8    LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C           LC_TELEPHONE=C         [11] LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C     attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] caret_6.0-80    ggplot2_2.2.1   lattice_0.20-35  loaded via a namespace (and not attached):  [1] Rcpp_0.12.17       lubridate_1.7.4    tidyr_0.8.1        class_7.3-14       assertthat_0.2.0   ipred_0.9-6         [7] psych_1.8.4        foreach_1.4.4      R6_2.2.2           plyr_1.8.4         magic_1.5-8        stats4_3.5.0       [13] pillar_1.2.3       rlang_0.2.1        lazyeval_0.2.1     data.table_1.11.4  kernlab_0.9-26     rpart_4.1-13       [19] Matrix_1.2-14      splines_3.5.0      CVST_0.2-2         ddalpha_1.3.4      gower_0.1.2        stringr_1.3.1      [25] foreign_0.8-70     RCurl_1.95-4.10    munsell_0.5.0      broom_0.4.4        compiler_3.5.0     pkgconfig_2.0.1    [31] mnormt_1.5-5       dimRed_0.1.0       nnet_7.3-12        tidyselect_0.2.4   tibble_1.4.2       prodlim_2018.04.18 [37] DRR_0.0.3          codetools_0.2-15   RcppRoll_0.3.0     dplyr_0.7.5        withr_2.1.2        bitops_1.0-6       [43] MASS_7.3-50        recipes_0.1.3      ModelMetrics_1.1.0 grid_3.5.0         jsonlite_1.5       nlme_3.1-137       [49] gtable_0.2.0       magrittr_1.5       scales_0.5.0       stringi_1.2.3      reshape2_1.4.3     bindrcpp_0.2.2     [55] timeDate_3043.102  robustbase_0.93-1  geometry_0.3-6     pls_2.6-0          xgboost_0.71.2     lava_1.6.1         [61] iterators_1.0.9    tools_3.5.0        glue_1.2.0         DEoptimR_1.0-8     purrr_0.2.5        sfsmisc_1.1-2      [67] abind_1.4-5        parallel_3.5.0     survival_2.42-3    colorspace_1.3-2   h2o_3.20.0.2       bindr_0.1.1
--
 
> | >
>

**Comment by topepo** [comment]
Please re-read the issue template. Providing a reproducible example and the results of `sessionInfo` will help get your question answered.
