### ISSUE TITLE
undefined columns selected

### ISSUE THREAD

**Issue by pandeyvineet** [topepo/caret#923]
CODE:
library(caret); library(kernlab); data(spam)
inTrain <- createDataPartition(y=spam$type,
                              p=0.75, list=FALSE)
training <- spam[inTrain,]
testing <- spam[-inTrain,]

M <- abs(cor(training[,-58]))
diag(M) <- 0
which(M > 0.8,arr.ind=T)

preProc <- preProcess(log10(spam[,-58]+1),method="pca",pcaComp=2)
spamPC <- predict(preProc,log10(spam[,-58]+1))

preProc <- preProcess(log10(training[,-58]+1),method="pca",pcaComp=2)
trainPC <- predict(preProc,log10(training[,-58]+1))
modelFit <- train(training$type ~ .,method="glm",preProc = "pca",data=trainPC)

When is execute this following error occurs:
Error in `[.data.frame`(data, , all.vars(Terms), drop = FALSE) : 
  undefined columns selected

R-Version :R version 3.5.1

**Comment by topepo** [comment]
You are computing the principal components using the principal components are inputs. 

The main issue though is that you are using the data frame name in the formula. This should do what you are interested in: 

```r
modelFit <- train(type ~ ., data = training, method="glm",preProc = "pca")
```
