### ISSUE TITLE
Continue training existing model with new data

### ISSUE THREAD

**Issue by ShehabElsayed** [topepo/caret#941]
Hello All,

I was wondering if there is a way to continue training an existing, pre-trained model based on new training data?

I am trying to study the performance of different models as the size of the training set increases. Currently I am retraining the models from scratch for every training set size which is time consuming.

Thanks.

**Comment by topepo** [comment]
No, I don't think that there is any general shortcut for doing this. There are for some specific types of models but, for most, you would have to start form scratch.

**Comment by ShehabElsayed** [comment]
I see, Thank you for your reply
