### ISSUE TITLE
Support for dbarts?

### ISSUE THREAD

**Issue by ignacio82** [topepo/caret#945]
Are you planning to add support for [dbarts](https://cran.r-project.org/web/packages/dbarts/dbarts.pdf) ? •	Jennifer Hill [said](https://andrewgelman.com/2017/05/18/causal-inference-using-bayesian-additive-regression-trees-questions/) last year “Anyone interested in BART should be using Vince Dorie’s dbarts package.” Additionally, It includes a function called `rbart()` which allow the inclusion of random effects in a BART model, to account for clustering. This could be very helpful indeed when it comes time to analyzing policy evaluation data, which has a lot of clustering.

**Comment by topepo** [comment]
This is a good idea. 

Unfortunately, `caret` is at the lifecycle point of having a fairly complete interface, so this isn't a good fit.  

The development work is focused on squashing bugs and any changed required by the underlying model packages.
