### ISSUE TITLE
variable importance for vanilla linear model?!

### ISSUE THREAD

**Issue by randomgambit** [topepo/caret#951]
Hi @topepo ,

I hope all is well. I was reading the docs about the variable importance in `caret` and found that for linear models you take the absolute value of the t-stat.

I wonder if there is some literature that supports that argument. Indeed, I thought that (assuming your variables are standardized), for the purpose of prediction it is the absolute size of the coefficient that matters. Also, with many many variables it is problematic to compare the t-stats, as many will be type -I errors. 

In essence, statistical inference and prediction/variable importance are often two different animals. But I know you are a stats PhD, so there must be some interesting insight here.

What do you think? Thanks!!

**Comment by topepo** [comment]
> I wonder if there is some literature that supports that argument.

Probably but not that I know of. 

> for the purpose of prediction it is the absolute size of the coefficient that matters.

Maybe. In other models, that is how I determine importance.

There are two reasons that I use the _t_ statistic here:

* It is basically a signal-to-noise ratio. Taking the noise into account, when you can, seems like a good idea. 

* It works if the user forgot to center and scale the predictors.

**Comment by randomgambit** [comment]
thanks for the quick answer. thats interesting
