### ISSUE TITLE
getModelInfo("glmnet")$sort logic : Lower alpha should be less important, as it would imply more features (more complexity)

### ISSUE THREAD

**Issue by wsrfad** [topepo/caret#960]
getModel("glmnet")$sort

```x[order(-x$lambda, x$alpha)]``

Are we not looking for a lower alpha in one standard error rule ?

**Comment by topepo** [comment]
You do not understand how that module is used. It is intended to sort by complexity and is only used when there are ties in the performance measure. Please read [the documentation](https://topepo.github.io/caret/using-your-own-model-in-train.html#Components) before posting.

**Comment by wsrfad** [comment]
I have read the whole documentation sir. A less complex model typically implies lesser features. Why do you choose a model with lesser alpha, in case of ties in lambda ? Shouldnt lesser alpha (or more ridge) imply more generalized or complex model ? Also, when we want to use oneSE rule, we would want to proceed in direction of lesser complexity, with similar performance metric. It would be great if you can help with that, or update the documentation with that ?
