### ISSUE TITLE
cv.glmnet to tune `alpha` : Will passing different alpha values using train / trainControl give us the correct one SE rmse, as we will only tune the alpha parameters, if we support getModelInfo for cv.glmnet

### ISSUE THREAD

**Issue by wsrfad** [topepo/caret#961]
To tune alpha parameter as well, we might use train function in R, but the tuning grid should perhaps include only alpha, as lambdas are being tuned internally. So, we in effect are not tuning the alpha/lambda combination appropriately using lambda parameter

**Comment by topepo** [comment]
No, we are not going to use `cv.glmnet`. Please read [the documentation](https://topepo.github.io/caret/model-training-and-tuning.html) to use that approach.

**Comment by wsrfad** [comment]
Yes sir, this model is not supported by train. But we may do that. My question is on top of that only. If we were to send a tuning grid with alphas, will we be able to tune lambda as well which are gotten by coordinate descent ? I do not think so. So should one write their own function to do cross validate alpha as well as mentioned in CV.glmnet documentation? What should be preferred ?

1. Using a tuning grid of alpha and lambda and passing it to train using glmnet ? Here we might have to be aware of the list of lambdas as they cannot be generated using coordinate descent

2. Using a tuning grid of alpha and passing it to CV.glmnet. This only helps one to get best value, not so for one se

3. Writing a function which calculates for each alpha, CV.glmnet results. Also capturing each lambda results arrived for each alpha. This way we can easily get the needed alpha lambda combination

I appreciate your help
