### ISSUE TITLE
omh error while installing caret

### ISSUE THREAD

**Issue by leeadh** [topepo/caret#974]
Hi all, i am trying to install caret. but whenever i do install.packages("caret"), this happens

auc_.cpp:2:10: fatal error: omp.h: No such file or directory
 #include <omp.h>
          ^~~~~~~
compilation terminated.
make: *** [auc_.o] Error 1
ERROR: compilation failed for package ‘ModelMetrics’
* removing ‘/home/ruser/R/x86_64-redhat-linux-gnu-library/3.4/ModelMetrics’
Warning in install.packages :
  installation of package ‘ModelMetrics’ had non-zero exit status
ERROR: dependency ‘ModelMetrics’ is not available for package ‘caret’
* removing ‘/home/ruser/R/x86_64-redhat-linux-gnu-library/3.4/caret’
Warning in install.packages :
  installation of package ‘caret’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpVQC0IL/downloaded_packages’

I tried everything possible but I am still unsure why this is happening. Any help

**Comment by topepo** [comment]
It looks like the `caret` dependency `ModelMetrics` requires OpenMP now. You'll need to get those headers (so that `omp.h` is found) and install that package first.

**Comment by JackStat** [comment]
Modelmetrics has used openmp since the beginning but openmp is not being automatically included as it used to be.  I am hoping to remove omp soon but for now you need to install it.

More information here

https://github.com/JackStat/ModelMetrics/issues/24

**Comment by wdtglrn** [comment]
I'm on Linux and getting the same error. I looked at the link with more information, but it looks tuned to Mac.

**Comment by topepo** [comment]
@wdtglrn  please move the discussion over to the `ModelMetrics` page.
