### ISSUE TITLE
Can we change the threshold of the prediction?

### ISSUE THREAD

**Issue by jmq19950824** [topepo/caret#979]
I want to predict the binary variable(suppose that yes=1 and no=0), and I can use the predict( ) function in R to realize. But when I want to let the prediction be yes only when the probability>0.8 (not 0.5 by default）, how can I do this? 
Thanks!

**Comment by jmq19950824** [comment]
One possible solution is that we can use the probability generated by predict( ) function and further set our own threshold. This may be difficult when I use the package **caret** and set the metric 'Accuracy' to select the best hyperparameter, cause I can't change the threshold when the prediction happened in the selection process of the hyperparameter

**Comment by ck2136** [comment]
Hello! @jmq19950824! This [section](http://topepo.github.io/caret/using-your-own-model-in-train.html#) maybe useful. It describes tuning the probability threshold. There's also Youden's index that you can look up.

**Comment by jmq19950824** [comment]
@ck2136 thanks a lot! I will study this section!

**Comment by ck2136** [comment]
@jmq19950824 No prob! I had to make some changes to the code since I used glm() not rf(). If you want to see what I did let me know :)

**Comment by jmq19950824** [comment]
@ck2136 Thanks. I have followed you and I hope we can make a deep communication, since I am still a newbie in the ML world!
