### ISSUE TITLE
Filename caret/man/learing_curve_dat.Rd is mispelled

### ISSUE THREAD

**Issue by gofraidh** [topepo/caret#982]
Not a bug but the filename [learing_curve_dat.Rd](https://github.com/topepo/caret/blob/master/pkg/caret/man/learing_curve_dat.Rd) seems to be mispelled, the mispelling occurs also when calling the function from within R.

**Comment by topepo** [comment]
![image](https://user-images.githubusercontent.com/5731043/54946193-e9f7a180-4f0d-11e9-9520-d1dd5c79f75d.png)
