### ISSUE TITLE
add noise variable var to tunable parameters for kernlab's gaussianpr

### ISSUE THREAD

**Issue by xnie** [topepo/caret#986]
Hi,

I'm using caret with kernlab's gaussianpr using a Radial Basis Function (RBF) kernel (in caret, method = 'gaussprRadial'). The only tuning parameter available is sigma, which controls the bandwidth of the RBF kernel. Would it be possible to add var as another tuning parameters? See the documentation for gausspr in https://cran.r-project.org/web/packages/kernlab/kernlab.pdf. 

The parameter var controls the noise level in the likelihood, and it is equivalent to the regularization strength. It appears that it is very important to be able to tune not just the rbf kernel, but also the regularization strength. Currently I have to write an outer loop to tune this parameter, and it's quite messy and painful.

Could we please add var as another tuning parameter for gaussprRadial?

Thanks!

**Comment by topepo** [comment]
I'd like to avoid doing that since it is only for regression and would break backward compatibility with existing code. You could add that using a [custom model]( https://topepo.github.io/caret/using-your-own-model-in-train.html) though.
