### ISSUE TITLE
Error in documentation "21.4 Example"

### ISSUE THREAD

**Issue by Make42** [topepo/caret#990]
When being at http://topepo.github.io/caret/feature-selection-using-genetic-algorithms.html#basic-syntax-1 and I press in the left frame (table of contents) on the link "21.4 Example" I get send to the section "5.2 An Example" instead.

**Comment by topepo** [comment]
Thanks

**Comment by Make42** [comment]
No offense, but this was not fixed - why did you close it?

**Comment by topepo** [comment]
The sources are fixed (see the commit). The web site takes a few hours to build and I'm about to do a release, so the user-face page will change in a few days.
