### ISSUE TITLE
sparse PLS - extracting scores

### ISSUE THREAD

**Issue by jnguofa** [topepo/caret#997]
Hello,

Thanks so much for the caret package!

I would like to use the splsda function for a multiclass data set but I need to be able to extract the "scores" (both from the splsda and predict.splsda.)  The plsda method seems to provide this by default.

Is there a way to do so?

Just in case, by "scores" I mean the definition used in the pls package (https://cran.r-project.org/web/packages/pls/index.html).  Can you clarify what is meant by "raw model scores" in the predict function (https://www.rdocumentation.org/packages/caret/versions/6.0-81/topics/plsda).

Many thanks!

**Comment by topepo** [comment]
"raw model scores" means the raw predictions of the outcome (that is probably poorly worded for this model). 

If you want the PLS components (related to the predictors), you could get those for the training set using the methods given by the `pls` package. We don't have a method to extract the PLS scores for new data (if that is what you are looking for).
